import type { PromptTemplate, Author } from './types'

const AUTHORS: Record<string, Author> = {
  lin: { id: 'u-lin', name: '林暮白', bio: '前电影编剧 / 现 AI 短剧厂牌主理人' },
  qi: { id: 'u-qi', name: '齐夜舟', bio: '短视频脚本 / 抖音现象级内容' },
  ying: { id: 'u-ying', name: '殷鹿鸣', bio: '广告创意 / 4A 出身' },
  ke: { id: 'u-ke', name: '柯临川', bio: 'MV 导演 / 视觉诗人' },
  su: { id: 'u-su', name: '苏无因', bio: '动漫编剧 / 二次元' },
  zhou: { id: 'u-zhou', name: '周以墨', bio: '游戏剧情 / 主机工作室' },
  lan: { id: 'u-lan', name: '蓝鲸落', bio: 'B 站百万 UP / 拉片狂魔' },
  mo: { id: 'u-mo', name: '莫听风', bio: '脱口秀转行 / 反转结构专精' },
}

const NOW = Date.now()
const day = 24 * 3600 * 1000

export const SEED_TEMPLATES: PromptTemplate[] = [
  {
    id: 't-001',
    title: '短剧 · 90 秒强冲突开场',
    description: '专为竖屏短剧设计：90 秒内建立反差、制造悬念、留下钩子。',
    category: 'short_drama',
    tags: ['短剧', '钩子', '反转'],
    visibility: 'public',
    author: AUTHORS.lin,
    sections: [
      {
        id: 's1',
        key: 'premise',
        title: '前置设定',
        body:
          '这是一个 {{genre}} 题材的竖屏短剧，时长 {{duration}} 秒。目标观众是 {{audience}}。第一句台词必须在前 3 秒出现反差。',
        collapsed: false,
      },
      {
        id: 's2',
        key: 'character',
        title: '角色档案',
        body:
          '主角 {{hero_name}}，{{hero_age}} 岁，{{hero_trait}}。\n对手 {{villain_name}}，{{villain_trait}}，与主角有 {{relationship}}。',
        collapsed: false,
      },
      {
        id: 's3',
        key: 'scene',
        title: '场景描述',
        body: '场景：{{location}}，{{time}}。关键道具：{{prop}}。',
        collapsed: false,
      },
      {
        id: 's4',
        key: 'camera',
        title: '镜头语言',
        body: '开镜 {{shot_size}}，{{camera_move}}，剪辑节奏 {{cut_rhythm}}。',
        collapsed: false,
      },
      {
        id: 's5',
        key: 'tone',
        title: '风格基调',
        body: '参考作品：{{reference}}。情绪曲线：{{emotion_curve}}。',
        collapsed: false,
      },
      {
        id: 's6',
        key: 'output',
        title: '输出约束',
        body: '输出 {{output_scenes}} 场戏，每场标注秒数；最后 5 秒必须留悬念钩子。',
        collapsed: false,
      },
    ],
    variables: [
      { key: 'genre', label: '题材', type: 'enum', options: ['悬疑', '甜宠', '复仇', '都市', '古风'], defaultValue: '悬疑' },
      { key: 'duration', label: '时长（秒）', type: 'number', defaultValue: '90' },
      { key: 'audience', label: '目标观众', type: 'text', defaultValue: 'Z 世代女性' },
      { key: 'hero_name', label: '主角名', type: 'text', defaultValue: '沈墨' },
      { key: 'hero_age', label: '主角年龄', type: 'number', defaultValue: '28' },
      { key: 'hero_trait', label: '主角性格', type: 'text', defaultValue: '沉默寡言、外冷内热' },
      { key: 'villain_name', label: '对手名', type: 'text', defaultValue: '陆知行' },
      { key: 'villain_trait', label: '对手特质', type: 'text', defaultValue: '表面温文尔雅' },
      { key: 'relationship', label: '人物关系', type: 'text', defaultValue: '前搭档的弟弟' },
      { key: 'location', label: '场景', type: 'text', defaultValue: '雨夜废弃工厂' },
      { key: 'time', label: '时间', type: 'text', defaultValue: '凌晨两点' },
      { key: 'prop', label: '关键道具', type: 'text', defaultValue: '一把生锈的钥匙' },
      { key: 'shot_size', label: '开镜景别', type: 'enum', options: ['大特写', '中景', '全景'], defaultValue: '大特写' },
      { key: 'camera_move', label: '运镜', type: 'text', defaultValue: '35mm 手持缓慢推进' },
      { key: 'cut_rhythm', label: '剪辑节奏', type: 'enum', options: ['快切', '缓推', '跳切'], defaultValue: '快切' },
      { key: 'reference', label: '参考作品', type: 'text', defaultValue: '诺兰《记忆碎片》' },
      { key: 'emotion_curve', label: '情绪曲线', type: 'text', defaultValue: '压抑 → 爆发 → 留白' },
      { key: 'output_scenes', label: '场数', type: 'number', defaultValue: '4' },
    ],
    versions: [],
    createdAt: NOW - 30 * day,
    updatedAt: NOW - 2 * day,
    cloneCount: 1287,
    rating: 4.8,
  },
  {
    id: 't-002',
    title: '短视频 · 30 秒爆款脚本',
    description: '抖音 / 视频号爆款脚本结构：钩子 → 痛点 → 转折 → CTA。',
    category: 'short_video',
    tags: ['短视频', '爆款', '钩子'],
    visibility: 'public',
    author: AUTHORS.qi,
    sections: [
      {
        id: 's1',
        key: 'premise',
        title: '前置设定',
        body: '平台 {{platform}}，受众 {{audience}}，卖点 {{selling_point}}。',
        collapsed: false,
      },
      {
        id: 's2',
        key: 'character',
        title: '角色档案',
        body: '出镜人 {{presenter}}，人设 {{persona}}。',
        collapsed: false,
      },
      {
        id: 's3',
        key: 'scene',
        title: '场景描述',
        body: '拍摄地 {{location}}，关键视觉锤 {{visual_hammer}}。',
        collapsed: false,
      },
      {
        id: 's4',
        key: 'camera',
        title: '镜头语言',
        body: '前 3 秒使用 {{hook_type}}，节奏 {{rhythm}}。',
        collapsed: false,
      },
      {
        id: 's5',
        key: 'tone',
        title: '风格基调',
        body: '情绪 {{mood}}，配乐 {{bgm}}。',
        collapsed: false,
      },
      {
        id: 's6',
        key: 'output',
        title: '输出约束',
        body: '字数 {{word_count}} 字以内，结尾 CTA：{{cta}}。',
        collapsed: false,
      },
    ],
    variables: [
      { key: 'platform', label: '平台', type: 'enum', options: ['抖音', '视频号', '小红书', 'B 站'], defaultValue: '抖音' },
      { key: 'audience', label: '受众', type: 'text', defaultValue: '25-35 岁职场女性' },
      { key: 'selling_point', label: '核心卖点', type: 'text', defaultValue: '3 分钟读完一本商业书' },
      { key: 'presenter', label: '出镜人', type: 'text', defaultValue: '女，28 岁，温柔知性' },
      { key: 'persona', label: '人设', type: 'text', defaultValue: '读书博主 / 反内卷' },
      { key: 'location', label: '拍摄地', type: 'text', defaultValue: '自家客厅，暖光' },
      { key: 'visual_hammer', label: '视觉锤', type: 'text', defaultValue: '一摞书 + 一杯咖啡' },
      { key: 'hook_type', label: '钩子类型', type: 'enum', options: ['反问', '数字', '反差', '悬念'], defaultValue: '反差' },
      { key: 'rhythm', label: '节奏', type: 'text', defaultValue: '快剪 1.2 倍' },
      { key: 'mood', label: '情绪', type: 'text', defaultValue: '松弛、治愈' },
      { key: 'bgm', label: '配乐', type: 'text', defaultValue: '轻钢琴' },
      { key: 'word_count', label: '字数', type: 'number', defaultValue: '200' },
      { key: 'cta', label: 'CTA', type: 'text', defaultValue: '评论区扣 1 送书单' },
    ],
    versions: [],
    createdAt: NOW - 25 * day,
    updatedAt: NOW - 1 * day,
    cloneCount: 2401,
    rating: 4.9,
  },
  {
    id: 't-003',
    title: '广告 · 30 秒品牌 TVC',
    description: '国际 4A 风格的 30 秒品牌 TVC 模板。',
    category: 'ad',
    tags: ['广告', '品牌', 'TVC'],
    visibility: 'public',
    author: AUTHORS.ying,
    sections: [
      {
        id: 's1',
        key: 'premise',
        title: '前置设定',
        body: '品牌 {{brand}}，品类 {{category}}，本次 campaign 主题 {{theme}}。',
        collapsed: false,
      },
      {
        id: 's2',
        key: 'character',
        title: '角色档案',
        body: '代言 / 主形象 {{spokesperson}}，目标人群 {{target}}。',
        collapsed: false,
      },
      {
        id: 's3',
        key: 'scene',
        title: '场景描述',
        body: '主场景 {{main_scene}}，转场地点 {{transition_scene}}。',
        collapsed: false,
      },
      {
        id: 's4',
        key: 'camera',
        title: '镜头语言',
        body: '主镜头语言 {{camera_style}}，参考广告 {{reference_ad}}。',
        collapsed: false,
      },
      {
        id: 's5',
        key: 'tone',
        title: '风格基调',
        body: '情绪 {{mood}}，色板 {{palette}}。',
        collapsed: false,
      },
      {
        id: 's6',
        key: 'output',
        title: '输出约束',
        body: '输出分镜 {{shots}} 个，结尾 slogan：{{slogan}}。',
        collapsed: false,
      },
    ],
    variables: [
      { key: 'brand', label: '品牌', type: 'text', defaultValue: 'AURA' },
      { key: 'category', label: '品类', type: 'text', defaultValue: '高端香水' },
      { key: 'theme', label: '主题', type: 'text', defaultValue: '气味的回忆' },
      { key: 'spokesperson', label: '代言', type: 'text', defaultValue: '周冬雨式清新女生' },
      { key: 'target', label: '目标人群', type: 'text', defaultValue: '25-35 都市女性' },
      { key: 'main_scene', label: '主场景', type: 'text', defaultValue: '雨后老弄堂' },
      { key: 'transition_scene', label: '转场场景', type: 'text', defaultValue: '现代公寓窗前' },
      { key: 'camera_style', label: '镜头语言', type: 'text', defaultValue: '胶片 35mm 浅景深' },
      { key: 'reference_ad', label: '参考广告', type: 'text', defaultValue: 'Chanel N°5 L\'Eau' },
      { key: 'mood', label: '情绪', type: 'text', defaultValue: '暧昧、低饱和、留白' },
      { key: 'palette', label: '色板', type: 'text', defaultValue: '雾灰 + 暖橘 + 哑金' },
      { key: 'shots', label: '分镜数', type: 'number', defaultValue: '8' },
      { key: 'slogan', label: 'Slogan', type: 'text', defaultValue: '有些气味，比记忆更久' },
    ],
    versions: [],
    createdAt: NOW - 20 * day,
    updatedAt: NOW - 3 * day,
    cloneCount: 873,
    rating: 4.7,
  },
  {
    id: 't-004',
    title: 'MV · 概念短片脚本',
    description: '为歌曲 MV 输出概念脚本、镜头与情绪曲线。',
    category: 'mv',
    tags: ['MV', '音乐', '影像'],
    visibility: 'public',
    author: AUTHORS.ke,
    sections: [
      {
        id: 's1',
        key: 'premise',
        title: '前置设定',
        body: '歌曲 {{song}}，风格 {{music_genre}}，核心意象 {{core_image}}。',
        collapsed: false,
      },
      {
        id: 's2',
        key: 'character',
        title: '角色档案',
        body: '主形象 {{protagonist}}，象征物 {{symbol}}。',
        collapsed: false,
      },
      {
        id: 's3',
        key: 'scene',
        title: '场景描述',
        body: '主要取景地 {{location}}，主色调 {{color_tone}}。',
        collapsed: false,
      },
      {
        id: 's4',
        key: 'camera',
        title: '镜头语言',
        body: '主镜头 {{lens}}，节奏对齐 {{beat_alignment}}。',
        collapsed: false,
      },
      {
        id: 's5',
        key: 'tone',
        title: '风格基调',
        body: '参考影像 {{visual_ref}}，情绪 {{emotion}}。',
        collapsed: false,
      },
      {
        id: 's6',
        key: 'output',
        title: '输出约束',
        body: '输出 {{verse_count}} 段分镜，对应歌曲段落 {{sections}}。',
        collapsed: false,
      },
    ],
    variables: [
      { key: 'song', label: '歌曲', type: 'text', defaultValue: '《潮汐》' },
      { key: 'music_genre', label: '曲风', type: 'enum', options: ['City Pop', 'Indie', '电子', '民谣'], defaultValue: 'City Pop' },
      { key: 'core_image', label: '核心意象', type: 'text', defaultValue: '在海边独自起舞的女孩' },
      { key: 'protagonist', label: '主形象', type: 'text', defaultValue: '短发女孩，20 岁' },
      { key: 'symbol', label: '象征物', type: 'text', defaultValue: '老式磁带' },
      { key: 'location', label: '取景地', type: 'text', defaultValue: '上海吴淞口老码头' },
      { key: 'color_tone', label: '主色调', type: 'text', defaultValue: '落日橘 + 海水青' },
      { key: 'lens', label: '主镜头', type: 'text', defaultValue: 'Anamorphic 变形宽银幕' },
      { key: 'beat_alignment', label: '节奏对齐', type: 'text', defaultValue: '鼓点切' },
      { key: 'visual_ref', label: '参考影像', type: 'text', defaultValue: '王家卫《重庆森林》' },
      { key: 'emotion', label: '情绪', type: 'text', defaultValue: '孤独、自由、微醺' },
      { key: 'verse_count', label: '段落数', type: 'number', defaultValue: '4' },
      { key: 'sections', label: '对应段落', type: 'text', defaultValue: '前奏 / 主歌 / 副歌 / 尾奏' },
    ],
    versions: [],
    createdAt: NOW - 18 * day,
    updatedAt: NOW - 5 * day,
    cloneCount: 514,
    rating: 4.6,
  },
  {
    id: 't-005',
    title: '动漫 · 番剧集大纲',
    description: '为番剧单集输出结构化大纲、关键场景与台词钩子。',
    category: 'anime',
    tags: ['动漫', '番剧', '大纲'],
    visibility: 'public',
    author: AUTHORS.su,
    sections: [
      {
        id: 's1',
        key: 'premise',
        title: '前置设定',
        body: '作品 {{title}}，类型 {{genre}}，本集主题 {{episode_theme}}。',
        collapsed: false,
      },
      {
        id: 's2',
        key: 'character',
        title: '角色档案',
        body: '焦点角色 {{focus}}，其对手 {{rival}}，本集心结 {{hangup}}。',
        collapsed: false,
      },
      {
        id: 's3',
        key: 'scene',
        title: '场景描述',
        body: '主场景 {{scene}}，关键地点 {{key_place}}。',
        collapsed: false,
      },
      {
        id: 's4',
        key: 'camera',
        title: '镜头语言',
        body: '分镜风格 {{storyboard}}，关键战斗 / 转折 {{climax}}。',
        collapsed: false,
      },
      {
        id: 's5',
        key: 'tone',
        title: '风格基调',
        body: '情绪 {{mood}}，作画参考 {{art_ref}}。',
        collapsed: false,
      },
      {
        id: 's6',
        key: 'output',
        title: '输出约束',
        body: '输出 {{scenes}} 场戏 + 关键台词 {{lines}} 条，结尾留尾 {{hook}}。',
        collapsed: false,
      },
    ],
    variables: [
      { key: 'title', label: '作品名', type: 'text', defaultValue: '《青焰之夏》' },
      { key: 'genre', label: '类型', type: 'enum', options: ['校园', '奇幻', '机战', '日常', '悬疑'], defaultValue: '校园' },
      { key: 'episode_theme', label: '本集主题', type: 'text', defaultValue: '告白失败后的自我重建' },
      { key: 'focus', label: '焦点角色', type: 'text', defaultValue: '夏目萤' },
      { key: 'rival', label: '对手', type: 'text', defaultValue: '雪村凪' },
      { key: 'hangup', label: '心结', type: 'text', defaultValue: '害怕被讨厌' },
      { key: 'scene', label: '主场景', type: 'text', defaultValue: '夏日烟火大会' },
      { key: 'key_place', label: '关键地点', type: 'text', defaultValue: '天台' },
      { key: 'storyboard', label: '分镜风格', type: 'text', defaultValue: '新海诚式留白 + 京都分镜' },
      { key: 'climax', label: '关键转折', type: 'text', defaultValue: '从高处俯瞰城市' },
      { key: 'mood', label: '情绪', type: 'text', defaultValue: '青涩、释怀' },
      { key: 'art_ref', label: '作画参考', type: 'text', defaultValue: '京阿尼' },
      { key: 'scenes', label: '场数', type: 'number', defaultValue: '6' },
      { key: 'lines', label: '关键台词数', type: 'number', defaultValue: '5' },
      { key: 'hook', label: '尾钩', type: 'text', defaultValue: '第二天桌上一封匿名信' },
    ],
    versions: [],
    createdAt: NOW - 15 * day,
    updatedAt: NOW - 6 * day,
    cloneCount: 612,
    rating: 4.7,
  },
  {
    id: 't-006',
    title: '游戏 · 支线任务剧情',
    description: '为开放世界 RPG 设计 15 分钟支线，含任务流与对白钩子。',
    category: 'game',
    tags: ['游戏', 'RPG', '支线'],
    visibility: 'public',
    author: AUTHORS.zhou,
    sections: [
      {
        id: 's1',
        key: 'premise',
        title: '前置设定',
        body: '游戏 {{game}}，区域 {{region}}，任务名 {{quest}}。',
        collapsed: false,
      },
      {
        id: 's2',
        key: 'character',
        title: '角色档案',
        body: '委托人 {{client}}，隐藏真相 {{truth}}。',
        collapsed: false,
      },
      {
        id: 's3',
        key: 'scene',
        title: '场景描述',
        body: '起始地 {{start}}，目的地 {{destination}}，关键地标 {{landmark}}。',
        collapsed: false,
      },
      {
        id: 's4',
        key: 'camera',
        title: '镜头语言',
        body: '演出风格 {{cutscene}}，关键镜头 {{key_shot}}。',
        collapsed: false,
      },
      {
        id: 's5',
        key: 'tone',
        title: '风格基调',
        body: '氛围 {{atmosphere}}，BGM 关键词 {{bgm_keyword}}。',
        collapsed: false,
      },
      {
        id: 's6',
        key: 'output',
        title: '输出约束',
        body: '输出 {{stages}} 个阶段，关键对白 {{dialogue}} 条，至少 2 个分支。',
        collapsed: false,
      },
    ],
    variables: [
      { key: 'game', label: '游戏', type: 'text', defaultValue: '《山海旅人 2》' },
      { key: 'region', label: '区域', type: 'text', defaultValue: '云泽古道' },
      { key: 'quest', label: '任务名', type: 'text', defaultValue: '灯下旧约' },
      { key: 'client', label: '委托人', type: 'text', defaultValue: '一位老邮差' },
      { key: 'truth', label: '隐藏真相', type: 'text', defaultValue: '他寄出的最后一封信从未到达' },
      { key: 'start', label: '起始地', type: 'text', defaultValue: '雾隐驿' },
      { key: 'destination', label: '目的地', type: 'text', defaultValue: '听涛镇' },
      { key: 'landmark', label: '关键地标', type: 'text', defaultValue: '断桥' },
      { key: 'cutscene', label: '演出风格', type: 'text', defaultValue: '章节式 2.5D 立绘' },
      { key: 'key_shot', label: '关键镜头', type: 'text', defaultValue: '蜡烛倒转燃回' },
      { key: 'atmosphere', label: '氛围', type: 'text', defaultValue: '怀旧、雨中、微光' },
      { key: 'bgm_keyword', label: 'BGM 关键词', type: 'text', defaultValue: '古琴 + 口琴' },
      { key: 'stages', label: '阶段数', type: 'number', defaultValue: '4' },
      { key: 'dialogue', label: '对白数', type: 'number', defaultValue: '8' },
    ],
    versions: [],
    createdAt: NOW - 12 * day,
    updatedAt: NOW - 1 * day,
    cloneCount: 421,
    rating: 4.6,
  },
  {
    id: 't-007',
    title: '短剧 · 古风甜宠开场',
    description: '古风 / 仙侠题材甜宠短剧开场，强调氛围与人物对位。',
    category: 'short_drama',
    tags: ['古风', '甜宠', '短剧'],
    visibility: 'public',
    author: AUTHORS.lin,
    sections: [
      {
        id: 's1',
        key: 'premise',
        title: '前置设定',
        body: '朝代 {{dynasty}}，主题 {{theme}}，受众 {{audience}}。',
        collapsed: false,
      },
      {
        id: 's2',
        key: 'character',
        title: '角色档案',
        body: '女主 {{heroine}}，{{heroine_trait}}；男主 {{hero}}，{{hero_trait}}。',
        collapsed: false,
      },
      {
        id: 's3',
        key: 'scene',
        title: '场景描述',
        body: '场景 {{location}}，节气 {{solar_term}}。',
        collapsed: false,
      },
      {
        id: 's4',
        key: 'camera',
        title: '镜头语言',
        body: '主镜头 {{shot}}，运镜 {{move}}。',
        collapsed: false,
      },
      {
        id: 's5',
        key: 'tone',
        title: '风格基调',
        body: '色调 {{palette}}，参考 {{ref}}。',
        collapsed: false,
      },
      {
        id: 's6',
        key: 'output',
        title: '输出约束',
        body: '输出 {{scenes}} 场戏 + 一句金句钩子。',
        collapsed: false,
      },
    ],
    variables: [
      { key: 'dynasty', label: '朝代', type: 'enum', options: ['架空', '唐', '宋', '明', '清'], defaultValue: '架空' },
      { key: 'theme', label: '主题', type: 'text', defaultValue: '复仇千金与腹黑王爷' },
      { key: 'audience', label: '受众', type: 'text', defaultValue: '18-30 女性' },
      { key: 'heroine', label: '女主', type: 'text', defaultValue: '苏婉宁' },
      { key: 'heroine_trait', label: '女主特质', type: 'text', defaultValue: '外表柔弱内心腹黑' },
      { key: 'hero', label: '男主', type: 'text', defaultValue: '萧彻' },
      { key: 'hero_trait', label: '男主特质', type: 'text', defaultValue: '冷面王爷 / 嘴硬心软' },
      { key: 'location', label: '场景', type: 'text', defaultValue: '王府花园 / 雨夜回廊' },
      { key: 'solar_term', label: '节气', type: 'text', defaultValue: '立秋' },
      { key: 'shot', label: '主镜头', type: 'text', defaultValue: '烟雾 + 慢镜' },
      { key: 'move', label: '运镜', type: 'text', defaultValue: '环绕 360°' },
      { key: 'palette', label: '色调', type: 'text', defaultValue: '水墨青 + 朱砂红' },
      { key: 'ref', label: '参考', type: 'text', defaultValue: '《知否》+《陈情令》' },
      { key: 'scenes', label: '场数', type: 'number', defaultValue: '4' },
    ],
    versions: [],
    createdAt: NOW - 10 * day,
    updatedAt: NOW - 1 * day,
    cloneCount: 998,
    rating: 4.7,
  },
  {
    id: 't-008',
    title: '短视频 · 知识口播脚本',
    description: '60 秒知识口播：钩子 → 现象 → 解释 → 行动。',
    category: 'short_video',
    tags: ['口播', '知识', '短视频'],
    visibility: 'public',
    author: AUTHORS.lan,
    sections: [
      {
        id: 's1',
        key: 'premise',
        title: '前置设定',
        body: '领域 {{field}}，主题 {{topic}}，目标读者 {{reader}}。',
        collapsed: false,
      },
      {
        id: 's2',
        key: 'character',
        title: '角色档案',
        body: '讲者 {{host}}，语气 {{tone_of_voice}}。',
        collapsed: false,
      },
      {
        id: 's3',
        key: 'scene',
        title: '场景描述',
        body: '录制场景 {{setting}}，视觉元素 {{visual}}。',
        collapsed: false,
      },
      {
        id: 's4',
        key: 'camera',
        title: '镜头语言',
        body: '中近景半身，节奏 {{rhythm}}，关键提示字幕 {{caption}}。',
        collapsed: false,
      },
      {
        id: 's5',
        key: 'tone',
        title: '风格基调',
        body: '情绪 {{mood}}，配乐 {{bgm}}。',
        collapsed: false,
      },
      {
        id: 's6',
        key: 'output',
        title: '输出约束',
        body: '字数 {{words}} 字以内，包含 1 个金句 + 1 个行动建议。',
        collapsed: false,
      },
    ],
    variables: [
      { key: 'field', label: '领域', type: 'text', defaultValue: '心理学' },
      { key: 'topic', label: '主题', type: 'text', defaultValue: '为什么越催越慢' },
      { key: 'reader', label: '目标读者', type: 'text', defaultValue: '家长' },
      { key: 'host', label: '讲者', type: 'text', defaultValue: '男，30+，沉稳学者' },
      { key: 'tone_of_voice', label: '语气', type: 'text', defaultValue: '温和、解释型' },
      { key: 'setting', label: '录制场景', type: 'text', defaultValue: '书房 + 书架背景' },
      { key: 'visual', label: '视觉元素', type: 'text', defaultValue: '手写白板 + 关键词高亮' },
      { key: 'rhythm', label: '节奏', type: 'text', defaultValue: '1.3 倍' },
      { key: 'caption', label: '字幕', type: 'text', defaultValue: '3 个关键词条' },
      { key: 'mood', label: '情绪', type: 'text', defaultValue: '共情、引导' },
      { key: 'bgm', label: '配乐', type: 'text', defaultValue: '轻 lo-fi' },
      { key: 'words', label: '字数', type: 'number', defaultValue: '260' },
    ],
    versions: [],
    createdAt: NOW - 9 * day,
    updatedAt: NOW - 2 * day,
    cloneCount: 1502,
    rating: 4.8,
  },
  {
    id: 't-009',
    title: '广告 · 电商详情页脚本',
    description: '为电商详情页主图视频输出 30-60 秒种草脚本。',
    category: 'ad',
    tags: ['电商', '种草', '详情页'],
    visibility: 'public',
    author: AUTHORS.ying,
    sections: [
      {
        id: 's1',
        key: 'premise',
        title: '前置设定',
        body: '产品 {{product}}，核心卖点 {{usp}}，价格带 {{price_band}}。',
        collapsed: false,
      },
      {
        id: 's2',
        key: 'character',
        title: '角色档案',
        body: '主理人 {{founder}}，目标用户 {{user}}。',
        collapsed: false,
      },
      {
        id: 's3',
        key: 'scene',
        title: '场景描述',
        body: '使用场景 {{usage_scene}}，核心痛点 {{pain_point}}。',
        collapsed: false,
      },
      {
        id: 's4',
        key: 'camera',
        title: '镜头语言',
        body: '开镜 {{open}}，产品特写 {{product_shot}}。',
        collapsed: false,
      },
      {
        id: 's5',
        key: 'tone',
        title: '风格基调',
        body: '情绪 {{mood}}，参考 {{ref}}。',
        collapsed: false,
      },
      {
        id: 's6',
        key: 'output',
        title: '输出约束',
        body: '输出 3 段式：痛点 / 方案 / 行动，结尾 CTA：{{cta}}。',
        collapsed: false,
      },
    ],
    variables: [
      { key: 'product', label: '产品', type: 'text', defaultValue: '智能护眼台灯' },
      { key: 'usp', label: '核心卖点', type: 'text', defaultValue: '0 频闪 + 自动感光' },
      { key: 'price_band', label: '价格带', type: 'text', defaultValue: '399-599' },
      { key: 'founder', label: '主理人', type: 'text', defaultValue: '前光学工程师' },
      { key: 'user', label: '目标用户', type: 'text', defaultValue: '深夜加班 / 学生' },
      { key: 'usage_scene', label: '使用场景', type: 'text', defaultValue: '深夜书桌前' },
      { key: 'pain_point', label: '痛点', type: 'text', defaultValue: '眼睛酸 / 易疲劳' },
      { key: 'open', label: '开镜', type: 'text', defaultValue: '昏暗中点亮台灯' },
      { key: 'product_shot', label: '产品特写', type: 'text', defaultValue: '灯头 360° 旋转' },
      { key: 'mood', label: '情绪', type: 'text', defaultValue: '温暖、专业' },
      { key: 'ref', label: '参考', type: 'text', defaultValue: '戴森广告' },
      { key: 'cta', label: 'CTA', type: 'text', defaultValue: '点击购物车领 100 元券' },
    ],
    versions: [],
    createdAt: NOW - 8 * day,
    updatedAt: NOW - 4 * day,
    cloneCount: 745,
    rating: 4.5,
  },
  {
    id: 't-010',
    title: '脱口秀 · 5 分钟段子结构',
    description: '脱口秀 5 分钟段子：铺垫 → 反复 → 翻番 → callback。',
    category: 'custom',
    tags: ['脱口秀', '段子', '结构'],
    visibility: 'public',
    author: AUTHORS.mo,
    sections: [
      {
        id: 's1',
        key: 'premise',
        title: '前置设定',
        body: '主题 {{topic}}，观察角度 {{angle}}，观众画像 {{crowd}}。',
        collapsed: false,
      },
      {
        id: 's2',
        key: 'character',
        title: '角色档案',
        body: '讲者人设 {{persona}}，招牌动作 {{signature}}。',
        collapsed: false,
      },
      {
        id: 's3',
        key: 'scene',
        title: '场景描述',
        body: '开场场景 {{opening_scene}}。',
        collapsed: false,
      },
      {
        id: 's4',
        key: 'camera',
        title: '镜头语言',
        body: '节奏 {{rhythm}}，停顿点 {{pause_at}}。',
        collapsed: false,
      },
      {
        id: 's5',
        key: 'tone',
        title: '风格基调',
        body: '风格 {{style}}，情绪曲线 {{arc}}。',
        collapsed: false,
      },
      {
        id: 's6',
        key: 'output',
        title: '输出约束',
        body: '输出 5 分钟段子结构 + 3 个 punchline + 1 个 callback。',
        collapsed: false,
      },
    ],
    variables: [
      { key: 'topic', label: '主题', type: 'text', defaultValue: '北上广打工人的玄学' },
      { key: 'angle', label: '观察角度', type: 'text', defaultValue: '拜佛的 KPI 化' },
      { key: 'crowd', label: '观众', type: 'text', defaultValue: '一线城市 25-35' },
      { key: 'persona', label: '人设', type: 'text', defaultValue: '冷静吐槽型' },
      { key: 'signature', label: '招牌动作', type: 'text', defaultValue: '挑眉 + 摊手' },
      { key: 'opening_scene', label: '开场场景', type: 'text', defaultValue: '雍和宫排队 3 小时' },
      { key: 'rhythm', label: '节奏', type: 'text', defaultValue: '前快后稳' },
      { key: 'pause_at', label: '停顿点', type: 'text', defaultValue: '反转到第三句前' },
      { key: 'style', label: '风格', type: 'text', defaultValue: '周奇墨式' },
      { key: 'arc', label: '情绪曲线', type: 'text', defaultValue: '共鸣 → 自嘲 → 反转' },
    ],
    versions: [],
    createdAt: NOW - 6 * day,
    updatedAt: NOW - 1 * day,
    cloneCount: 388,
    rating: 4.6,
  },
  {
    id: 't-011',
    title: '广告 · 节日情感短片',
    description: '春节 / 中秋 / 圣诞等节日情感 TVC 模板。',
    category: 'ad',
    tags: ['节日', '情感', 'TVC'],
    visibility: 'public',
    author: AUTHORS.ying,
    sections: [
      {
        id: 's1',
        key: 'premise',
        title: '前置设定',
        body: '节日 {{festival}}，品牌 {{brand}}，情感关键词 {{emotion_keyword}}。',
        collapsed: false,
      },
      {
        id: 's2',
        key: 'character',
        title: '角色档案',
        body: '核心家庭 {{family}}，人物 {{members}}。',
        collapsed: false,
      },
      {
        id: 's3',
        key: 'scene',
        title: '场景描述',
        body: '主场景 {{scene}}，节令元素 {{symbol}}。',
        collapsed: false,
      },
      {
        id: 's4',
        key: 'camera',
        title: '镜头语言',
        body: '主镜头 {{shot}}，关键特写 {{closeup}}。',
        collapsed: false,
      },
      {
        id: 's5',
        key: 'tone',
        title: '风格基调',
        body: '色板 {{palette}}，参考 {{ref}}。',
        collapsed: false,
      },
      {
        id: 's6',
        key: 'output',
        title: '输出约束',
        body: '输出 {{duration}} 秒脚本 + 结尾 slogan：{{slogan}}。',
        collapsed: false,
      },
    ],
    variables: [
      { key: 'festival', label: '节日', type: 'enum', options: ['春节', '中秋', '圣诞', '七夕', '端午'], defaultValue: '春节' },
      { key: 'brand', label: '品牌', type: 'text', defaultValue: 'AURA' },
      { key: 'emotion_keyword', label: '情感关键词', type: 'text', defaultValue: '团圆' },
      { key: 'family', label: '家庭结构', type: 'text', defaultValue: '三代同堂' },
      { key: 'members', label: '成员', type: 'text', defaultValue: '爷爷、父亲、儿子' },
      { key: 'scene', label: '主场景', type: 'text', defaultValue: '北方小院，雪夜' },
      { key: 'symbol', label: '节令元素', type: 'text', defaultValue: '红灯笼 / 饺子' },
      { key: 'shot', label: '主镜头', type: 'text', defaultValue: '固定机位长镜头' },
      { key: 'closeup', label: '关键特写', type: 'text', defaultValue: '老人手' },
      { key: 'palette', label: '色板', type: 'text', defaultValue: '中国红 + 米白 + 雪青' },
      { key: 'ref', label: '参考', type: 'text', defaultValue: 'Apple 春节大片' },
      { key: 'duration', label: '时长（秒）', type: 'number', defaultValue: '90' },
      { key: 'slogan', label: 'Slogan', type: 'text', defaultValue: '回家，就是最好的礼物' },
    ],
    versions: [],
    createdAt: NOW - 5 * day,
    updatedAt: NOW - 1 * day,
    cloneCount: 663,
    rating: 4.8,
  },
  {
    id: 't-012',
    title: '游戏 · Boss 战演出脚本',
    description: '为 Boss 战演出写一段 90 秒演出脚本。',
    category: 'game',
    tags: ['游戏', 'Boss', '演出'],
    visibility: 'public',
    author: AUTHORS.zhou,
    sections: [
      {
        id: 's1',
        key: 'premise',
        title: '前置设定',
        body: 'Boss {{boss}}，所在区域 {{zone}}，阶段 {{phase}}。',
        collapsed: false,
      },
      {
        id: 's2',
        key: 'character',
        title: '角色档案',
        body: 'Boss 背景 {{lore}}，玩家此刻 {{player_state}}。',
        collapsed: false,
      },
      {
        id: 's3',
        key: 'scene',
        title: '场景描述',
        body: '战场 {{arena}}，关键元素 {{arena_prop}}。',
        collapsed: false,
      },
      {
        id: 's4',
        key: 'camera',
        title: '镜头语言',
        body: '主运镜 {{camera}}，关键帧 {{keyframes}}。',
        collapsed: false,
      },
      {
        id: 's5',
        key: 'tone',
        title: '风格基调',
        body: '氛围 {{atmosphere}}，配乐 {{bgm}}。',
        collapsed: false,
      },
      {
        id: 's6',
        key: 'output',
        title: '输出约束',
        body: '输出 90 秒演出脚本 + 1 句 Boss 台词。',
        collapsed: false,
      },
    ],
    variables: [
      { key: 'boss', label: 'Boss', type: 'text', defaultValue: '灰烬之龙·索里安' },
      { key: 'zone', label: '区域', type: 'text', defaultValue: '断脊山巅' },
      { key: 'phase', label: '阶段', type: 'enum', options: ['入场', '一阶段', '二阶段', '终结'], defaultValue: '二阶段' },
      { key: 'lore', label: 'Boss 背景', type: 'text', defaultValue: '曾是守护圣山的神，因人类贪欲堕入灰烬' },
      { key: 'player_state', label: '玩家状态', type: 'text', defaultValue: '残血、孤注一掷' },
      { key: 'arena', label: '战场', type: 'text', defaultValue: '漂浮的碎石祭坛' },
      { key: 'arena_prop', label: '关键元素', type: 'text', defaultValue: '古钟 / 灰烬' },
      { key: 'camera', label: '运镜', type: 'text', defaultValue: '环绕 + 慢镜切快剪' },
      { key: 'keyframes', label: '关键帧', type: 'text', defaultValue: '古钟敲响 + 翅膀展开' },
      { key: 'atmosphere', label: '氛围', type: 'text', defaultValue: '悲壮 / 史诗' },
      { key: 'bgm', label: '配乐', type: 'text', defaultValue: '管弦 + 童声合唱' },
    ],
    versions: [],
    createdAt: NOW - 4 * day,
    updatedAt: NOW - 1 * day,
    cloneCount: 297,
    rating: 4.7,
  },
]
