// Game IP Derivative Works Database - Extended Set Part 8
(function(){
  const EXT = [
  // ============================================================
  // FIRE EMBLEM
  // ============================================================
  {ip:"Fire Emblem", title:"Fire Emblem: Mystery of the Emblem (Anime OVA)", type:"anime", year:1996, region:"JP", publisher:"Shochiku", desc:"OVA 2 集。", tags:["OVA"]},
  {ip:"Fire Emblem", title:"Fire Emblem: Genealogy of the Holy War (Manga)", type:"manga", year:2001, region:"JP", publisher:"Shogakukan", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Fire Emblem", title:"Fire Emblem: Thracia 776 (Manga)", type:"manga", year:2001, region:"JP", publisher:"Shogakukan", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Fire Emblem", title:"Fire Emblem: Binding Blade (Manga)", type:"manga", year:2002, region:"JP", publisher:"Shogakukan", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Fire Emblem", title:"Fire Emblem: The Blazing Blade (Manga)", type:"manga", year:2004, region:"JP", publisher:"Shogakukan", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Fire Emblem", title:"Fire Emblem: The Sacred Stones (Manga)", type:"manga", year:2005, region:"JP", publisher:"Shogakukan", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Fire Emblem", title:"Fire Emblem: Path of Radiance (Manga)", type:"manga", year:2005, region:"JP", publisher:"Shogakukan", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Fire Emblem", title:"Fire Emblem: Radiant Dawn (Manga)", type:"manga", year:2006, region:"JP", publisher:"Shogakukan", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Fire Emblem", title:"Fire Emblem: Awakening (Manga)", type:"manga", year:2012, region:"JP", publisher:"Shogakukan", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Fire Emblem", title:"Fire Emblem: Fates (Manga)", type:"manga", year:2015, region:"JP", publisher:"Shogakukan", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Fire Emblem", title:"Fire Emblem: Three Houses (Manga)", type:"manga", year:2019, region:"JP", publisher:"Shogakukan", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Fire Emblem", title:"Fire Emblem: Engage (Manga)", type:"manga", year:2023, region:"JP", publisher:"Shogakukan", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Fire Emblem", title:"Fire Emblem Heroes (Mobile)", type:"game-mobile", year:2017, region:"Global", publisher:"Nintendo", desc:"手游。", tags:["手游"]},
  {ip:"Fire Emblem", title:"Fire Emblem Warriors", type:"game-spinoff", year:2017, region:"JP", publisher:"Omega Force / Nintendo", desc:"无双衍生。", tags:["无双"]},
  {ip:"Fire Emblem", title:"Fire Emblem Warriors: Three Hopes", type:"game-spinoff", year:2022, region:"JP", publisher:"Omega Force", desc:"无双续作。", tags:["无双"]},
  {ip:"Fire Emblem", title:"Tokyo Mirage Sessions #FE", type:"game-spinoff", year:2015, region:"JP", publisher:"Atlus / Nintendo", desc:"x 女神异闻录联动。", tags:["RPG"]},
  {ip:"Fire Emblem", title:"Fire Emblem Echoes: Shadows of Valentia", type:"game-spinoff", year:2017, region:"JP", publisher:"Nintendo", desc:"重制。", tags:["重制"]},
  {ip:"Fire Emblem", title:"Fire Emblem: Shadow Dragon and the Blade of Light", type:"game-spinoff", year:2008, region:"JP", publisher:"Nintendo", desc:"DS 重制。", tags:["重制"]},
  {ip:"Fire Emblem", title:"Fire Emblem: New Mystery of the Emblem", type:"game-spinoff", year:2010, region:"JP", publisher:"Nintendo", desc:"DS 重制。", tags:["重制"]},
  {ip:"Fire Emblem", title:"Fire Emblem Engage OST", type:"ost", year:2023, region:"JP", publisher:"Nintendo", desc:"原声。", tags:["OST"]},
  {ip:"Fire Emblem", title:"Fire Emblem: Three Houses OST", type:"ost", year:2019, region:"JP", publisher:"Nintendo", desc:"原声。", tags:["OST"]},
  {ip:"Fire Emblem", title:"Fire Emblem (Plush - Marth)", type:"merch-figure", year:2017, region:"JP", publisher:"Nintendo", desc:"马尔斯毛绒。", tags:["毛绒"]},
  {ip:"Fire Emblem", title:"Fire Emblem amiibo (Chrom, Marth, Ike)", type:"merch-figure", year:2014, region:"Global", publisher:"Nintendo", desc:"amiibo。", tags:["amiibo"]},
  {ip:"Fire Emblem", title:"Fire Emblem (Trading Card Game - Fire Emblem Cipher)", type:"merch-card", year:2015, region:"JP", publisher:"Nintendo", desc:"TCG。", tags:["TCG"]},
  {ip:"Fire Emblem", title:"Fire Emblem Engage (The Art of Fire Emblem)", type:"artbook", year:2023, region:"JP", publisher:"Nintendo", desc:"画集。", tags:["画集"]},
  {ip:"Fire Emblem", title:"Fire Emblem (Live Concert 25th Anniversary)", type:"concert", year:2015, region:"JP", publisher:"Nintendo", desc:"25 周年音乐会。", tags:["音乐会"]},
  {ip:"Fire Emblem", title:"Fire Emblem (Smartphone App - Fire Emblem Cipher)", type:"game-mobile", year:2017, region:"JP", publisher:"Nintendo", desc:"手游。", tags:["手游"]},
  {ip:"Fire Emblem", title:"Fire Emblem (Anime in Production - Netflix)", type:"anime", year:2026, region:"JP", publisher:"Netflix", desc:"动画制作中。", tags:["动画"]},
  {ip:"Fire Emblem", title:"Fire Emblem: Path of Radiance (Soundtrack)", type:"ost", year:2005, region:"JP", publisher:"Nintendo", desc:"原声。", tags:["OST"]},

  // ============================================================
  // KIRBY
  // ============================================================
  {ip:"Kirby", title:"Kirby: Right Back at Ya! (Anime)", type:"anime", year:2001, region:"JP", publisher:"Warpstar", desc:"100 集动画。", tags:["动画"]},
  {ip:"Kirby", title:"Kirby (Novel - Kirby: The Dark Invasion)", type:"novel", year:2018, region:"JP", publisher:"Shogakukan", desc:"小说。", tags:["小说"]},
  {ip:"Kirby", title:"Kirby (Manga - Hoshi no Kirby)", type:"manga", year:1994, region:"JP", publisher:"Shogakukan", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Kirby", title:"Kirby (Manga - Hoshi no Kirby Manga Selection)", type:"manga", year:2017, region:"JP", publisher:"Shogakukan", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Kirby", title:"Kirby Fighters (Game)", type:"game-spinoff", year:2012, region:"JP", publisher:"HAL Laboratory", desc:"格斗衍生。", tags:["FTG"]},
  {ip:"Kirby", title:"Kirby: Triple Deluxe (Game)", type:"game-spinoff", year:2014, region:"JP", publisher:"HAL Laboratory", desc:"续作。", tags:["ACT"]},
  {ip:"Kirby", title:"Kirby: Planet Robobot (Game)", type:"game-spinoff", year:2016, region:"JP", publisher:"HAL Laboratory", desc:"续作。", tags:["ACT"]},
  {ip:"Kirby", title:"Kirby Star Allies (Game)", type:"game-spinoff", year:2018, region:"JP", publisher:"HAL Laboratory", desc:"续作。", tags:["ACT"]},
  {ip:"Kirby", title:"Kirby and the Forgotten Land (Game)", type:"game-spinoff", year:2022, region:"JP", publisher:"HAL Laboratory", desc:"3D 续作。", tags:["ACT"]},
  {ip:"Kirby", title:"Kirby's Return to Dream Land Deluxe (Game)", type:"game-spinoff", year:2023, region:"JP", publisher:"HAL Laboratory", desc:"复刻。", tags:["复刻"]},
  {ip:"Kirby", title:"Super Kirby Clash (Game)", type:"game-mobile", year:2019, region:"Global", publisher:"Nintendo", desc:"手游。", tags:["手游"]},
  {ip:"Kirby", title:"Kirby Battle Royale (Game)", type:"game-spinoff", year:2017, region:"JP", publisher:"HAL Laboratory", desc:"3DS 衍生。", tags:["ACT"]},
  {ip:"Kirby", title:"Kirby: Canvas Curse (Game)", type:"game-spinoff", year:2005, region:"JP", publisher:"HAL Laboratory", desc:"NDS 衍生。", tags:["ACT"]},
  {ip:"Kirby", title:"Kirby: Mass Attack (Game)", type:"game-spinoff", year:2011, region:"JP", publisher:"HAL Laboratory", desc:"NDS 衍生。", tags:["ACT"]},
  {ip:"Kirby", title:"Kirby's Dream Land (Game Boy)", type:"game-spinoff", year:1992, region:"JP", publisher:"HAL Laboratory", desc:"GB 续作。", tags:["ACT"]},
  {ip:"Kirby", title:"Kirby's Dream Land 2 (Game Boy)", type:"game-spinoff", year:1995, region:"JP", publisher:"HAL Laboratory", desc:"GB 续作。", tags:["ACT"]},
  {ip:"Kirby", title:"Kirby: Squeak Squad (Game)", type:"game-spinoff", year:2006, region:"JP", publisher:"HAL Laboratory", desc:"NDS 续作。", tags:["ACT"]},
  {ip:"Kirby", title:"Kirby: Squeak Squad OST", type:"ost", year:2006, region:"JP", publisher:"HAL Laboratory", desc:"原声。", tags:["OST"]},
  {ip:"Kirby", title:"Kirby's Epic Yarn (Game)", type:"game-spinoff", year:2010, region:"JP", publisher:"Good-Feel / Nintendo", desc:"Wii 衍生。", tags:["ACT"]},
  {ip:"Kirby", title:"Kirby's Extra Epic Yarn (3DS)", type:"game-spinoff", year:2019, region:"JP", publisher:"Nintendo", desc:"3DS 续作。", tags:["ACT"]},
  {ip:"Kirby", title:"Kirby: Triple Deluxe OST", type:"ost", year:2014, region:"JP", publisher:"HAL Laboratory", desc:"原声。", tags:["OST"]},
  {ip:"Kirby", title:"Kirby: Planet Robobot OST", type:"ost", year:2016, region:"JP", publisher:"HAL Laboratory", desc:"原声。", tags:["OST"]},
  {ip:"Kirby", title:"Kirby and the Forgotten Land OST", type:"ost", year:2022, region:"JP", publisher:"HAL Laboratory", desc:"原声。", tags:["OST"]},
  {ip:"Kirby", title:"Kirby Plush (San-ei)", type:"merch-figure", year:1992, region:"JP", publisher:"San-ei", desc:"卡比毛绒。", tags:["毛绒"]},
  {ip:"Kirby", title:"Kirby amiibo (Multiple)", type:"merch-figure", year:2016, region:"Global", publisher:"Nintendo", desc:"amiibo。", tags:["amiibo"]},
  {ip:"Kirby", title:"Kirby (Funko Pop - Kirby)", type:"merch-figure", year:2019, region:"US", publisher:"Funko", desc:"Funko 公仔。", tags:["Funko"]},
  {ip:"Kirby", title:"Kirby x Uniqlo UT", type:"merch-cloth", year:2019, region:"Global", publisher:"Uniqlo", desc:"UT 联名。", tags:["服装"]},
  {ip:"Kirby", title:"Kirby's Adventure: The Art of Kirby", type:"artbook", year:2017, region:"JP", publisher:"Viz Media", desc:"画集。", tags:["画集"]},
  {ip:"Kirby", title:"Kirby: Star Allies Concert", type:"concert", year:2018, region:"JP", publisher:"Nintendo", desc:"音乐会。", tags:["音乐会"]},

  // ============================================================
  // ANIMAL CROSSING
  // ============================================================
  {ip:"Animal Crossing", title:"Animal Crossing: The Movie (Film 2006)", type:"film-anime", year:2006, region:"JP", publisher:"Nippon Ichi Software", desc:"剧场版。", tags:["剧场版"]},
  {ip:"Animal Crossing", title:"Animal Crossing (Manga - Oideyo Doubutsu no Mori)", type:"manga", year:2004, region:"JP", publisher:"Shogakukan", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Animal Crossing", title:"Animal Crossing: New Horizons (Game)", type:"game-spinoff", year:2020, region:"JP", publisher:"Nintendo", desc:"Switch 续作。", tags:["生活模拟"]},
  {ip:"Animal Crossing", title:"Animal Crossing: New Leaf (Game)", type:"game-spinoff", year:2012, region:"JP", publisher:"Nintendo", desc:"3DS 续作。", tags:["生活模拟"]},
  {ip:"Animal Crossing", title:"Animal Crossing: New Horizons OST", type:"ost", year:2020, region:"JP", publisher:"Nintendo", desc:"原声。", tags:["OST"]},
  {ip:"Animal Crossing", title:"Animal Crossing (Plush - Tom Nook)", type:"merch-figure", year:2002, region:"JP", publisher:"Nintendo", desc:"狸克毛绒。", tags:["毛绒"]},
  {ip:"Animal Crossing", title:"Animal Crossing amiibo (Multiple)", type:"merch-figure", year:2015, region:"Global", publisher:"Nintendo", desc:"amiibo。", tags:["amiibo"]},
  {ip:"Animal Crossing", title:"Animal Crossing x Uniqlo UT", type:"merch-cloth", year:2020, region:"Global", publisher:"Uniqlo", desc:"UT 联名。", tags:["服装"]},
  {ip:"Animal Crossing", title:"Animal Crossing: New Horizons x Build-A-Bear", type:"merch-figure", year:2020, region:"US", publisher:"Build-A-Bear", desc:"毛绒联名。", tags:["毛绒"]},
  {ip:"Animal Crossing", title:"Animal Crossing: New Horizons x Nook Inc. Porch Poster", type:"merch-cloth", year:2020, region:"US", publisher:"Nintendo", desc:"家居联动。", tags:["家居"]},
  {ip:"Animal Crossing", title:"Animal Crossing: New Horizons (Isabelle Funko Pop)", type:"merch-figure", year:2020, region:"US", publisher:"Funko", desc:"西施惠公仔。", tags:["Funko"]},
  {ip:"Animal Crossing", title:"Animal Crossing x Hello Kitty (Sanrio)", type:"collab", year:2021, region:"JP", publisher:"Sanrio", desc:"三丽鸥联名。", tags:["联名"]},
  {ip:"Animal Crossing", title:"Animal Crossing (Concert - Live at Nintendo Live)", type:"concert", year:2021, region:"JP", publisher:"Nintendo", desc:"音乐会。", tags:["音乐会"]},
  {ip:"Animal Crossing", title:"Animal Crossing: New Horizons (Art Book)", type:"artbook", year:2020, region:"JP", publisher:"Nintendo", desc:"画集。", tags:["画集"]},
  {ip:"Animal Crossing", title:"Animal Crossing: Pocket Camp (Mobile)", type:"game-mobile", year:2017, region:"Global", publisher:"Nintendo", desc:"手游。", tags:["手游"]},
  {ip:"Animal Crossing", title:"Animal Crossing: Happy Home Designer", type:"game-spinoff", year:2015, region:"JP", publisher:"Nintendo", desc:"3DS 衍生。", tags:["生活模拟"]},
  {ip:"Animal Crossing", title:"Animal Crossing: amiibo Festival", type:"game-spinoff", year:2015, region:"JP", publisher:"Nintendo", desc:"Wii U 桌游。", tags:["桌游"]},
  {ip:"Animal Crossing", title:"Animal Crossing x Tunick (Photo Project)", type:"collab", year:2023, region:"Global", publisher:"Spencer Tunick", desc:"艺术联动。", tags:["艺术联动"]},
  {ip:"Animal Crossing", title:"Animal Crossing (Manga - Kenta & Friends)", type:"manga", year:2020, region:"JP", publisher:"Shogakukan", desc:"漫画。", tags:["少年漫画"]},

  // ============================================================
  // SPLATOON
  // ============================================================
  {ip:"Splatoon", title:"Splatoon (Manga - Himekuma de Go Go)", type:"manga", year:2016, region:"JP", publisher:"Shogakukan", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Splatoon", title:"Splatoon 2 (Manga - S2 Koshien)", type:"manga", year:2018, region:"JP", publisher:"Shogakukan", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Splatoon", title:"Splatoon 3 (Manga - Otomodachi Collection)", type:"manga", year:2022, region:"JP", publisher:"Shogakukan", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Splatoon", title:"Splatoon (Manga - Splatoon: Ikari no Gotcha)", type:"manga", year:2018, region:"JP", publisher:"Shogakukan", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Splatoon", title:"Splatoon 2: Octo Expansion (DLC)", type:"game-spinoff", year:2018, region:"JP", publisher:"Nintendo", desc:"DLC。", tags:["DLC"]},
  {ip:"Splatoon", title:"Splatoon 3: Side Order (DLC)", type:"game-spinoff", year:2024, region:"JP", publisher:"Nintendo", desc:"DLC。", tags:["DLC"]},
  {ip:"Splatoon", title:"Splatoon 2: Final Fest (Concert)", type:"concert", year:2019, region:"JP", publisher:"Nintendo", desc:"终结祭音乐会。", tags:["音乐会"]},
  {ip:"Splatoon", title:"Splatoon OST (Squid Squad)", type:"ost", year:2015, region:"JP", publisher:"Nintendo", desc:"原声。", tags:["OST"]},
  {ip:"Splatoon", title:"Splatoon 2 OST", type:"ost", year:2017, region:"JP", publisher:"Nintendo", desc:"原声。", tags:["OST"]},
  {ip:"Splatoon", title:"Splatoon 3 OST", type:"ost", year:2022, region:"JP", publisher:"Nintendo", desc:"原声。", tags:["OST"]},
  {ip:"Splatoon", title:"Splatoon (Plush - Inklings)", type:"merch-figure", year:2017, region:"JP", publisher:"Nintendo", desc:"毛绒。", tags:["毛绒"]},
  {ip:"Splatoon", title:"Splatoon amiibo", type:"merch-figure", year:2015, region:"Global", publisher:"Nintendo", desc:"amiibo。", tags:["amiibo"]},
  {ip:"Splatoon", title:"Splatoon x Uniqlo UT", type:"merch-cloth", year:2018, region:"Global", publisher:"Uniqlo", desc:"UT 联名。", tags:["服装"]},
  {ip:"Splatoon", title:"Splatoon (Art Book)", type:"artbook", year:2017, region:"JP", publisher:"Nintendo", desc:"画集。", tags:["画集"]},
  {ip:"Splatoon", title:"Splatoon (The Art of Splatoon 2)", type:"artbook", year:2018, region:"JP", publisher:"Nintendo", desc:"画集。", tags:["画集"]},
  {ip:"Splatoon", title:"Splatoon (The Art of Splatoon 3)", type:"artbook", year:2022, region:"JP", publisher:"Nintendo", desc:"画集。", tags:["画集"]},
  {ip:"Splatoon", title:"Splatoon (Novel - Splatoon: The Toy Box)", type:"novel", year:2018, region:"JP", publisher:"Shogakukan", desc:"小说。", tags:["小说"]},

  // ============================================================
  // METROID
  // ============================================================
  {ip:"Metroid", title:"Metroid (Manga)", type:"manga", year:1993, region:"JP", publisher:"Kodansha", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Metroid", title:"Metroid: Zero Mission (Manga)", type:"manga", year:2004, region:"JP", publisher:"Shogakukan", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Metroid", title:"Metroid: Samus Returns (Game)", type:"game-spinoff", year:2017, region:"JP", publisher:"MercurySteam / Nintendo", desc:"3DS 重制。", tags:["重制"]},
  {ip:"Metroid", title:"Metroid Dread (Game)", type:"game-spinoff", year:2021, region:"JP", publisher:"MercurySteam", desc:"续作。", tags:["ACT"]},
  {ip:"Metroid", title:"Metroid Prime (Remastered 2023)", type:"game-spinoff", year:2023, region:"JP", publisher:"Retro Studios", desc:"重制。", tags:["重制"]},
  {ip:"Metroid", title:"Metroid Prime 2: Echoes", type:"game-spinoff", year:2004, region:"US", publisher:"Retro Studios", desc:"续作。", tags:["ACT"]},
  {ip:"Metroid", title:"Metroid Prime 3: Corruption", type:"game-spinoff", year:2007, region:"US", publisher:"Retro Studios", desc:"续作。", tags:["ACT"]},
  {ip:"Metroid", title:"Metroid Prime 4 (Upcoming)", type:"game-spinoff", year:2026, region:"US", publisher:"Retro Studios", desc:"新作。", tags:["ACT"]},
  {ip:"Metroid", title:"Metroid (Manga - Samus & Joey)", type:"manga", year:2013, region:"US", publisher:"Scholastic", desc:"美式漫画。", tags:["美式漫画"]},
  {ip:"Metroid", title:"Metroid (Plush - Samus)", type:"merch-figure", year:2017, region:"JP", publisher:"Nintendo", desc:"萨姆斯毛绒。", tags:["毛绒"]},
  {ip:"Metroid", title:"Metroid amiibo (Samus)", type:"merch-figure", year:2017, region:"Global", publisher:"Nintendo", desc:"amiibo。", tags:["amiibo"]},
  {ip:"Metroid", title:"Metroid (OST - Metroid Prime 3)", type:"ost", year:2007, region:"US", publisher:"Nintendo", desc:"原声。", tags:["OST"]},
  {ip:"Metroid", title:"Metroid Dread OST", type:"ost", year:2021, region:"JP", publisher:"Nintendo", desc:"原声。", tags:["OST"]},
  {ip:"Metroid", title:"Metroid (Art of Metroid Prime)", type:"artbook", year:2010, region:"US", publisher:"Dark Horse", desc:"画集。", tags:["画集"]},

  // ============================================================
  // DONKEY KONG
  // ============================================================
  {ip:"Donkey Kong", title:"Donkey Kong Country (TV Series)", type:"tv", year:1996, region:"US", publisher:"Nelvana", desc:"动画剧集。", tags:["动画"]},
  {ip:"Donkey Kong", title:"Donkey Kong Country (Manga)", type:"manga", year:1994, region:"JP", publisher:"Shogakukan", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Donkey Kong", title:"Donkey Konga (Game)", type:"game-spinoff", year:2003, region:"JP", publisher:"Nintendo", desc:"音乐游戏。", tags:["音乐"]},
  {ip:"Donkey Kong", title:"Donkey Konga 2 (Game)", type:"game-spinoff", year:2004, region:"JP", publisher:"Nintendo", desc:"音乐游戏。", tags:["音乐"]},
  {ip:"Donkey Kong", title:"Donkey Konga 3 (Game)", type:"game-spinoff", year:2005, region:"JP", publisher:"Nintendo", desc:"音乐游戏。", tags:["音乐"]},
  {ip:"Donkey Kong", title:"Donkey Kong Jungle Beat (Game)", type:"game-spinoff", year:2004, region:"JP", publisher:"Nintendo", desc:"动作游戏。", tags:["ACT"]},
  {ip:"Donkey Kong", title:"DK: King of Swing (Game)", type:"game-spinoff", year:2005, region:"JP", publisher:"Nintendo", desc:"GBA 动作。", tags:["ACT"]},
  {ip:"Donkey Kong", title:"Donkey Kong Barrel Blast (Game)", type:"game-spinoff", year:2007, region:"JP", publisher:"Nintendo", desc:"Wii 衍生。", tags:["ACT"]},
  {ip:"Donkey Kong", title:"Donkey Kong Country Returns (Game)", type:"game-spinoff", year:2010, region:"JP", publisher:"Nintendo / Retro", desc:"Wii 续作。", tags:["ACT"]},
  {ip:"Donkey Kong", title:"Donkey Kong Country: Tropical Freeze", type:"game-spinoff", year:2014, region:"JP", publisher:"Nintendo / Retro", desc:"Wii U 续作。", tags:["ACT"]},
  {ip:"Donkey Kong", title:"Donkey Kong Country: Tropical Freeze (Switch)", type:"game-spinoff", year:2018, region:"JP", publisher:"Nintendo", desc:"Switch 复刻。", tags:["复刻"]},
  {ip:"Donkey Kong", title:"Donkey Kong (Manga - Manga Selection)", type:"manga", year:2017, region:"JP", publisher:"Shogakukan", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Donkey Kong", title:"Donkey Kong Country: Tropical Freeze OST", type:"ost", year:2014, region:"JP", publisher:"Nintendo", desc:"原声。", tags:["OST"]},
  {ip:"Donkey Kong", title:"Donkey Kong (Plush - Donkey Kong)", type:"merch-figure", year:1985, region:"JP", publisher:"San-ei", desc:"大金刚毛绒。", tags:["毛绒"]},
  {ip:"Donkey Kong", title:"Donkey Kong amiibo (Donkey Kong, Diddy, etc.)", type:"merch-figure", year:2014, region:"Global", publisher:"Nintendo", desc:"amiibo。", tags:["amiibo"]},
  {ip:"Donkey Kong", title:"Donkey Kong (Theme Park - Super Nintendo World)", type:"theme-park", year:2024, region:"JP", publisher:"Universal", desc:"主题区。", tags:["主题区"]},
  {ip:"Donkey Kong", title:"Donkey Kong (Samba de Amigo)", type:"game-spinoff", year:2008, region:"JP", publisher:"Sega", desc:"音乐。", tags:["音乐"]},
  {ip:"Donkey Kong", title:"Donkey Kong Country (Manga - Pauline Edition)", type:"manga", year:2018, region:"JP", publisher:"Shogakukan", desc:"漫画。", tags:["少年漫画"]},

  // ============================================================
  // BAYONETTA
  // ============================================================
  {ip:"Bayonetta", title:"Bayonetta: Bloody Fate (Anime Film)", type:"film-anime", year:2013, region:"JP", publisher:"Gonzo", desc:"动画剧场版。", tags:["剧场版"]},
  {ip:"Bayonetta", title:"Bayonetta (Manga)", type:"manga", year:2008, region:"JP", publisher:"Kadokawa", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Bayonetta", title:"Bayonetta 2 (Game)", type:"game-spinoff", year:2014, region:"JP", publisher:"PlatinumGames / Nintendo", desc:"续作。", tags:["ACT"]},
  {ip:"Bayonetta", title:"Bayonetta 3 (Game)", type:"game-spinoff", year:2022, region:"JP", publisher:"PlatinumGames / Nintendo", desc:"续作。", tags:["ACT"]},
  {ip:"Bayonetta", title:"Bayonetta Origins: Cereza and the Lost Demon", type:"game-spinoff", year:2023, region:"JP", publisher:"Nintendo / Platinum", desc:"前传。", tags:["ACT"]},
  {ip:"Bayonetta", title:"Bayonetta (Nendoroid)", type:"merch-figure", year:2019, region:"JP", publisher:"Good Smile", desc:"贝优妮塔粘土人。", tags:["粘土人"]},
  {ip:"Bayonetta", title:"Bayonetta (Figma)", type:"merch-figure", year:2018, region:"JP", publisher:"Max Factory", desc:"Figma。", tags:["Figma"]},
  {ip:"Bayonetta", title:"Bayonetta (Plush)", type:"merch-figure", year:2010, region:"JP", publisher:"PlatinumGames", desc:"毛绒。", tags:["毛绒"]},
  {ip:"Bayonetta", title:"Bayonetta OST (Various)", type:"ost", year:2009, region:"JP", publisher:"PlatinumGames", desc:"原声。", tags:["OST"]},
  {ip:"Bayonetta", title:"Bayonetta 3 OST", type:"ost", year:2022, region:"JP", publisher:"Nintendo", desc:"原声。", tags:["OST"]},
  {ip:"Bayonetta", title:"Bayonetta (Trading Cards - Platinum Games)", type:"merch-card", year:2010, region:"JP", publisher:"PlatinumGames", desc:"卡牌。", tags:["TCG"]},
  {ip:"Bayonetta", title:"Bayonetta (Cosplay Costumes)", type:"merch-cloth", year:2010, region:"JP", publisher:"PlatinumGames", desc:"COS 服。", tags:["COS"]},

  // ============================================================
  // ACE ATTORNEY
  // ============================================================
  {ip:"Ace Attorney", title:"Ace Attorney (Anime Season 1)", type:"anime", year:2016, region:"JP", publisher:"A-1 Pictures", desc:"24 集动画。", tags:["动画"]},
  {ip:"Ace Attorney", title:"Ace Attorney (Anime Season 2)", type:"anime", year:2018, region:"JP", publisher:"CloverWorks", desc:"续作。", tags:["动画"]},
  {ip:"Ace Attorney", title:"Phoenix Wright: Ace Attorney (Manga)", type:"manga", year:2001, region:"JP", publisher:"Kodansha", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Ace Attorney", title:"Ace Attorney: Trials and Tribulations (Manga)", type:"manga", year:2003, region:"JP", publisher:"Kodansha", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Ace Attorney", title:"Ace Attorney: Apollo Justice (Manga)", type:"manga", year:2008, region:"JP", publisher:"Kodansha", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Ace Attorney", title:"Ace Attorney (Gyakuten Saiban Manga Anthology)", type:"manga", year:2012, region:"JP", publisher:"Kodansha", desc:"漫画选集。", tags:["少年漫画"]},
  {ip:"Ace Attorney", title:"Ace Attorney: Dual Destinies (Manga)", type:"manga", year:2014, region:"JP", publisher:"Kodansha", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Ace Attorney", title:"Ace Attorney: Spirit of Justice (Manga)", type:"manga", year:2017, region:"JP", publisher:"Kodansha", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Ace Attorney", title:"Ace Attorney 5 (Game)", type:"game-spinoff", year:2013, region:"JP", publisher:"Capcom", desc:"续作。", tags:["冒险"]},
  {ip:"Ace Attorney", title:"Ace Attorney 6: Spirit of Justice", type:"game-spinoff", year:2016, region:"JP", publisher:"Capcom", desc:"续作。", tags:["冒险"]},
  {ip:"Ace Attorney", title:"Phoenix Wright: Ace Attorney - Dual Destinies", type:"game-spinoff", year:2017, region:"JP", publisher:"Capcom", desc:"3DS 复刻。", tags:["复刻"]},
  {ip:"Ace Attorney", title:"Phoenix Wright: Ace Attorney - Spirit of Justice", type:"game-spinoff", year:2019, region:"JP", publisher:"Capcom", desc:"3DS 复刻。", tags:["复刻"]},
  {ip:"Ace Attorney", title:"The Great Ace Attorney Chronicles", type:"game-spinoff", year:2021, region:"JP", publisher:"Capcom", desc:"新作。", tags:["冒险"]},
  {ip:"Ace Attorney", title:"The Great Ace Attorney 2: Resolve", type:"game-spinoff", year:2017, region:"JP", publisher:"Capcom", desc:"3DS 续作。", tags:["冒险"]},
  {ip:"Ace Attorney", title:"Ace Attorney: Miles Edgeworth (Prosecutor's Path)", type:"game-mobile", year:2017, region:"JP", publisher:"Capcom", desc:"手游。", tags:["手游"]},
  {ip:"Ace Attorney", title:"Ace Attorney (Nendoroid - Phoenix Wright)", type:"merch-figure", year:2018, region:"JP", publisher:"Good Smile", desc:"成步堂粘土人。", tags:["粘土人"]},
  {ip:"Ace Attorney", title:"Ace Attorney (Plush - Phoenix)", type:"merch-figure", year:2017, region:"JP", publisher:"Capcom", desc:"成步堂毛绒。", tags:["毛绒"]},
  {ip:"Ace Attorney", title:"Ace Attorney (OST - Phoenix Wright OST)", type:"ost", year:2001, region:"JP", publisher:"Capcom", desc:"原声。", tags:["OST"]},
  {ip:"Ace Attorney", title:"Ace Attorney (OST - Trials and Tribulations)", type:"ost", year:2004, region:"JP", publisher:"Capcom", desc:"原声。", tags:["OST"]},
  {ip:"Ace Attorney", title:"Ace Attorney (OST - The Great Ace Attorney)", type:"ost", year:2015, region:"JP", publisher:"Capcom", desc:"原声。", tags:["OST"]},
  {ip:"Ace Attorney", title:"Ace Attorney (Stage Play)", type:"theater", year:2017, region:"JP", publisher:"Capcom", desc:"舞台剧。", tags:["舞台剧"]},
  {ip:"Ace Attorney", title:"Ace Attorney (Art Book)", type:"artbook", year:2013, region:"JP", publisher:"Capcom", desc:"画集。", tags:["画集"]},
  {ip:"Ace Attorney", title:"Ace Attorney (Mystery Series - Novel)", type:"novel", year:2018, region:"JP", publisher:"Kadokawa", desc:"小说。", tags:["小说"]},
  {ip:"Ace Attorney", title:"Ace Attorney (Live-Action Film - China)", type:"film-live", year:2025, region:"CN", publisher:"Huanxi Media", desc:"真人电影。", tags:["真人电影"]},

  // ============================================================
  // MEGA MAN
  // ============================================================
  {ip:"Mega Man", title:"Mega Man (Manga - Mega Man NT Warrior)", type:"manga", year:2001, region:"JP", publisher:"Shogakukan", desc:"网络作战。", tags:["少年漫画"]},
  {ip:"Mega Man", title:"Mega Man NT Warrior (Anime)", type:"anime", year:2002, region:"JP", publisher:"Xebec", desc:"动画。", tags:["动画"]},
  {ip:"Mega Man", title:"Mega Man NT Warrior: Axess (Anime)", type:"anime", year:2003, region:"JP", publisher:"Xebec", desc:"动画。", tags:["动画"]},
  {ip:"Mega Man", title:"Mega Man NT Warrior: Stream (Anime)", type:"anime", year:2004, region:"JP", publisher:"Xebec", desc:"动画。", tags:["动画"]},
  {ip:"Mega Man", title:"Mega Man Star Force (Anime)", type:"anime", year:2006, region:"JP", publisher:"Xebec", desc:"动画。", tags:["动画"]},
  {ip:"Mega Man", title:"Mega Man Star Force (Manga)", type:"manga", year:2006, region:"JP", publisher:"Shogakukan", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Mega Man", title:"Mega Man (Archie Comics)", type:"manga", year:2011, region:"US", publisher:"Archie Comics", desc:"美式漫画。", tags:["美式漫画"]},
  {ip:"Mega Man", title:"Mega Man (Manga - The Sequel Novel)", type:"novel", year:2010, region:"JP", publisher:"Shogakukan", desc:"小说。", tags:["小说"]},
  {ip:"Mega Man", title:"Mega Man 11 (Game)", type:"game-spinoff", year:2018, region:"JP", publisher:"Capcom", desc:"续作。", tags:["ACT"]},
  {ip:"Mega Man", title:"Mega Man X (Game Series 1-8)", type:"game-spinoff", year:1993, region:"JP", publisher:"Capcom", desc:"X 系列。", tags:["ACT"]},
  {ip:"Mega Man", title:"Mega Man X Dive (Mobile)", type:"game-mobile", year:2020, region:"JP", publisher:"Capcom", desc:"手游。", tags:["手游"]},
  {ip:"Mega Man", title:"Mega Man Zero (Game Series)", type:"game-spinoff", year:2002, region:"JP", publisher:"Inti Creates", desc:"GBA 续作。", tags:["ACT"]},
  {ip:"Mega Man", title:"Mega Man ZX (Game Series)", type:"game-spinoff", year:2006, region:"JP", publisher:"Inti Creates", desc:"NDS 续作。", tags:["ACT"]},
  {ip:"Mega Man", title:"Mega Man Battle Network (Game Series)", type:"game-spinoff", year:2001, region:"JP", publisher:"Capcom", desc:"GBA 续作。", tags:["RPG"]},
  {ip:"Mega Man", title:"Mega Man Legends (Game)", type:"game-spinoff", year:1997, region:"JP", publisher:"Capcom", desc:"PS1 续作。", tags:["ACT"]},
  {ip:"Mega Man", title:"Mega Man Legends 2 (Game)", type:"game-spinoff", year:2000, region:"JP", publisher:"Capcom", desc:"续作。", tags:["ACT"]},
  {ip:"Mega Man", title:"Mega Man (Plush - Mega Man)", type:"merch-figure", year:2017, region:"JP", publisher:"Capcom", desc:"洛克人毛绒。", tags:["毛绒"]},
  {ip:"Mega Man", title:"Mega Man (Funko Pop)", type:"merch-figure", year:2018, region:"US", publisher:"Funko", desc:"Funko 公仔。", tags:["Funko"]},
  {ip:"Mega Man", title:"Mega Man (Action Figure - D-Arts)", type:"merch-figure", year:2014, region:"JP", publisher:"Bandai", desc:"可动人偶。", tags:["可动"]},
  {ip:"Mega Man", title:"Mega Man (Nendoroid)", type:"merch-figure", year:2018, region:"JP", publisher:"Good Smile", desc:"粘土人。", tags:["粘土人"]},
  {ip:"Mega Man", title:"Mega Man OST (Various)", type:"ost", year:1987, region:"JP", publisher:"Capcom", desc:"原声。", tags:["OST"]},
  {ip:"Mega Man", title:"Mega Man 11 OST", type:"ost", year:2018, region:"JP", publisher:"Capcom", desc:"原声。", tags:["OST"]},
  {ip:"Mega Man", title:"Mega Man (Pachinko)", type:"pachinko", year:2016, region:"JP", publisher:"Sammy", desc:"柏青哥。", tags:["柏青哥"]},
  {ip:"Mega Man", title:"Mega Man x Uniqlo UT", type:"merch-cloth", year:2018, region:"Global", publisher:"Uniqlo", desc:"UT 联名。", tags:["服装"]},
  {ip:"Mega Man", title:"Mega Man x Bandai (Robot)", type:"merch-toy", year:2019, region:"JP", publisher:"Bandai", desc:"可动模型。", tags:["模型"]},

  // ============================================================
  // TRAILS (FALCOM)
  // ============================================================
  {ip:"Trails", title:"Trails in the Sky (Manga)", type:"manga", year:2011, region:"JP", publisher:"Kadokawa", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Trails", title:"Trails of Cold Steel (Manga)", type:"manga", year:2014, region:"JP", publisher:"Kadokawa", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Trails", title:"Trails of Cold Steel (Anime)", type:"anime", year:2019, region:"JP", publisher:"Kinema Citrus", desc:"动画。", tags:["动画"]},
  {ip:"Trails", title:"Trails of Cold Steel (Manga - Altina's Story)", type:"manga", year:2018, region:"JP", publisher:"Kadokawa", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Trails", title:"Trails of Cold Steel (Manga - The Animation)", type:"manga", year:2019, region:"JP", publisher:"Kadokawa", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Trails", title:"Trails of Cold Steel (Stage Play)", type:"theater", year:2016, region:"JP", publisher:"Falcom", desc:"舞台剧。", tags:["舞台剧"]},
  {ip:"Trails", title:"Trails of Cold Steel (Novel - The Novel)", type:"novel", year:2016, region:"JP", publisher:"Kadokawa", desc:"小说。", tags:["小说"]},
  {ip:"Trails", title:"Trails (OST - Falcom jdk BAND)", type:"ost", year:2010, region:"JP", publisher:"Falcom", desc:"原声。", tags:["OST"]},
  {ip:"Trails", title:"Trails in the Sky OST", type:"ost", year:2004, region:"JP", publisher:"Falcom", desc:"原声。", tags:["OST"]},
  {ip:"Trails", title:"Trails of Cold Steel OST", type:"ost", year:2013, region:"JP", publisher:"Falcom", desc:"原声。", tags:["OST"]},
  {ip:"Trails", title:"Trails (Plush - Estelle)", type:"merch-figure", year:2014, region:"JP", publisher:"Falcom", desc:"艾丝蒂尔毛绒。", tags:["毛绒"]},
  {ip:"Trails", title:"Trails (Nendoroid - Estelle Bright)", type:"merch-figure", year:2019, region:"JP", publisher:"Good Smile", desc:"艾丝蒂尔粘土人。", tags:["粘土人"]},
  {ip:"Trails", title:"Trails (Nendoroid - Joshua Bright)", type:"merch-figure", year:2019, region:"JP", publisher:"Good Smile", desc:"约书亚粘土人。", tags:["粘土人"]},
  {ip:"Trails", title:"Trails (Nendoroid - Rean)", type:"merch-figure", year:2019, region:"JP", publisher:"Good Smile", desc:"黎恩粘土人。", tags:["粘土人"]},
  {ip:"Trails", title:"Trails (Art Book - Falcom)", type:"artbook", year:2017, region:"JP", publisher:"Falcom", desc:"画集。", tags:["画集"]},
  {ip:"Trails", title:"Trails (Falcom Music Festival)", type:"concert", year:2017, region:"JP", publisher:"Falcom", desc:"音乐会。", tags:["音乐会"]},
  {ip:"Trails", title:"Trails (Funko Pop - Estelle)", type:"merch-figure", year:2020, region:"US", publisher:"Funko", desc:"Funko 公仔。", tags:["Funko"]},

  // ============================================================
  // YS (FALCOM)
  // ============================================================
  {ip:"Ys", title:"Ys I & II (Manga)", type:"manga", year:1988, region:"JP", publisher:"Kadokawa", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Ys", title:"Ys III: Wanderers from Ys (Manga)", type:"manga", year:1990, region:"JP", publisher:"Kadokawa", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Ys", title:"Ys IV: Mask of the Sun (Manga)", type:"manga", year:1994, region:"JP", publisher:"Kadokawa", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Ys", title:"Ys vs. Sora no Kiseki: Alternative Saga", type:"game-spinoff", year:2010, region:"JP", publisher:"Falcom", desc:"动作衍生。", tags:["ACT"]},
  {ip:"Ys", title:"Ys Origin", type:"game-spinoff", year:2006, region:"JP", publisher:"Falcom", desc:"前传。", tags:["ARPG"]},
  {ip:"Ys", title:"Ys VIII: Lacrimosa of Dana", type:"game-spinoff", year:2016, region:"JP", publisher:"Falcom", desc:"续作。", tags:["ARPG"]},
  {ip:"Ys", title:"Ys IX: Monstrum Nox", type:"game-spinoff", year:2019, region:"JP", publisher:"Falcom", desc:"续作。", tags:["ARPG"]},
  {ip:"Ys", title:"Ys X: Nordics", type:"game-spinoff", year:2023, region:"JP", publisher:"Falcom", desc:"续作。", tags:["ARPG"]},
  {ip:"Ys", title:"Ys (OST - Falcom Sound Team jdk)", type:"ost", year:1987, region:"JP", publisher:"Falcom", desc:"原声。", tags:["OST"]},
  {ip:"Ys", title:"Ys (Nendoroid - Adol)", type:"merch-figure", year:2018, region:"JP", publisher:"Good Smile", desc:"亚特鲁粘土人。", tags:["粘土人"]},
  {ip:"Ys", title:"Ys (Funko Pop - Adol)", type:"merch-figure", year:2020, region:"US", publisher:"Funko", desc:"Funko 公仔。", tags:["Funko"]},
  {ip:"Ys", title:"Ys (Plush - Adol)", type:"merch-figure", year:2018, region:"JP", publisher:"Falcom", desc:"亚特鲁毛绒。", tags:["毛绒"]},

  // ============================================================
  // DANGANRONPA
  // ============================================================
  {ip:"Danganronpa", title:"Danganronpa: The Animation", type:"anime", year:2013, region:"JP", publisher:"Lerche", desc:"13 集动画。", tags:["动画"]},
  {ip:"Danganronpa", title:"Danganronpa 3: The End of Hope's Peak High School (Anime)", type:"anime", year:2016, region:"JP", publisher:"Lerche", desc:"动画续作。", tags:["动画"]},
  {ip:"Danganronpa", title:"Danganronpa V3: Killing Harmony (Game)", type:"game-spinoff", year:2017, region:"JP", publisher:"Spike Chunsoft", desc:"续作。", tags:["冒险"]},
  {ip:"Danganronpa", title:"Danganronpa 2: Goodbye Despair (Game)", type:"game-spinoff", year:2012, region:"JP", publisher:"Spike Chunsoft", desc:"续作。", tags:["冒险"]},
  {ip:"Danganronpa", title:"Danganronpa S: Ultimate Summer Camp", type:"game-spinoff", year:2021, region:"JP", publisher:"Spike Chunsoft", desc:"Q 版。", tags:["策略"]},
  {ip:"Danganronpa", title:"Danganronpa: Trigger Happy Havoc (Manga)", type:"manga", year:2011, region:"JP", publisher:"Ichijinsha", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Danganronpa", title:"Danganronpa 2: Goodbye Despair (Manga)", type:"manga", year:2012, region:"JP", publisher:"Ichijinsha", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Danganronpa", title:"Danganronpa: The Animation (Manga)", type:"manga", year:2013, region:"JP", publisher:"Ichijinsha", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Danganronpa", title:"Danganronpa: Kirigiri (Novel)", type:"novel", year:2013, region:"JP", publisher:"Ichijinsha", desc:"小说。", tags:["小说"]},
  {ip:"Danganronpa", title:"Danganronpa: Togami (Novel)", type:"novel", year:2014, region:"JP", publisher:"Ichijinsha", desc:"小说。", tags:["小说"]},
  {ip:"Danganronpa", title:"Danganronpa: Nanami (Novel)", type:"novel", year:2014, region:"JP", publisher:"Ichijinsha", desc:"小说。", tags:["小说"]},
  {ip:"Danganronpa", title:"Danganronpa (Nendoroid - Monokuma)", type:"merch-figure", year:2014, region:"JP", publisher:"Good Smile", desc:"黑白熊粘土人。", tags:["粘土人"]},
  {ip:"Danganronpa", title:"Danganronpa (Plush - Monokuma)", type:"merch-figure", year:2014, region:"JP", publisher:"Spike Chunsoft", desc:"黑白熊毛绒。", tags:["毛绒"]},
  {ip:"Danganronpa", title:"Danganronpa (Funko Pop - Monokuma)", type:"merch-figure", year:2018, region:"US", publisher:"Funko", desc:"Funko 公仔。", tags:["Funko"]},
  {ip:"Danganronpa", title:"Danganronpa OST (Masafumi Takada)", type:"ost", year:2010, region:"JP", publisher:"Spike Chunsoft", desc:"原声。", tags:["OST"]},
  {ip:"Danganronpa", title:"Danganronpa 2 OST", type:"ost", year:2012, region:"JP", publisher:"Spike Chunsoft", desc:"原声。", tags:["OST"]},
  {ip:"Danganronpa", title:"Danganronpa V3 OST", type:"ost", year:2017, region:"JP", publisher:"Spike Chunsoft", desc:"原声。", tags:["OST"]},
  {ip:"Danganronpa", title:"Danganronpa: Killer Killer (Manga)", type:"manga", year:2015, region:"JP", publisher:"Ichijinsha", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Danganronpa", title:"Danganronpa (Stage Play)", type:"theater", year:2014, region:"JP", publisher:"Marvelous", desc:"舞台剧。", tags:["舞台剧"]},
  {ip:"Danganronpa", title:"Danganronpa 2.5 (Manga)", type:"manga", year:2016, region:"JP", publisher:"Ichijinsha", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Danganronpa", title:"Danganronpa (Trading Card)", type:"merch-card", year:2015, region:"JP", publisher:"Spike Chunsoft", desc:"TCG。", tags:["TCG"]},

  // ============================================================
  // YAKUZA / LIKE A DRAGON
  // ============================================================
  {ip:"Yakuza", title:"Yakuza (Live-Action Film 2007 - Japan)", type:"film-live", year:2007, region:"JP", publisher:"Sega / Toei", desc:"日本真人电影。", tags:["真人电影"]},
  {ip:"Yakuza", title:"Yakuza: Like a Dragon (Live-Action Film - Like a Dragon)", type:"film-live", year:2024, region:"JP", publisher:"Sega", desc:"真人电影。", tags:["真人电影"]},
  {ip:"Yakuza", title:"Yakuza (Manga - Kurohyou)", type:"manga", year:2010, region:"JP", publisher:"Sega", desc:"外传漫画。", tags:["少年漫画"]},
  {ip:"Yakuza", title:"Yakuza (Manga - Kurohyou 2)", type:"manga", year:2012, region:"JP", publisher:"Sega", desc:"外传续作。", tags:["少年漫画"]},
  {ip:"Yakuza", title:"Like a Dragon: Ishin! (Kiwami)", type:"game-spinoff", year:2023, region:"JP", publisher:"Sega / RGG Studio", desc:"动作 RPG。", tags:["ARPG"]},
  {ip:"Yakuza", title:"Yakuza 0 (Game)", type:"game-spinoff", year:2015, region:"JP", publisher:"Sega", desc:"前传。", tags:["ACT"]},
  {ip:"Yakuza", title:"Yakuza Kiwami", type:"game-spinoff", year:2016, region:"JP", publisher:"Sega", desc:"重制。", tags:["重制"]},
  {ip:"Yakuza", title:"Yakuza Kiwami 2", type:"game-spinoff", year:2017, region:"JP", publisher:"Sega", desc:"重制。", tags:["重制"]},
  {ip:"Yakuza", title:"Yakuza 3 Remastered", type:"game-spinoff", year:2021, region:"JP", publisher:"Sega", desc:"重制。", tags:["重制"]},
  {ip:"Yakuza", title:"Yakuza 4 Remastered", type:"game-spinoff", year:2021, region:"JP", publisher:"Sega", desc:"重制。", tags:["重制"]},
  {ip:"Yakuza", title:"Yakuza 5 Remastered", type:"game-spinoff", year:2021, region:"JP", publisher:"Sega", desc:"重制。", tags:["重制"]},
  {ip:"Yakuza", title:"Yakuza 6: The Song of Life", type:"game-spinoff", year:2016, region:"JP", publisher:"Sega", desc:"续作。", tags:["ACT"]},
  {ip:"Yakuza", title:"Like a Dragon: Infinite Wealth", type:"game-spinoff", year:2024, region:"JP", publisher:"Sega", desc:"续作。", tags:["RPG"]},
  {ip:"Yakuza", title:"Like a Dragon: Pirate Yakuza in Hawaii", type:"game-spinoff", year:2025, region:"JP", publisher:"Sega", desc:"续作。", tags:["ACT"]},
  {ip:"Yakuza", title:"Yakuza: Dead Souls", type:"game-spinoff", year:2011, region:"JP", publisher:"Sega", desc:"僵尸外传。", tags:["ACT"]},
  {ip:"Yakuza", title:"Yakuza: Black Panther (Kurohyou)", type:"game-spinoff", year:2010, region:"JP", publisher:"Sega", desc:"PSP 外传。", tags:["ACT"]},
  {ip:"Yakuza", title:"Ryu ga Gotoku Online (Mobile)", type:"game-mobile", year:2018, region:"JP", publisher:"Sega", desc:"手游。", tags:["手游"]},
  {ip:"Yakuza", title:"Judgment (Game)", type:"game-spinoff", year:2018, region:"JP", publisher:"Sega", desc:"外传。", tags:["ACT"]},
  {ip:"Yakuza", title:"Lost Judgment", type:"game-spinoff", year:2021, region:"JP", publisher:"Sega", desc:"续作。", tags:["ACT"]},
  {ip:"Yakuza", title:"Like a Dragon Gaiden: The Man Who Erased His Name", type:"game-spinoff", year:2023, region:"JP", publisher:"Sega", desc:"外传。", tags:["ACT"]},
  {ip:"Yakuza", title:"Yakuza (Manga - Ryu ga Gotoku Side Stories)", type:"manga", year:2017, region:"JP", publisher:"Sega", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Yakuza", title:"Yakuza (Novel - The Film)", type:"novel", year:2007, region:"JP", publisher:"Sega", desc:"小说。", tags:["小说"]},
  {ip:"Yakuza", title:"Yakuza (OST - Various)", type:"ost", year:2005, region:"JP", publisher:"Sega", desc:"原声。", tags:["OST"]},
  {ip:"Yakuza", title:"Yakuza (Plush - Kiryu)", type:"merch-figure", year:2017, region:"JP", publisher:"Sega", desc:"桐生毛绒。", tags:["毛绒"]},
  {ip:"Yakuza", title:"Yakuza (Funko Pop - Kiryu)", type:"merch-figure", year:2018, region:"US", publisher:"Funko", desc:"Funko 公仔。", tags:["Funko"]},
  {ip:"Yakuza", title:"Yakuza (Art Book - Yakuza: Like a Dragon Artbook)", type:"artbook", year:2020, region:"JP", publisher:"Sega", desc:"画集。", tags:["画集"]},
  {ip:"Yakuza", title:"Yakuza (Theme Cafe - Sega)", type:"cafe", year:2018, region:"JP", publisher:"Sega", desc:"主题咖啡。", tags:["主题咖啡"]},
  {ip:"Yakuza", title:"Yakuza (Pachinko)", type:"pachinko", year:2012, region:"JP", publisher:"Sammy", desc:"柏青哥。", tags:["柏青哥"]},
  ];
  window.DATA = window.DATA.concat(EXT);
})();
