// Game IP Derivative Works Database - Extended Set Part 7
(function(){
  const EXT = [
  // ============================================================
  // LEAGUE OF LEGENDS (Riot Games)
  // ============================================================
  {ip:"League of Legends", title:"Arcane (Netflix Animated Series)", type:"anime", year:2021, region:"US", publisher:"Riot Games / Fortiche", desc:"2 季网飞动画。", tags:["动画"]},
  {ip:"League of Legends", title:"Arcane S2 (Netflix)", type:"anime", year:2024, region:"US", publisher:"Riot Games / Fortiche", desc:"续作。", tags:["动画"]},
  {ip:"League of Legends", title:"League of Legends: Wild Rift (Mobile)", type:"game-mobile", year:2020, region:"Global", publisher:"Riot Games", desc:"手游 MOBA。", tags:["MOBA"]},
  {ip:"League of Legends", title:"League of Legends (Manga - Zed, Jhin, Ekko)", type:"manga", year:2018, region:"US", publisher:"Marvel", desc:"漫威漫画。", tags:["美式漫画"]},
  {ip:"League of Legends", title:"League of Legends: Ashe: Warmother (Manga)", type:"manga", year:2019, region:"US", publisher:"Marvel", desc:"漫威漫画。", tags:["美式漫画"]},
  {ip:"League of Legends", title:"League of Legends: Lux (Manga)", type:"manga", year:2019, region:"US", publisher:"Marvel", desc:"漫威漫画。", tags:["美式漫画"]},
  {ip:"League of Legends", title:"League of Legends: Spirit Blossom (Webseries)", type:"web-series", year:2020, region:"US", publisher:"Riot Games", desc:"Web 短剧。", tags:["Web 短剧"]},
  {ip:"League of Legends", title:"League of Legends: Warriors (2022 Cinematic)", type:"web-series", year:2022, region:"US", publisher:"Riot Games", desc:"动画短片。", tags:["短片"]},
  {ip:"League of Legends", title:"Ruined King: A League of Legends Story", type:"game-spinoff", year:2021, region:"US", publisher:"Riot Games / Airship", desc:"回合制 RPG。", tags:["RPG"]},
  {ip:"League of Legends", title:"Hextech Mayhem: A League of Legends Story", type:"game-spinoff", year:2021, region:"US", publisher:"Riot Games / Choice Provisions", desc:"音乐节奏。", tags:["音乐"]},
  {ip:"League of Legends", title:"Mageseeker: A League of Legends Story", type:"game-spinoff", year:2023, region:"US", publisher:"Riot Games / Digital Sun", desc:"ARPG。", tags:["ARPG"]},
  {ip:"League of Legends", title:"Convergence: A League of Legends Story", type:"game-spinoff", year:2023, region:"US", publisher:"Riot Games / Double Stallion", desc:"动作。", tags:["ACT"]},
  {ip:"League of Legends", title:"Song of Nunu: A League of Legends Story", type:"game-spinoff", year:2023, region:"US", publisher:"Riot Games / Tequila Works", desc:"冒险。", tags:["冒险"]},
  {ip:"League of Legends", title:"Bandle Tale: A League of Legends Story", type:"game-spinoff", year:2024, region:"US", publisher:"Riot Games / Lazy Bear", desc:"生活模拟。", tags:["生活"]},
  {ip:"League of Legends", title:"2XKO (Fighting Game)", type:"game-spinoff", year:2025, region:"US", publisher:"Riot Games", desc:"格斗新作。", tags:["FTG"]},
  {ip:"League of Legends", title:"Project L (Fighting Game - Renamed)", type:"game-spinoff", year:2025, region:"US", publisher:"Riot Games", desc:"格斗新作。", tags:["FTG"]},
  {ip:"League of Legends", title:"League of Legends: Teamfight Tactics (TFT)", type:"game-spinoff", year:2019, region:"US", publisher:"Riot Games", desc:"自走棋。", tags:["自走棋"]},
  {ip:"League of Legends", title:"League of Legends: Legends of Runeterra", type:"game-mobile", year:2020, region:"US", publisher:"Riot Games", desc:"卡牌游戏。", tags:["卡牌"]},
  {ip:"League of Legends", title:"League of Legends Esports Manager", type:"game-mobile", year:2023, region:"US", publisher:"Riot Games", desc:"电竞经理。", tags:["模拟"]},
  {ip:"League of Legends", title:"Arcane OST (Various Artists)", type:"ost", year:2021, region:"US", publisher:"Riot Games", desc:"动画原声。", tags:["OST"]},
  {ip:"League of Legends", title:"Worlds Anthem (2023 - GODS)", type:"ost", year:2023, region:"US", publisher:"Riot Games", desc:"S13 主题曲。", tags:["主题曲"]},
  {ip:"League of Legends", title:"Worlds Anthem (2022 - Star Walkin')", type:"ost", year:2022, region:"US", publisher:"Riot Games", desc:"S12 主题曲。", tags:["主题曲"]},
  {ip:"League of Legends", title:"Worlds Anthem (2024)", type:"ost", year:2024, region:"US", publisher:"Riot Games", desc:"S14 主题曲。", tags:["主题曲"]},
  {ip:"League of Legends", title:"K/DA (Music Group - virtual)", type:"ost", year:2018, region:"US", publisher:"Riot Games", desc:"虚拟偶像组合。", tags:["虚拟偶像"]},
  {ip:"League of Legends", title:"K/DA: ALL OUT (Album)", type:"ost", year:2020, region:"US", publisher:"Riot Games", desc:"专辑。", tags:["OST"]},
  {ip:"League of Legends", title:"True Damage (Music Group)", type:"ost", year:2019, region:"US", publisher:"Riot Games", desc:"虚拟组合。", tags:["虚拟偶像"]},
  {ip:"League of Legends", title:"Heartsteel (Music Group)", type:"ost", year:2023, region:"US", publisher:"Riot Games", desc:"虚拟组合。", tags:["虚拟偶像"]},
  {ip:"League of Legends", title:"League of Legends Funko Pop (Jinx)", type:"merch-figure", year:2020, region:"US", publisher:"Funko", desc:"Funko 公仔。", tags:["Funko"]},
  {ip:"League of Legends", title:"League of Legends: Ahri (Nendoroid)", type:"merch-figure", year:2022, region:"JP", publisher:"Good Smile", desc:"阿狸粘土人。", tags:["粘土人"]},
  {ip:"League of Legends", title:"League of Legends: Jinx Statue", type:"merch-figure", year:2021, region:"US", publisher:"Gaming Heads", desc:"金克丝雕像。", tags:["雕像"]},
  {ip:"League of Legends", title:"League of Legends x Uniqlo UT", type:"merch-cloth", year:2020, region:"Global", publisher:"Uniqlo", desc:"UT 联名。", tags:["服装"]},
  {ip:"League of Legends", title:"League of Legends x Louis Vuitton", type:"collab", year:2019, region:"Global", publisher:"Louis Vuitton", desc:"LV 联名。", tags:["奢侈品"]},
  {ip:"League of Legends", title:"League of Legends x Nike", type:"merch-cloth", year:2020, region:"Global", publisher:"Nike", desc:"耐克联名。", tags:["服装"]},
  {ip:"League of Legends", title:"League of Legends x H&M", type:"merch-cloth", year:2022, region:"Global", publisher:"H&M", desc:"H&M 联名。", tags:["服装"]},
  {ip:"League of Legends", title:"League of Legends (Esports - Worlds)", type:"event", year:2011, region:"Global", publisher:"Riot Games", desc:"全球总决赛。", tags:["电竞赛"]},
  {ip:"League of Legends", title:"League of Legends (Esports - MSI)", type:"event", year:2015, region:"Global", publisher:"Riot Games", desc:"季中冠军赛。", tags:["电竞赛"]},
  {ip:"League of Legends", title:"League of Legends (Trading Card Game - LoR)", type:"merch-card", year:2020, region:"US", publisher:"Riot Games", desc:"TCG。", tags:["TCG"]},
  {ip:"League of Legends", title:"League of Legends (Statue - Jinx Arcane)", type:"merch-figure", year:2021, region:"US", publisher:"Pure Arts", desc:"雕像。", tags:["雕像"]},
  {ip:"League of Legends", title:"League of Legends: Worlds Anthem 2021 (Burn It All Down)", type:"ost", year:2021, region:"US", publisher:"Riot Games", desc:"S11 主题曲。", tags:["主题曲"]},
  {ip:"League of Legends", title:"League of Legends: Arcane Concert", type:"concert", year:2022, region:"US", publisher:"Riot Games", desc:"动画音乐会。", tags:["音乐会"]},

  // ============================================================
  // VALORANT (Riot Games)
  // ============================================================
  {ip:"Valorant", title:"Valorant (Esports - Champions)", type:"event", year:2022, region:"Global", publisher:"Riot Games", desc:"全球冠军赛。", tags:["电竞赛"]},
  {ip:"Valorant", title:"Valorant: Agent Cinematic Series (Jett)", type:"web-series", year:2020, region:"US", publisher:"Riot Games", desc:"特工动画。", tags:["短动画"]},
  {ip:"Valorant", title:"Valorant: The Agents", type:"web-series", year:2020, region:"US", publisher:"Riot Games", desc:"特工介绍。", tags:["短片"]},
  {ip:"Valorant", title:"Valorant (Manga)", type:"manga", year:2022, region:"US", publisher:"Marvel", desc:"漫威漫画。", tags:["美式漫画"]},
  {ip:"Valorant", title:"Valorant Mobile (Mobile)", type:"game-mobile", year:2025, region:"Global", publisher:"Riot Games", desc:"手游。", tags:["手游"]},
  {ip:"Valorant", title:"Valorant (Action Figure - Jett)", type:"merch-figure", year:2021, region:"US", publisher:"Funko", desc:"Funko 公仔。", tags:["Funko"]},
  {ip:"Valorant", title:"Valorant Funko Pop (Jett, Phoenix, Sage)", type:"merch-figure", year:2021, region:"US", publisher:"Funko", desc:"Funko 系列。", tags:["Funko"]},
  {ip:"Valorant", title:"Valorant x Uniqlo UT", type:"merch-cloth", year:2021, region:"Global", publisher:"Uniqlo", desc:"UT 联名。", tags:["服装"]},
  {ip:"Valorant", title:"Valorant OST (Champions 2022 Theme)", type:"ost", year:2022, region:"US", publisher:"Riot Games", desc:"主题曲。", tags:["OST"]},

  // ============================================================
  // OVERWATCH (Blizzard)
  // ============================================================
  {ip:"Overwatch", title:"Overwatch (Original Game)", type:"game-spinoff", year:2016, region:"US", publisher:"Blizzard", desc:"原版。", tags:["FPS"]},
  {ip:"Overwatch", title:"Overwatch 2", type:"game-spinoff", year:2022, region:"US", publisher:"Blizzard", desc:"续作。", tags:["FPS"]},
  {ip:"Overwatch", title:"Overwatch (Animated Shorts)", type:"web-series", year:2016, region:"US", publisher:"Blizzard", desc:"动画短片系列。", tags:["短动画"]},
  {ip:"Overwatch", title:"Overwatch: Reunion (Cinematic)", type:"web-series", year:2018, region:"US", publisher:"Blizzard", desc:"动画短片。", tags:["短片"]},
  {ip:"Overwatch", title:"Overwatch: Zero Hour (Cinematic)", type:"web-series", year:2019, region:"US", publisher:"Blizzard", desc:"动画短片。", tags:["短片"]},
  {ip:"Overwatch", title:"Overwatch (Manga - Anthology)", type:"manga", year:2018, region:"US", publisher:"Dark Horse", desc:"黑马漫画。", tags:["美式漫画"]},
  {ip:"Overwatch", title:"Overwatch: Tracer - London Calling (Comic)", type:"manga", year:2020, region:"US", publisher:"Dark Horse", desc:"黑马漫画。", tags:["美式漫画"]},
  {ip:"Overwatch", title:"Overwatch: The Art of Overwatch", type:"artbook", year:2017, region:"US", publisher:"Dark Horse", desc:"画集。", tags:["画集"]},
  {ip:"Overwatch", title:"Overwatch: The Art of Overwatch 2", type:"artbook", year:2022, region:"US", publisher:"Dark Horse", desc:"画集。", tags:["画集"]},
  {ip:"Overwatch", title:"Overwatch (Funko Pop - Tracer)", type:"merch-figure", year:2016, region:"US", publisher:"Funko", desc:"Funko 公仔。", tags:["Funko"]},
  {ip:"Overwatch", title:"Overwatch (Nendoroid - Tracer)", type:"merch-figure", year:2017, region:"JP", publisher:"Good Smile", desc:"猎空粘土人。", tags:["粘土人"]},
  {ip:"Overwatch", title:"Overwatch (Nendoroid - D.Va)", type:"merch-figure", year:2019, region:"JP", publisher:"Good Smile", desc:"D.Va 粘土人。", tags:["粘土人"]},
  {ip:"Overwatch", title:"Overwatch (Nendoroid - Mercy)", type:"merch-figure", year:2018, region:"JP", publisher:"Good Smile", desc:"天使粘土人。", tags:["粘土人"]},
  {ip:"Overwatch", title:"Overwatch (Figma - Genji)", type:"merch-figure", year:2018, region:"JP", publisher:"Max Factory", desc:"源氏 Figma。", tags:["Figma"]},
  {ip:"Overwatch", title:"Overwatch (Statue - Tracer)", type:"merch-figure", year:2018, region:"US", publisher:"Gaming Heads", desc:"雕像。", tags:["雕像"]},
  {ip:"Overwatch", title:"Overwatch (Plush - Pachimari)", type:"merch-figure", year:2017, region:"US", publisher:"Blizzard", desc:"Pachimari 毛绒。", tags:["毛绒"]},
  {ip:"Overwatch", title:"Overwatch x Uniqlo UT", type:"merch-cloth", year:2018, region:"Global", publisher:"Uniqlo", desc:"UT 联名。", tags:["服装"]},
  {ip:"Overwatch", title:"Overwatch (Trading Card Game)", type:"merch-card", year:2019, region:"US", publisher:"Cryptozoic", desc:"TCG。", tags:["TCG"]},
  {ip:"Overwatch", title:"Overwatch (Board Game - Watchpoint)", type:"game-board", year:2018, region:"US", publisher:"Cryptozoic", desc:"桌游。", tags:["桌游"]},
  {ip:"Overwatch", title:"Overwatch OST (Original Soundtrack)", type:"ost", year:2016, region:"US", publisher:"Blizzard", desc:"原声。", tags:["OST"]},
  {ip:"Overwatch", title:"Overwatch 2 OST", type:"ost", year:2022, region:"US", publisher:"Blizzard", desc:"原声。", tags:["OST"]},
  {ip:"Overwatch", title:"Overwatch (Esports - League)", type:"event", year:2018, region:"Global", publisher:"Blizzard", desc:"OWL 联赛。", tags:["电竞赛"]},
  {ip:"Overwatch", title:"Overwatch (Cosplay Costumes)", type:"merch-cloth", year:2017, region:"US", publisher:"Miccostumes", desc:"COS 服。", tags:["COS"]},

  // ============================================================
  // WORLD OF WARCRAFT (Blizzard)
  // ============================================================
  {ip:"World of Warcraft", title:"Warcraft: Orcs & Humans (Original Game)", type:"game-spinoff", year:1994, region:"US", publisher:"Blizzard", desc:"初代 RTS。", tags:["RTS"]},
  {ip:"World of Warcraft", title:"Warcraft II: Tides of Darkness", type:"game-spinoff", year:1995, region:"US", publisher:"Blizzard", desc:"RTS 续作。", tags:["RTS"]},
  {ip:"World of Warcraft", title:"Warcraft III: Reign of Chaos", type:"game-spinoff", year:2002, region:"US", publisher:"Blizzard", desc:"RTS 第三作。", tags:["RTS"]},
  {ip:"World of Warcraft", title:"Warcraft III: The Frozen Throne", type:"game-spinoff", year:2003, region:"US", publisher:"Blizzard", desc:"资料片。", tags:["RTS"]},
  {ip:"World of Warcraft", title:"Warcraft (Film 2016)", type:"film-live", year:2016, region:"US", publisher:"Legendary / Universal", desc:"真人电影。", tags:["真人电影"]},
  {ip:"World of Warcraft", title:"Warcraft (Manga - The Sunwell Trilogy)", type:"manga", year:2005, region:"US", publisher:"Wildstorm", desc:"美式漫画。", tags:["美式漫画"]},
  {ip:"World of Warcraft", title:"World of Warcraft: The Comic (Wildstorm)", type:"manga", year:2007, region:"US", publisher:"Wildstorm", desc:"美式漫画。", tags:["美式漫画"]},
  {ip:"World of Warcraft", title:"World of Warcraft (Manga - Pearl of Pandaria)", type:"manga", year:2014, region:"US", publisher:"Dark Horse", desc:"黑马漫画。", tags:["美式漫画"]},
  {ip:"World of Warcraft", title:"World of Warcraft (Manga - Deathwing)", type:"manga", year:2012, region:"US", publisher:"DC Comics", desc:"DC 漫画。", tags:["美式漫画"]},
  {ip:"World of Warcraft", title:"World of Warcraft (Novel - Arthas: Rise of the Lich King)", type:"novel", year:2009, region:"US", publisher:"Del Rey", desc:"阿尔萨斯前传。", tags:["小说"]},
  {ip:"World of Warcraft", title:"World of Warcraft (Novel - The Burning Crusade)", type:"novel", year:2007, region:"US", publisher:"Pocket Star", desc:"小说。", tags:["小说"]},
  {ip:"World of Warcraft", title:"World of Warcraft (Novel - Stormrage)", type:"novel", year:2010, region:"US", publisher:"Del Rey", desc:"小说。", tags:["小说"]},
  {ip:"World of Warcraft", title:"World of Warcraft (Novel - Thrall: Twilight of the Aspects)", type:"novel", year:2011, region:"US", publisher:"Del Rey", desc:"小说。", tags:["小说"]},
  {ip:"World of Warcraft", title:"World of Warcraft (Novel - War Crimes)", type:"novel", year:2014, region:"US", publisher:"Del Rey", desc:"小说。", tags:["小说"]},
  {ip:"World of Warcraft", title:"World of Warcraft: Illidan (Novel)", type:"novel", year:2016, region:"US", publisher:"Del Rey", desc:"伊利丹小说。", tags:["小说"]},
  {ip:"World of Warcraft", title:"World of Warcraft: Sylvanas (Novel)", type:"novel", year:2022, region:"US", publisher:"Del Rey", desc:"希尔瓦娜斯小说。", tags:["小说"]},
  {ip:"World of Warcraft", title:"World of Warcraft (WoW Classic)", type:"game-spinoff", year:2019, region:"US", publisher:"Blizzard", desc:"怀旧服。", tags:["MMO"]},
  {ip:"World of Warcraft", title:"World of Warcraft: Burning Crusade Classic", type:"game-spinoff", year:2021, region:"US", publisher:"Blizzard", desc:"资料片怀旧服。", tags:["MMO"]},
  {ip:"World of Warcraft", title:"World of Warcraft: Wrath of the Lich King Classic", type:"game-spinoff", year:2022, region:"US", publisher:"Blizzard", desc:"资料片怀旧服。", tags:["MMO"]},
  {ip:"World of Warcraft", title:"World of Warcraft: Dragonflight", type:"game-spinoff", year:2022, region:"US", publisher:"Blizzard", desc:"《巨龙时代》资料片。", tags:["MMO"]},
  {ip:"World of Warcraft", title:"World of Warcraft: The War Within", type:"game-spinoff", year:2024, region:"US", publisher:"Blizzard", desc:"《至暗之夜》资料片。", tags:["MMO"]},
  {ip:"World of Warcraft", title:"Hearthstone", type:"game-mobile", year:2014, region:"US", publisher:"Blizzard", desc:"炉石传说。", tags:["卡牌"]},
  {ip:"World of Warcraft", title:"World of Warcraft: The Burning Crusade (OST)", type:"ost", year:2007, region:"US", publisher:"Blizzard", desc:"原声。", tags:["OST"]},
  {ip:"World of Warcraft", title:"World of Warcraft: Wrath of the Lich King OST", type:"ost", year:2008, region:"US", publisher:"Blizzard", desc:"原声。", tags:["OST"]},
  {ip:"World of Warcraft", title:"World of Warcraft OST (Various)", type:"ost", year:2004, region:"US", publisher:"Blizzard", desc:"原声集。", tags:["OST"]},
  {ip:"World of Warcraft", title:"World of Warcraft Funko Pop (Sylvanas)", type:"merch-figure", year:2018, region:"US", publisher:"Funko", desc:"希尔瓦娜斯公仔。", tags:["Funko"]},
  {ip:"World of Warcraft", title:"World of Warcraft Funko Pop (Arthas)", type:"merch-figure", year:2018, region:"US", publisher:"Funko", desc:"阿尔萨斯公仔。", tags:["Funko"]},
  {ip:"World of Warcraft", title:"World of Warcraft (Ashbringer Replica)", type:"merch-toy", year:2018, region:"US", publisher:"Blizzard", desc:"灰烬使者复刻。", tags:["道具"]},
  {ip:"World of Warcraft", title:"World of Warcraft: Doomhammer Replica", type:"merch-toy", year:2019, region:"US", publisher:"Blizzard", desc:"毁灭之锤复刻。", tags:["道具"]},
  {ip:"World of Warcraft", title:"World of Warcraft: Sylvanas Statue", type:"merch-figure", year:2022, region:"US", publisher:"Sideshow", desc:"雕像。", tags:["雕像"]},
  {ip:"World of Warcraft", title:"World of Warcraft (Mount Replica - Frost Wyrm)", type:"merch-toy", year:2020, region:"US", publisher:"Blizzard", desc:"冰霜巨龙坐骑复刻。", tags:["道具"]},
  {ip:"World of Warcraft", title:"World of Warcraft: Shadowlands OST", type:"ost", year:2020, region:"US", publisher:"Blizzard", desc:"暗影界原声。", tags:["OST"]},
  {ip:"World of Warcraft", title:"World of Warcraft (Trading Card Game)", type:"merch-card", year:2006, region:"US", publisher:"Upper Deck", desc:"TCG。", tags:["TCG"]},
  {ip:"World of Warcraft", title:"World of Warcraft: The Board Game", type:"game-board", year:2005, region:"US", publisher:"Fantasy Flight", desc:"桌游。", tags:["桌游"]},
  {ip:"World of Warcraft", title:"Warcraft (Manga - Ashbringer Comic)", type:"manga", year:2008, region:"US", publisher:"Wildstorm", desc:"漫画。", tags:["美式漫画"]},
  {ip:"World of Warcraft", title:"World of Warcraft (BlizzCon Opening Cinematics)", type:"web-series", year:2004, region:"US", publisher:"Blizzard", desc:"开场动画。", tags:["短片"]},
  {ip:"World of Warcraft", title:"World of Warcraft: Legion (OST)", type:"ost", year:2016, region:"US", publisher:"Blizzard", desc:"原声。", tags:["OST"]},

  // ============================================================
  // DIABLO (Blizzard)
  // ============================================================
  {ip:"Diablo", title:"Diablo (1997 Original)", type:"game-spinoff", year:1997, region:"US", publisher:"Blizzard", desc:"原版。", tags:["ARPG"]},
  {ip:"Diablo", title:"Diablo II", type:"game-spinoff", year:2000, region:"US", publisher:"Blizzard", desc:"续作。", tags:["ARPG"]},
  {ip:"Diablo", title:"Diablo II: Lord of Destruction", type:"game-spinoff", year:2001, region:"US", publisher:"Blizzard", desc:"资料片。", tags:["ARPG"]},
  {ip:"Diablo", title:"Diablo III", type:"game-spinoff", year:2012, region:"US", publisher:"Blizzard", desc:"续作。", tags:["ARPG"]},
  {ip:"Diablo", title:"Diablo III: Reaper of Souls", type:"game-spinoff", year:2014, region:"US", publisher:"Blizzard", desc:"资料片。", tags:["ARPG"]},
  {ip:"Diablo", title:"Diablo IV", type:"game-spinoff", year:2023, region:"US", publisher:"Blizzard", desc:"续作。", tags:["ARPG"]},
  {ip:"Diablo", title:"Diablo IV: Vessel of Hatred", type:"game-spinoff", year:2024, region:"US", publisher:"Blizzard", desc:"DLC。", tags:["DLC"]},
  {ip:"Diablo", title:"Diablo Immortal (Mobile)", type:"game-mobile", year:2022, region:"Global", publisher:"Blizzard / NetEase", desc:"手游。", tags:["手游"]},
  {ip:"Diablo", title:"Diablo (Manga - The Kingdom of Shadow)", type:"manga", year:2001, region:"US", publisher:"Tokyopop", desc:"漫画。", tags:["美式漫画"]},
  {ip:"Diablo", title:"Diablo III: Heroes Rise, Darkness Falls (Manga)", type:"manga", year:2012, region:"US", publisher:"Titan Comics", desc:"漫画。", tags:["美式漫画"]},
  {ip:"Diablo", title:"Diablo (Manga - Sword of Justice)", type:"manga", year:2013, region:"US", publisher:"Titan Comics", desc:"漫画。", tags:["美式漫画"]},
  {ip:"Diablo", title:"Diablo (Novel - The Sin War)", type:"novel", year:2006, region:"US", publisher:"Pocket Star", desc:"小说。", tags:["小说"]},
  {ip:"Diablo", title:"Diablo (Novel - Demonsbane)", type:"novel", year:2007, region:"US", publisher:"Pocket Star", desc:"小说。", tags:["小说"]},
  {ip:"Diablo", title:"Diablo (Novel - The Veiled Prophet)", type:"novel", year:2000, region:"US", publisher:"Pocket Books", desc:"小说。", tags:["小说"]},
  {ip:"Diablo", title:"Diablo (Manga - Demonic)", type:"manga", year:2012, region:"US", publisher:"UDON", desc:"漫画。", tags:["美式漫画"]},
  {ip:"Diablo", title:"Diablo OST (Matt Uelmen)", type:"ost", year:1997, region:"US", publisher:"Blizzard", desc:"原声。", tags:["OST"]},
  {ip:"Diablo", title:"Diablo II OST", type:"ost", year:2000, region:"US", publisher:"Blizzard", desc:"原声。", tags:["OST"]},
  {ip:"Diablo", title:"Diablo III OST", type:"ost", year:2012, region:"US", publisher:"Blizzard", desc:"原声。", tags:["OST"]},
  {ip:"Diablo", title:"Diablo IV OST", type:"ost", year:2023, region:"US", publisher:"Blizzard", desc:"原声。", tags:["OST"]},
  {ip:"Diablo", title:"Diablo (Plush - Treasure Goblin)", type:"merch-figure", year:2018, region:"US", publisher:"Blizzard", desc:"哥布林毛绒。", tags:["毛绒"]},
  {ip:"Diablo", title:"Diablo (Funko Pop - Diablo)", type:"merch-figure", year:2018, region:"US", publisher:"Funko", desc:"Funko 公仔。", tags:["Funko"]},
  {ip:"Diablo", title:"Diablo (Funko Pop - Lilith)", type:"merch-figure", year:2023, region:"US", publisher:"Funko", desc:"莉莉丝公仔。", tags:["Funko"]},
  {ip:"Diablo", title:"Diablo (Action Figure - Diablo)", type:"merch-figure", year:2019, region:"US", publisher:"NECA", desc:"可动人偶。", tags:["可动"]},
  {ip:"Diablo", title:"Diablo IV (Sword Replica)", type:"merch-toy", year:2023, region:"US", publisher:"Blizzard", desc:"剑复刻。", tags:["道具"]},
  {ip:"Diablo", title:"Diablo (Mug)", type:"merch-toy", year:2018, region:"US", publisher:"Blizzard", desc:"主题杯。", tags:["餐饮联动"]},
  {ip:"Diablo", title:"Diablo (Board Game - Reaper of Souls)", type:"game-board", year:2019, region:"US", publisher:"USAopoly", desc:"桌游。", tags:["桌游"]},

  // ============================================================
  // STARCRAFT
  // ============================================================
  {ip:"StarCraft", title:"StarCraft: Brood War (Novel)", type:"novel", year:1998, region:"US", publisher:"Pocket Books", desc:"小说。", tags:["小说"]},
  {ip:"StarCraft", title:"StarCraft: The Dark Templar Saga (Novel)", type:"novel", year:2005, region:"US", publisher:"Pocket Books", desc:"小说三部曲。", tags:["小说"]},
  {ip:"StarCraft", title:"StarCraft: Heaven's Devils (Novel)", type:"novel", year:2010, region:"US", publisher:"Pocket Star", desc:"小说。", tags:["小说"]},
  {ip:"StarCraft", title:"StarCraft II: Wings of Liberty", type:"game-spinoff", year:2010, region:"US", publisher:"Blizzard", desc:"续作。", tags:["RTS"]},
  {ip:"StarCraft", title:"StarCraft II: Heart of the Swarm", type:"game-spinoff", year:2013, region:"US", publisher:"Blizzard", desc:"续作。", tags:["RTS"]},
  {ip:"StarCraft", title:"StarCraft II: Legacy of the Void", type:"game-spinoff", year:2015, region:"US", publisher:"Blizzard", desc:"续作。", tags:["RTS"]},
  {ip:"StarCraft", title:"StarCraft (Manga - Frontline News)", type:"manga", year:2010, region:"US", publisher:"Tokyopop", desc:"美式漫画。", tags:["美式漫画"]},
  {ip:"StarCraft", title:"StarCraft (Manga - The Revelation)", type:"manga", year:2010, region:"US", publisher:"Tokyopop", desc:"漫画。", tags:["美式漫画"]},
  {ip:"StarCraft", title:"StarCraft (Manga - Ghost Academy)", type:"manga", year:2011, region:"US", publisher:"Tokyopop", desc:"漫画。", tags:["美式漫画"]},
  {ip:"StarCraft", title:"StarCraft (Manga - Kerrigan: Hope and Vengeance)", type:"manga", year:2012, region:"US", publisher:"Tokyopop", desc:"漫画。", tags:["美式漫画"]},
  {ip:"StarCraft", title:"StarCraft (Manga - Frontline)", type:"manga", year:2009, region:"US", publisher:"Tokyopop", desc:"漫画。", tags:["美式漫画"]},
  {ip:"StarCraft", title:"StarCraft (Manga - Revolution)", type:"manga", year:2010, region:"US", publisher:"Tokyopop", desc:"漫画。", tags:["美式漫画"]},
  {ip:"StarCraft", title:"StarCraft II: Legacy of the Void OST", type:"ost", year:2015, region:"US", publisher:"Blizzard", desc:"原声。", tags:["OST"]},
  {ip:"StarCraft", title:"StarCraft (Plush - Zergling)", type:"merch-figure", year:2018, region:"US", publisher:"Blizzard", desc:"小狗毛绒。", tags:["毛绒"]},
  {ip:"StarCraft", title:"StarCraft (Funko Pop - Kerrigan)", type:"merch-figure", year:2018, region:"US", publisher:"Funko", desc:"凯瑞甘公仔。", tags:["Funko"]},
  {ip:"StarCraft", title:"StarCraft (Funko Pop - Jim Raynor)", type:"merch-figure", year:2018, region:"US", publisher:"Funko", desc:"雷诺公仔。", tags:["Funko"]},
  {ip:"StarCraft", title:"StarCraft Remastered", type:"game-spinoff", year:2017, region:"US", publisher:"Blizzard", desc:"重制。", tags:["重制"]},
  {ip:"StarCraft", title:"StarCraft: Brood War Remastered", type:"game-spinoff", year:2017, region:"US", publisher:"Blizzard", desc:"重制。", tags:["重制"]},
  {ip:"StarCraft", title:"StarCraft (Trading Card Game)", type:"merch-card", year:2000, region:"US", publisher:"Upper Deck", desc:"TCG。", tags:["TCG"]},
  {ip:"StarCraft", title:"StarCraft (Mug)", type:"merch-toy", year:2018, region:"US", publisher:"Blizzard", desc:"主题杯。", tags:["餐饮联动"]},

  // ============================================================
  // ELDER SCROLLS
  // ============================================================
  {ip:"Elder Scrolls", title:"The Elder Scrolls: Arena (1994)", type:"game-spinoff", year:1994, region:"US", publisher:"Bethesda", desc:"初代。", tags:["RPG"]},
  {ip:"Elder Scrolls", title:"The Elder Scrolls II: Daggerfall", type:"game-spinoff", year:1996, region:"US", publisher:"Bethesda", desc:"续作。", tags:["RPG"]},
  {ip:"Elder Scrolls", title:"The Elder Scrolls III: Morrowind", type:"game-spinoff", year:2002, region:"US", publisher:"Bethesda", desc:"续作。", tags:["RPG"]},
  {ip:"Elder Scrolls", title:"The Elder Scrolls IV: Oblivion", type:"game-spinoff", year:2006, region:"US", publisher:"Bethesda", desc:"续作。", tags:["RPG"]},
  {ip:"Elder Scrolls", title:"The Elder Scrolls V: Skyrim", type:"game-spinoff", year:2011, region:"US", publisher:"Bethesda", desc:"续作。", tags:["RPG"]},
  {ip:"Elder Scrolls", title:"The Elder Scrolls V: Skyrim Special Edition", type:"game-spinoff", year:2016, region:"US", publisher:"Bethesda", desc:"重制。", tags:["重制"]},
  {ip:"Elder Scrolls", title:"The Elder Scrolls Online", type:"game-spinoff", year:2014, region:"US", publisher:"Zenimax", desc:"网游。", tags:["MMO"]},
  {ip:"Elder Scrolls", title:"The Elder Scrolls VI (Upcoming)", type:"game-spinoff", year:2027, region:"US", publisher:"Bethesda", desc:"新作。", tags:["RPG"]},
  {ip:"Elder Scrolls", title:"The Elder Scrolls (Novels - The Infernal City)", type:"novel", year:2009, region:"US", publisher:"Del Rey", desc:"小说。", tags:["小说"]},
  {ip:"Elder Scrolls", title:"The Elder Scrolls (Novel - Lord of Souls)", type:"novel", year:2011, region:"US", publisher:"Del Rey", desc:"小说。", tags:["小说"]},
  {ip:"Elder Scrolls", title:"The Elder Scrolls V: Skyrim - The Dragonborn Comes (Music Box)", type:"ost", year:2011, region:"US", publisher:"Bethesda", desc:"八音盒。", tags:["OST"]},
  {ip:"Elder Scrolls", title:"The Elder Scrolls V: Skyrim OST (Jeremy Soule)", type:"ost", year:2011, region:"US", publisher:"Bethesda", desc:"原声。", tags:["OST"]},
  {ip:"Elder Scrolls", title:"The Elder Scrolls (Manga)", type:"manga", year:2016, region:"US", publisher:"Dark Horse", desc:"黑马漫画。", tags:["美式漫画"]},
  {ip:"Elder Scrolls", title:"The Elder Scrolls Online: The Art of the Game", type:"artbook", year:2015, region:"US", publisher:"Dark Horse", desc:"画集。", tags:["画集"]},
  {ip:"Elder Scrolls", title:"Skyrim Funko Pop (Dragonborn)", type:"merch-figure", year:2018, region:"US", publisher:"Funko", desc:"Funko 公仔。", tags:["Funko"]},
  {ip:"Elder Scrolls", title:"Skyrim (Daedric Helmet Replica)", type:"merch-toy", year:2018, region:"US", publisher:"Bethesda", desc:"头盔复刻。", tags:["道具"]},
  {ip:"Elder Scrolls", title:"Skyrim (Mead)", type:"merch-toy", year:2018, region:"US", publisher:"Bethesda", desc:"蜂蜜酒。", tags:["饮品联动"]},
  {ip:"Elder Scrolls", title:"Skyrim (Mug - Holds Whiskey)", type:"merch-toy", year:2018, region:"US", publisher:"Bethesda", desc:"威士忌杯。", tags:["餐饮联动"]},
  {ip:"Elder Scrolls", title:"Elder Scrolls (Funko Pop - Daedric Prince)", type:"merch-figure", year:2018, region:"US", publisher:"Funko", desc:"Funko 公仔。", tags:["Funko"]},
  {ip:"Elder Scrolls", title:"Skyrim x Mountain Dew", type:"collab", year:2018, region:"US", publisher:"Mountain Dew", desc:"激浪联名。", tags:["饮品联动"]},
  {ip:"Elder Scrolls", title:"Elder Scrolls: Legends (Card Game)", type:"game-mobile", year:2017, region:"US", publisher:"Bethesda", desc:"卡牌手游。", tags:["卡牌"]},
  {ip:"Elder Scrolls", title:"Skyrim (Board Game - The Adventure Game)", type:"game-board", year:2022, region:"US", publisher:"Modiphius", desc:"桌游。", tags:["桌游"]},
  {ip:"Elder Scrolls", title:"The Elder Scrolls: Castles (Mobile)", type:"game-mobile", year:2023, region:"Global", publisher:"Bethesda", desc:"手游。", tags:["手游"]},
  {ip:"Elder Scrolls", title:"Skyrim (Live-Action Trailer - 'Skyrim Very Special Edition')", type:"web-series", year:2016, region:"US", publisher:"Bethesda", desc:"真人短片。", tags:["短片"]},
  {ip:"Elder Scrolls", title:"Elder Scrolls (Cosplay Costumes)", type:"merch-cloth", year:2015, region:"US", publisher:"Miccostumes", desc:"COS 服装。", tags:["COS"]},

  // ============================================================
  // FALLOUT
  // ============================================================
  {ip:"Fallout", title:"Fallout (1997 Original)", type:"game-spinoff", year:1997, region:"US", publisher:"Interplay", desc:"初代。", tags:["RPG"]},
  {ip:"Fallout", title:"Fallout 2", type:"game-spinoff", year:1998, region:"US", publisher:"Interplay", desc:"续作。", tags:["RPG"]},
  {ip:"Fallout", title:"Fallout 3", type:"game-spinoff", year:2008, region:"US", publisher:"Bethesda", desc:"续作。", tags:["RPG"]},
  {ip:"Fallout", title:"Fallout: New Vegas", type:"game-spinoff", year:2010, region:"US", publisher:"Obsidian / Bethesda", desc:"外包。", tags:["RPG"]},
  {ip:"Fallout", title:"Fallout 4", type:"game-spinoff", year:2015, region:"US", publisher:"Bethesda", desc:"续作。", tags:["RPG"]},
  {ip:"Fallout", title:"Fallout 4 VR", type:"game-spinoff", year:2017, region:"US", publisher:"Bethesda", desc:"VR 版。", tags:["VR"]},
  {ip:"Fallout", title:"Fallout 76", type:"game-spinoff", year:2018, region:"US", publisher:"Bethesda", desc:"网游。", tags:["网游"]},
  {ip:"Fallout", title:"Fallout Shelter", type:"game-mobile", year:2015, region:"Global", publisher:"Bethesda", desc:"手游。", tags:["手游"]},
  {ip:"Fallout", title:"Fallout (Amazon TV Series)", type:"tv", year:2024, region:"US", publisher:"Amazon Prime / Bethesda", desc:"真人剧。", tags:["真人剧"]},
  {ip:"Fallout", title:"Fallout: The Front", type:"game-mobile", year:2024, region:"Global", publisher:"Bethesda", desc:"手游新作。", tags:["手游"]},
  {ip:"Fallout", title:"Fallout 4: Nuka-World", type:"game-spinoff", year:2016, region:"US", publisher:"Bethesda", desc:"DLC。", tags:["DLC"]},
  {ip:"Fallout", title:"Fallout 4: Far Harbor", type:"game-spinoff", year:2016, region:"US", publisher:"Bethesda", desc:"DLC。", tags:["DLC"]},
  {ip:"Fallout", title:"Fallout 4: Automatron", type:"game-spinoff", year:2016, region:"US", publisher:"Bethesda", desc:"DLC。", tags:["DLC"]},
  {ip:"Fallout", title:"Fallout: Brotherhood of Steel", type:"game-spinoff", year:2004, region:"US", publisher:"Interplay", desc:"PS2 衍生。", tags:["ACT"]},
  {ip:"Fallout", title:"Fallout Tactics: Brotherhood of Steel", type:"game-spinoff", year:2001, region:"US", publisher:"Interplay", desc:"策略衍生。", tags:["策略"]},
  {ip:"Fallout", title:"Fallout: Brotherhood of Steel 2 (Cancelled)", type:"game-spinoff", year:2004, region:"US", publisher:"Interplay", desc:"取消续作。", tags:["ACT"]},
  {ip:"Fallout", title:"Fallout (Manga)", type:"manga", year:2019, region:"US", publisher:"Dark Horse", desc:"黑马漫画。", tags:["美式漫画"]},
  {ip:"Fallout", title:"Fallout: Brotherhood of Steel (Manga)", type:"manga", year:2004, region:"US", publisher:"Dark Horse", desc:"黑马漫画。", tags:["美式漫画"]},
  {ip:"Fallout", title:"Fallout (Novel - The Vault Dweller)", type:"novel", year:2019, region:"US", publisher:"Pocket Books", desc:"小说。", tags:["小说"]},
  {ip:"Fallout", title:"Fallout (Novel - The Wanderer)", type:"novel", year:2020, region:"US", publisher:"Pocket Books", desc:"小说。", tags:["小说"]},
  {ip:"Fallout", title:"Fallout 4 OST (Inon Zur)", type:"ost", year:2015, region:"US", publisher:"Bethesda", desc:"原声。", tags:["OST"]},
  {ip:"Fallout", title:"Fallout 76 OST", type:"ost", year:2018, region:"US", publisher:"Bethesda", desc:"原声。", tags:["OST"]},
  {ip:"Fallout", title:"Fallout: New Vegas OST", type:"ost", year:2010, region:"US", publisher:"Obsidian", desc:"原声。", tags:["OST"]},
  {ip:"Fallout", title:"Fallout (Funko Pop - Vault Boy)", type:"merch-figure", year:2017, region:"US", publisher:"Funko", desc:"Funko 公仔。", tags:["Funko"]},
  {ip:"Fallout", title:"Fallout (Nuka-Cola Replica)", type:"merch-toy", year:2018, region:"US", publisher:"Bethesda", desc:"核子可乐复刻。", tags:["道具"]},
  {ip:"Fallout", title:"Fallout (Pip-Boy Replica)", type:"merch-toy", year:2015, region:"US", publisher:"Bethesda", desc:"Pip-Boy 复刻。", tags:["道具"]},
  {ip:"Fallout", title:"Fallout (Funko Pop - Power Armor)", type:"merch-figure", year:2018, region:"US", publisher:"Funko", desc:"动力装甲公仔。", tags:["Funko"]},
  {ip:"Fallout", title:"Fallout (Mug - Nuka-Cola)", type:"merch-toy", year:2018, region:"US", publisher:"Bethesda", desc:"核子可乐杯。", tags:["餐饮联动"]},
  {ip:"Fallout", title:"Fallout (Nuka-Cola Victory)", type:"merch-toy", year:2020, region:"US", publisher:"Bethesda", desc:"核子可乐。", tags:["饮品联动"]},
  {ip:"Fallout", title:"Fallout (Trading Card Game)", type:"merch-card", year:2017, region:"US", publisher:"Cryptozoic", desc:"TCG。", tags:["TCG"]},
  {ip:"Fallout", title:"Fallout: The Roleplaying Game", type:"game-board", year:2021, region:"US", publisher:"Modiphius", desc:"RPG 桌游。", tags:["桌游"]},
  {ip:"Fallout", title:"Fallout (Board Game)", type:"game-board", year:2021, region:"US", publisher:"Fantasy Flight", desc:"桌游。", tags:["桌游"]},
  {ip:"Fallout", title:"Fallout (Cosplay Costumes)", type:"merch-cloth", year:2016, region:"US", publisher:"Miccostumes", desc:"COS 服装。", tags:["COS"]},

  // ============================================================
  // MINECRAFT
  // ============================================================
  {ip:"Minecraft", title:"Minecraft: Story Mode (Telltale)", type:"game-spinoff", year:2015, region:"US", publisher:"Telltale", desc:"故事模式。", tags:["冒险"]},
  {ip:"Minecraft", title:"Minecraft: Story Mode Season 2", type:"game-spinoff", year:2017, region:"US", publisher:"Telltale", desc:"续作。", tags:["冒险"]},
  {ip:"Minecraft", title:"Minecraft Dungeons", type:"game-spinoff", year:2020, region:"US", publisher:"Mojang", desc:"ARPG 衍生。", tags:["ARPG"]},
  {ip:"Minecraft", title:"Minecraft Earth (AR Mobile)", type:"game-mobile", year:2019, region:"Global", publisher:"Mojang", desc:"AR 手游 (已停服)。", tags:["AR"]},
  {ip:"Minecraft", title:"Minecraft Legends", type:"game-spinoff", year:2023, region:"US", publisher:"Mojang", desc:"动作策略。", tags:["ACT"]},
  {ip:"Minecraft", title:"Minecraft (Manga - Boku no Friend Steve)", type:"manga", year:2016, region:"JP", publisher:"Shogakukan", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Minecraft", title:"Minecraft (Novel - The Island)", type:"novel", year:2016, region:"US", publisher:"Del Rey", desc:"小说。", tags:["小说"]},
  {ip:"Minecraft", title:"Minecraft (Novel - The Crash)", type:"novel", year:2018, region:"US", publisher:"Del Rey", desc:"小说。", tags:["小说"]},
  {ip:"Minecraft", title:"Minecraft (Novel - The End)", type:"novel", year:2019, region:"US", publisher:"Del Rey", desc:"小说。", tags:["小说"]},
  {ip:"Minecraft", title:"Minecraft (Novel - The Voyage)", type:"novel", year:2020, region:"US", publisher:"Del Rey", desc:"小说。", tags:["小说"]},
  {ip:"Minecraft", title:"Minecraft (Comic - WEBTOONS)", type:"web-series", year:2018, region:"Global", publisher:"WEBTOON", desc:"Web 漫画。", tags:["Web 漫画"]},
  {ip:"Minecraft", title:"Minecraft (LEGO)", type:"merch-toy", year:2012, region:"Global", publisher:"LEGO", desc:"乐高。", tags:["积木"]},
  {ip:"Minecraft", title:"Minecraft (Funko Pop - Steve)", type:"merch-figure", year:2019, region:"US", publisher:"Funko", desc:"Funko 公仔。", tags:["Funko"]},
  {ip:"Minecraft", title:"Minecraft (Funko Pop - Creeper)", type:"merch-figure", year:2019, region:"US", publisher:"Funko", desc:"苦力怕公仔。", tags:["Funko"]},
  {ip:"Minecraft", title:"Minecraft (JINX Plush)", type:"merch-figure", year:2014, region:"US", publisher:"JINX", desc:"毛绒。", tags:["毛绒"]},
  {ip:"Minecraft", title:"Minecraft (Mattel Action Figures)", type:"merch-figure", year:2014, region:"US", publisher:"Mattel", desc:"可动人偶。", tags:["可动"]},
  {ip:"Minecraft", title:"Minecraft OST (C418)", type:"ost", year:2011, region:"US", publisher:"Mojang", desc:"原声。", tags:["OST"]},
  {ip:"Minecraft", title:"Minecraft (OST - Volume Beta / C418)", type:"ost", year:2013, region:"US", publisher:"Mojang", desc:"原声。", tags:["OST"]},
  {ip:"Minecraft", title:"Minecraft Live Concert (C418/Lena Raine)", type:"concert", year:2023, region:"Global", publisher:"Mojang", desc:"音乐会。", tags:["音乐会"]},
  {ip:"Minecraft", title:"Minecraft (Trading Card Game)", type:"merch-card", year:2022, region:"US", publisher:"Mixlore", desc:"TCG。", tags:["TCG"]},
  {ip:"Minecraft", title:"Minecraft (Mojang Board Game)", type:"game-board", year:2014, region:"US", publisher:"Mojang", desc:"桌游。", tags:["桌游"]},
  {ip:"Minecraft", title:"Minecraft x McDonalds", type:"collab", year:2024, region:"Global", publisher:"McDonalds", desc:"麦当劳联名。", tags:["餐饮联动"]},
  {ip:"Minecraft", title:"Minecraft x Nerf", type:"merch-toy", year:2020, region:"US", publisher:"Nerf", desc:"玩具枪联名。", tags:["玩具枪"]},
  {ip:"Minecraft", title:"Minecraft (Spin Master Toy Line)", type:"merch-toy", year:2020, region:"US", publisher:"Spin Master", desc:"玩具。", tags:["玩具"]},
  {ip:"Minecraft", title:"Minecraft (AOTC Live Action Film in Development)", type:"film-live", year:2025, region:"US", publisher:"Warner Bros.", desc:"真人电影开发中。", tags:["真人电影"]},
  {ip:"Minecraft", title:"Minecraft (Official Flexible Spending Guide)", type:"artbook", year:2015, region:"US", publisher:"Mojang", desc:"画集。", tags:["画集"]},
  {ip:"Minecraft", title:"Minecraft (Monopoly)", type:"game-board", year:2014, region:"US", publisher:"USAopoly", desc:"大富翁。", tags:["桌游"]},
  {ip:"Minecraft", title:"Minecraft x Adidas", type:"merch-cloth", year:2022, region:"Global", publisher:"Adidas", desc:"阿迪达斯联名。", tags:["服装"]},

  // ============================================================
  // FORTNITE
  // ============================================================
  {ip:"Fortnite", title:"Fortnite: Save the World", type:"game-spinoff", year:2017, region:"US", publisher:"Epic Games", desc:"PVE 模式。", tags:["TPS"]},
  {ip:"Fortnite", title:"Fortnite Battle Royale", type:"game-spinoff", year:2017, region:"US", publisher:"Epic Games", desc:"大逃杀。", tags:["TPS"]},
  {ip:"Fortnite", title:"Fortnite (LEGO)", type:"merch-toy", year:2023, region:"Global", publisher:"LEGO", desc:"乐高。", tags:["积木"]},
  {ip:"Fortnite", title:"Fortnite x Marshmello (Concert)", type:"concert", year:2019, region:"US", publisher:"Epic Games", desc:"游戏内音乐会。", tags:["音乐会"]},
  {ip:"Fortnite", title:"Fortnite x Travis Scott (Concert)", type:"concert", year:2020, region:"US", publisher:"Epic Games", desc:"游戏内音乐会。", tags:["音乐会"]},
  {ip:"Fortnite", title:"Fortnite x Ariana Grande (Concert)", type:"concert", year:2021, region:"US", publisher:"Epic Games", desc:"游戏内音乐会。", tags:["音乐会"]},
  {ip:"Fortnite", title:"Fortnite x The Weeknd (Concert)", type:"concert", year:2023, region:"US", publisher:"Epic Games", desc:"游戏内音乐会。", tags:["音乐会"]},
  {ip:"Fortnite", title:"Fortnite x Eminem (Concert)", type:"concert", year:2024, region:"US", publisher:"Epic Games", desc:"游戏内音乐会。", tags:["音乐会"]},
  {ip:"Fortnite", title:"Fortnite (Funko Pop - Skull Trooper)", type:"merch-figure", year:2018, region:"US", publisher:"Funko", desc:"Funko 公仔。", tags:["Funko"]},
  {ip:"Fortnite", title:"Fortnite (Monopoly)", type:"game-board", year:2019, region:"US", publisher:"USAopoly", desc:"大富翁。", tags:["桌游"]},
  {ip:"Fortnite", title:"Fortnite (Trading Card Game)", type:"merch-card", year:2019, region:"US", publisher:"Panini", desc:"TCG。", tags:["TCG"]},
  {ip:"Fortnite", title:"Fortnite (Action Figure - McFarlane)", type:"merch-figure", year:2018, region:"US", publisher:"McFarlane Toys", desc:"可动人偶。", tags:["可动"]},
  {ip:"Fortnite", title:"Fortnite (Nerf Guns)", type:"merch-toy", year:2018, region:"US", publisher:"Nerf", desc:"玩具枪。", tags:["玩具枪"]},
  {ip:"Fortnite", title:"Fortnite (Plush - Llama)", type:"merch-figure", year:2018, region:"US", publisher:"Epic Games", desc:"羊驼毛绒。", tags:["毛绒"]},
  {ip:"Fortnite", title:"Fortnite (OST)", type:"ost", year:2018, region:"US", publisher:"Epic Games", desc:"原声。", tags:["OST"]},
  {ip:"Fortnite", title:"Fortnite x Marvel Crossover", type:"collab", year:2018, region:"US", publisher:"Epic Games / Marvel", desc:"漫威联动。", tags:["跨界"]},
  {ip:"Fortnite", title:"Fortnite x Star Wars Crossover", type:"collab", year:2019, region:"US", publisher:"Epic Games / Lucasfilm", desc:"星球大战联动。", tags:["跨界"]},
  {ip:"Fortnite", title:"Fortnite x Batman Crossover", type:"collab", year:2019, region:"US", publisher:"Epic Games / DC", desc:"蝙蝠侠联动。", tags:["跨界"]},
  {ip:"Fortnite", title:"Fortnite (Manga - Battle Royale)", type:"manga", year:2020, region:"JP", publisher:"Shogakukan", desc:"漫画。", tags:["少年漫画"]},
  ];
  window.DATA = window.DATA.concat(EXT);
})();
