// Game IP Derivative Works Database - Extended Set Part 5
(function(){
  const EXT = [
  // ============================================================
  // GOD OF WAR (Sony)
  // ============================================================
  {ip:"God of War", title:"God of War: Ascension (Game)", type:"game-spinoff", year:2013, region:"US", publisher:"Sony / Santa Monica", desc:"前传。", tags:["ACT"]},
  {ip:"God of War", title:"God of War: Chains of Olympus (PSP)", type:"game-spinoff", year:2008, region:"US", publisher:"Ready at Dawn", desc:"PSP 前传。", tags:["ACT"]},
  {ip:"God of War", title:"God of War: Ghost of Sparta", type:"game-spinoff", year:2010, region:"US", publisher:"Ready at Dawn", desc:"PSP 续作。", tags:["ACT"]},
  {ip:"God of War", title:"God of War (2018)", type:"game-spinoff", year:2018, region:"US", publisher:"Sony / Santa Monica", desc:"北欧篇重启。", tags:["ACT"]},
  {ip:"God of War", title:"God of War: Ragnarök", type:"game-spinoff", year:2022, region:"US", publisher:"Sony / Santa Monica", desc:"北欧篇续作。", tags:["ACT"]},
  {ip:"God of War", title:"God of War: Ragnarök - Valhalla", type:"game-spinoff", year:2023, region:"US", publisher:"Sony", desc:"DLC。", tags:["DLC"]},
  {ip:"God of War", title:"God of War: Betrayal", type:"game-mobile", year:2007, region:"US", publisher:"Sony", desc:"2D 手游。", tags:["手游"]},
  {ip:"God of War", title:"God of War (Comic Series - DC)", type:"manga", year:2010, region:"US", publisher:"DC Comics", desc:"DC 漫画。", tags:["美式漫画"]},
  {ip:"God of War", title:"God of War: Fallen God (Comic)", type:"manga", year:2021, region:"US", publisher:"Dark Horse", desc:"黑马漫画。", tags:["美式漫画"]},
  {ip:"God of War", title:"God of War (Novel)", type:"novel", year:2010, region:"US", publisher:"Pocket Star", desc:"《3》小说化。", tags:["小说"]},
  {ip:"God of War", title:"God of War: The Official Novelization", type:"novel", year:2018, region:"US", publisher:"Titan Books", desc:"北欧篇小说。", tags:["小说"]},
  {ip:"God of War", title:"God of War: Lore and Legends (Art Book)", type:"artbook", year:2020, region:"US", publisher:"Dark Horse", desc:"画集。", tags:["画集"]},
  {ip:"God of War", title:"God of War: The Art of the Trilogy", type:"artbook", year:2013, region:"US", publisher:"Titan Books", desc:"画集。", tags:["画集"]},
  {ip:"God of War", title:"God of War OST (Bear McCreary)", type:"ost", year:2018, region:"US", publisher:"Sony", desc:"北欧篇原声。", tags:["OST"]},
  {ip:"God of War", title:"God of War: Ragnarök OST (Bear McCreary)", type:"ost", year:2022, region:"US", publisher:"Sony", desc:"原声。", tags:["OST"]},
  {ip:"God of War", title:"God of War (2005) OST", type:"ost", year:2005, region:"US", publisher:"Sony", desc:"原声。", tags:["OST"]},
  {ip:"God of War", title:"God of War (Live-Action Series - Amazon)", type:"tv", year:2025, region:"US", publisher:"Amazon Prime", desc:"真人剧制作中。", tags:["真人剧"]},
  {ip:"God of War", title:"God of War Funko Pop (Kratos)", type:"merch-figure", year:2018, region:"US", publisher:"Funko", desc:"Funko 公仔。", tags:["Funko"]},
  {ip:"God of War", title:"God of War (Leviathan Axe Replica)", type:"merch-toy", year:2018, region:"US", publisher:"Replicas Swords", desc:"利维坦之斧复刻。", tags:["道具"]},
  {ip:"God of War", title:"God of War (Blade of Olympus Replica)", type:"merch-toy", year:2010, region:"US", publisher:"United Cutlery", desc:"奥林匹斯之剑复刻。", tags:["道具"]},
  {ip:"God of War", title:"God of War Action Figure (NECA)", type:"merch-figure", year:2019, region:"US", publisher:"NECA", desc:"可动人偶。", tags:["可动"]},
  {ip:"God of War", title:"God of War x Adidas", type:"collab", year:2022, region:"Global", publisher:"Adidas", desc:"联名鞋。", tags:["服装"]},
  {ip:"God of War", title:"God of War x Marvel Comics", type:"manga", year:2024, region:"US", publisher:"Marvel", desc:"漫威合作。", tags:["美式漫画"]},
  {ip:"God of War", title:"God of War (Monopoly)", type:"game-board", year:2019, region:"US", publisher:"USAopoly", desc:"大富翁。", tags:["桌游"]},

  // ============================================================
  // THE LAST OF US
  // ============================================================
  {ip:"The Last of Us", title:"The Last of Us (HBO TV Series)", type:"tv", year:2023, region:"US", publisher:"HBO / Naughty Dog", desc:"真人剧。", tags:["真人剧"]},
  {ip:"The Last of Us", title:"The Last of Us Part II (Game)", type:"game-spinoff", year:2020, region:"US", publisher:"Naughty Dog", desc:"续作。", tags:["ACT"]},
  {ip:"The Last of Us", title:"The Last of Us Remastered", type:"game-spinoff", year:2014, region:"US", publisher:"Naughty Dog", desc:"PS4 高清版。", tags:["重制"]},
  {ip:"The Last of Us", title:"The Last of Us: Left Behind", type:"game-spinoff", year:2014, region:"US", publisher:"Naughty Dog", desc:"DLC。", tags:["DLC"]},
  {ip:"The Last of Us", title:"The Last of Us: Part I (Remake)", type:"game-spinoff", year:2022, region:"US", publisher:"Naughty Dog", desc:"PS5 重制。", tags:["重制"]},
  {ip:"The Last of Us", title:"The Last of Us Part II Remastered", type:"game-spinoff", year:2024, region:"US", publisher:"Naughty Dog", desc:"PS5 重制。", tags:["重制"]},
  {ip:"The Last of Us", title:"The Last of Us: American Dreams (Manga)", type:"manga", year:2013, region:"US", publisher:"Dark Horse", desc:"黑马漫画。", tags:["美式漫画"]},
  {ip:"The Last of Us", title:"The Last of Us (Novelization)", type:"novel", year:2014, region:"US", publisher:"Pocket Star", desc:"小说。", tags:["小说"]},
  {ip:"The Last of Us", title:"The Last of Us Part II (Novelization)", type:"novel", year:2020, region:"US", publisher:"Pocket Star", desc:"小说。", tags:["小说"]},
  {ip:"Last of Us", title:"The Last of Us: The Art of the Game", type:"artbook", year:2014, region:"US", publisher:"Future Press", desc:"画集。", tags:["画集"]},
  {ip:"Last of Us", title:"The Last of Us Part II: The Art of the Game", type:"artbook", year:2020, region:"US", publisher:"Future Press", desc:"画集。", tags:["画集"]},
  {ip:"Last of Us", title:"The Last of Us OST (Gustavo Santaolalla)", type:"ost", year:2013, region:"US", publisher:"Sony", desc:"原声。", tags:["OST"]},
  {ip:"Last of Us", title:"The Last of Us Part II OST", type:"ost", year:2020, region:"US", publisher:"Sony", desc:"原声。", tags:["OST"]},
  {ip:"Last of Us", title:"The Last of Us Funko Pop (Joel & Ellie)", type:"merch-figure", year:2019, region:"US", publisher:"Funko", desc:"Funko 公仔。", tags:["Funko"]},
  {ip:"Last of Us", title:"The Last of Us Action Figure (McFarlane)", type:"merch-figure", year:2020, region:"US", publisher:"McFarlane Toys", desc:"可动人偶。", tags:["可动"]},
  {ip:"Last of Us", title:"The Last of Us Clicker Statue", type:"merch-figure", year:2021, region:"US", publisher:"Dark Horse", desc:"雕像。", tags:["雕像"]},
  {ip:"Last of Us", title:"The Last of Us Plush (Ellie)", type:"merch-figure", year:2014, region:"US", publisher:"Kidrobot", desc:"毛绒。", tags:["毛绒"]},
  {ip:"Last of Us", title:"The Last of Us x UNIQLO UT", type:"merch-cloth", year:2023, region:"Global", publisher:"Uniqlo / Sony", desc:"UT 联名。", tags:["服装"]},
  {ip:"Last of Us", title:"The Last of Us: Board Game", type:"game-board", year:2022, region:"US", publisher:"CMON", desc:"桌游。", tags:["桌游"]},
  {ip:"Last of Us", title:"The Last of Us (TV Series S2)", type:"tv", year:2025, region:"US", publisher:"HBO", desc:"HBO 第二季。", tags:["真人剧"]},

  // ============================================================
  // UNCHARTED
  // ============================================================
  {ip:"Uncharted", title:"Uncharted (Film 2022)", type:"film-live", year:2022, region:"US", publisher:"Sony / Columbia", desc:"汤姆·霍兰德主演真人电影。", tags:["真人电影"]},
  {ip:"Uncharted", title:"Uncharted: Drake's Fortune (Game)", type:"game-spinoff", year:2007, region:"US", publisher:"Naughty Dog", desc:"原版。", tags:["ACT"]},
  {ip:"Uncharted", title:"Uncharted 2: Among Thieves", type:"game-spinoff", year:2009, region:"US", publisher:"Naughty Dog", desc:"续作。", tags:["ACT"]},
  {ip:"Uncharted", title:"Uncharted 3: Drake's Deception", type:"game-spinoff", year:2011, region:"US", publisher:"Naughty Dog", desc:"续作。", tags:["ACT"]},
  {ip:"Uncharted", title:"Uncharted: The Lost Legacy", type:"game-spinoff", year:2017, region:"US", publisher:"Naughty Dog", desc:"外传。", tags:["ACT"]},
  {ip:"Uncharted", title:"Uncharted 4: A Thief's End", type:"game-spinoff", year:2016, region:"US", publisher:"Naughty Dog", desc:"续作。", tags:["ACT"]},
  {ip:"Uncharted", title:"Uncharted: The Nathan Drake Collection", type:"game-spinoff", year:2015, region:"US", publisher:"Naughty Dog", desc:"合集。", tags:["合集"]},
  {ip:"Uncharted", title:"Uncharted: Legacy of Thieves Collection (PS5)", type:"game-spinoff", year:2022, region:"US", publisher:"Naughty Dog", desc:"PS5 复刻。", tags:["复刻"]},
  {ip:"Uncharted", title:"Uncharted (Eye of Indra - Webseries)", type:"web-series", year:2009, region:"US", publisher:"Naughty Dog", desc:"真人短剧。", tags:["真人短剧"]},
  {ip:"Uncharted", title:"Uncharted: Drake's Journal (Manga)", type:"manga", year:2010, region:"US", publisher:"DC Comics", desc:"DC 漫画。", tags:["美式漫画"]},
  {ip:"Uncharted", title:"Uncharted (Manga)", type:"manga", year:2016, region:"US", publisher:"Titan Comics", desc:"漫画。", tags:["美式漫画"]},
  {ip:"Uncharted", title:"Uncharted: The Fourth Labyrinth (Novel)", type:"novel", year:2011, region:"US", publisher:"Del Rey", desc:"小说。", tags:["小说"]},
  {ip:"Uncharted", title:"Uncharted: The Official Movie Novelization", type:"novel", year:2022, region:"US", publisher:"Titan Books", desc:"电影小说。", tags:["小说"]},
  {ip:"Uncharted", title:"Uncharted OST (Greg Edmonson / Henry Jackman)", type:"ost", year:2007, region:"US", publisher:"Sony", desc:"原声。", tags:["OST"]},
  {ip:"Uncharted", title:"Uncharted 2 OST", type:"ost", year:2009, region:"US", publisher:"Sony", desc:"原声。", tags:["OST"]},
  {ip:"Uncharted", title:"Uncharted 4 OST (Henry Jackman)", type:"ost", year:2016, region:"US", publisher:"Sony", desc:"原声。", tags:["OST"]},
  {ip:"Uncharted", title:"Uncharted Funko Pop", type:"merch-figure", year:2020, region:"US", publisher:"Funko", desc:"Funko 公仔。", tags:["Funko"]},
  {ip:"Uncharted", title:"Uncharted (Statue by Gaming Heads)", type:"merch-figure", year:2017, region:"US", publisher:"Gaming Heads", desc:"雕像。", tags:["雕像"]},
  {ip:"Uncharted", title:"Uncharted (Nathan Drake Action Figure)", type:"merch-figure", year:2011, region:"US", publisher:"NECA", desc:"可动人偶。", tags:["可动"]},
  {ip:"Uncharted", title:"Uncharted Board Game", type:"game-board", year:2022, region:"US", publisher:"CMON", desc:"桌游。", tags:["桌游"]},

  // ============================================================
  // TOMB RAIDER
  // ============================================================
  {ip:"Tomb Raider", title:"Lara Croft: Tomb Raider (Film 2001)", type:"film-live", year:2001, region:"US", publisher:"Paramount", desc:"安吉丽娜·朱莉主演。", tags:["真人电影"]},
  {ip:"Tomb Raider", title:"Lara Croft Tomb Raider: The Cradle of Life (Film 2003)", type:"film-live", year:2003, region:"US", publisher:"Paramount", desc:"续作。", tags:["真人电影"]},
  {ip:"Tomb Raider", title:"Tomb Raider (Film 2018)", type:"film-live", year:2018, region:"US", publisher:"Warner Bros.", desc:"艾丽西亚·维坎德主演重启作。", tags:["真人电影"]},
  {ip:"Tomb Raider", title:"Tomb Raider 2 (Film - Netflix 2025)", type:"film-live", year:2025, region:"US", publisher:"Netflix", desc:"续作。", tags:["真人电影"]},
  {ip:"Tomb Raider", title:"Tomb Raider: The Legend of Lara Croft (Netflix Anime)", type:"anime", year:2024, region:"US", publisher:"Netflix / Powerhouse", desc:"动画剧集。", tags:["动画"]},
  {ip:"Tomb Raider", title:"Tomb Raider (Mobile)", type:"game-mobile", year:2010, region:"US", publisher:"Square Enix", desc:"手游。", tags:["手游"]},
  {ip:"Tomb Raider", title:"Tomb Raider (Mobile 2015)", type:"game-mobile", year:2015, region:"US", publisher:"Square Enix", desc:"手游。", tags:["手游"]},
  {ip:"Tomb Raider", title:"Lara Croft GO", type:"game-mobile", year:2015, region:"US", publisher:"Square Enix", desc:"解谜手游。", tags:["手游"]},
  {ip:"Tomb Raider", title:"Lara Croft: Relic Run", type:"game-mobile", year:2016, region:"US", publisher:"Square Enix", desc:"跑酷手游。", tags:["手游"]},
  {ip:"Tomb Raider", title:"Shadow of the Tomb Raider", type:"game-spinoff", year:2018, region:"US", publisher:"Square Enix", desc:"重启三部曲终章。", tags:["ACT"]},
  {ip:"Tomb Raider", title:"Rise of the Tomb Raider", type:"game-spinoff", year:2015, region:"US", publisher:"Square Enix", desc:"重启三部曲。", tags:["ACT"]},
  {ip:"Tomb Raider", title:"Tomb Raider (2013 Reboot)", type:"game-spinoff", year:2013, region:"US", publisher:"Square Enix", desc:"重启三部曲首章。", tags:["ACT"]},
  {ip:"Tomb Raider", title:"Tomb Raider: Definitive Edition", type:"game-spinoff", year:2014, region:"US", publisher:"Square Enix", desc:"PS4 重制。", tags:["重制"]},
  {ip:"Tomb Raider", title:"Tomb Raider: Legend", type:"game-spinoff", year:2006, region:"US", publisher:"Eidos", desc:"续作。", tags:["ACT"]},
  {ip:"Tomb Raider", title:"Tomb Raider: Anniversary", type:"game-spinoff", year:2007, region:"US", publisher:"Eidos", desc:"初代重制。", tags:["重制"]},
  {ip:"Tomb Raider", title:"Tomb Raider: Underworld", type:"game-spinoff", year:2008, region:"US", publisher:"Eidos", desc:"续作。", tags:["ACT"]},
  {ip:"Tomb Raider", title:"Lara Croft and the Guardian of Light", type:"game-spinoff", year:2010, region:"US", publisher:"Square Enix", desc:"俯视动作。", tags:["ACT"]},
  {ip:"Tomb Raider", title:"Lara Croft and the Temple of Osiris", type:"game-spinoff", year:2014, region:"US", publisher:"Square Enix", desc:"续作。", tags:["ACT"]},
  {ip:"Tomb Raider", title:"Tomb Raider (Top Cow Comic)", type:"manga", year:1999, region:"US", publisher:"Top Cow", desc:"美式漫画。", tags:["美式漫画"]},
  {ip:"Tomb Raider", title:"Tomb Raider (Dark Horse Comic)", type:"manga", year:2014, region:"US", publisher:"Dark Horse", desc:"黑马漫画。", tags:["美式漫画"]},
  {ip:"Tomb Raider", title:"Tomb Raider: The Last Revelation (Novel)", type:"novel", year:2004, region:"US", publisher:"Pocket Books", desc:"小说。", tags:["小说"]},
  {ip:"Tomb Raider", title:"Tomb Raider: The Man of Bronze (Novel)", type:"novel", year:2004, region:"US", publisher:"Pocket Books", desc:"小说。", tags:["小说"]},
  {ip:"Tomb Raider", title:"Tomb Raider (OST 2013)", type:"ost", year:2013, region:"US", publisher:"Square Enix", desc:"原声。", tags:["OST"]},
  {ip:"Tomb Raider", title:"Tomb Raider: Definitive Survivor Trilogy OST", type:"ost", year:2018, region:"US", publisher:"Square Enix", desc:"三部曲原声。", tags:["OST"]},
  {ip:"Tomb Raider", title:"Lara Croft Funko Pop", type:"merch-figure", year:2018, region:"US", publisher:"Funko", desc:"Funko 公仔。", tags:["Funko"]},
  {ip:"Tomb Raider", title:"Lara Croft Action Figure (NECA)", type:"merch-figure", year:2018, region:"US", publisher:"NECA", desc:"可动人偶。", tags:["可动"]},
  {ip:"Tomb Raider", title:"Lara Croft Plush", type:"merch-figure", year:2010, region:"US", publisher:"Square Enix", desc:"毛绒。", tags:["毛绒"]},
  {ip:"Tomb Raider", title:"Tomb Raider OST - Alison Haislip Concert", type:"concert", year:2018, region:"US", publisher:"Square Enix", desc:"音乐会。", tags:["音乐会"]},

  // ============================================================
  // GRAND THEFT AUTO
  // ============================================================
  {ip:"Grand Theft Auto", title:"GTA: San Andreas (Game)", type:"game-spinoff", year:2004, region:"US", publisher:"Rockstar", desc:"续作。", tags:["ACT"]},
  {ip:"Grand Theft Auto", title:"GTA IV (Game)", type:"game-spinoff", year:2008, region:"US", publisher:"Rockstar", desc:"续作。", tags:["ACT"]},
  {ip:"Grand Theft Auto", title:"GTA V (Game)", type:"game-spinoff", year:2013, region:"US", publisher:"Rockstar", desc:"续作。", tags:["ACT"]},
  {ip:"Grand Theft Auto", title:"GTA Online", type:"game-spinoff", year:2013, region:"US", publisher:"Rockstar", desc:"网游。", tags:["网游"]},
  {ip:"Grand Theft Auto", title:"GTA: The Trilogy - The Definitive Edition", type:"game-spinoff", year:2021, region:"US", publisher:"Rockstar", desc:"三部曲复刻。", tags:["复刻"]},
  {ip:"Grand Theft Auto", title:"GTA VI (Upcoming)", type:"game-spinoff", year:2025, region:"US", publisher:"Rockstar", desc:"新作。", tags:["ACT"]},
  {ip:"Grand Theft Auto", title:"GTA: Vice City Stories", type:"game-spinoff", year:2006, region:"US", publisher:"Rockstar", desc:"PSP 续作。", tags:["ACT"]},
  {ip:"Grand Theft Auto", title:"GTA: Liberty City Stories", type:"game-spinoff", year:2005, region:"US", publisher:"Rockstar", desc:"PSP 续作。", tags:["ACT"]},
  {ip:"Grand Theft Auto", title:"GTA: Chinatown Wars", type:"game-spinoff", year:2009, region:"US", publisher:"Rockstar", desc:"NDS 续作。", tags:["ACT"]},
  {ip:"Grand Theft Auto", title:"GTA: Vice City", type:"game-spinoff", year:2002, region:"US", publisher:"Rockstar", desc:"续作。", tags:["ACT"]},
  {ip:"Grand Theft Auto", title:"GTA: San Andreas (Mobile)", type:"game-mobile", year:2013, region:"US", publisher:"Rockstar", desc:"手游版。", tags:["手游"]},
  {ip:"Grand Theft Auto", title:"GTA: Liberty City Stories (Mobile)", type:"game-mobile", year:2015, region:"US", publisher:"Rockstar", desc:"手游。", tags:["手游"]},
  {ip:"Grand Theft Auto", title:"GTA: Chinatown Wars (iOS)", type:"game-mobile", year:2010, region:"US", publisher:"Rockstar", desc:"手游。", tags:["手游"]},
  {ip:"Grand Theft Auto", title:"GTA V (Comic)", type:"manga", year:2017, region:"US", publisher:"Titan Comics", desc:"漫画。", tags:["美式漫画"]},
  {ip:"Grand Theft Auto", title:"GTA: San Andreas (Strategy Guide)", type:"artbook", year:2004, region:"US", publisher:"Brady Games", desc:"攻略本。", tags:["攻略"]},
  {ip:"Grand Theft Auto", title:"GTA V OST (Various Artists)", type:"ost", year:2013, region:"US", publisher:"Rockstar", desc:"原声。", tags:["OST"]},
  {ip:"Grand Theft Auto", title:"GTA: San Andreas OST", type:"ost", year:2004, region:"US", publisher:"Rockstar", desc:"原声。", tags:["OST"]},
  {ip:"Grand Theft Auto", title:"GTA: Vice City OST", type:"ost", year:2002, region:"US", publisher:"Rockstar", desc:"原声。", tags:["OST"]},
  {ip:"Grand Theft Auto", title:"GTA IV OST", type:"ost", year:2008, region:"US", publisher:"Rockstar", desc:"原声。", tags:["OST"]},
  {ip:"Grand Theft Auto", title:"GTA Funko Pop (Trevor)", type:"merch-figure", year:2017, region:"US", publisher:"Funko", desc:"Funko 公仔。", tags:["Funko"]},
  {ip:"Grand Theft Auto", title:"GTA Action Figure (NECA)", type:"merch-figure", year:2019, region:"US", publisher:"NECA", desc:"可动人偶。", tags:["可动"]},
  {ip:"Grand Theft Auto", title:"GTA Plush (CJ)", type:"merch-figure", year:2018, region:"US", publisher:"Kidrobot", desc:"毛绒。", tags:["毛绒"]},
  {ip:"Grand Theft Auto", title:"GTA: San Andreas x Crocs", type:"collab", year:2022, region:"Global", publisher:"Crocs", desc:"联名鞋。", tags:["鞋类"]},
  {ip:"Grand Theft Auto", title:"GTA Monopoly", type:"game-board", year:2020, region:"US", publisher:"USAopoly", desc:"大富翁。", tags:["桌游"]},
  {ip:"Grand Theft Auto", title:"GTA Poker Chips (Official)", type:"merch-toy", year:2013, region:"US", publisher:"Rockstar", desc:"扑克筹码。", tags:["道具"]},
  {ip:"Grand Theft Auto", title:"GTA V x Diamond Casino OST", type:"ost", year:2019, region:"US", publisher:"Rockstar", desc:"DLC 原声。", tags:["OST"]},
  {ip:"Grand Theft Auto", title:"GTA Pachinko", type:"pachinko", year:2015, region:"JP", publisher:"Sammy", desc:"柏青哥。", tags:["柏青哥"]},

  // ============================================================
  // RED DEAD REDEMPTION
  // ============================================================
  {ip:"Red Dead Redemption", title:"Red Dead Redemption 2 (Game)", type:"game-spinoff", year:2018, region:"US", publisher:"Rockstar", desc:"前传续作。", tags:["ACT"]},
  {ip:"Red Dead Redemption", title:"Red Dead Redemption (Original)", type:"game-spinoff", year:2010, region:"US", publisher:"Rockstar", desc:"原版。", tags:["ACT"]},
  {ip:"Red Dead Redemption", title:"Red Dead Online", type:"game-spinoff", year:2019, region:"US", publisher:"Rockstar", desc:"网游。", tags:["网游"]},
  {ip:"Red Dead Redemption", title:"Red Dead Revolver", type:"game-spinoff", year:2004, region:"US", publisher:"Rockstar", desc:"系列起源。", tags:["ACT"]},
  {ip:"Red Dead Redemption", title:"Red Dead Redemption: Undead Nightmare", type:"game-spinoff", year:2010, region:"US", publisher:"Rockstar", desc:"僵尸 DLC。", tags:["DLC"]},
  {ip:"Red Dead Redemption", title:"Red Dead Redemption 2: The Art of the Game", type:"artbook", year:2018, region:"US", publisher:"Insight Editions", desc:"画集。", tags:["画集"]},
  {ip:"Red Dead Redemption", title:"Red Dead Redemption 2 (Comic)", type:"manga", year:2022, region:"US", publisher:"Titan Comics", desc:"漫画。", tags:["美式漫画"]},
  {ip:"Red Dead Redemption", title:"Red Dead Redemption (Film - Netflix 2025)", type:"film-live", year:2025, region:"US", publisher:"Netflix", desc:"真人电影制作中。", tags:["真人电影"]},
  {ip:"Red Dead Redemption", title:"Red Dead Redemption 2 OST", type:"ost", year:2018, region:"US", publisher:"Rockstar", desc:"原声。", tags:["OST"]},
  {ip:"Red Dead Redemption", title:"Red Dead Redemption (Original) OST", type:"ost", year:2010, region:"US", publisher:"Rockstar", desc:"原声。", tags:["OST"]},
  {ip:"Red Dead Redemption", title:"Red Dead Redemption Funko Pop (Arthur)", type:"merch-figure", year:2019, region:"US", publisher:"Funko", desc:"Funko 公仔。", tags:["Funko"]},
  {ip:"Red Dead Redemption", title:"Red Dead Redemption 2 (LEGO)", type:"merch-toy", year:2020, region:"US", publisher:"LEGO Ideas", desc:"乐高。", tags:["积木"]},
  {ip:"Red Dead Redemption", title:"Red Dead Redemption Action Figure (NECA)", type:"merch-figure", year:2020, region:"US", publisher:"NECA", desc:"可动人偶。", tags:["可动"]},
  {ip:"Red Dead Redemption", title:"Red Dead Redemption (Revolver Replica)", type:"merch-toy", year:2018, region:"US", publisher:"Rockstar", desc:"复刻左轮。", tags:["道具"]},
  {ip:"Red Dead Redemption", title:"Red Dead Redemption x Stetson Hat", type:"merch-cloth", year:2018, region:"US", publisher:"Stetson", desc:"联名帽。", tags:["服装"]},

  // ============================================================
  // PERSONA / SHIN MEGAMI TENSEI (Atlus)
  // ============================================================
  {ip:"Persona", title:"Persona 5 The Animation", type:"anime", year:2018, region:"JP", publisher:"A-1 Pictures", desc:"《5》动画。", tags:["动画"]},
  {ip:"Persona", title:"Persona 4 The Animation", type:"anime", year:2011, region:"JP", publisher:"AIC A.S.T.A.", desc:"《4》动画。", tags:["动画"]},
  {ip:"Persona", title:"Persona 3 The Animation", type:"anime", year:2013, region:"JP", publisher:"A-1 Pictures", desc:"《3》动画。", tags:["动画"]},
  {ip:"Persona", title:"Persona 5 Strikers", type:"game-spinoff", year:2020, region:"JP", publisher:"Atlus / Omega Force", desc:"无双式。", tags:["无双"]},
  {ip:"Persona", title:"Persona Q: Shadow of the Labyrinth", type:"game-spinoff", year:2014, region:"JP", publisher:"Atlus", desc:"3DS 迷宫 RPG。", tags:["迷宫 RPG"]},
  {ip:"Persona", title:"Persona Q2: New Cinema Labyrinth", type:"game-spinoff", year:2018, region:"JP", publisher:"Atlus", desc:"3DS 续作。", tags:["迷宫 RPG"]},
  {ip:"Persona", title:"Persona 4 Golden", type:"game-spinoff", year:2012, region:"JP", publisher:"Atlus", desc:"PSV 重制。", tags:["重制"]},
  {ip:"Persona", title:"Persona 4 Arena", type:"game-spinoff", year:2012, region:"JP", publisher:"Arc System Works", desc:"格斗续作。", tags:["FTG"]},
  {ip:"Persona", title:"Persona 4 Arena Ultimax", type:"game-spinoff", year:2013, region:"JP", publisher:"Arc System Works", desc:"格斗续作。", tags:["FTG"]},
  {ip:"Persona", title:"Persona 5 Royal", type:"game-spinoff", year:2019, region:"JP", publisher:"Atlus", desc:"PS4 增强版。", tags:["RPG"]},
  {ip:"Persona", title:"Persona 3 Reload", type:"game-spinoff", year:2024, region:"JP", publisher:"Atlus", desc:"《3》重制。", tags:["重制"]},
  {ip:"Persona", title:"Persona 3 Portable", type:"game-spinoff", year:2009, region:"JP", publisher:"Atlus", desc:"PSP 版。", tags:["RPG"]},
  {ip:"Persona", title:"Persona 5 Tactica", type:"game-spinoff", year:2023, region:"JP", publisher:"Atlus", desc:"SRPG。", tags:["SRPG"]},
  {ip:"Persona", title:"Persona 4: Dancing All Night", type:"game-spinoff", year:2015, region:"JP", publisher:"Atlus", desc:"音乐游戏。", tags:["音乐"]},
  {ip:"Persona", title:"Persona 5: Dancing in Starlight", type:"game-spinoff", year:2018, region:"JP", publisher:"Atlus", desc:"音乐游戏。", tags:["音乐"]},
  {ip:"Persona", title:"Persona 3: Dancing in Moonlight", type:"game-spinoff", year:2018, region:"JP", publisher:"Atlus", desc:"音乐游戏。", tags:["音乐"]},
  {ip:"Persona", title:"Persona (Manga)", type:"manga", year:2007, region:"JP", publisher:"Ichijinsha", desc:"《4》漫画。", tags:["少年漫画"]},
  {ip:"Persona", title:"Persona 5 (Manga)", type:"manga", year:2016, region:"JP", publisher:"Ichijinsha", desc:"《5》漫画。", tags:["少年漫画"]},
  {ip:"Persona", title:"Persona 5: Mementos Mission (Manga)", type:"manga", year:2018, region:"JP", publisher:"Ichijinsha", desc:"衍生漫画。", tags:["少年漫画"]},
  {ip:"Persona", title:"Persona 4 (Novel)", type:"novel", year:2012, region:"JP", publisher:"Ichijinsha", desc:"小说。", tags:["小说"]},
  {ip:"Persona", title:"Persona 5 (Novel)", type:"novel", year:2017, region:"JP", publisher:"Ichijinsha", desc:"小说。", tags:["小说"]},
  {ip:"Persona", title:"Persona 5 Royal (Novel)", type:"novel", year:2019, region:"JP", publisher:"Ichijinsha", desc:"小说。", tags:["小说"]},
  {ip:"Persona", title:"Persona 5 The Day Breakers (Anime Special)", type:"anime", year:2016, region:"JP", publisher:"A-1 Pictures", desc:"动画特别篇。", tags:["动画特别篇"]},
  {ip:"Persona", title:"Persona 3 The Movie (Film Series)", type:"film-anime", year:2013, region:"JP", publisher:"AIC A.S.T.A.", desc:"剧场版四部曲。", tags:["剧场版"]},
  {ip:"Persona", title:"Persona 5 The Animation: Dark Sun...", type:"anime", year:2018, region:"JP", publisher:"A-1 Pictures", desc:"特别篇。", tags:["动画特别篇"]},
  {ip:"Persona", title:"Persona 5 The Animation: Stars and Ours", type:"anime", year:2019, region:"JP", publisher:"A-1 Pictures", desc:"特别篇。", tags:["动画特别篇"]},
  {ip:"Persona", title:"Persona 5 OST", type:"ost", year:2017, region:"JP", publisher:"Atlus", desc:"原声。", tags:["OST"]},
  {ip:"Persona", title:"Persona 5 Royal OST", type:"ost", year:2019, region:"JP", publisher:"Atlus", desc:"原声。", tags:["OST"]},
  {ip:"Persona", title:"Persona 4 OST", type:"ost", year:2008, region:"JP", publisher:"Atlus", desc:"原声。", tags:["OST"]},
  {ip:"Persona", title:"Persona 3 OST", type:"ost", year:2006, region:"JP", publisher:"Atlus", desc:"原声。", tags:["OST"]},
  {ip:"Persona", title:"Persona Music Live", type:"concert", year:2019, region:"JP", publisher:"Atlus", desc:"音乐会。", tags:["音乐会"]},
  {ip:"Persona", title:"Persona Super Live 2019 (P5)", type:"concert", year:2019, region:"US", publisher:"Atlus", desc:"超级音乐会。", tags:["音乐会"]},
  {ip:"Persona", title:"Persona 5 Royal Concert Tour", type:"concert", year:2023, region:"US", publisher:"Atlus", desc:"北美巡演。", tags:["音乐会"]},
  {ip:"Persona", title:"Persona 25th Anniversary Concert", type:"concert", year:2021, region:"JP", publisher:"Atlus", desc:"25 周年音乐会。", tags:["周年"]},
  {ip:"Persona", title:"Persona 5 Plush (Joker)", type:"merch-figure", year:2018, region:"JP", publisher:"Atlus", desc:"Joker 毛绒。", tags:["毛绒"]},
  {ip:"Persona", title:"Persona 5 Nendoroid (Joker)", type:"merch-figure", year:2018, region:"JP", publisher:"Good Smile", desc:"粘土人。", tags:["粘土人"]},
  {ip:"Persona", title:"Persona 5 (Trading Card Game)", type:"merch-card", year:2018, region:"JP", publisher:"Atlus", desc:"TCG。", tags:["TCG"]},
  {ip:"Persona", title:"Persona 5 (Watches - SuperGroupies)", type:"merch-cloth", year:2019, region:"JP", publisher:"SuperGroupies", desc:"联名表。", tags:["手表"]},
  {ip:"Persona", title:"Persona 5 (Hoodie - SuperGroupies)", type:"merch-cloth", year:2019, region:"JP", publisher:"SuperGroupies", desc:"联名衣。", tags:["服装"]},
  {ip:"Persona", title:"Persona 5 x Afuri Ramen", type:"collab", year:2018, region:"JP", publisher:"Afuri", desc:"拉面联名。", tags:["餐饮联动"]},
  {ip:"Persona", title:"Persona 5 x Lawson", type:"collab", year:2019, region:"JP", publisher:"Lawson", desc:"便利店联名。", tags:["餐饮联动"]},
  {ip:"Persona", title:"Persona 5 (Stage Play)", type:"theater", year:2019, region:"JP", publisher:"Marvelous", desc:"舞台剧。", tags:["舞台剧"]},
  {ip:"Persona", title:"Persona 4 (Stage Play)", type:"theater", year:2014, region:"JP", publisher:"Marvelous", desc:"舞台剧。", tags:["舞台剧"]},
  {ip:"Persona", title:"Persona 4 Golden (Stage Play)", type:"theater", year:2015, region:"JP", publisher:"Marvelous", desc:"舞台剧。", tags:["舞台剧"]},
  {ip:"Persona", title:"Persona 5 Royal x Capcom Cafe", type:"cafe", year:2019, region:"JP", publisher:"Capcom Cafe", desc:"主题咖啡。", tags:["主题咖啡"]},
  {ip:"Persona", title:"Persona 5 x TOWER RECORDS", type:"collab", year:2018, region:"JP", publisher:"Tower Records", desc:"唱片店联名。", tags:["唱片店"]},

  // ============================================================
  // DARK SOULS / ELDEN RING (FromSoftware)
  // ============================================================
  {ip:"Dark Souls", title:"Dark Souls: Design Works (Artbook)", type:"artbook", year:2012, region:"JP", publisher:"FromSoftware / Udon", desc:"画集。", tags:["画集"]},
  {ip:"Dark Souls", title:"Dark Souls: The Official Guide", type:"artbook", year:2011, region:"UK", publisher:"Future Press", desc:"攻略。", tags:["攻略"]},
  {ip:"Dark Souls", title:"Dark Souls II (Game)", type:"game-spinoff", year:2014, region:"JP", publisher:"FromSoftware", desc:"续作。", tags:["ARPG"]},
  {ip:"Dark Souls", title:"Dark Souls III (Game)", type:"game-spinoff", year:2016, region:"JP", publisher:"FromSoftware", desc:"续作。", tags:["ARPG"]},
  {ip:"Dark Souls", title:"Dark Souls II: Crown of the Sunken King", type:"game-spinoff", year:2014, region:"JP", publisher:"FromSoftware", desc:"DLC。", tags:["DLC"]},
  {ip:"Dark Souls", title:"Dark Souls II: Crown of the Old Iron King", type:"game-spinoff", year:2014, region:"JP", publisher:"FromSoftware", desc:"DLC。", tags:["DLC"]},
  {ip:"Dark Souls", title:"Dark Souls II: Crown of the Ivory King", type:"game-spinoff", year:2014, region:"JP", publisher:"FromSoftware", desc:"DLC。", tags:["DLC"]},
  {ip:"Dark Souls", title:"Dark Souls III: Ashes of Ariandel", type:"game-spinoff", year:2016, region:"JP", publisher:"FromSoftware", desc:"DLC。", tags:["DLC"]},
  {ip:"Dark Souls", title:"Dark Souls III: The Ringed City", type:"game-spinoff", year:2017, region:"JP", publisher:"FromSoftware", desc:"DLC。", tags:["DLC"]},
  {ip:"Dark Souls", title:"Dark Souls: Remastered", type:"game-spinoff", year:2018, region:"JP", publisher:"FromSoftware", desc:"重制。", tags:["重制"]},
  {ip:"Dark Souls", title:"Dark Souls: Prepare to Die Edition", type:"game-spinoff", year:2012, region:"JP", publisher:"FromSoftware", desc:"PC 增强版。", tags:["RPG"]},
  {ip:"Dark Souls", title:"Dark Souls (Tabletop RPG)", type:"game-board", year:2017, region:"US", publisher:"Steamforged Games", desc:"桌游 RPG。", tags:["桌游"]},
  {ip:"Dark Souls", title:"Dark Souls (Board Game)", type:"game-board", year:2017, region:"US", publisher:"Steamforged Games", desc:"桌游。", tags:["桌游"]},
  {ip:"Dark Souls", title:"Dark Souls: The Card Game", type:"merch-card", year:2017, region:"US", publisher:"Steamforged Games", desc:"桌游卡牌。", tags:["桌游"]},
  {ip:"Dark Souls", title:"Dark Souls: Remastered OST", type:"ost", year:2018, region:"JP", publisher:"FromSoftware", desc:"原声。", tags:["OST"]},
  {ip:"Dark Souls", title:"Dark Souls III OST", type:"ost", year:2016, region:"JP", publisher:"FromSoftware", desc:"原声。", tags:["OST"]},
  {ip:"Dark Souls", title:"Dark Souls: Siegmeyer of Catarina (Plush)", type:"merch-figure", year:2014, region:"JP", publisher:"FromSoftware", desc:"洋葱骑士毛绒。", tags:["毛绒"]},
  {ip:"Dark Souls", title:"Dark Souls: Solaire Plush", type:"merch-figure", year:2014, region:"JP", publisher:"FromSoftware", desc:"太阳骑士毛绒。", tags:["毛绒"]},
  {ip:"Dark Souls", title:"Dark Souls x NikoMaki", type:"collab", year:2019, region:"JP", publisher:"NikoMaki", desc:"扭蛋联名。", tags:["扭蛋"]},
  {ip:"Dark Souls", title:"Dark Souls (Roleplay Cosplay Costumes)", type:"merch-cloth", year:2015, region:"US", publisher:"Miccostumes", desc:"COS 服装。", tags:["COS"]},
  {ip:"Elden Ring", title:"Elden Ring OST", type:"ost", year:2022, region:"JP", publisher:"FromSoftware", desc:"原声。", tags:["OST"]},
  {ip:"Elden Ring", title:"Elden Ring: Shadow of the Erdtree", type:"game-spinoff", year:2024, region:"JP", publisher:"FromSoftware", desc:"大型 DLC。", tags:["DLC"]},
  {ip:"Elden Ring", title:"Elden Ring: Official Strategy Guide", type:"artbook", year:2022, region:"JP", publisher:"Future Press", desc:"攻略。", tags:["攻略"]},
  {ip:"Elden Ring", title:"Elden Ring: The Art of the Game", type:"artbook", year:2022, region:"JP", publisher:"Udon", desc:"画集。", tags:["画集"]},
  {ip:"Elden Ring", title:"Elden Ring (Manga - ENEN no Shouboutai crossover)", type:"manga", year:2023, region:"JP", publisher:"FromSoftware", desc:"漫画合作。", tags:["少年漫画"]},
  {ip:"Elden Ring", title:"Elden Ring Board Game", type:"game-board", year:2024, region:"US", publisher:"Steamforged Games", desc:"桌游。", tags:["桌游"]},
  {ip:"Elden Ring", title:"Elden Ring Plush (Torrent)", type:"merch-figure", year:2022, region:"JP", publisher:"FromSoftware", desc:"托雷特毛绒。", tags:["毛绒"]},
  {ip:"Elden Ring", title:"Elden Ring Action Figure (Figma - Melina)", type:"merch-figure", year:2023, region:"JP", publisher:"Max Factory", desc:"Figma 可动。", tags:["Figma"]},
  {ip:"Elden Ring", title:"Elden Ring Nendoroid (Tarnished)", type:"merch-figure", year:2023, region:"JP", publisher:"Good Smile", desc:"粘土人。", tags:["粘土人"]},
  {ip:"Elden Ring", title:"Elden Ring x Bandai Spirits", type:"merch-toy", year:2023, region:"JP", publisher:"Bandai", desc:"模型联名。", tags:["模型"]},
  {ip:"Elden Ring", title:"Elden Ring Concert (FromSoftware)", type:"concert", year:2023, region:"JP", publisher:"FromSoftware", desc:"音乐会。", tags:["音乐会"]},
  {ip:"Elden Ring", title:"Elden Ring Live Concert Tour: Symphony of the Lands Between", type:"concert", year:2024, region:"Global", publisher:"FromSoftware", desc:"全球巡演。", tags:["交响乐"]},
  {ip:"Elden Ring", title:"Elden Ring (Manga - Comic Anthology)", type:"manga", year:2023, region:"JP", publisher:"Kadokawa", desc:"漫画选集。", tags:["少年漫画"]},

  // ============================================================
  // BLOODBORNE
  // ============================================================
  {ip:"Bloodborne", title:"Bloodborne: The Old Hunters", type:"game-spinoff", year:2015, region:"JP", publisher:"FromSoftware", desc:"DLC。", tags:["DLC"]},
  {ip:"Bloodborne", title:"Bloodborne OST (Mika Kitamura)", type:"ost", year:2015, region:"JP", publisher:"FromSoftware", desc:"原声。", tags:["OST"]},
  {ip:"Bloodborne", title:"Bloodborne: The Art of the Game", type:"artbook", year:2015, region:"JP", publisher:"Udon", desc:"画集。", tags:["画集"]},
  {ip:"Bloodborne", title:"Bloodborne (Comic - Titan)", type:"manga", year:2018, region:"US", publisher:"Titan Comics", desc:"漫画。", tags:["美式漫画"]},
  {ip:"Bloodborne", title:"Bloodborne (Board Game)", type:"game-board", year:2020, region:"US", publisher:"CMON", desc:"桌游。", tags:["桌游"]},
  {ip:"Bloodborne", title:"Bloodborne (Card Game)", type:"merch-card", year:2019, region:"US", publisher:"CMON", desc:"桌游卡牌。", tags:["桌游"]},
  {ip:"Bloodborne", title:"Bloodborne (Cosplay - Ludwig)", type:"merch-cloth", year:2016, region:"US", publisher:"Miccostumes", desc:"COS 服装。", tags:["COS"]},
  {ip:"Bloodborne", title:"Bloodborne Plush (Plain Doll)", type:"merch-figure", year:2016, region:"JP", publisher:"FromSoftware", desc:"人偶毛绒。", tags:["毛绒"]},
  {ip:"Bloodborne", title:"Bloodborne Action Figure (Figma - Hunter)", type:"merch-figure", year:2017, region:"JP", publisher:"Max Factory", desc:"Figma 可动。", tags:["Figma"]},
  {ip:"Bloodborne", title:"Bloodborne: The Hunter's Nightmare Concert", type:"concert", year:2024, region:"JP", publisher:"FromSoftware", desc:"音乐会。", tags:["音乐会"]},
  ];
  window.DATA = window.DATA.concat(EXT);
})();
