// Game IP Derivative Works Database - Extended Set Part 2
// Appends to window.DATA
(function(){
  const EXT = [
  // ============================================================
  // FINAL FANTASY (Square Enix)
  // ============================================================
  {ip:"Final Fantasy", title:"Final Fantasy: Legend of the Crystals (OVA)", type:"anime", year:1994, region:"JP", publisher:"Square / Madhouse", desc:"《V》1000 年后的 OVA 动画。", tags:["OVA"]},
  {ip:"Final Fantasy", title:"Final Fantasy: The Spirits Within (Film)", type:"film-anime", year:2001, region:"US", publisher:"Square Pictures / Columbia", desc:"首部 CG 电影长片,获奥斯卡特别技术奖。", tags:["CG 电影"]},
  {ip:"Final Fantasy", title:"Final Fantasy VII: Advent Children (Film)", type:"film-anime", year:2005, region:"JP", publisher:"Square Enix", desc:"《VII》后传剧场版。", tags:["CG 剧场版"]},
  {ip:"Final Fantasy", title:"Final Fantasy VII: Advent Children Complete", type:"film-anime", year:2009, region:"JP", publisher:"Square Enix", desc:"《Advent Children》加长版。", tags:["CG 剧场版"]},
  {ip:"Final Fantasy", title:"Final Fantasy VII: Dirge of Cerberus", type:"game-spinoff", year:2006, region:"JP", publisher:"Square Enix", desc:"《VII》衍生射击。", tags:["TPS"]},
  {ip:"Final Fantasy", title:"Final Fantasy VII: Crisis Core", type:"game-spinoff", year:2007, region:"JP", publisher:"Square Enix", desc:"扎克斯前传。", tags:["ARPG"]},
  {ip:"Final Fantasy", title:"Final Fantasy VII: Ever Crisis", type:"game-mobile", year:2023, region:"Global", publisher:"Square Enix", desc:"VII 全编年史手游。", tags:["手游"]},
  {ip:"Final Fantasy", title:"Final Fantasy VII Rebirth", type:"game-spinoff", year:2024, region:"JP", publisher:"Square Enix", desc:"《VII》重制三部曲第二作。", tags:["重制"]},
  {ip:"Final Fantasy", title:"Final Fantasy VII Remake Intergrade", type:"game-spinoff", year:2021, region:"JP", publisher:"Square Enix", desc:"《VII》重制第一作增强版。", tags:["重制"]},
  {ip:"Final Fantasy", title:"Final Fantasy VII Remake", type:"game-spinoff", year:2020, region:"JP", publisher:"Square Enix", desc:"《VII》重制第一作。", tags:["重制"]},
  {ip:"Final Fantasy", title:"Final Fantasy VII: Last Order (OVA)", type:"anime", year:2005, region:"JP", publisher:"Square Enix", desc:"《VII》前传 OVA。", tags:["OVA"]},
  {ip:"Final Fantasy", title:"Final Fantasy VII: On the Way to a Smile", type:"novel", year:2009, region:"JP", publisher:"Square Enix", desc:"《VII》后传短篇集。", tags:["小说"]},
  {ip:"Final Fantasy", title:"Final Fantasy VII: The Kids Are Alright", type:"manga", year:2020, region:"JP", publisher:"Square Enix", desc:"蒂法与玛琳的日常。", tags:["漫画"]},
  {ip:"Final Fantasy", title:"Final Fantasy XV", type:"game-spinoff", year:2016, region:"JP", publisher:"Square Enix", desc:"ARPG。", tags:["ARPG"]},
  {ip:"Final Fantasy", title:"Final Fantasy XV: Brotherhood (Anime)", type:"anime", year:2016, region:"JP", publisher:"A-1 Pictures", desc:"《XV》前传 5 集动画。", tags:["动画"]},
  {ip:"Final Fantasy", title:"Final Fantasy XV: Kingsglaive (Film)", type:"film-anime", year:2016, region:"JP", publisher:"Square Enix", desc:"CG 剧场版。", tags:["CG 剧场版"]},
  {ip:"Final Fantasy", title:"Final Fantasy XV: Episode Gladiolus / Prompto / Ignis", type:"game-spinoff", year:2017, region:"JP", publisher:"Square Enix", desc:"DLC 角色章。", tags:["DLC"]},
  {ip:"Final Fantasy", title:"Final Fantasy XIV Online", type:"game-spinoff", year:2013, region:"JP", publisher:"Square Enix", desc:"MMORPG。", tags:["MMO"]},
  {ip:"Final Fantasy", title:"Final Fantasy XIV: Dad of Light (TV)", type:"tv", year:2017, region:"JP", publisher:"TV Tokyo", desc:"父子通过 FFXIV 交流的真人剧。", tags:["真人剧"]},
  {ip:"Final Fantasy", title:"Final Fantasy XIV: Endwalker OST", type:"ost", year:2021, region:"JP", publisher:"Square Enix", desc:"6.0 原声带。", tags:["OST"]},
  {ip:"Final Fantasy", title:"Final Fantasy XIV: Shadowbringers OST", type:"ost", year:2019, region:"JP", publisher:"Square Enix", desc:"5.0 原声带。", tags:["OST"]},
  {ip:"Final Fantasy", title:"Final Fantasy XIV: A Realm Reborn OST", type:"ost", year:2013, region:"JP", publisher:"Square Enix", desc:"2.0 原声带。", tags:["OST"]},
  {ip:"Final Fantasy", title:"Final Fantasy XVI", type:"game-spinoff", year:2023, region:"JP", publisher:"Square Enix", desc:"《XVI》正统续作。", tags:["ARPG"]},
  {ip:"Final Fantasy", title:"Final Fantasy XVI: Dominance (Novel)", type:"novel", year:2024, region:"JP", publisher:"Square Enix", desc:"官方前传小说。", tags:["小说"]},
  {ip:"Final Fantasy", title:"Final Fantasy XI (MMO)", type:"game-spinoff", year:2002, region:"JP", publisher:"Square Enix", desc:"系列首部 MMO。", tags:["MMO"]},
  {ip:"Final Fantasy", title:"Final Fantasy X / X-2", type:"game-spinoff", year:2001, region:"JP", publisher:"Square", desc:"尤娜与提达的故事。", tags:["RPG"]},
  {ip:"Final Fantasy", title:"Final Fantasy X-2: Last Mission", type:"game-spinoff", year:2004, region:"JP", publisher:"Square Enix", desc:"《X-2》后传。", tags:["RPG"]},
  {ip:"Final Fantasy", title:"Final Fantasy: Unlimited (Anime)", type:"anime", year:2001, region:"JP", publisher:"Gonzo", desc:"原创 25 集动画。", tags:["动画"]},
  {ip:"Final Fantasy", title:"Final Fantasy (Manga Anthology)", type:"manga", year:2003, region:"JP", publisher:"Square Enix", desc:"短篇漫画合集。", tags:["短篇"]},
  {ip:"Final Fantasy", title:"Final Fantasy Tactics (Novel)", type:"novel", year:2007, region:"JP", publisher:"Square Enix", desc:"《Tactics》衍生小说。", tags:["小说"]},
  {ip:"Final Fantasy", title:"Final Fantasy Tactics Advance", type:"game-spinoff", year:2003, region:"JP", publisher:"Square Enix", desc:"GBA 策略续作。", tags:["策略"]},
  {ip:"Final Fantasy", title:"Final Fantasy Tactics A2: Grimoire of the Rift", type:"game-spinoff", year:2007, region:"JP", publisher:"Square Enix", desc:"NDS 策略续作。", tags:["策略"]},
  {ip:"Final Fantasy", title:"Final Fantasy Tactics: The War of the Lions", type:"game-spinoff", year:2007, region:"JP", publisher:"Square Enix", desc:"PSP 重制版。", tags:["重制"]},
  {ip:"Final Fantasy", title:"Final Fantasy Crystal Chronicles", type:"game-spinoff", year:2003, region:"JP", publisher:"Square Enix", desc:"联机 ARPG。", tags:["ARPG"]},
  {ip:"Final Fantasy", title:"Final Fantasy Crystal Chronicles Remastered", type:"game-spinoff", year:2020, region:"JP", publisher:"Square Enix", desc:"高清复刻版。", tags:["重制"]},
  {ip:"Final Fantasy", title:"Final Fantasy: 4 Heroes of Light", type:"game-spinoff", year:2009, region:"JP", publisher:"Square Enix", desc:"NDS 复刻风 RPG。", tags:["RPG"]},
  {ip:"Final Fantasy", title:"Final Fantasy Dimensions", type:"game-mobile", year:2012, region:"JP", publisher:"Square Enix", desc:"手游复刻风。", tags:["手游"]},
  {ip:"Final Fantasy", title:"Final Fantasy Record Keeper", type:"game-mobile", year:2014, region:"JP", publisher:"DeNA", desc:"系列回顾手游。", tags:["手游"]},
  {ip:"Final Fantasy", title:"Final Fantasy Brave Exvius", type:"game-mobile", year:2015, region:"JP", publisher:"Alinea / Alim", desc:"系列联动手游。", tags:["手游"]},
  {ip:"Final Fantasy", title:"Final Fantasy War of the Visions", type:"game-mobile", year:2019, region:"JP", publisher:"Square Enix", desc:"《Tactics》精神续作手游。", tags:["手游"]},
  {ip:"Final Fantasy", title:"Final Fantasy IX (Manga)", type:"manga", year:2000, region:"JP", publisher:"Square Enix", desc:"官方漫画。", tags:["漫画"]},
  {ip:"Final Fantasy", title:"Final Fantasy (Mamare Touno)", type:"novel", year:2007, region:"JP", publisher:"Square Enix", desc:"轻小说。", tags:["轻小说"]},
  {ip:"Final Fantasy", title:"Final Fantasy XIV: Hildibrand Adventures", type:"web-series", year:2014, region:"JP", publisher:"Square Enix", desc:"官方搞笑短剧。", tags:["短剧"]},
  {ip:"Final Fantasy", title:"Final Fantasy Art Book: Yoshitaka Amano Collection", type:"artbook", year:2017, region:"JP", publisher:"Square Enix", desc:"天野喜孝画集。", tags:["画集"]},
  {ip:"Final Fantasy", title:"Final Fantasy VII: 10th Anniversary Ultimania", type:"artbook", year:2007, region:"JP", publisher:"Square Enix", desc:"10 周年纪念。", tags:["设定集"]},
  {ip:"Final Fantasy", title:"Final Fantasy VII Remake: World Preview", type:"artbook", year:2020, region:"JP", publisher:"Square Enix", desc:"重制世界介绍。", tags:["设定集"]},
  {ip:"Final Fantasy", title:"Final Fantasy Plush (Square Enix e-STORE)", type:"merch-figure", year:2000, region:"JP", publisher:"Square Enix", desc:"系列毛绒。", tags:["毛绒"]},
  {ip:"Final Fantasy", title:"Moogle (Cactuar) Plush", type:"merch-figure", year:2005, region:"JP", publisher:"Square Enix", desc:"莫古利 / 仙人掌毛绒。", tags:["毛绒"]},
  {ip:"Final Fantasy", title:"Final Fantasy VII Remake PS4 Pro Bundle", type:"merch-cloth", year:2020, region:"JP", publisher:"Square Enix / Sony", desc:"限定主机套装。", tags:["硬件联动"]},
  {ip:"Final Fantasy", title:"Final Symphony (Concert)", type:"concert", year:2013, region:"EU", publisher:"AWR Music", desc:"伦敦 FF 交响音乐会。", tags:["交响乐"]},
  {ip:"Final Fantasy", title:"Distant Worlds: Music from Final Fantasy", type:"concert", year:2007, region:"US", publisher:"AWR Music", desc:"全球巡演。", tags:["交响乐"]},
  {ip:"Final Fantasy", title:"Final Fantasy XIV Fan Fest", type:"event", year:2014, region:"Global", publisher:"Square Enix", desc:"全球粉丝节。", tags:["粉丝节"]},
  {ip:"Final Fantasy", title:"Final Fantasy Cactuar Potion", type:"collab", year:2019, region:"JP", publisher:"Square Enix", desc:"仙人掌果汁。", tags:["饮品联动"]},
  {ip:"Final Fantasy", title:"Final Fantasy VII Remake x Cup Noodle", type:"collab", year:2020, region:"JP", publisher:"Nissin", desc:"日清拉面联名。", tags:["餐饮联动"]},
  {ip:"Final Fantasy", title:"Final Fantasy XIV: Shadowbringers x Vans", type:"collab", year:2019, region:"US", publisher:"Vans", desc:"Vans 联名。", tags:["服装"]},
  {ip:"Final Fantasy", title:"Final Fantasy Tactics OST", type:"ost", year:1997, region:"JP", publisher:"Square", desc:"野岛一成作曲。", tags:["OST"]},
  {ip:"Final Fantasy", title:"Final Fantasy X OST", type:"ost", year:2001, region:"JP", publisher:"Square", desc:"植松伸夫。", tags:["OST"]},
  {ip:"Final Fantasy", title:"Final Fantasy IX OST Plus", type:"ost", year:2000, region:"JP", publisher:"Square", desc:"《IX》原声。", tags:["OST"]},
  {ip:"Final Fantasy", title:"Final Fantasy Tactics (Radio Drama)", type:"audio", year:2003, region:"JP", publisher:"Square Enix", desc:"广播剧。", tags:["广播剧"]},
  {ip:"Final Fantasy", title:"Final Fantasy IV (DS Remake)", type:"game-spinoff", year:2007, region:"JP", publisher:"Square Enix", desc:"NDS 复刻。", tags:["重制"]},
  {ip:"Final Fantasy", title:"Final Fantasy IV: The After Years", type:"game-spinoff", year:2008, region:"JP", publisher:"Square Enix", desc:"《IV》后传。", tags:["RPG"]},
  {ip:"Final Fantasy", title:"Final Fantasy Type-0 HD", type:"game-spinoff", year:2015, region:"JP", publisher:"Square Enix", desc:"PSP 高清复刻。", tags:["重制"]},
  {ip:"Final Fantasy", title:"Final Fantasy Agito", type:"game-mobile", year:2013, region:"JP", publisher:"Square Enix", desc:"手游。", tags:["手游"]},
  {ip:"Final Fantasy", title:"Final Fantasy Awakening", type:"game-mobile", year:2018, region:"CN", publisher:"Tencent / Square Enix", desc:"国服手游。", tags:["手游"]},
  {ip:"Final Fantasy", title:"Mobius Final Fantasy", type:"game-mobile", year:2015, region:"JP", publisher:"Square Enix", desc:"手游 RPG。", tags:["手游"]},
  {ip:"Final Fantasy", title:"Final Fantasy Brave Exvius OST", type:"ost", year:2016, region:"JP", publisher:"Square Enix", desc:"手游原声。", tags:["OST"]},
  {ip:"Final Fantasy", title:"Final Fantasy Remake x Titan Quest Crossover", type:"collab", year:2021, region:"Global", publisher:"Square Enix", desc:"跨界联动。", tags:["跨界"]},
  {ip:"Final Fantasy", title:"Final Fantasy (Pikazo Music Box)", type:"ost", year:2019, region:"JP", publisher:"Square Enix", desc:"八音盒专辑。", tags:["八音盒"]},
  {ip:"Final Fantasy", title:"Final Fantasy: Pachislot", type:"pachinko", year:2010, region:"JP", publisher:"Sammy", desc:"柏青斯洛。", tags:["柏青斯洛"]},
  {ip:"Final Fantasy", title:"Final Fantasy Crystal Slot", type:"pachinko", year:2013, region:"JP", publisher:"Sammy", desc:"柏青斯洛。", tags:["柏青斯洛"]},
  {ip:"Final Fantasy", title:"Final Fantasy x Coca-Cola", type:"collab", year:2018, region:"Global", publisher:"Coca-Cola", desc:"可口可乐联名。", tags:["饮品联动"]},

  // ============================================================
  // KINGDOM HEARTS
  // ============================================================
  {ip:"Kingdom Hearts", title:"Kingdom Hearts (Manga)", type:"manga", year:2005, region:"JP", publisher:"Square Enix", desc:"原作剧情漫画化。", tags:["少年漫画"]},
  {ip:"Kingdom Hearts", title:"Kingdom Hearts II (Manga)", type:"manga", year:2007, region:"JP", publisher:"Square Enix", desc:"《II》漫画。", tags:["少年漫画"]},
  {ip:"Kingdom Hearts", title:"Kingdom Hearts 358/2 Days (Manga)", type:"manga", year:2010, region:"JP", publisher:"Square Enix", desc:"洛克萨斯前传。", tags:["少年漫画"]},
  {ip:"Kingdom Hearts", title:"Kingdom Hearts (Novel)", type:"novel", year:2017, region:"JP", publisher:"Square Enix", desc:"长篇小说。", tags:["小说"]},
  {ip:"Kingdom Hearts", title:"Kingdom Hearts (Light Novel)", type:"novel", year:2018, region:"JP", publisher:"Square Enix", desc:"轻小说版。", tags:["轻小说"]},
  {ip:"Kingdom Hearts", title:"Kingdom Hearts III OST", type:"ost", year:2019, region:"JP", publisher:"Square Enix", desc:"原声带。", tags:["OST"]},
  {ip:"Kingdom Hearts", title:"Kingdom Hearts II OST", type:"ost", year:2005, region:"JP", publisher:"Square Enix", desc:"原声带。", tags:["OST"]},
  {ip:"Kingdom Hearts", title:"Kingdom Hearts Orchestra", type:"concert", year:2017, region:"Global", publisher:"Disney / Square Enix", desc:"世界巡演。", tags:["交响乐"]},
  {ip:"Kingdom Hearts", title:"Kingdom Hearts Dark Road (Mobile)", type:"game-mobile", year:2020, region:"Global", publisher:"Square Enix", desc:"XIII 后传衍生手游。", tags:["手游"]},
  {ip:"Kingdom Hearts", title:"Kingdom Hearts Union X", type:"game-mobile", year:2017, region:"Global", publisher:"Square Enix", desc:"Unchained X 重制。", tags:["手游"]},
  {ip:"Kingdom Hearts", title:"Kingdom Hearts Melody of Memory", type:"game-spinoff", year:2020, region:"JP", publisher:"Square Enix", desc:"音乐节奏游戏。", tags:["音乐"]},
  {ip:"Kingdom Hearts", title:"Kingdom Hearts Re:Chain of Memories", type:"game-spinoff", year:2007, region:"JP", publisher:"Square Enix", desc:"PS2 重制。", tags:["重制"]},
  {ip:"Kingdom Hearts", title:"Kingdom Hearts 0.2 Birth by Sleep", type:"game-spinoff", year:2017, region:"JP", publisher:"Square Enix", desc:"III 序章。", tags:["动作"]},
  {ip:"Kingdom Hearts", title:"Kingdom Hearts HD 1.5 ReMIX", type:"game-spinoff", year:2013, region:"JP", publisher:"Square Enix", desc:"高清合集。", tags:["合集"]},
  {ip:"Kingdom Hearts", title:"Kingdom Hearts HD 2.5 ReMIX", type:"game-spinoff", year:2014, region:"JP", publisher:"Square Enix", desc:"高清合集 II。", tags:["合集"]},
  {ip:"Kingdom Hearts", title:"Kingdom Hearts HD 2.8 Final Chapter Prologue", type:"game-spinoff", year:2017, region:"JP", publisher:"Square Enix", desc:"高清合集。", tags:["合集"]},
  {ip:"Kingdom Hearts", title:"Kingdom Hearts All-Age Puzzle", type:"game-board", year:2003, region:"JP", publisher:"Enix", desc:"全年龄拼图。", tags:["拼图"]},
  {ip:"Kingdom Hearts", title:"Kingdom Hearts III Re Mind", type:"game-spinoff", year:2020, region:"JP", publisher:"Square Enix", desc:"DLC 后篇。", tags:["DLC"]},
  {ip:"Kingdom Hearts", title:"Kingdom Hearts Plush Series (King Mickey)", type:"merch-figure", year:2002, region:"JP", publisher:"Square Enix", desc:"米奇国王毛绒。", tags:["毛绒"]},
  {ip:"Kingdom Hearts", title:"Kingdom Hearts Keyblades Replica", type:"merch-toy", year:2003, region:"JP", publisher:"PROPLICA / Square Enix", desc:"钥匙剑 1:1 复刻。", tags:["道具"]},
  {ip:"Kingdom Hearts", title:"Kingdom Hearts III Ultimania", type:"artbook", year:2019, region:"JP", publisher:"Square Enix", desc:"3 官方设定集。", tags:["设定集"]},
  {ip:"Kingdom Hearts", title:"Kingdom Hearts x Tokyo Disneyland", type:"collab", year:2019, region:"JP", publisher:"Tokyo Disney", desc:"东京迪士尼联动。", tags:["主题乐园"]},
  {ip:"Kingdom Hearts", title:"Kingdom Hearts Funko Pop", type:"merch-figure", year:2018, region:"US", publisher:"Funko", desc:"Funko 公仔。", tags:["Funko"]},
  {ip:"Kingdom Hearts", title:"Kingdom Hearts x Gucci", type:"collab", year:2022, region:"Global", publisher:"Gucci", desc:"古驰联名。", tags:["奢侈品"]},
  {ip:"Kingdom Hearts", title:"Kingdom Hearts IV (Upcoming)", type:"game-spinoff", year:2025, region:"JP", publisher:"Square Enix", desc:"系列续作。", tags:["新作"]},
  {ip:"Kingdom Hearts", title:"Kingdom Hearts X (Back Cover)", type:"film-anime", year:2017, region:"JP", publisher:"Square Enix", desc:"2.8 收录电影短片。", tags:["CG 短片"]},
  {ip:"Kingdom Hearts", title:"Kingdom Hearts Birth by Sleep (PSP)", type:"game-spinoff", year:2010, region:"JP", publisher:"Square Enix", desc:"PSP 衍生。", tags:["ARPG"]},
  {ip:"Kingdom Hearts", title:"Kingdom Hearts Re:coded", type:"game-spinoff", year:2011, region:"JP", publisher:"Square Enix", desc:"NDS 衍生。", tags:["ARPG"]},
  {ip:"Kingdom Hearts", title:"Kingdom Hearts V-CAST", type:"game-mobile", year:2004, region:"US", publisher:"Square Enix / Verizon", desc:"Verizon 手机短篇。", tags:["手游"]},
  {ip:"Kingdom Hearts", title:"Kingdom Hearts (Trading Card Game)", type:"merch-card", year:2003, region:"JP", publisher:"Enix / Taito", desc:"集换卡牌。", tags:["TCG"]},

  // ============================================================
  // DRAGON QUEST
  // ============================================================
  {ip:"Dragon Quest", title:"Dragon Quest: Abel Yuusha no Densetsu (Anime)", type:"anime", year:1989, region:"JP", publisher:"Toei Animation", desc:"《IV》动画版。", tags:["动画"]},
  {ip:"Dragon Quest", title:"Dragon Quest: Dai no Daibouken (Anime 1991)", type:"anime", year:1991, region:"JP", publisher:"Toei Animation", desc:"《达伊的大冒险》长篇动画。", tags:["长篇动画"]},
  {ip:"Dragon Quest", title:"Dragon Quest: The Adventure of Dai (2020 Anime)", type:"anime", year:2020, region:"JP", publisher:"Toei Animation", desc:"重制版动画。", tags:["重制动画"]},
  {ip:"Dragon Quest", title:"Dragon Quest: Your Story (Film)", type:"film-anime", year:2019, region:"JP", publisher:"Toho", desc:"3DCG 剧场版。", tags:["CG 剧场版"]},
  {ip:"Dragon Quest", title:"Dragon Quest: Dai no Daibouken - The Live Stage", type:"theater", year:2018, region:"JP", publisher:"Toei", desc:"舞台剧。", tags:["舞台剧"]},
  {ip:"Dragon Quest", title:"Dragon Quest (Manga Anthology)", type:"manga", year:1989, region:"JP", publisher:"Shueisha", desc:"系列漫画。", tags:["少年漫画"]},
  {ip:"Dragon Quest", title:"Dragon Quest: Dai no Daibouken (Manga)", type:"manga", year:1989, region:"JP", publisher:"Shueisha", desc:"三条陆 / 稻田浩司漫画。", tags:["少年漫画","长篇"]},
  {ip:"Dragon Quest", title:"Dragon Quest: Emblem of Roto (Manga)", type:"manga", year:1991, region:"JP", publisher:"Shueisha", desc:"藤原カムイ《洛特之纹章》。", tags:["少年漫画"]},
  {ip:"Dragon Quest", title:"Dragon Quest Monsters+", type:"manga", year:2017, region:"JP", publisher:"V Jump", desc:"怪物篇漫画。", tags:["少年漫画"]},
  {ip:"Dragon Quest", title:"Dragon Quest: Monster Battle Road", type:"game-board", year:2007, region:"JP", publisher:"Square Enix", desc:"街机卡牌。", tags:["街机"]},
  {ip:"Dragon Quest", title:"Dragon Quest: Monster Battle Road II", type:"game-board", year:2009, region:"JP", publisher:"Square Enix", desc:"街机续作。", tags:["街机"]},
  {ip:"Dragon Quest", title:"Dragon Quest: Monster Battle Road Victory", type:"game-board", year:2011, region:"JP", publisher:"Square Enix", desc:"街机续作。", tags:["街机"]},
  {ip:"Dragon Quest", title:"Dragon Quest Heroes: Rocket Slime", type:"game-spinoff", year:2005, region:"JP", publisher:"Square Enix", desc:"DS 动作冒险。", tags:["动作"]},
  {ip:"Dragon Quest", title:"Dragon Quest Heroes: The World Tree's Woe and the Blight Below", type:"game-spinoff", year:2015, region:"JP", publisher:"Square Enix", desc:"无双式。", tags:["无双"]},
  {ip:"Dragon Quest", title:"Dragon Quest Heroes II", type:"game-spinoff", year:2016, region:"JP", publisher:"Square Enix", desc:"无双式续作。", tags:["无双"]},
  {ip:"Dragon Quest", title:"Dragon Quest Builders", type:"game-spinoff", year:2016, region:"JP", publisher:"Square Enix", desc:"沙盒建造。", tags:["沙盒"]},
  {ip:"Dragon Quest", title:"Dragon Quest Builders 2", type:"game-spinoff", year:2019, region:"JP", publisher:"Square Enix", desc:"沙盒续作。", tags:["沙盒"]},
  {ip:"Dragon Quest", title:"Dragon Quest Tact", type:"game-mobile", year:2020, region:"JP", publisher:"Square Enix", desc:"策略手游。", tags:["手游"]},
  {ip:"Dragon Quest", title:"Dragon Quest Walk", type:"game-mobile", year:2019, region:"JP", publisher:"Square Enix", desc:"AR 步行。", tags:["AR"]},
  {ip:"Dragon Quest", title:"Dragon Quest of the Stars", type:"game-mobile", year:2015, region:"JP", publisher:"Square Enix", desc:"手游 RPG。", tags:["手游"]},
  {ip:"Dragon Quest", title:"Dragon Quest Smash/Grow (Arcade)", type:"game-board", year:2021, region:"JP", publisher:"Square Enix", desc:"街机。", tags:["街机"]},
  {ip:"Dragon Quest", title:"Dragon Quest: The Adventure of Dai (Game)", type:"game-spinoff", year:2023, region:"JP", publisher:"Square Enix", desc:"动画同期游戏。", tags:["ARPG"]},
  {ip:"Dragon Quest", title:"Dragon Quest XI S Echoes of an Elusive Age", type:"game-spinoff", year:2019, region:"JP", publisher:"Square Enix", desc:"Switch 版增强。", tags:["RPG"]},
  {ip:"Dragon Quest", title:"Dragon Quest X (Online)", type:"game-spinoff", year:2012, region:"JP", publisher:"Square Enix", desc:"MMORPG。", tags:["MMO"]},
  {ip:"Dragon Quest", title:"Dragon Quest Pachislot", type:"pachinko", year:2011, region:"JP", publisher:"Sammy", desc:"柏青斯洛。", tags:["柏青斯洛"]},
  {ip:"Dragon Quest", title:"Dragon Quest Pachinko", type:"pachinko", year:2013, region:"JP", publisher:"Sammy", desc:"柏青哥。", tags:["柏青哥"]},
  {ip:"Dragon Quest", title:"Dragon Quest Music Concert", type:"concert", year:2016, region:"JP", publisher:"Square Enix", desc:"管弦音乐会。", tags:["交响乐"]},
  {ip:"Dragon Quest", title:"Dragon Quest Symphonic Suite (Orchestral)", type:"ost", year:1988, region:"JP", publisher:"Apollon / Enix", desc:"东京爱乐 CD。", tags:["OST"]},
  {ip:"Dragon Quest", title:"Dragon Quest: Legend of the Hero Abel (Soundtrack)", type:"ost", year:1989, region:"JP", publisher:"Toei", desc:"动画原声。", tags:["OST"]},
  {ip:"Dragon Quest", title:"Dragon Quest: Dai no Daibouken (Manga Volumes 1-37)", type:"manga", year:1989, region:"JP", publisher:"Shueisha", desc:"全套 37 卷。", tags:["长篇漫画"]},
  {ip:"Dragon Quest", title:"Dragon Quest Slime Plush (Enix Shop)", type:"merch-figure", year:1990, region:"JP", publisher:"Enix", desc:"史莱姆毛绒。", tags:["毛绒"]},
  {ip:"Dragon Quest", title:"Dragon Quest x Uniqlo UT", type:"merch-cloth", year:2019, region:"Global", publisher:"Uniqlo / Square Enix", desc:"UT 联名。", tags:["服装"]},
  {ip:"Dragon Quest", title:"Dragon Quest x Stanley", type:"collab", year:2022, region:"JP", publisher:"Stanley", desc:"Stanley 联名水杯。", tags:["餐饮联动"]},
  {ip:"Dragon Quest", title:"Dragon Quest Slime Ring (U-TREASURE)", type:"merch-cloth", year:2017, region:"JP", publisher:"U-TREASURE", desc:"史莱姆戒指。", tags:["珠宝"]},
  {ip:"Dragon Quest", title:"Dragon Quest: Tantei Slime (Novel)", type:"novel", year:2017, region:"JP", publisher:"Square Enix", desc:"小说。", tags:["小说"]},
  {ip:"Dragon Quest", title:"Dragon Quest: Dai no Daibouken (Novel)", type:"novel", year:2020, region:"JP", publisher:"Shueisha", desc:"重制版小说。", tags:["小说"]},
  {ip:"Dragon Quest", title:"Dragon Quest Monsters: Caravan Heart", type:"game-spinoff", year:2003, region:"JP", publisher:"Enix", desc:"GBC 外传。", tags:["RPG"]},
  {ip:"Dragon Quest", title:"Dragon Quest Monsters: Terry's Wonderland", type:"game-spinoff", year:1998, region:"JP", publisher:"Enix", desc:"GBC 外传。", tags:["RPG"]},
  {ip:"Dragon Quest", title:"Dragon Quest Monsters: Joker", type:"game-spinoff", year:2006, region:"JP", publisher:"Square Enix", desc:"NDS 怪物篇。", tags:["RPG"]},
  {ip:"Dragon Quest", title:"Dragon Quest Monsters: Joker 3", type:"game-spinoff", year:2016, region:"JP", publisher:"Square Enix", desc:"3DS 怪物篇。", tags:["RPG"]},
  {ip:"Dragon Quest", title:"Dragon Quest 25th Anniversary Concert", type:"concert", year:2011, region:"JP", publisher:"Square Enix", desc:"25 周年音乐会。", tags:["周年"]},
  {ip:"Dragon Quest", title:"Dragon Quest Slime Onsen (Spa)", type:"collab", year:2019, region:"JP", publisher:"Kadokawa", desc:"史莱姆温泉。", tags:["温泉联动"]},
  {ip:"Dragon Quest", title:"Dragon Quest: Monster Battle Road (Trading Card Game)", type:"merch-card", year:2008, region:"JP", publisher:"Square Enix", desc:"卡牌游戏。", tags:["TCG"]},
  {ip:"Dragon Quest", title:"Dragon Quest Museum Exhibition", type:"exhibition", year:2018, region:"JP", publisher:"Square Enix", desc:"官方展览。", tags:["展览"]},

  // ============================================================
  // SONIC THE HEDGEHOG
  // ============================================================
  {ip:"Sonic", title:"Adventures of Sonic the Hedgehog", type:"anime", year:1993, region:"US", publisher:"DiC", desc:"美式动画短剧。", tags:["美式动画"]},
  {ip:"Sonic", title:"Sonic the Hedgehog (SatAM)", type:"tv", year:1993, region:"US", publisher:"DiC", desc:"经典美式动画。", tags:["美式动画"]},
  {ip:"Sonic", title:"Sonic Underground", type:"tv", year:1999, region:"US", publisher:"DiC", desc:"索尼克乐队动画。", tags:["美式动画"]},
  {ip:"Sonic", title:"Sonic X (Anime)", type:"anime", year:2003, region:"JP", publisher:"TMS Entertainment", desc:"日式动画 78 集。", tags:["日式动画"]},
  {ip:"Sonic", title:"Sonic Boom (TV Series)", type:"tv", year:2014, region:"US", publisher:"BKN International / Sega", desc:"Sonic Boom 动画。", tags:["3D 动画"]},
  {ip:"Sonic", title:"Sonic Prime (Netflix)", type:"anime", year:2022, region:"CA", publisher:"WildBrain / Netflix", desc:"3DCG 网飞动画。", tags:["3DCG 动画"]},
  {ip:"Sonic", title:"Sonic the Hedgehog (Film 2020)", type:"film-live", year:2020, region:"US", publisher:"Paramount / Sega", desc:"首部真人电影。", tags:["真人电影"]},
  {ip:"Sonic", title:"Sonic the Hedgehog 2 (Film 2022)", type:"film-live", year:2022, region:"US", publisher:"Paramount", desc:"真人电影续作。", tags:["真人电影"]},
  {ip:"Sonic", title:"Sonic the Hedgehog 3 (Film 2024)", type:"film-live", year:2024, region:"US", publisher:"Paramount", desc:"真人电影第三作。", tags:["真人电影"]},
  {ip:"Sonic", title:"Sonic the Hedgehog 4 (Film 2027)", type:"film-live", year:2027, region:"US", publisher:"Paramount", desc:"真人电影续作 (制作中)。", tags:["真人电影"]},
  {ip:"Sonic", title:"Knuckles (Paramount+) ", type:"tv", year:2024, region:"US", publisher:"Paramount+", desc:"纳克鲁斯真人剧。", tags:["真人剧"]},
  {ip:"Sonic", title:"Sonic the Comic", type:"manga", year:1993, region:"UK", publisher:"Fleetway", desc:"英国漫画。", tags:["英式漫画"]},
  {ip:"Sonic", title:"Sonic the Hedgehog (Archie Comics)", type:"manga", year:1993, region:"US", publisher:"Archie Comics", desc:"阿奇漫画 280+ 期。", tags:["长篇漫画"]},
  {ip:"Sonic", title:"Sonic the Hedgehog (IDW Comics)", type:"manga", year:2018, region:"US", publisher:"IDW", desc:"IDW 漫画。", tags:["美式漫画"]},
  {ip:"Sonic", title:"Sonic X (Manga)", type:"manga", year:2004, region:"JP", publisher:"Shogakukan", desc:"《X》漫画。", tags:["少年漫画"]},
  {ip:"Sonic", title:"Sonic the Hedgehog: The Movie (OVA)", type:"anime", year:1996, region:"JP", publisher:"Sega / TMS", desc:"2 集 OVA。", tags:["OVA"]},
  {ip:"Sonic", title:"Night of the Werehog (Short)", type:"film-anime", year:2008, region:"JP", publisher:"Sega", desc:"短片动画。", tags:["短片"]},
  {ip:"Sonic", title:"Sonic Mania Adventures (Shorts)", type:"web-series", year:2018, region:"US", publisher:"Sega", desc:"5 集短动画。", tags:["短动画"]},
  {ip:"Sonic", title:"Sonic Colors: Rise of the Wisps (Short)", type:"web-series", year:2021, region:"US", publisher:"Sega", desc:"短片。", tags:["短动画"]},
  {ip:"Sonic", title:"Sonic Frontiers: Prologue", type:"web-series", year:2022, region:"US", publisher:"Sega", desc:"短片。", tags:["短动画"]},
  {ip:"Sonic", title:"Sonic & Knuckles (Manual Comics)", type:"manga", year:1994, region:"US", publisher:"Sega", desc:"说明书漫画。", tags:["短篇"]},
  {ip:"Sonic", title:"Sonic the Hedgehog (Archie Mini Series)", type:"manga", year:1993, region:"US", publisher:"Archie", desc:"迷你系列。", tags:["美式漫画"]},
  {ip:"Sonic", title:"Sonic CD (Intro Animation)", type:"anime", year:1993, region:"JP", publisher:"Toei Animation", desc:"CD 开场动画。", tags:["短片"]},
  {ip:"Sonic", title:"Sonic Runners (Mobile)", type:"game-mobile", year:2015, region:"Global", publisher:"Sega", desc:"手游跑酷。", tags:["手游"]},
  {ip:"Sonic", title:"Sonic Dash", type:"game-mobile", year:2013, region:"Global", publisher:"Sega / Hardlight", desc:"手游跑酷。", tags:["手游"]},
  {ip:"Sonic", title:"Sonic Forces: Speed Battle", type:"game-mobile", year:2017, region:"Global", publisher:"Sega", desc:"对战跑酷。", tags:["手游"]},
  {ip:"Sonic", title:"Sonic Racing: CrossWorlds", type:"game-spinoff", year:2025, region:"JP", publisher:"Sega", desc:"赛车新作。", tags:["赛车"]},
  {ip:"Sonic", title:"Team Sonic Racing", type:"game-spinoff", year:2019, region:"US", publisher:"Sega", desc:"赛车游戏。", tags:["赛车"]},
  {ip:"Sonic", title:"Sonic & All-Stars Racing Transformed", type:"game-spinoff", year:2012, region:"UK", publisher:"Sumo Digital", desc:"赛车游戏。", tags:["赛车"]},
  {ip:"Sonic", title:"Mario & Sonic at the Olympic Games", type:"game-spinoff", year:2007, region:"JP", publisher:"Sega", desc:"奥运联动。", tags:["联动"]},
  {ip:"Sonic", title:"Mario & Sonic at the Olympic Games Tokyo 2020", type:"game-spinoff", year:2019, region:"JP", publisher:"Sega", desc:"奥运联动。", tags:["联动"]},
  {ip:"Sonic", title:"Sonic Unleashed: The Soundtrack", type:"ost", year:2008, region:"JP", publisher:"Sega", desc:"原声。", tags:["OST"]},
  {ip:"Sonic", title:"Sonic the Hedgehog 2 (OST)", type:"ost", year:1992, region:"JP", publisher:"Sega", desc:"MD 原声。", tags:["OST"]},
  {ip:"Sonic", title:"Sonic Adventure OST", type:"ost", year:1999, region:"JP", publisher:"Sega", desc:"DC 原声。", tags:["OST"]},
  {ip:"Sonic", title:"Sonic the Hedgehog (OST 2006)", type:"ost", year:2006, region:"JP", publisher:"Sega", desc:"原声。", tags:["OST"]},
  {ip:"Sonic", title:"Sonic Frontiers OST", type:"ost", year:2022, region:"JP", publisher:"Sega", desc:"原声。", tags:["OST"]},
  {ip:"Sonic", title:"Sonic Movie OST", type:"ost", year:2020, region:"US", publisher:"Paramount", desc:"电影原声。", tags:["OST"]},
  {ip:"Sonic", title:"Sonic 30th Anniversary Symphony", type:"concert", year:2021, region:"US", publisher:"Sega", desc:"30 周年音乐会。", tags:["交响乐"]},
  {ip:"Sonic", title:"Sonic: Symphonic Adventure", type:"concert", year:2024, region:"JP", publisher:"Sega", desc:"索尼克交响。", tags:["交响乐"]},
  {ip:"Sonic", title:"Sonic Plush (Sega Goods)", type:"merch-figure", year:1991, region:"JP", publisher:"Sega", desc:"正版毛绒。", tags:["毛绒"]},
  {ip:"Sonic", title:"Sonic x Puma Sneakers", type:"merch-cloth", year:2022, region:"Global", publisher:"Puma", desc:"彪马联名鞋。", tags:["服装"]},
  {ip:"Sonic", title:"Sonic LEGO", type:"merch-toy", year:2021, region:"Global", publisher:"Lego / Sega", desc:"乐高绿丘区套装。", tags:["积木"]},
  {ip:"Sonic", title:"Sonic Funko Pop", type:"merch-figure", year:2020, region:"US", publisher:"Funko", desc:"Funko 公仔。", tags:["Funko"]},
  {ip:"Sonic", title:"Sonic Movie 2 Plush", type:"merch-figure", year:2022, region:"US", publisher:"Build-A-Bear", desc:"电影周边毛绒。", tags:["毛绒"]},
  {ip:"Sonic", title:"Sonic: Dash & Spin (Pinball)", type:"game-board", year:2023, region:"JP", publisher:"Sega", desc:"弹珠台。", tags:["弹珠台"]},
  {ip:"Sonic", title:"Sonic Slot (Pachislot)", type:"pachinko", year:2014, region:"JP", publisher:"Sammy", desc:"柏青斯洛。", tags:["柏青斯洛"]},
  {ip:"Sonic", title:"Sonic Cafe (Tokyo)", type:"cafe", year:2022, region:"JP", publisher:"Sega", desc:"东京索尼克咖啡。", tags:["主题咖啡"]},
  {ip:"Sonic", title:"Sonic 30th Anniversary Exhibition", type:"exhibition", year:2021, region:"JP", publisher:"Sega", desc:"30 周年展。", tags:["展览"]},
  {ip:"Sonic", title:"Sonic Stadium (Live Show)", type:"event", year:2023, region:"JP", publisher:"Sega", desc:"粉丝节。", tags:["线下活动"]},
  {ip:"Sonic", title:"Sonic x McDonalds Happy Meal", type:"collab", year:2022, region:"Global", publisher:"McDonalds", desc:"麦当劳联动。", tags:["餐饮联动"]},
  {ip:"Sonic", title:"Sonic Channel (Web Comic)", type:"web-series", year:2014, region:"JP", publisher:"Sega", desc:"Web 短篇。", tags:["网络漫画"]},
  ];
  window.DATA = window.DATA.concat(EXT);
})();
