// Game IP Derivative Works Database - Extended Set Part 3
(function(){
  const EXT = [
  // ============================================================
  // RESIDENT EVIL (Capcom)
  // ============================================================
  {ip:"Resident Evil", title:"Resident Evil (Film 2002)", type:"film-live", year:2002, region:"US", publisher:"Sony Pictures / Constantin", desc:"米拉·乔沃维奇主演。", tags:["真人电影"]},
  {ip:"Resident Evil", title:"Resident Evil: Apocalypse (Film)", type:"film-live", year:2004, region:"US", publisher:"Sony Pictures", desc:"第二部真人电影。", tags:["真人电影"]},
  {ip:"Resident Evil", title:"Resident Evil: Extinction (Film)", type:"film-live", year:2007, region:"US", publisher:"Sony Pictures", desc:"第三部真人电影。", tags:["真人电影"]},
  {ip:"Resident Evil", title:"Resident Evil: Afterlife (Film)", type:"film-live", year:2010, region:"US", publisher:"Sony Pictures", desc:"第四部真人电影。", tags:["真人电影"]},
  {ip:"Resident Evil", title:"Resident Evil: Retribution (Film)", type:"film-live", year:2012, region:"US", publisher:"Sony Pictures", desc:"第五部真人电影。", tags:["真人电影"]},
  {ip:"Resident Evil", title:"Resident Evil: The Final Chapter (Film)", type:"film-live", year:2016, region:"US", publisher:"Sony Pictures", desc:"第六部真人电影。", tags:["真人电影"]},
  {ip:"Resident Evil", title:"Resident Evil: Welcome to Raccoon City (Film)", type:"film-live", year:2021, region:"US", publisher:"Sony Pictures", desc:"重启真人电影。", tags:["真人电影"]},
  {ip:"Resident Evil", title:"Resident Evil (Netflix Series)", type:"tv", year:2022, region:"US", publisher:"Netflix", desc:"网飞真人剧。", tags:["真人剧"]},
  {ip:"Resident Evil", title:"Resident Evil: Degeneration (CG Film)", type:"film-anime", year:2008, region:"JP", publisher:"Capcom / Sony Pictures", desc:"CG 长片。", tags:["CG 剧场版"]},
  {ip:"Resident Evil", title:"Resident Evil: Damnation (CG Film)", type:"film-anime", year:2012, region:"JP", publisher:"Capcom / Sony Pictures", desc:"CG 续作。", tags:["CG 剧场版"]},
  {ip:"Resident Evil", title:"Resident Evil: Vendetta (CG Film)", type:"film-anime", year:2017, region:"JP", publisher:"Capcom / Marza Animation", desc:"CG 第三作。", tags:["CG 剧场版"]},
  {ip:"Resident Evil", title:"Resident Evil: Death Island (CG Film)", type:"film-anime", year:2023, region:"JP", publisher:"Capcom", desc:"CG 第四作。", tags:["CG 剧场版"]},
  {ip:"Resident Evil", title:"Resident Evil: Infinite Darkness (Anime)", type:"anime", year:2021, region:"JP", publisher:"Netflix / Capcom", desc:"CG 剧集。", tags:["CG 剧集"]},
  {ip:"Resident Evil", title:"Resident Evil 4 (Remake)", type:"game-spinoff", year:2023, region:"JP", publisher:"Capcom", desc:"《4》重制。", tags:["重制"]},
  {ip:"Resident Evil", title:"Resident Evil 2 (Remake)", type:"game-spinoff", year:2019, region:"JP", publisher:"Capcom", desc:"《2》重制。", tags:["重制"]},
  {ip:"Resident Evil", title:"Resident Evil 3 (Remake)", type:"game-spinoff", year:2020, region:"JP", publisher:"Capcom", desc:"《3》重制。", tags:["重制"]},
  {ip:"Resident Evil", title:"Resident Evil Village (8)", type:"game-spinoff", year:2021, region:"JP", publisher:"Capcom", desc:"《8：村庄》。", tags:["生存恐怖"]},
  {ip:"Resident Evil", title:"Resident Evil: Revelations", type:"game-spinoff", year:2012, region:"JP", publisher:"Capcom", desc:"3DS 外传。", tags:["生存恐怖"]},
  {ip:"Resident Evil", title:"Resident Evil: Revelations 2", type:"game-spinoff", year:2015, region:"JP", publisher:"Capcom", desc:"外传续作。", tags:["生存恐怖"]},
  {ip:"Resident Evil", title:"Resident Evil Outbreak", type:"game-spinoff", year:2003, region:"JP", publisher:"Capcom", desc:"PS2 联机。", tags:["生存恐怖"]},
  {ip:"Resident Evil", title:"Resident Evil Outbreak File #2", type:"game-spinoff", year:2004, region:"JP", publisher:"Capcom", desc:"联机续作。", tags:["生存恐怖"]},
  {ip:"Resident Evil", title:"Resident Evil: The Umbrella Chronicles", type:"game-spinoff", year:2007, region:"JP", publisher:"Capcom", desc:"Wii 光枪。", tags:["光枪"]},
  {ip:"Resident Evil", title:"Resident Evil: The Darkside Chronicles", type:"game-spinoff", year:2009, region:"JP", publisher:"Capcom", desc:"Wii 光枪。", tags:["光枪"]},
  {ip:"Resident Evil", title:"Resident Evil Survivor", type:"game-spinoff", year:2000, region:"JP", publisher:"Capcom", desc:"PS1 光枪。", tags:["光枪"]},
  {ip:"Resident Evil", title:"Resident Evil: Dead Aim", type:"game-spinoff", year:2003, region:"JP", publisher:"Capcom", desc:"PS2 光枪。", tags:["光枪"]},
  {ip:"Resident Evil", title:"Resident Evil Gaiden", type:"game-spinoff", year:2001, region:"JP", publisher:"Capcom", desc:"GBC 外传。", tags:["外传"]},
  {ip:"Resident Evil", title:"Resident Evil Operation: Raccoon City", type:"game-spinoff", year:2012, region:"US", publisher:"Slant Six / Capcom", desc:"TPS 衍生。", tags:["TPS"]},
  {ip:"Resident Evil", title:"Resident Evil: Umbrella Corps", type:"game-spinoff", year:2016, region:"JP", publisher:"Capcom", desc:"对抗 TPS。", tags:["TPS"]},
  {ip:"Resident Evil", title:"Resident Evil Re:Verse", type:"game-spinoff", year:2022, region:"JP", publisher:"Capcom", desc:"多人对抗。", tags:["对抗"]},
  {ip:"Resident Evil", title:"Resident Evil Resistance", type:"game-spinoff", year:2020, region:"JP", publisher:"Capcom", desc:"非对称对抗。", tags:["对抗"]},
  {ip:"Resident Evil", title:"Resident Evil: The Mercenaries 3D", type:"game-spinoff", year:2011, region:"JP", publisher:"Capcom", desc:"3DS 迷你游戏。", tags:["动作"]},
  {ip:"Resident Evil", title:"Resident Evil (Mobile)", type:"game-mobile", year:2017, region:"Global", publisher:"Capcom / Longzhen", desc:"手游动作。", tags:["手游"]},
  {ip:"Resident Evil", title:"Resident Evil Survival Unit (Mobile)", type:"game-mobile", year:2024, region:"Global", publisher:"Capcom / Aniplex", desc:"手游。", tags:["手游"]},
  {ip:"Resident Evil", title:"Resident Evil (GBC Remake)", type:"game-spinoff", year:2001, region:"JP", publisher:"Capcom", desc:"GBC 重制。", tags:["重制"]},
  {ip:"Resident Evil", title:"Resident Evil Code: Veronica X", type:"game-spinoff", year:2001, region:"JP", publisher:"Capcom", desc:"PS2/Dreamcast 重制。", tags:["重制"]},
  {ip:"Resident Evil", title:"Resident Evil Zero", type:"game-spinoff", year:2002, region:"JP", publisher:"Capcom", desc:"NDS 前传。", tags:["生存恐怖"]},
  {ip:"Resident Evil", title:"Resident Evil 5", type:"game-spinoff", year:2009, region:"JP", publisher:"Capcom", desc:"TPS 续作。", tags:["TPS"]},
  {ip:"Resident Evil", title:"Resident Evil 6", type:"game-spinoff", year:2012, region:"JP", publisher:"Capcom", desc:"TPS 续作。", tags:["TPS"]},
  {ip:"Resident Evil", title:"Resident Evil 7: Biohazard", type:"game-spinoff", year:2017, region:"JP", publisher:"Capcom", desc:"第一人称回归。", tags:["生存恐怖"]},
  {ip:"Resident Evil", title:"Resident Evil 4 (2005 Original)", type:"game-spinoff", year:2005, region:"JP", publisher:"Capcom", desc:"原版。", tags:["生存恐怖"]},
  {ip:"Resident Evil", title:"Resident Evil (Manga)", type:"manga", year:1998, region:"JP", publisher:"Akita Shoten", desc:"漫画版。", tags:["少年漫画"]},
  {ip:"Resident Evil", title:"Resident Evil: Marhawa Desire (Manga)", type:"manga", year:2007, region:"JP", publisher:"Capcom / Mag Garden", desc:"《5》前传漫画。", tags:["少年漫画"]},
  {ip:"Resident Evil", title:"Resident Evil: Heavenly Island (Manga)", type:"manga", year:2011, region:"JP", publisher:"Capcom", desc:"《6》前传漫画。", tags:["少年漫画"]},
  {ip:"Resident Evil", title:"Resident Evil (S.D. Perry Novels)", type:"novel", year:1998, region:"US", publisher:"Simon & Schuster", desc:"英美小说系列。", tags:["小说"]},
  {ip:"Resident Evil", title:"Resident Evil: Caliban Cove (Novel)", type:"novel", year:2001, region:"US", publisher:"S.D. Perry", desc:"小说。", tags:["小说"]},
  {ip:"Resident Evil", title:"Resident Evil: City of the Dead (Novel)", type:"novel", year:2003, region:"US", publisher:"S.D. Perry", desc:"小说。", tags:["小说"]},
  {ip:"Resident Evil", title:"Resident Evil: Umbrella Conspiracy (Novel)", type:"novel", year:1998, region:"US", publisher:"S.D. Perry", desc:"小说。", tags:["小说"]},
  {ip:"Resident Evil", title:"Resident Evil (Stage Play 2024)", type:"theater", year:2024, region:"JP", publisher:"Capcom", desc:"日本 2.5 次元舞台剧。", tags:["舞台剧"]},
  {ip:"Resident Evil", title:"Resident Evil OST Collections", type:"ost", year:2017, region:"JP", publisher:"Capcom", desc:"系列原声集。", tags:["OST"]},
  {ip:"Resident Evil", title:"Resident Evil 4 OST (2005)", type:"ost", year:2005, region:"JP", publisher:"Capcom", desc:"《4》原声。", tags:["OST"]},
  {ip:"Resident Evil", title:"Resident Evil Village OST", type:"ost", year:2021, region:"JP", publisher:"Capcom", desc:"《8》原声。", tags:["OST"]},
  {ip:"Resident Evil", title:"Resident Evil Plush (Licker Series)", type:"merch-figure", year:2019, region:"JP", publisher:"Capcom", desc:"舔食者毛绒。", tags:["毛绒"]},
  {ip:"Resident Evil", title:"Resident Evil Nendoroid", type:"merch-figure", year:2018, region:"JP", publisher:"Good Smile", desc:"粘土人。", tags:["粘土人"]},
  {ip:"Resident Evil", title:"Resident Evil x PUBG Mobile", type:"collab", year:2020, region:"Global", publisher:"Krafton", desc:"PUBG 联动。", tags:["跨界"]},
  {ip:"Resident Evil", title:"Resident Evil Pachislot", type:"pachinko", year:2015, region:"JP", publisher:"Sammy", desc:"柏青斯洛。", tags:["柏青斯洛"]},
  {ip:"Resident Evil", title:"Resident Evil 2 Pachinko", type:"pachinko", year:2019, region:"JP", publisher:"Sammy", desc:"柏青哥。", tags:["柏青哥"]},
  {ip:"Resident Evil", title:"Resident Evil: Welcome to Raccoon City (Novelization)", type:"novel", year:2021, region:"US", publisher:"Titan Books", desc:"电影小说。", tags:["小说"]},
  {ip:"Resident Evil", title:"Resident Evil (Biohazard) Stage Play", type:"theater", year:2021, region:"JP", publisher:"Capcom", desc:"2.5 次元舞台剧。", tags:["舞台剧"]},
  {ip:"Resident Evil", title:"Resident Evil Funko Pop", type:"merch-figure", year:2020, region:"US", publisher:"Funko", desc:"Funko 公仔。", tags:["Funko"]},
  {ip:"Resident Evil", title:"Resident Evil Village x Resident Evil 4 Remake (Bundle)", type:"merch-cloth", year:2023, region:"JP", publisher:"Capcom", desc:"PS5 套装。", tags:["硬件"]},

  // ============================================================
  // MONSTER HUNTER
  // ============================================================
  {ip:"Monster Hunter", title:"Monster Hunter (Film 2020)", type:"film-live", year:2020, region:"US", publisher:"Sony / Constantin", desc:"米拉·乔沃维奇主演真人电影。", tags:["真人电影"]},
  {ip:"Monster Hunter", title:"Monster Hunter 4 Ultimate (Web Anime)", type:"web-series", year:2014, region:"JP", publisher:"Capcom", desc:"《4G》官方短动画。", tags:["短动画"]},
  {ip:"Monster Hunter", title:"Monster Hunter: Diary of a Fleet Lady (Manga)", type:"manga", year:2010, region:"JP", publisher:"Enterbrain", desc:"《P3》衍生漫画。", tags:["少年漫画"]},
  {ip:"Monster Hunter", title:"Monster Hunter Orage (Manga)", type:"manga", year:2008, region:"JP", publisher:"Mag Garden", desc:"《MH2》衍生漫画。", tags:["少年漫画"]},
  {ip:"Monster Hunter", title:"Monster Hunter: Hunter's Encyclopedia", type:"artbook", year:2010, region:"JP", publisher:"Capcom", desc:"百科设定集。", tags:["百科"]},
  {ip:"Monster Hunter", title:"Monster Hunter Illustrations (1-3)", type:"artbook", year:2012, region:"JP", publisher:"Capcom", desc:"全系列插画。", tags:["画集"]},
  {ip:"Monster Hunter", title:"Monster Hunter Stories (Anime)", type:"anime", year:2016, region:"JP", publisher:"David Production", desc:"《Stories》动画。", tags:["动画"]},
  {ip:"Monster Hunter", title:"Monster Hunter Stories Ride On (Anime)", type:"anime", year:2016, region:"JP", publisher:"David Production", desc:"动画第二季。", tags:["动画"]},
  {ip:"Monster Hunter", title:"Monster Hunter Stories: Ride On (TV Series 2016)", type:"anime", year:2016, region:"JP", publisher:"David Production", desc:"长篇动画。", tags:["长篇动画"]},
  {ip:"Monster Hunter", title:"Monster Hunter Rise (Game)", type:"game-spinoff", year:2021, region:"JP", publisher:"Capcom", desc:"Switch 续作。", tags:["ARPG"]},
  {ip:"Monster Hunter", title:"Monster Hunter World: Iceborne", type:"game-spinoff", year:2019, region:"JP", publisher:"Capcom", desc:"大型 DLC。", tags:["DLC"]},
  {ip:"Monster Hunter", title:"Monster Hunter Rise: Sunbreak", type:"game-spinoff", year:2022, region:"JP", publisher:"Capcom", desc:"大型 DLC。", tags:["DLC"]},
  {ip:"Monster Hunter", title:"Monster Hunter Frontier (Online)", type:"game-spinoff", year:2007, region:"JP", publisher:"Capcom", desc:"MMO 系列。", tags:["MMO"]},
  {ip:"Monster Hunter", title:"Monster Hunter Freedom", type:"game-spinoff", year:2005, region:"JP", publisher:"Capcom", desc:"PSP 续作。", tags:["ARPG"]},
  {ip:"Monster Hunter", title:"Monster Hunter Freedom Unite", type:"game-spinoff", year:2008, region:"JP", publisher:"Capcom", desc:"PSP 续作。", tags:["ARPG"]},
  {ip:"Monster Hunter", title:"Monster Hunter Generations", type:"game-spinoff", year:2015, region:"JP", publisher:"Capcom", desc:"3DS 续作。", tags:["ARPG"]},
  {ip:"Monster Hunter", title:"Monster Hunter Generations Ultimate", type:"game-spinoff", year:2017, region:"JP", publisher:"Capcom", desc:"3DS 增强版。", tags:["ARPG"]},
  {ip:"Monster Hunter", title:"Monster Hunter Stories", type:"game-spinoff", year:2016, region:"JP", publisher:"Capcom", desc:"3DS RPG。", tags:["RPG"]},
  {ip:"Monster Hunter", title:"Monster Hunter Stories 2", type:"game-spinoff", year:2021, region:"JP", publisher:"Capcom", desc:"RPG 续作。", tags:["RPG"]},
  {ip:"Monster Hunter", title:"Monster Hunter Explore", type:"game-mobile", year:2015, region:"JP", publisher:"Capcom", desc:"手游。", tags:["手游"]},
  {ip:"Monster Hunter", title:"Monster Hunter Riders", type:"game-mobile", year:2020, region:"JP", publisher:"Capcom", desc:"手游。", tags:["手游"]},
  {ip:"Monster Hunter", title:"Monster Hunter Now", type:"game-mobile", year:2023, region:"Global", publisher:"Capcom / Niantic", desc:"AR 手游。", tags:["AR"]},
  {ip:"Monster Hunter", title:"Monster Hunter Mezeporta Kaitaku", type:"game-mobile", year:2016, region:"JP", publisher:"Capcom", desc:"经营手游。", tags:["手游"]},
  {ip:"Monster Hunter", title:"Monster Hunter: Dynamic Hunting", type:"game-mobile", year:2011, region:"JP", publisher:"Capcom", desc:"街机改编手游。", tags:["手游"]},
  {ip:"Monster Hunter", title:"Monster Hunter Pachislot", type:"pachinko", year:2016, region:"JP", publisher:"Sammy", desc:"柏青斯洛。", tags:["柏青斯洛"]},
  {ip:"Monster Hunter", title:"Monster Hunter Pachinko", type:"pachinko", year:2018, region:"JP", publisher:"Sammy", desc:"柏青哥。", tags:["柏青哥"]},
  {ip:"Monster Hunter", title:"Monster Hunter x Uniqlo UT", type:"merch-cloth", year:2018, region:"Global", publisher:"Uniqlo / Capcom", desc:"UT 联名。", tags:["服装"]},
  {ip:"Monster Hunter", title:"Monster Hunter x JINS Glasses", type:"merch-cloth", year:2019, region:"JP", publisher:"JINS", desc:"眼镜联名。", tags:["眼镜"]},
  {ip:"Monster Hunter", title:"Monster Hunter Plush (Capcom Store)", type:"merch-figure", year:2010, region:"JP", publisher:"Capcom", desc:"怪物毛绒。", tags:["毛绒"]},
  {ip:"Monster Hunter", title:"Monster Hunter Figure Builder (Capcom)", type:"merch-figure", year:2014, region:"JP", publisher:"Capcom", desc:"可动人偶。", tags:["可动"]},
  {ip:"Monster Hunter", title:"Monster Hunter World OST", type:"ost", year:2018, region:"JP", publisher:"Capcom", desc:"原声。", tags:["OST"]},
  {ip:"Monster Hunter", title:"Monster Hunter: World Live Concert", type:"concert", year:2018, region:"JP", publisher:"Capcom", desc:"东京音乐会。", tags:["音乐会"]},
  {ip:"Monster Hunter", title:"Monster Hunter Festa", type:"event", year:2014, region:"JP", publisher:"Capcom", desc:"官方粉丝节。", tags:["粉丝节"]},
  {ip:"Monster Hunter", title:"Monster Hunter Book (Mizuno Kaito)", type:"novel", year:2017, region:"JP", publisher:"Capcom", desc:"官方小说。", tags:["小说"]},
  {ip:"Monster Hunter", title:"Monster Hunter: Mezeporta Stories (Novel)", type:"novel", year:2017, region:"JP", publisher:"Capcom", desc:"周边小说。", tags:["小说"]},
  {ip:"Monster Hunter", title:"Monster Hunter: Legends of the Guild (Netflix)", type:"film-anime", year:2021, region:"US", publisher:"Capcom / Netflix", desc:"网飞 CG 动画。", tags:["CG 电影"]},

  // ============================================================
  // DEVIL MAY CRY
  // ============================================================
  {ip:"Devil May Cry", title:"Devil May Cry (Anime 2007)", type:"anime", year:2007, region:"JP", publisher:"Madhouse", desc:"12 集动画。", tags:["动画"]},
  {ip:"Devil May Cry", title:"Devil May Cry (Manga)", type:"manga", year:2005, region:"JP", publisher:"Kadokawa", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Devil May Cry", title:"Devil May Cry 3 (Manga)", type:"manga", year:2005, region:"JP", publisher:"Kadokawa", desc:"《3》漫画。", tags:["少年漫画"]},
  {ip:"Devil May Cry", title:"Devil May Cry 5 (Game)", type:"game-spinoff", year:2019, region:"JP", publisher:"Capcom", desc:"系列续作。", tags:["ACT"]},
  {ip:"Devil May Cry", title:"DmC: Devil May Cry", type:"game-spinoff", year:2013, region:"UK", publisher:"Ninja Theory / Capcom", desc:"外包重启作。", tags:["ACT"]},
  {ip:"Devil May Cry", title:"Devil May Cry HD Collection", type:"game-spinoff", year:2018, region:"JP", publisher:"Capcom", desc:"高清合集。", tags:["合集"]},
  {ip:"Devil May Cry", title:"Devil May Cry 4: Special Edition", type:"game-spinoff", year:2015, region:"JP", publisher:"Capcom", desc:"特别版。", tags:["ACT"]},
  {ip:"Devil May Cry", title:"Devil May Cry: Peak of Combat (Mobile)", type:"game-mobile", year:2024, region:"CN", publisher:"Capcom / Tencent", desc:"国服手游。", tags:["手游"]},
  {ip:"Devil May Cry", title:"Devil May Cry: Vergil's Story (Novel)", type:"novel", year:2018, region:"JP", publisher:"Capcom", desc:"维吉尔前传。", tags:["小说"]},
  {ip:"Devil May Cry", title:"Devil May Cry (Novel)", type:"novel", year:2006, region:"JP", publisher:"Kadokawa", desc:"小说。", tags:["小说"]},
  {ip:"Devil May Cry", title:"Devil May Cry OST (Various)", type:"ost", year:2005, region:"JP", publisher:"Capcom", desc:"原声带合集。", tags:["OST"]},
  {ip:"Devil May Cry", title:"Devil May Cry 5 OST", type:"ost", year:2019, region:"JP", publisher:"Capcom", desc:"《5》原声。", tags:["OST"]},
  {ip:"Devil May Cry", title:"Devil May Cry Nendoroid (Dante)", type:"merch-figure", year:2019, region:"JP", publisher:"Good Smile", desc:"粘土人。", tags:["粘土人"]},
  {ip:"Devil May Cry", title:"Devil May Cry Live-Action Stage Play", type:"theater", year:2019, region:"JP", publisher:"Capcom", desc:"舞台剧。", tags:["舞台剧"]},
  {ip:"Devil May Cry", title:"Devil May Cry Plush (Rebellion)", type:"merch-figure", year:2010, region:"JP", publisher:"Capcom", desc:"但丁毛绒。", tags:["毛绒"]},
  {ip:"Devil May Cry", title:"Devil May Cry (Manga: Vergil)", type:"manga", year:2020, region:"JP", publisher:"Capcom", desc:"维吉尔漫画。", tags:["少年漫画"]},
  {ip:"Devil May Cry", title:"Devil May Cry: Bloody Palace (Mobile)", type:"game-mobile", year:2019, region:"JP", publisher:"Capcom", desc:"塔防手游。", tags:["手游"]},
  {ip:"Devil May Cry", title:"Devil May Cry: Prequel Novel", type:"novel", year:2019, region:"JP", publisher:"Capcom", desc:"《5》前传小说。", tags:["小说"]},
  {ip:"Devil May Cry", title:"Devil May Cry (Trading Card Game)", type:"merch-card", year:2006, region:"JP", publisher:"Capcom", desc:"集换卡牌。", tags:["TCG"]},

  // ============================================================
  // METAL GEAR (Konami)
  // ============================================================
  {ip:"Metal Gear", title:"Metal Gear Solid: The Twin Snakes", type:"game-spinoff", year:2004, region:"JP", publisher:"Konami / Silicon Knights", desc:"NGC 重制。", tags:["重制"]},
  {ip:"Metal Gear", title:"Metal Gear Solid 2: Sons of Liberty", type:"game-spinoff", year:2001, region:"JP", publisher:"Konami", desc:"续作。", tags:["潜行"]},
  {ip:"Metal Gear", title:"Metal Gear Solid 3: Snake Eater", type:"game-spinoff", year:2004, region:"JP", publisher:"Konami", desc:"前传。", tags:["潜行"]},
  {ip:"Metal Gear", title:"Metal Gear Solid 4: Guns of the Patriots", type:"game-spinoff", year:2008, region:"JP", publisher:"Konami", desc:"PS3 续作。", tags:["潜行"]},
  {ip:"Metal Gear", title:"Metal Gear Solid V: The Phantom Pain", type:"game-spinoff", year:2015, region:"JP", publisher:"Konami", desc:"系列终章。", tags:["潜行"]},
  {ip:"Metal Gear", title:"Metal Gear Solid V: Ground Zeroes", type:"game-spinoff", year:2014, region:"JP", publisher:"Konami", desc:"序章。", tags:["潜行"]},
  {ip:"Metal Gear", title:"Metal Gear Rising: Revengeance", type:"game-spinoff", year:2013, region:"JP", publisher:"Konami / PlatinumGames", desc:"动作衍生。", tags:["ACT"]},
  {ip:"Metal Gear", title:"Metal Gear Solid: Peace Walker", type:"game-spinoff", year:2010, region:"JP", publisher:"Konami", desc:"PSP 续作。", tags:["潜行"]},
  {ip:"Metal Gear", title:"Metal Gear Solid: Portable Ops", type:"game-spinoff", year:2006, region:"JP", publisher:"Konami", desc:"PSP 续作。", tags:["潜行"]},
  {ip:"Metal Gear", title:"Metal Gear Survive", type:"game-spinoff", year:2018, region:"JP", publisher:"Konami", desc:"生存外传。", tags:["生存"]},
  {ip:"Metal Gear", title:"Metal Gear Solid (Manga)", type:"manga", year:2001, region:"JP", publisher:"Shogakukan", desc:"《Solid》漫画。", tags:["少年漫画"]},
  {ip:"Metal Gear", title:"Metal Gear Solid: Sons of Liberty (Manga)", type:"manga", year:2003, region:"JP", publisher:"Shogakukan", desc:"《2》漫画。", tags:["少年漫画"]},
  {ip:"Metal Gear", title:"Metal Gear Solid: The Guns of Patriots (Novel)", type:"novel", year:2008, region:"JP", publisher:"Kadokawa", desc:"小说。", tags:["小说"]},
  {ip:"Metal Gear", title:"Metal Gear Solid (Film - Darren Aronofsky 2009)", type:"film-live", year:2009, region:"US", publisher:"Sony / Columbia", desc:"原型真人电影企划。", tags:["真人电影"]},
  {ip:"Metal Gear", title:"Metal Gear Solid: Master Collection Vol. 1", type:"game-spinoff", year:2023, region:"JP", publisher:"Konami", desc:"合集。", tags:["合集"]},
  {ip:"Metal Gear", title:"Metal Gear Solid Δ: Snake Eater (Remake)", type:"game-spinoff", year:2025, region:"JP", publisher:"Konami", desc:"《3》重制。", tags:["重制"]},
  {ip:"Metal Gear", title:"Metal Gear Solid OST (1-3)", type:"ost", year:2004, region:"JP", publisher:"Konami", desc:"原声合集。", tags:["OST"]},
  {ip:"Metal Gear", title:"Metal Gear Solid 4 OST", type:"ost", year:2008, region:"JP", publisher:"Konami", desc:"原声。", tags:["OST"]},
  {ip:"Metal Gear", title:"Metal Gear Solid (Radio Drama)", type:"audio", year:2001, region:"JP", publisher:"Konami", desc:"广播剧。", tags:["广播剧"]},
  {ip:"Metal Gear", title:"Metal Gear Solid: The Legacy Collection", type:"game-spinoff", year:2013, region:"JP", publisher:"Konami", desc:"25 周年合集。", tags:["合集"]},
  {ip:"Metal Gear", title:"Metal Gear Solid (Trading Cards)", type:"merch-card", year:2001, region:"JP", publisher:"Konami", desc:"TCG 卡牌。", tags:["TCG"]},
  {ip:"Metal Gear", title:"Metal Gear Solid Snake Plush", type:"merch-figure", year:2004, region:"JP", publisher:"Konami", desc:"Snake 毛绒。", tags:["毛绒"]},

  // ============================================================
  // CASTLEVANIA (Konami)
  // ============================================================
  {ip:"Castlevania", title:"Castlevania (NES 1986)", type:"game-spinoff", year:1986, region:"JP", publisher:"Konami", desc:"原版。", tags:["ACT"]},
  {ip:"Castlevania", title:"Castlevania (TV Series 2017-2021)", type:"anime", year:2017, region:"US", publisher:"Netflix / Frederator", desc:"网飞 4 季动画。", tags:["动画"]},
  {ip:"Castlevania: Nocturne (TV Series)", type:"anime", year:2023, region:"US", publisher:"Netflix / Powerhouse Animation", desc:"网飞续作。", tags:["动画"]},
  {ip:"Castlevania", title:"Castlevania (Film 2009 Rumored)", type:"film-live", year:2009, region:"US", publisher:"Konami", desc:"真人电影企划。", tags:["真人电影"]},
  {ip:"Castlevania", title:"Castlevania: Lament of Innocence", type:"game-spinoff", year:2003, region:"JP", publisher:"Konami", desc:"PS2 续作。", tags:["ACT"]},
  {ip:"Castlevania", title:"Castlevania: Curse of Darkness", type:"game-spinoff", year:2005, region:"JP", publisher:"Konami", desc:"PS2 续作。", tags:["ACT"]},
  {ip:"Castlevania", title:"Castlevania: Lords of Shadow", type:"game-spinoff", year:2010, region:"EU", publisher:"MercurySteam / Konami", desc:"外包重启。", tags:["ACT"]},
  {ip:"Castlevania", title:"Castlevania: Lords of Shadow 2", type:"game-spinoff", year:2014, region:"EU", publisher:"MercurySteam", desc:"续作。", tags:["ACT"]},
  {ip:"Castlevania", title:"Castlevania: Lords of Shadow - Mirror of Fate", type:"game-spinoff", year:2013, region:"EU", publisher:"MercurySteam", desc:"3DS 中间作。", tags:["ACT"]},
  {ip:"Castlevania", title:"Castlevania: Aria of Sorrow", type:"game-spinoff", year:2003, region:"JP", publisher:"Konami", desc:"GBA 续作。", tags:["Metroidvania"]},
  {ip:"Castlevania", title:"Castlevania: Dawn of Sorrow", type:"game-spinoff", year:2005, region:"JP", publisher:"Konami", desc:"NDS 续作。", tags:["Metroidvania"]},
  {ip:"Castlevania", title:"Castlevania: Portrait of Ruin", type:"game-spinoff", year:2006, region:"JP", publisher:"Konami", desc:"NDS 续作。", tags:["Metroidvania"]},
  {ip:"Castlevania", title:"Castlevania: Order of Ecclesia", type:"game-spinoff", year:2008, region:"JP", publisher:"Konami", desc:"NDS 续作。", tags:["Metroidvania"]},
  {ip:"Castlevania", title:"Castlevania: Circle of the Moon", type:"game-spinoff", year:2001, region:"JP", publisher:"Konami", desc:"GBA 续作。", tags:["Metroidvania"]},
  {ip:"Castlevania", title:"Castlevania: Harmony of Dissonance", type:"game-spinoff", year:2002, region:"JP", publisher:"Konami", desc:"GBA 续作。", tags:["Metroidvania"]},
  {ip:"Castlevania", title:"Castlevania: The Dracula X Chronicles", type:"game-spinoff", year:2007, region:"JP", publisher:"Konami", desc:"PSP 复刻。", tags:["重制"]},
  {ip:"Castlevania", title:"Super Castlevania IV", type:"game-spinoff", year:1991, region:"JP", publisher:"Konami", desc:"SFC 续作。", tags:["ACT"]},
  {ip:"Castlevania", title:"Castlevania: Symphony of the Night", type:"game-spinoff", year:1997, region:"JP", publisher:"Konami", desc:"PS1 经典。", tags:["Metroidvania"]},
  {ip:"Castlevania", title:"Castlevania: Rondo of Blood", type:"game-spinoff", year:1993, region:"JP", publisher:"Konami", desc:"PCE CD 续作。", tags:["ACT"]},
  {ip:"Castlevania", title:"Castlevania: Bloodlines", type:"game-spinoff", year:1994, region:"JP", publisher:"Konami", desc:"MD 续作。", tags:["ACT"]},
  {ip:"Castlevania", title:"Castlevania (Manga)", type:"manga", year:2005, region:"JP", publisher:"Kadokawa", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Castlevania", title:"Castlevania: Nocturne (Manga)", type:"manga", year:2024, region:"JP", publisher:"Kadokawa", desc:"《Nocturne》漫画。", tags:["少年漫画"]},
  {ip:"Castlevania", title:"Castlevania: Nocturne OST", type:"ost", year:2023, region:"US", publisher:"Netflix", desc:"动画原声。", tags:["OST"]},
  {ip:"Castlevania", title:"Castlevania (Symphony of the Night OST)", type:"ost", year:1997, region:"JP", publisher:"Konami", desc:"原声。", tags:["OST"]},
  {ip:"Castlevania", title:"Castlevania: Lords of Shadow OST", type:"ost", year:2010, region:"EU", publisher:"Konami", desc:"原声。", tags:["OST"]},
  {ip:"Castlevania", title:"Castlevania Pachislot", type:"pachinko", year:2003, region:"JP", publisher:"Konami", desc:"柏青斯洛。", tags:["柏青斯洛"]},
  {ip:"Castlevania", title:"Castlevania Pachinko", type:"pachinko", year:2015, region:"JP", publisher:"Konami", desc:"柏青哥。", tags:["柏青哥"]},
  {ip:"Castlevania", title:"Castlevania (Grimoire of Souls - Apple Arcade)", type:"game-mobile", year:2021, region:"Global", publisher:"Konami", desc:"苹果街机独佔。", tags:["手游"]},
  {ip:"Castlevania", title:"Castlevania: Belmont's Curse (Castlevania: Nocturne)", type:"web-series", year:2023, region:"US", publisher:"Netflix", desc:"动画续作。", tags:["动画"]},
  ];
  window.DATA = window.DATA.concat(EXT);
})();
