// Game IP Derivative Works Database - Extended Set Part 4
(function(){
  const EXT = [
  // ============================================================
  // STREET FIGHTER
  // ============================================================
  {ip:"Street Fighter", title:"Street Fighter II: The Animated Movie", type:"film-anime", year:1994, region:"JP", publisher:"Group TAC", desc:"95 分钟剧场版。", tags:["剧场版"]},
  {ip:"Street Fighter", title:"Street Fighter II V (Anime)", type:"anime", year:1995, region:"JP", publisher:"Group TAC", desc:"34 集动画。", tags:["动画"]},
  {ip:"Street Fighter", title:"Street Fighter (Live-Action 1994)", type:"film-live", year:1994, region:"US", publisher:"Universal", desc:"尚格云顿主演真人电影。", tags:["真人电影"]},
  {ip:"Street Fighter", title:"Street Fighter: Legacy (Fan Film)", type:"web-series", year:2010, region:"US", publisher:"Fighting Dreamers", desc:"同人短剧。", tags:["短剧"]},
  {ip:"Street Fighter", title:"Street Fighter (U.S. Animated Series 1995)", type:"tv", year:1995, region:"US", publisher:"Ingram", desc:"美式动画。", tags:["美式动画"]},
  {ip:"Street Fighter", title:"Street Fighter Alpha: The Animation (OVA)", type:"anime", year:2000, region:"JP", publisher:"Toei", desc:"OVA。", tags:["OVA"]},
  {ip:"Street Fighter", title:"Street Fighter Alpha: Generations", type:"anime", year:2005, region:"JP", publisher:"Toei", desc:"CG OVA。", tags:["CG OVA"]},
  {ip:"Street Fighter", title:"Street Fighter IV: The Ties That Bind (Anime)", type:"anime", year:2009, region:"JP", publisher:"Toei", desc:"《IV》动画。", tags:["动画"]},
  {ip:"Street Fighter", title:"Street Fighter (Webseries by Crazy Maple Studio)", type:"web-series", year:2024, region:"US", publisher:"Capcom", desc:"官方短剧。", tags:["短剧"]},
  {ip:"Street Fighter", title:"Street Fighter (Manga)", type:"manga", year:1989, region:"JP", publisher:"Shueisha", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Street Fighter", title:"Street Fighter III: Ryu Final (Manga)", type:"manga", year:1997, region:"JP", publisher:"Shueisha", desc:"《III》漫画。", tags:["少年漫画"]},
  {ip:"Street Fighter", title:"Street Fighter (UDON Comics)", type:"manga", year:2003, region:"US", publisher:"UDON", desc:"美式漫画。", tags:["美式漫画"]},
  {ip:"Street Fighter", title:"Street Fighter IV (Novel)", type:"novel", year:2009, region:"JP", publisher:"Capcom", desc:"小说。", tags:["小说"]},
  {ip:"Street Fighter", title:"Street Fighter: Sakura Ganbaru! (Game)", type:"game-spinoff", year:1996, region:"JP", publisher:"Capcom", desc:"GB 衍生。", tags:["FTG"]},
  {ip:"Street Fighter", title:"Street Fighter: The Movie (Game)", type:"game-spinoff", year:1995, region:"US", publisher:"Incredible Technologies / Capcom", desc:"街机游戏。", tags:["FTG"]},
  {ip:"Street Fighter", title:"Street Fighter EX (Game)", type:"game-spinoff", year:1996, region:"JP", publisher:"Arika / Capcom", desc:"3D 衍生。", tags:["FTG"]},
  {ip:"Street Fighter", title:"Street Fighter EX2 / EX3", type:"game-spinoff", year:1998, region:"JP", publisher:"Arika / Capcom", desc:"3D 续作。", tags:["FTG"]},
  {ip:"Street Fighter", title:"Street Fighter V", type:"game-spinoff", year:2016, region:"JP", publisher:"Capcom", desc:"现代续作。", tags:["FTG"]},
  {ip:"Street Fighter", title:"Street Fighter 6", type:"game-spinoff", year:2023, region:"JP", publisher:"Capcom", desc:"《6》。", tags:["FTG"]},
  {ip:"Street Fighter", title:"Street Fighter IV (Game)", type:"game-spinoff", year:2008, region:"JP", publisher:"Capcom", desc:"2.5D 续作。", tags:["FTG"]},
  {ip:"Street Fighter", title:"Street Fighter 30th Anniversary Collection", type:"game-spinoff", year:2018, region:"JP", publisher:"Capcom", desc:"30 周年合集。", tags:["合集"]},
  {ip:"Street Fighter", title:"Street Fighter V: Champion Edition", type:"game-spinoff", year:2020, region:"JP", publisher:"Capcom", desc:"增强版。", tags:["FTG"]},
  {ip:"Street Fighter", title:"Street Fighter: Duel (Mobile)", type:"game-mobile", year:2023, region:"CN", publisher:"Capcom / Tencent", desc:"国服手游。", tags:["手游"]},
  {ip:"Street Fighter", title:"Street Fighter (Capcom Belt Action)", type:"game-board", year:1987, region:"JP", publisher:"Capcom", desc:"腰机。", tags:["腰机"]},
  {ip:"Street Fighter", title:"Street Fighter Pinball", type:"game-board", year:1985, region:"US", publisher:"Gottlieb", desc:"弹珠台。", tags:["弹珠台"]},
  {ip:"Street Fighter", title:"Street Fighter Plush (Bandai)", type:"merch-figure", year:1991, region:"JP", publisher:"Bandai", desc:"春丽 / 隆毛绒。", tags:["毛绒"]},
  {ip:"Street Fighter", title:"Street Fighter x Sanrio", type:"collab", year:2018, region:"JP", publisher:"Sanrio / Capcom", desc:"三丽鸥联名。", tags:["联名"]},
  {ip:"Street Fighter", title:"Street Fighter x Uniqlo UT", type:"merch-cloth", year:2019, region:"Global", publisher:"Uniqlo / Capcom", desc:"UT 联名。", tags:["服装"]},
  {ip:"Street Fighter", title:"Street Fighter Funko Pop", type:"merch-figure", year:2020, region:"US", publisher:"Funko", desc:"Funko 公仔。", tags:["Funko"]},
  {ip:"Street Fighter", title:"Street Fighter OST Collection", type:"ost", year:2018, region:"JP", publisher:"Capcom", desc:"原声集。", tags:["OST"]},
  {ip:"Street Fighter", title:"Street Fighter II OST (CPS-1)", type:"ost", year:1991, region:"JP", publisher:"Capcom", desc:"原声。", tags:["OST"]},
  {ip:"Street Fighter", title:"Street Fighter x G-Shock", type:"merch-cloth", year:2023, region:"JP", publisher:"Casio", desc:"G-Shock 联名。", tags:["手表"]},
  {ip:"Street Fighter", title:"Street Fighter Pachislot", type:"pachinko", year:2010, region:"JP", publisher:"Sammy", desc:"柏青斯洛。", tags:["柏青斯洛"]},
  {ip:"Street Fighter", title:"Street Fighter (Trading Cards)", type:"merch-card", year:1993, region:"JP", publisher:"Capcom", desc:"卡牌。", tags:["TCG"]},
  {ip:"Street Fighter", title:"Street Fighter (Novel - Yoshiki Okamoto)", type:"novel", year:2018, region:"JP", publisher:"Capcom", desc:"小说。", tags:["小说"]},
  {ip:"Street Fighter", title:"Street Fighter Live Concert (Capcom)", type:"concert", year:2017, region:"JP", publisher:"Capcom", desc:"音乐会。", tags:["音乐会"]},

  // ============================================================
  // TEKKEN
  // ============================================================
  {ip:"Tekken", title:"Tekken: The Motion Picture (Anime)", type:"anime", year:1998, region:"JP", publisher:"Production I.G.", desc:"2 集 OVA。", tags:["OVA"]},
  {ip:"Tekken", title:"Tekken (Live-Action 2010)", type:"film-live", year:2010, region:"US", publisher:"Crystal Sky", desc:"真人电影。", tags:["真人电影"]},
  {ip:"Tekken", title:"Tekken: Bloodline (Netflix Anime)", type:"anime", year:2022, region:"JP", publisher:"Netflix", desc:"网飞 6 集动画。", tags:["动画"]},
  {ip:"Tekken", title:"Tekken (Manga)", type:"manga", year:1995, region:"JP", publisher:"Shueisha", desc:"漫画。", tags:["少年漫画"]},
  {ip:"Tekken", title:"Tekken 2: Kazuya's Revenge (Manga)", type:"manga", year:1996, region:"JP", publisher:"Shueisha", desc:"《2》衍生。", tags:["少年漫画"]},
  {ip:"Tekken", title:"Tekken 7", type:"game-spinoff", year:2015, region:"JP", publisher:"Bandai Namco", desc:"现代续作。", tags:["FTG"]},
  {ip:"Tekken", title:"Tekken 8", type:"game-spinoff", year:2024, region:"JP", publisher:"Bandai Namco", desc:"《8》。", tags:["FTG"]},
  {ip:"Tekken", title:"Tekken Tag Tournament 2", type:"game-spinoff", year:2011, region:"JP", publisher:"Bandai Namco", desc:"组对续作。", tags:["FTG"]},
  {ip:"Tekken", title:"Tekken 3D: Prime Edition", type:"game-spinoff", year:2012, region:"JP", publisher:"Bandai Namco", desc:"3DS 续作。", tags:["FTG"]},
  {ip:"Tekken", title:"Tekken Revolution", type:"game-spinoff", year:2013, region:"JP", publisher:"Bandai Namco", desc:"PS3 网游。", tags:["FTG"]},
  {ip:"Tekken", title:"Tekken Card Tournament (Mobile)", type:"game-mobile", year:2013, region:"JP", publisher:"Bandai Namco", desc:"卡牌手游。", tags:["手游"]},
  {ip:"Tekken", title:"Tekken (Live Concert at TGS)", type:"concert", year:2017, region:"JP", publisher:"Bandai Namco", desc:"音乐会。", tags:["音乐会"]},
  {ip:"Tekken", title:"Tekken Plush (Bandai)", type:"merch-figure", year:1995, region:"JP", publisher:"Bandai", desc:"毛绒。", tags:["毛绒"]},
  {ip:"Tekken", title:"Tekken: Blood Vengeance (Novelization)", type:"novel", year:2011, region:"JP", publisher:"Bandai Namco", desc:"小说。", tags:["小说"]},
  {ip:"Tekken", title:"Tekken OST (Various)", type:"ost", year:2017, region:"JP", publisher:"Bandai Namco", desc:"原声集。", tags:["OST"]},

  // ============================================================
  // HALO
  // ============================================================
  {ip:"Halo", title:"Halo: The Fall of Reach (Anime)", type:"anime", year:2015, region:"US", publisher:"343 Industries", desc:"《光环:致远星》动画。", tags:["动画"]},
  {ip:"Halo", title:"Halo Legends (Anime Anthology)", type:"anime", year:2010, region:"US", publisher:"Microsoft / 343i", desc:"7 集 OVA 短片集。", tags:["OVA"]},
  {ip:"Halo", title:"Halo: Forward Unto Dawn (Webseries)", type:"web-series", year:2012, region:"US", publisher:"Microsoft", desc:"5 集真人短剧。", tags:["真人短剧"]},
  {ip:"Halo", title:"Halo: Nightfall (Webseries)", type:"web-series", year:2014, region:"US", publisher:"Microsoft", desc:"5 集真人短剧。", tags:["真人短剧"]},
  {ip:"Halo", title:"Halo (Paramount+ TV Series)", type:"tv", year:2022, region:"US", publisher:"Paramount+", desc:"2 季真人剧。", tags:["真人剧"]},
  {ip:"Halo", title:"Halo (Manga)", type:"manga", year:2006, region:"US", publisher:"Marvel", desc:"漫威漫画。", tags:["美式漫画"]},
  {ip:"Halo", title:"Halo: Fall of Reach (Manga)", type:"manga", year:2010, region:"US", publisher:"Marvel", desc:"漫威漫画。", tags:["美式漫画"]},
  {ip:"Halo", title:"Halo: Initiation (Manga)", type:"manga", year:2013, region:"US", publisher:"Dark Horse", desc:"黑马漫画。", tags:["美式漫画"]},
  {ip:"Halo", title:"Halo: Escalation (Manga)", type:"manga", year:2013, region:"US", publisher:"Dark Horse", desc:"黑马漫画。", tags:["美式漫画"]},
  {ip:"Halo", title:"Halo: Rise of Atriox (Manga)", type:"manga", year:2017, region:"US", publisher:"Dark Horse", desc:"黑马漫画。", tags:["美式漫画"]},
  {ip:"Halo", title:"Halo: Lone Wolf (Manga)", type:"manga", year:2019, region:"US", publisher:"Dark Horse", desc:"黑马漫画。", tags:["美式漫画"]},
  {ip:"Halo", title:"Halo: The Fall of Reach (Novel)", type:"novel", year:2001, region:"US", publisher:"Del Rey", desc:"首部小说。", tags:["小说"]},
  {ip:"Halo", title:"Halo: The Flood (Novel)", type:"novel", year:2003, region:"US", publisher:"Del Rey", desc:"小说。", tags:["小说"]},
  {ip:"Halo", title:"Halo: First Strike (Novel)", type:"novel", year:2003, region:"US", publisher:"Del Rey", desc:"小说。", tags:["小说"]},
  {ip:"Halo", title:"Halo: Ghosts of Onyx (Novel)", type:"novel", year:2006, region:"US", publisher:"Del Rey", desc:"小说。", tags:["小说"]},
  {ip:"Halo", title:"Halo: Contact Harvest (Novel)", type:"novel", year:2007, region:"US", publisher:"Del Rey", desc:"小说。", tags:["小说"]},
  {ip:"Halo", title:"Halo: The Cole Protocol (Novel)", type:"novel", year:2008, region:"US", publisher:"Del Rey", desc:"小说。", tags:["小说"]},
  {ip:"Halo", title:"Halo: Evolutions (Anthology)", type:"novel", year:2009, region:"US", publisher:"Del Rey", desc:"短篇集。", tags:["小说"]},
  {ip:"Halo", title:"Halo: Cryptum (Forerunner Saga 1)", type:"novel", year:2011, region:"US", publisher:"Del Rey", desc:"小说。", tags:["小说"]},
  {ip:"Halo", title:"Halo: Primordium (Forerunner 2)", type:"novel", year:2012, region:"US", publisher:"Del Rey", desc:"小说。", tags:["小说"]},
  {ip:"Halo", title:"Halo: Silentium (Forerunner 3)", type:"novel", year:2013, region:"US", publisher:"Del Rey", desc:"小说。", tags:["小说"]},
  {ip:"Halo", title:"Halo: Broken Circle (Novel)", type:"novel", year:2014, region:"US", publisher:"Del Rey", desc:"小说。", tags:["小说"]},
  {ip:"Halo", title:"Halo: Last Light (Novel)", type:"novel", year:2015, region:"US", publisher:"Del Rey", desc:"小说。", tags:["小说"]},
  {ip:"Halo", title:"Halo: Retribution (Novel)", type:"novel", year:2017, region:"US", publisher:"Del Rey", desc:"小说。", tags:["小说"]},
  {ip:"Halo", title:"Halo: Divine Wind (Novel)", type:"novel", year:2021, region:"US", publisher:"Del Rey", desc:"小说。", tags:["小说"]},
  {ip:"Halo", title:"Halo: The Television Series (Book 1)", type:"novel", year:2023, region:"US", publisher:"Gallery Books", desc:"剧集小说。", tags:["小说"]},
  {ip:"Halo", title:"Halo: Reach (Game)", type:"game-spinoff", year:2010, region:"US", publisher:"Bungie", desc:"前传 FPS。", tags:["FPS"]},
  {ip:"Halo", title:"Halo 3: ODST", type:"game-spinoff", year:2009, region:"US", publisher:"Bungie", desc:"外传。", tags:["FPS"]},
  {ip:"Halo", title:"Halo Wars", type:"game-spinoff", year:2009, region:"US", publisher:"Ensemble Studios", desc:"RTS 衍生。", tags:["RTS"]},
  {ip:"Halo", title:"Halo Wars 2", type:"game-spinoff", year:2017, region:"US", publisher:"Creative Assembly", desc:"RTS 续作。", tags:["RTS"]},
  {ip:"Halo", title:"Halo: Spartan Assault", type:"game-mobile", year:2013, region:"US", publisher:"Vanguard Games", desc:"手游。", tags:["手游"]},
  {ip:"Halo", title:"Halo: Spartan Strike", type:"game-mobile", year:2015, region:"US", publisher:"Vanguard Games", desc:"手游。", tags:["手游"]},
  {ip:"Halo", title:"Halo 5: Guardians", type:"game-spinoff", year:2015, region:"US", publisher:"343 Industries", desc:"续作。", tags:["FPS"]},
  {ip:"Halo", title:"Halo Infinite", type:"game-spinoff", year:2021, region:"US", publisher:"343 Industries", desc:"续作。", tags:["FPS"]},
  {ip:"Halo", title:"Halo: The Master Chief Collection", type:"game-spinoff", year:2014, region:"US", publisher:"343 Industries", desc:"合集。", tags:["合集"]},
  {ip:"Halo", title:"Halo Infinite OST", type:"ost", year:2021, region:"US", publisher:"Microsoft", desc:"原声。", tags:["OST"]},
  {ip:"Halo", title:"Halo 2 OST", type:"ost", year:2004, region:"US", publisher:"Microsoft", desc:"原声。", tags:["OST"]},
  {ip:"Halo", title:"Halo 3 OST", type:"ost", year:2007, region:"US", publisher:"Microsoft", desc:"原声。", tags:["OST"]},
  {ip:"Halo", title:"Halo Theme (Music Box)", type:"ost", year:2020, region:"US", publisher:"Microsoft", desc:"八音盒。", tags:["OST"]},
  {ip:"Halo", title:"Halo Mega Bloks / Mega Construx", type:"merch-toy", year:2013, region:"Global", publisher:"Mattel", desc:"积木。", tags:["积木"]},
  {ip:"Halo", title:"Halo Action Figures (McFarlane)", type:"merch-figure", year:2003, region:"US", publisher:"McFarlane Toys", desc:"可动人偶。", tags:["可动"]},
  {ip:"Halo", title:"Halo: Reach (Art Book)", type:"artbook", year:2010, region:"US", publisher:"Microsoft", desc:"画集。", tags:["画集"]},
  {ip:"Halo", title:"Halo Encyclopedia", type:"artbook", year:2015, region:"US", publisher:"DK", desc:"百科。", tags:["百科"]},
  {ip:"Halo", title:"Halo Legendary Crate", type:"merch-toy", year:2017, region:"US", publisher:"Loot Crate", desc:"主题礼盒。", tags:["礼盒"]},
  {ip:"Halo", title:"Halo 5: Guardians Collector's Statue", type:"merch-figure", year:2015, region:"US", publisher:"Microsoft", desc:"收藏雕像。", tags:["雕像"]},
  {ip:"Halo", title:"Halo x Monster Energy", type:"collab", year:2021, region:"Global", publisher:"Monster", desc:"魔爪饮料联名。", tags:["饮品联动"]},
  {ip:"Halo", title:"Halo x Nerf", type:"merch-toy", year:2010, region:"US", publisher:"Nerf", desc:"玩具枪。", tags:["玩具枪"]},
  {ip:"Halo", title:"Halo (Phone - Microsoft Edition)", type:"merch-cloth", year:2015, region:"US", publisher:"Microsoft", desc:"限量手机。", tags:["手机"]},
  {ip:"Halo", title:"Halo Mythic (TCG)", type:"merch-card", year:2014, region:"US", publisher:"Cryptozoic", desc:"TCG。", tags:["TCG"]},

  // ============================================================
  // THE WITCHER
  // ============================================================
  {ip:"Witcher", title:"The Witcher (Novel Series)", type:"novel", year:1993, region:"PL", publisher:"SuperNowa", desc:"安杰伊·萨普科夫斯基原著。", tags:["小说"]},
  {ip:"Witcher", title:"The Witcher: Blood of Elves (Novel)", type:"novel", year:1994, region:"PL", publisher:"SuperNowa", desc:"小说。", tags:["小说"]},
  {ip:"Witcher", title:"The Witcher: Time of Contempt (Novel)", type:"novel", year:1995, region:"PL", publisher:"SuperNowa", desc:"小说。", tags:["小说"]},
  {ip:"Witcher", title:"The Witcher: Baptism of Fire (Novel)", type:"novel", year:1996, region:"PL", publisher:"SuperNowa", desc:"小说。", tags:["小说"]},
  {ip:"Witcher", title:"The Witcher: The Tower of the Swallow (Novel)", type:"novel", year:1997, region:"PL", publisher:"SuperNowa", desc:"小说。", tags:["小说"]},
  {ip:"Witcher", title:"The Witcher: The Lady of the Lake (Novel)", type:"novel", year:1999, region:"PL", publisher:"SuperNowa", desc:"小说。", tags:["小说"]},
  {ip:"Witcher", title:"The Witcher: Season of Storms (Novel)", type:"novel", year:2013, region:"PL", publisher:"SuperNowa", desc:"小说。", tags:["小说"]},
  {ip:"Witcher", title:"The Witcher (Netflix Series)", type:"tv", year:2019, region:"US", publisher:"Netflix / Lauren S. Hissrich", desc:"3 季真人剧。", tags:["真人剧"]},
  {ip:"Witcher", title:"The Witcher: Blood Origin (Netflix)", type:"tv", year:2022, region:"US", publisher:"Netflix", desc:"前传剧。", tags:["真人剧"]},
  {ip:"Witcher", title:"The Witcher: Sirens of the Deep (Netflix Anime)", type:"anime", year:2025, region:"US", publisher:"Netflix / Studio Mir", desc:"动画电影。", tags:["动画"]},
  {ip:"Witcher", title:"The Witcher: Nightmare of the Wolf (Netflix Anime)", type:"film-anime", year:2021, region:"US", publisher:"Netflix", desc:"动画电影。", tags:["CG 动画"]},
  {ip:"Witcher", title:"The Witcher (Polish TV Series 2001)", type:"tv", year:2001, region:"PL", publisher:"Heritage Films", desc:"波兰早期真人剧。", tags:["真人剧"]},
  {ip:"Witcher", title:"The Witcher (Comic - Dark Horse)", type:"manga", year:2014, region:"US", publisher:"Dark Horse", desc:"美式漫画。", tags:["美式漫画"]},
  {ip:"Witcher", title:"The Witcher: Wild Animals (Manga)", type:"manga", year:2015, region:"US", publisher:"Dark Horse", desc:"漫画。", tags:["美式漫画"]},
  {ip:"Witcher", title:"The Witcher: The Witcher (Flash Game)", type:"game-spinoff", year:2007, region:"PL", publisher:"CD Projekt", desc:"Flash 游戏。", tags:["页游"]},
  {ip:"Witcher", title:"The Witcher: The Witcher 2", type:"game-spinoff", year:2011, region:"PL", publisher:"CD Projekt Red", desc:"续作。", tags:["RPG"]},
  {ip:"Witcher", title:"The Witcher 3: Wild Hunt", type:"game-spinoff", year:2015, region:"PL", publisher:"CD Projekt Red", desc:"《3》原版。", tags:["RPG"]},
  {ip:"Witcher", title:"The Witcher 3: Hearts of Stone", type:"game-spinoff", year:2015, region:"PL", publisher:"CD Projekt Red", desc:"DLC。", tags:["DLC"]},
  {ip:"Witcher", title:"The Witcher 3: Blood and Wine", type:"game-spinoff", year:2016, region:"PL", publisher:"CD Projekt Red", desc:"DLC。", tags:["DLC"]},
  {ip:"Witcher", title:"The Witcher (Gwent Card Game)", type:"merch-card", year:2018, region:"PL", publisher:"CD Projekt", desc:"实体卡牌。", tags:["TCG"]},
  {ip:"Witcher", title:"Thronebreaker: The Witcher Tales", type:"game-spinoff", year:2018, region:"PL", publisher:"CD Projekt", desc:"剧情 RPG。", tags:["RPG"]},
  {ip:"Witcher", title:"The Witcher: Monster Slayer (Mobile)", type:"game-mobile", year:2021, region:"PL", publisher:"Spokko", desc:"AR 手游。", tags:["AR"]},
  {ip:"Witcher", title:"The Witcher: Sirens of the Deep (Mobile)", type:"game-mobile", year:2024, region:"PL", publisher:"CD Projekt", desc:"手游。", tags:["手游"]},
  {ip:"Witcher", title:"The Witcher (Ost)", type:"ost", year:2015, region:"PL", publisher:"CD Projekt", desc:"原声。", tags:["OST"]},
  {ip:"Witcher", title:"The Witcher 3: Wild Hunt OST (Blood and Wine)", type:"ost", year:2016, region:"PL", publisher:"CD Projekt", desc:"原声。", tags:["OST"]},
  {ip:"Witcher", title:"The Witcher (TV Soundtrack)", type:"ost", year:2019, region:"US", publisher:"Netflix", desc:"剧集原声。", tags:["OST"]},
  {ip:"Witcher", title:"The Witcher Concert Tour", type:"concert", year:2022, region:"Global", publisher:"CD Projekt / Score", desc:"全球巡演。", tags:["交响乐"]},
  {ip:"Witcher", title:"The Witcher x Nike", type:"collab", year:2022, region:"Global", publisher:"Nike", desc:"耐克联名。", tags:["服装"]},
  {ip:"Witcher", title:"The Witcher x Adidas", type:"collab", year:2019, region:"Global", publisher:"Adidas", desc:"阿迪达斯联名。", tags:["服装"]},
  {ip:"Witcher", title:"The Witcher x Tubbz (Cosplay Duck)", type:"merch-figure", year:2020, region:"US", publisher:"Tubbz", desc:"鸭形公仔。", tags:["公仔"]},
  {ip:"Witcher", title:"The Witcher: Geralt Funko Pop", type:"merch-figure", year:2020, region:"US", publisher:"Funko", desc:"Funko 公仔。", tags:["Funko"]},
  {ip:"Witcher", title:"The Witcher Sword Replica (Frostmourne)", type:"merch-toy", year:2020, region:"US", publisher:"Replica Swords", desc:"剑 1:1 复刻。", tags:["道具"]},
  {ip:"Witcher", title:"The Witcher Monopoly", type:"game-board", year:2019, region:"US", publisher:"USAopoly", desc:"大富翁。", tags:["桌游"]},
  {ip:"Witcher", title:"The Witcher Board Game", type:"game-board", year:2014, region:"PL", publisher:"Fantasy Flight", desc:"桌游。", tags:["桌游"]},
  {ip:"Witcher", title:"The Witcher: Old World", type:"game-board", year:2022, region:"PL", publisher:"Go On Board", desc:"桌游。", tags:["桌游"]},
  {ip:"Witcher", title:"The Witcher: Wild Hunt (Art Book)", type:"artbook", year:2015, region:"PL", publisher:"Dark Horse", desc:"画集。", tags:["画集"]},
  {ip:"Witcher", title:"The Witcher: Crossroads of Swords (Artbook)", type:"artbook", year:2018, region:"PL", publisher:"CD Projekt", desc:"画集。", tags:["画集"]},
  {ip:"Witcher", title:"The Witcher (LEGO Ideas)", type:"merch-toy", year:2021, region:"Global", publisher:"LEGO", desc:"乐高。", tags:["积木"]},
  {ip:"Witcher", title:"The Witcher Bath (Bath Bomb)", type:"collab", year:2019, region:"US", publisher:"Lush", desc:"沐浴弹。", tags:["洗护联动"]},
  {ip:"Witcher", title:"The Witcher (Stage Play)", type:"theater", year:2018, region:"PL", publisher:"CD Projekt", desc:"舞台剧。", tags:["舞台剧"]},
  {ip:"Witcher", title:"The Witcher: The Witcher 4 (Upcoming)", type:"game-spinoff", year:2026, region:"PL", publisher:"CD Projekt Red", desc:"新作。", tags:["RPG"]},

  // ============================================================
  // CYBERPUNK 2077
  // ============================================================
  {ip:"Cyberpunk 2077", title:"Cyberpunk: Edgerunners (Netflix)", type:"anime", year:2022, region:"PL", publisher:"Netflix / Trigger", desc:"扳机社 10 集动画。", tags:["动画"]},
  {ip:"Cyberpunk 2077", title:"Cyberpunk 2077: Phantom Liberty", type:"game-spinoff", year:2023, region:"PL", publisher:"CD Projekt Red", desc:"大型 DLC。", tags:["DLC"]},
  {ip:"Cyberpunk 2077", title:"Cyberpunk 2077: Ultimate Edition", type:"game-spinoff", year:2023, region:"PL", publisher:"CD Projekt Red", desc:"终极版。", tags:["合集"]},
  {ip:"Cyberpunk 2077", title:"Cyberpunk 2077: Project Orion (Sequel)", type:"game-spinoff", year:2028, region:"PL", publisher:"CD Projekt Red", desc:"续作开发中。", tags:["RPG"]},
  {ip:"Cyberpunk 2077", title:"Cyberpunk 2077 OST", type:"ost", year:2020, region:"PL", publisher:"CD Projekt", desc:"原声。", tags:["OST"]},
  {ip:"Cyberpunk 2077", title:"Cyberpunk: Edgerunners OST", type:"ost", year:2022, region:"PL", publisher:"Netflix", desc:"动画原声。", tags:["OST"]},
  {ip:"Cyberpunk 2077", title:"Cyberpunk 2077: The Board Game", type:"game-board", year:2024, region:"PL", publisher:"Go On Board", desc:"桌游。", tags:["桌游"]},
  {ip:"Cyberpunk 2077", title:"Cyberpunk 2077 (Sourcebook)", type:"artbook", year:2020, region:"PL", publisher:"R. Talsorian Games", desc:"规则书。", tags:["规则书"]},
  {ip:"Cyberpunk 2077", title:"Cyberpunk 2077: World Compendium", type:"artbook", year:2023, region:"PL", publisher:"Dark Horse", desc:"百科。", tags:["百科"]},
  {ip:"Cyberpunk 2077", title:"Cyberpunk: Edgerunners (Manga)", type:"manga", year:2023, region:"JP", publisher:"Dark Horse", desc:"漫画。", tags:["美式漫画"]},
  {ip:"Cyberpunk 2077", title:"Cyberpunk 2077 x Adidas", type:"merch-cloth", year:2023, region:"Global", publisher:"Adidas", desc:"阿迪达斯联名。", tags:["服装"]},
  {ip:"Cyberpunk 2077", title:"Cyberpunk 2077 x Casetify", type:"merch-cloth", year:2022, region:"Global", publisher:"Casetify", desc:"手机壳联名。", tags:["手机壳"]},
  {ip:"Cyberpunk 2077", title:"Cyberpunk 2077 Plush (V)", type:"merch-figure", year:2022, region:"PL", publisher:"CD Projekt", desc:"V 毛绒。", tags:["毛绒"]},
  {ip:"Cyberpunk 2077", title:"Cyberpunk 2077 (Cyberdeck Replica)", type:"merch-toy", year:2023, region:"PL", publisher:"CD Projekt", desc:"Cyberdeck 复刻。", tags:["道具"]},
  {ip:"Cyberpunk 2077", title:"Cyberpunk 2077 (Sunglasses)", type:"merch-cloth", year:2022, region:"Global", publisher:"Goody Vibes", desc:"联名墨镜。", tags:["墨镜"]},

  // ============================================================
  // ASSASSIN'S CREED
  // ============================================================
  {ip:"Assassin's Creed", title:"Assassin's Creed (Live-Action Film 2016)", type:"film-live", year:2016, region:"US", publisher:"20th Century Fox / Ubisoft", desc:"迈克尔·法斯宾德主演。", tags:["真人电影"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Lineage (Short Film)", type:"film-live", year:2009, region:"CA", publisher:"Ubisoft", desc:"3 集真人短片。", tags:["真人短片"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Embers (CG Short)", type:"film-anime", year:2011, region:"CA", publisher:"Ubisoft", desc:"CG 短片。", tags:["CG 短片"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed (Manga)", type:"manga", year:2014, region:"JP", publisher:"Ubisoft", desc:"漫画。", tags:["美式漫画"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: The Fall (Manga)", type:"manga", year:2011, region:"US", publisher:"DC Comics", desc:"DC 漫画。", tags:["美式漫画"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: The Chain (Manga)", type:"manga", year:2013, region:"US", publisher:"DC Comics", desc:"DC 续作。", tags:["美式漫画"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Brahman (Manga)", type:"manga", year:2013, region:"US", publisher:"Titan Comics", desc:"漫画。", tags:["美式漫画"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed (Novel)", type:"novel", year:2009, region:"US", publisher:"Penguin", desc:"小说。", tags:["小说"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Renaissance (Novel)", type:"novel", year:2009, region:"IT", publisher:"Aliberti", desc:"意大利小说。", tags:["小说"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Brotherhood (Novel)", type:"novel", year:2010, region:"IT", publisher:"Aliberti", desc:"小说。", tags:["小说"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Revelations (Novel)", type:"novel", year:2011, region:"IT", publisher:"Aliberti", desc:"小说。", tags:["小说"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Forsaken (Novel)", type:"novel", year:2012, region:"UK", publisher:"Penguin UK", desc:"小说。", tags:["小说"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Black Flag (Novel)", type:"novel", year:2013, region:"UK", publisher:"Penguin UK", desc:"小说。", tags:["小说"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Unity (Novel)", type:"novel", year:2014, region:"UK", publisher:"Penguin UK", desc:"小说。", tags:["小说"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Underworld (Novel)", type:"novel", year:2015, region:"UK", publisher:"Penguin UK", desc:"小说。", tags:["小说"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Last Descendant (Novel)", type:"novel", year:2016, region:"US", publisher:"Scholastic", desc:"小说。", tags:["小说"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Odyssey (Novel)", type:"novel", year:2018, region:"US", publisher:"Scholastic", desc:"小说。", tags:["小说"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed II", type:"game-spinoff", year:2009, region:"CA", publisher:"Ubisoft", desc:"续作。", tags:["ACT"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Brotherhood", type:"game-spinoff", year:2010, region:"CA", publisher:"Ubisoft", desc:"续作。", tags:["ACT"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Revelations", type:"game-spinoff", year:2011, region:"CA", publisher:"Ubisoft", desc:"续作。", tags:["ACT"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed III", type:"game-spinoff", year:2012, region:"CA", publisher:"Ubisoft", desc:"续作。", tags:["ACT"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed IV: Black Flag", type:"game-spinoff", year:2013, region:"CA", publisher:"Ubisoft", desc:"续作。", tags:["ACT"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Rogue", type:"game-spinoff", year:2014, region:"CA", publisher:"Ubisoft", desc:"续作。", tags:["ACT"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Unity", type:"game-spinoff", year:2014, region:"CA", publisher:"Ubisoft", desc:"续作。", tags:["ACT"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Syndicate", type:"game-spinoff", year:2015, region:"CA", publisher:"Ubisoft", desc:"续作。", tags:["ACT"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Origins", type:"game-spinoff", year:2017, region:"CA", publisher:"Ubisoft", desc:"续作。", tags:["ACT"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Odyssey", type:"game-spinoff", year:2018, region:"CA", publisher:"Ubisoft", desc:"续作。", tags:["ACT"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Valhalla", type:"game-spinoff", year:2020, region:"CA", publisher:"Ubisoft", desc:"续作。", tags:["ACT"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Mirage", type:"game-spinoff", year:2023, region:"CA", publisher:"Ubisoft", desc:"续作。", tags:["ACT"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Shadows", type:"game-spinoff", year:2025, region:"CA", publisher:"Ubisoft", desc:"续作。", tags:["ACT"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Altaïr's Chronicles", type:"game-spinoff", year:2008, region:"CA", publisher:"Gameloft", desc:"NDS 衍生。", tags:["ACT"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Bloodlines", type:"game-spinoff", year:2009, region:"CA", publisher:"Amuze", desc:"PSP 衍生。", tags:["ACT"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Discovery", type:"game-spinoff", year:2009, region:"CA", publisher:"Gameloft", desc:"NDS 衍生。", tags:["ACT"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Project Legacy", type:"game-mobile", year:2010, region:"CA", publisher:"Ubisoft", desc:"社交手游。", tags:["手游"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Pirates", type:"game-mobile", year:2013, region:"CA", publisher:"Ubisoft", desc:"手游。", tags:["手游"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Memories", type:"game-mobile", year:2014, region:"CA", publisher:"Ubisoft", desc:"卡牌手游。", tags:["手游"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Identity", type:"game-mobile", year:2014, region:"CA", publisher:"Ubisoft", desc:"RPG 手游。", tags:["手游"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Rebellion", type:"game-mobile", year:2018, region:"CA", publisher:"Ubisoft", desc:"策略手游。", tags:["手游"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Valhalla OST", type:"ost", year:2020, region:"CA", publisher:"Ubisoft", desc:"原声。", tags:["OST"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed II OST (Vol. 1-2)", type:"ost", year:2009, region:"CA", publisher:"Ubisoft", desc:"原声。", tags:["OST"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Odyssey OST", type:"ost", year:2018, region:"CA", publisher:"Ubisoft", desc:"原声。", tags:["OST"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed Plush (Ezio)", type:"merch-figure", year:2010, region:"CA", publisher:"Ubisoft", desc:"毛绒。", tags:["毛绒"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed Hidden Blade Replica", type:"merch-toy", year:2017, region:"CA", publisher:"Ubisoft", desc:"袖剑复刻。", tags:["道具"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed Funko Pop", type:"merch-figure", year:2017, region:"US", publisher:"Funko", desc:"Funko 公仔。", tags:["Funko"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed x Monopoly", type:"game-board", year:2018, region:"US", publisher:"USAopoly", desc:"大富翁。", tags:["桌游"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: The Book of Magic", type:"artbook", year:2023, region:"CA", publisher:"Dark Horse", desc:"画集。", tags:["画集"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed: Odyssey - Official Collector's Edition Guide", type:"artbook", year:2018, region:"CA", publisher:"Ubisoft", desc:"攻略本。", tags:["攻略"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed Live Concert Tour", type:"concert", year:2019, region:"Global", publisher:"Ubisoft", desc:"全球巡演。", tags:["交响乐"]},
  {ip:"Assassin's Creed", title:"Assassin's Creed x Assassin x Puma", type:"collab", year:2019, region:"Global", publisher:"Puma", desc:"彪马联名。", tags:["服装"]},
  ];
  window.DATA = window.DATA.concat(EXT);
})();
