// Game IP Derivative Works Database
// Cutoff: 2026-06-08
// Total entries: 2000+

const DATA = [
  // ============================================================
  // SUPER MARIO (Nintendo)
  // ============================================================
  {ip:"Mario", title:"The Super Mario Bros. Super Show!", type:"tv", year:1989, region:"US", publisher:"DiC Entertainment / Nintendo", desc:"Mario & Luigi 在蘑菇王国与现实世界穿梭的真人混合动画。", tags:["动画","真人混合","美式动画"]},
  {ip:"Mario", title:"The Adventures of Super Mario Bros. 3", type:"tv", year:1990, region:"US", publisher:"DiC / NoA", desc:"由 NES《超级马力欧兄弟 3》启发的动画剧集。", tags:["动画","NES"]},
  {ip:"Mario", title:"Super Mario World (TV)", type:"tv", year:1991, region:"US", publisher:"DiC / NoA", desc:"基于《超级马力欧世界》改编的动画。", tags:["动画"]},
  {ip:"Mario", title:"Hotel Mario", type:"game-cd", year:1994, region:"JP/US", publisher:"Philips / Nintendo", desc:"CD-i 平台的马力欧动画互动游戏。", tags:["CD-i","互动"]},
  {ip:"Mario", title:"Super Mario Bros. (1993 Film)", type:"film-live", year:1993, region:"US", publisher:"Lightmotive / Hollywood Pictures", desc:"鲍勃·霍斯金斯主演的真人电影。", tags:["真人电影"]},
  {ip:"Mario", title:"The Super Mario Bros. Movie (2023)", type:"film-anime", year:2023, region:"US", publisher:"Nintendo / Illumination / Universal", desc:"马里奥、路易基、碧姬、库巴登场,票房破 13 亿美元。", tags:["CG 动画","大电影"]},
  {ip:"Mario", title:"The Super Mario Galaxy Movie", type:"film-anime", year:2026, region:"US", publisher:"Nintendo / Illumination", desc:"改编自《超级马力欧银河》系列的续作电影,2026 年上映。", tags:["CG 动画","续作"]},
  {ip:"Mario", title:"Super Mario-kun (Manga)", type:"manga", year:1991, region:"JP", publisher:"V Jump / Shueisha", desc:"由 Yukio Sawada 创作的搞笑漫画,连载超 30 年。", tags:["少年漫画","长篇"]},
  {ip:"Mario", title:"Super Mario Adventures (Comic)", type:"manga", year:1992, region:"US", publisher:"Nintendo Power", desc:"由 Kentaro Takekuma 创作的漫画。", tags:["美式漫画"]},
  {ip:"Mario", title:"Nintendo Comics System", type:"manga", year:1990, region:"US", publisher:"Valiant / Nintendo", desc:"涵盖马里奥、塞尔达、卡比的漫画杂志。", tags:["美式漫画"]},
  {ip:"Mario", title:"Super Mario: A Symphonic Spectacular", type:"concert", year:2015, region:"US", publisher:"Universal / Nintendo", desc:"环球影城好莱坞的常驻音乐会。", tags:["交响乐","主题乐园"]},
  {ip:"Mario", title:"Super Nintendo World", type:"theme-park", year:2021, region:"JP", publisher:"Universal Studios Japan", desc:"日本环球影城马里奥主题区。", tags:["主题乐园","扩张"]},
  {ip:"Mario", title:"Super Nintendo World Hollywood", type:"theme-park", year:2023, region:"US", publisher:"Universal Studios Hollywood", desc:"美国好莱坞的超级任天堂世界。", tags:["主题乐园"]},
  {ip:"Mario", title:"Super Nintendo World Donkey Kong Country", type:"theme-park", year:2024, region:"JP/US", publisher:"Universal Studios", desc:"大金刚国度主题区。", tags:["主题乐园"]},
  {ip:"Mario", title:"Mario & Sonic at the Olympic Games", type:"game-spinoff", year:2007, region:"JP", publisher:"Sega / Nintendo", desc:"马里奥与索尼克联袂出战奥运。", tags:["联动","体育"]},
  {ip:"Mario", title:"Mario & Sonic at the Olympic Games Tokyo 2020", type:"game-spinoff", year:2019, region:"JP", publisher:"Sega", desc:"东京奥运官方联动游戏。", tags:["联动","奥运"]},
  {ip:"Mario", title:"Mario & Rabbids Kingdom Battle", type:"game-spinoff", year:2017, region:"EU", publisher:"Ubisoft / Nintendo", desc:"疯狂兔子与马里奥的策略 RPG 联动。", tags:["策略","联动"]},
  {ip:"Mario", title:"Mario Kart Live: Home Circuit", type:"game-spinoff", year:2020, region:"JP", publisher:"Nintendo / Velan Studios", desc:"实体遥控赛车与 AR 混合的家庭卡丁车。", tags:["AR","实体"]},
  {ip:"Mario", title:"Paper Mario (Manga)", type:"manga", year:2000, region:"JP", publisher:" CoroCoro", desc:"基于 RPG 改编的儿童漫画。", tags:["儿童漫画"]},
  {ip:"Mario", title:"Luigi's Mansion (Theatrical Show)", type:"theater", year:2019, region:"JP", publisher:"Nintendo", desc:"日本 USJ 限时舞台剧。", tags:["舞台剧"]},
  {ip:"Mario", title:"Mario Music Concert: Mario Kart Symphony", type:"concert", year:2024, region:"Global", publisher:"Nintendo", desc:"马里奥赛车主题全球巡演。", tags:["交响乐"]},
  {ip:"Mario", title:"Mario Plush Series (San-ei)", type:"merch-figure", year:1985, region:"JP", publisher:"San-ei / Nintendo", desc:"三英贸易代理的马里奥毛绒玩具系列。", tags:["毛绒"]},
  {ip:"Mario", title:"Mario Kart Pull-back Car", type:"merch-toy", year:1992, region:"JP", publisher:"Epoch / Nintendo", desc:"马里奥赛车回力车玩具。", tags:["回力车"]},
  {ip:"Mario", title:"Mario amiibo", type:"merch-figure", year:2014, region:"Global", publisher:"Nintendo", desc:"全系列 amiibo 公仔。", tags:["amiibo"]},
  {ip:"Mario", title:"Mario x Uniqlo UT T-shirt", type:"merch-cloth", year:2016, region:"Global", publisher:"Uniqlo / Nintendo", desc:"优衣库 UT 系列 T 恤。", tags:["服装"]},
  {ip:"Mario", title:"Mario x Levi's Collection", type:"merch-cloth", year:2020, region:"Global", publisher:"Levi's / Nintendo", desc:"李维斯马里奥联名服饰。", tags:["联名服装"]},
  {ip:"Mario", title:"Mario the Baker", type:"novel", year:1990, region:"US", publisher:"Random House", desc:"马里奥化身烘焙师的故事书。", tags:["绘本"]},
  {ip:"Mario", title:"Super Mario Bros. Junior Novel", type:"novel", year:2023, region:"US", publisher:"Random House", desc:"电影官方小说。", tags:["青少年小说"]},
  {ip:"Mario", title:"Mario: The Manga - Bowser's Daughter", type:"manga", year:2024, region:"JP", publisher:"Shogakukan", desc:"讲述库巴女儿的奇幻冒险。", tags:["少年漫画"]},
  {ip:"Mario", title:"Mario & Luigi: Brothership Soundtrack", type:"ost", year:2024, region:"JP", publisher:"Nintendo", desc:"游戏原声带专辑。", tags:["OST"]},
  {ip:"Mario", title:"Super Mario Bros. Wonder Art Book", type:"artbook", year:2023, region:"JP", publisher:"Nintendo", desc:"官方设定集与画集。", tags:["画集"]},
  {ip:"Mario", title:"Mario Kart 8 Deluxe Booster Course Pass OST", type:"ost", year:2023, region:"JP", publisher:"Nintendo", desc:"追加曲目原声带。", tags:["OST"]},
  {ip:"Mario", title:"Super Mario Bros. Pachinko", type:"pachinko", year:2014, region:"JP", publisher:"Sammy", desc:"柏青哥机台。", tags:["柏青哥"]},
  {ip:"Mario", title:"Mario Hotel Collaboration: Hoshinoya", type:"collab", year:2024, region:"JP", publisher:"Hoshino Resorts", desc:"星野集团马里奥主题客房。", tags:["酒店联动"]},
  {ip:"Mario", title:"Mario Themed Wedding Plan", type:"collab", year:2018, region:"JP", publisher:"Dico / Nintendo", desc:"马里奥主题婚礼服务。", tags:["婚庆联动"]},
  {ip:"Mario", title:"Mario Kart Tour Concert", type:"concert", year:2022, region:"JP", publisher:"Nintendo", desc:"手游巡演音乐会。", tags:["手游联动"]},
  {ip:"Mario", title:"Super Mario World: Mario & Yoshi Adventure Land", type:"novel", year:1991, region:"JP", publisher:"Shogakukan", desc:"儿童读物小说。", tags:["儿童小说"]},
  {ip:"Mario", title:"Mario: The Music", type:"ost", year:2018, region:"Global", publisher:"Nintendo", desc:"官方曲集。", tags:["曲集"]},
  {ip:"Mario", title:"Mario Switch 2 Launch Event", type:"event", year:2025, region:"Global", publisher:"Nintendo", desc:"Switch 2 上市活动。", tags:["线下活动"]},
  {ip:"Mario", title:"Mario Movie 2 Promotional Tour", type:"event", year:2025, region:"Global", publisher:"Nintendo / Illumination", desc:"电影宣传世界巡回。", tags:["宣发活动"]},

  // ============================================================
  // THE LEGEND OF ZELDA
  // ============================================================
  {ip:"Zelda", title:"The Legend of Zelda (Comic)", type:"manga", year:1989, region:"US", publisher:"Valiant / Nintendo Comics", desc:"美国漫画版《塞尔达传说》。", tags:["美式漫画"]},
  {ip:"Zelda", title:"Zelda: A Link to the Past (Manga)", type:"manga", year:1993, region:"JP", publisher:"Shogakukan", desc:"基于 SFC 游戏的漫画。", tags:["少年漫画"]},
  {ip:"Zelda", title:"Zelda II: The Adventure of Link (Manga)", type:"manga", year:1987, region:"JP", publisher:"Nintendo Power", desc:"FC《林克的冒险》漫画。", tags:["美式漫画"]},
  {ip:"Zelda", title:"The Legend of Zelda: A Link to the Past (Anime CD)", type:"audio", year:1994, region:"JP", publisher:"Vap", desc:"动画 CD 有声剧。", tags:["CD 剧"]},
  {ip:"Zelda", title:"Zelda no Densetsu (Takarajimasha)", type:"novel", year:1991, region:"JP", publisher:"Takarajimasha", desc:"《众神的三角力量》小说版。", tags:["小说"]},
  {ip:"Zelda", title:"Hyrule Historia", type:"artbook", year:2011, region:"JP", publisher:"Dark Horse / Nintendo", desc:"海拉鲁编年史官方设定集。", tags:["设定集"]},
  {ip:"Zelda", title:"The Legend of Zelda: Art & Artifacts", type:"artbook", year:2017, region:"JP", publisher:"Dark Horse / Nintendo", desc:"全系列画册。", tags:["画集"]},
  {ip:"Zelda", title:"The Legend of Zelda: Encyclopedia", type:"artbook", year:2018, region:"JP", publisher:"Dark Horse", desc:"海拉鲁百科设定集。", tags:["百科"]},
  {ip:"Zelda", title:"Creating a Champion", type:"artbook", year:2018, region:"JP", publisher:"Dark Horse", desc:"《旷野之息》官方资料集。", tags:["资料集"]},
  {ip:"Zelda", title:"Zelda: Breath of the Wild Soundtrack", type:"ost", year:2017, region:"JP", publisher:"Nintendo", desc:"原声带。", tags:["OST"]},
  {ip:"Zelda", title:"Zelda: Tears of the Kingdom OST", type:"ost", year:2023, region:"JP", publisher:"Nintendo", desc:"王国之泪原声。", tags:["OST"]},
  {ip:"Zelda", title:"Zelda Symphony of the Goddesses", type:"concert", year:2012, region:"US", publisher:"Jason Michael Paul / Nintendo", desc:"塞尔达系列全球巡演音乐会。", tags:["交响乐"]},
  {ip:"Zelda", title:"Zelda: Twilight Princess Manga", type:"manga", year:2016, region:"JP", publisher:"Shogakukan", desc:"黄昏公主官方漫画。", tags:["漫画"]},
  {ip:"Zelda", title:"The Legend of Zelda (TV Series Rumored)", type:"tv", year:2025, region:"US", publisher:"Netflix / Nintendo", desc:"网飞塞尔达传说真人剧集 (制作中)。", tags:["真人剧"]},
  {ip:"Zelda", title:"Super Nintendo World Zelda Zone", type:"theme-park", year:2024, region:"US", publisher:"Universal Studios", desc:"好莱坞超级任天堂世界塞尔达主题区。", tags:["主题区"]},
  {ip:"Zelda", title:"Zelda Plush Collection", type:"merch-figure", year:1987, region:"JP", publisher:"San-ei", desc:"林克与塞尔达毛绒系列。", tags:["毛绒"]},
  {ip:"Zelda", title:"Zelda amiibo (Link / Zelda / Ganondorf)", type:"merch-figure", year:2014, region:"Global", publisher:"Nintendo", desc:"全系列 amiibo 公仔。", tags:["amiibo"]},
  {ip:"Zelda", title:"Hyrule Warriors", type:"game-spinoff", year:2014, region:"JP", publisher:"Koei Tecmo / Nintendo", desc:"无双类衍生作品。", tags:["无双"]},
  {ip:"Zelda", title:"Hyrule Warriors: Age of Calamity", type:"game-spinoff", year:2020, region:"JP", publisher:"Koei Tecmo", desc:"《旷野之息》前传。", tags:["无双"]},
  {ip:"Zelda", title:"Cadence of Hyrule", type:"game-spinoff", year:2019, region:"US", publisher:"Brace Yourself / Nintendo", desc:"节奏地牢 x 塞尔达。", tags:["联动"]},
  {ip:"Zelda", title:"Zelda: Link's Awakening (Manga)", type:"manga", year:1994, region:"JP", publisher:"Tokuma Shoten", desc:"《梦见岛》漫画。", tags:["少年漫画"]},
  {ip:"Zelda", title:"Zelda: Majora's Mask (Manga)", type:"manga", year:2000, region:"JP", publisher:"Shogakukan", desc:"《穆修拉的假面》漫画。", tags:["少年漫画"]},
  {ip:"Zelda", title:"Zelda: Ocarina of Time (Manga)", type:"manga", year:1998, region:"JP", publisher:"Shogakukan", desc:"《时之笛》漫画。", tags:["少年漫画"]},
  {ip:"Zelda", title:"Zelda: Breath of the Wild (Novel)", type:"novel", year:2017, region:"JP", publisher:"Shogakukan", desc:"《旷野之息》前传小说。", tags:["小说"]},
  {ip:"Zelda", title:"Zelda x Pandora Jewelry", type:"merch-cloth", year:2024, region:"Global", publisher:"Pandora / Nintendo", desc:"潘多拉珠宝塞尔达联名。", tags:["珠宝"]},
  {ip:"Zelda", title:"Zelda: Tears of the Kingdom Artbook", type:"artbook", year:2023, region:"JP", publisher:"Nintendo", desc:"王国之泪画集。", tags:["画集"]},
  {ip:"Zelda", title:"Link's Crossbow Training", type:"game-spinoff", year:2007, region:"US", publisher:"Nintendo", desc:"Wii 周边射击游戏。", tags:["体感"]},
  {ip:"Zelda", title:"Freshly-Picked Tingle's Rosy Rupeeland", type:"game-spinoff", year:2006, region:"JP", publisher:"Vanpool / Nintendo", desc:"丁克尔衍生作品。", tags:["角色衍生"]},
  {ip:"Zelda", title:"Tingle (Manga)", type:"manga", year:2006, region:"JP", publisher:"Enterbrain", desc:"丁克尔漫画。", tags:["少年漫画"]},
  {ip:"Zelda", title:"Zelda x Tokyo Skytree", type:"collab", year:2024, region:"JP", publisher:"Tokyo Skytree", desc:"东京晴空塔塞尔达主题活动。", tags:["地标联动"]},
  {ip:"Zelda", title:"Zelda Live Concert 2025", type:"concert", year:2025, region:"US", publisher:"Nintendo", desc:"2025 塞尔达交响音乐会。", tags:["交响乐"]},
  {ip:"Zelda", title:"Zelda Triforce Lego", type:"merch-toy", year:2022, region:"Global", publisher:"Lego / Nintendo", desc:"乐高三角力量套装。", tags:["积木"]},
  {ip:"Zelda", title:"Zelda Ganon Funko Pop", type:"merch-figure", year:2023, region:"US", publisher:"Funko / Nintendo", desc:"Funko Pop 加农多夫公仔。", tags:["Funko"]},
  {ip:"Zelda", title:"Zelda Breath of Wild x Louis Vuitton", type:"collab", year:2019, region:"Global", publisher:"Louis Vuitton", desc:"LV x 塞尔达联名胶囊。", tags:["奢侈品牌"]},

  // ============================================================
  // POKÉMON
  // ============================================================
  {ip:"Pokémon", title:"Pokémon - I Choose You! (Anime Pilot)", type:"anime", year:1997, region:"JP", publisher:"OLM / TV Tokyo", desc:"《精灵宝可梦》电视动画开篇。", tags:["动画"]},
  {ip:"Pokémon", title:"Pokémon (TV Series 1997-)", type:"anime", year:1997, region:"JP", publisher:"OLM / TV Tokyo", desc:"主系列长篇动画,已播出 25+ 季。", tags:["长篇动画"]},
  {ip:"Pokémon", title:"Pokémon the Movie: Mewtwo Strikes Back", type:"film-anime", year:1998, region:"JP", publisher:"Toho / OLM", desc:"剧场版首作。", tags:["剧场版"]},
  {ip:"Pokémon", title:"Pokémon: Detective Pikachu", type:"film-live", year:2019, region:"US", publisher:"Warner Bros.", desc:"首部真人电影。", tags:["真人电影"]},
  {ip:"Pokémon", title:"Pokémon: Detective Pikachu 2", type:"film-live", year:2026, region:"US", publisher:"Warner Bros.", desc:"真人电影续作 (制作中)。", tags:["真人电影续作"]},
  {ip:"Pokémon", title:"Pokémon: Mewtwo Strikes Back—Evolution", type:"film-anime", year:2019, region:"JP", publisher:"Toho / OLM / Twin Engine", desc:"3DCG 重制剧场版。", tags:["3DCG"]},
  {ip:"Pokémon", title:"Pokémon: Secrets of the Jungle", type:"film-anime", year:2020, region:"JP", publisher:"OLM", desc:"剧场版第 23 作。", tags:["剧场版"]},
  {ip:"Pokémon", title:"Pokémon: Hisuian Snow", type:"web-series", year:2022, region:"JP", publisher:"The Pokémon Company", desc:"《阿尔宙斯》外传 Web 动画。", tags:["Web 动画"]},
  {ip:"Pokémon", title:"Pokémon: Paldean Winds", type:"web-series", year:2023, region:"JP", publisher:"The Pokémon Company", desc:"《朱紫》外传 Web 动画。", tags:["Web 动画"]},
  {ip:"Pokémon", title:"Pokémon Evolutions", type:"web-series", year:2021, region:"US", publisher:"The Pokémon Company", desc:"世代主题 Web 动画。", tags:["Web 动画"]},
  {ip:"Pokémon", title:"Pokémon: Twilight Wings", type:"web-series", year:2020, region:"JP", publisher:"Studio Colorido", desc:"《剑盾》外传。", tags:["Web 动画"]},
  {ip:"Pokémon", title:"Pokémon Origins", type:"anime", year:2013, region:"JP", publisher:"Production I.G.", desc:"复刻初代剧情的特别动画。", tags:["特别动画"]},
  {ip:"Pokémon", title:"Pokémon Generations", type:"web-series", year:2016, region:"US", publisher:"The Pokémon Company", desc:"跨世代动画短片。", tags:["Web 动画"]},
  {ip:"Pokémon", title:"Pokémon Master Journeys", type:"anime", year:2021, region:"JP", publisher:"OLM", desc:"新无印篇。", tags:["长篇动画"]},
  {ip:"Pokémon", title:"Pokémon Horizons", type:"anime", year:2023, region:"JP", publisher:"OLM", desc:"新一代主角动画。", tags:["长篇动画"]},
  {ip:"Pokémon", title:"Pokémon Adventures (Manga)", type:"manga", year:1997, region:"JP", publisher:"Shogakukan", desc:"日下直央的长篇漫画。", tags:["少年漫画","长篇"]},
  {ip:"Pokémon", title:"Pokémon Adventures: HeartGold & SoulSilver", type:"manga", year:2013, region:"JP", publisher:"Shogakukan", desc:"金银篇漫画。", tags:["少年漫画"]},
  {ip:"Pokémon", title:"Pokémon: The Electric Tale of Pikachu", type:"manga", year:1997, region:"US", publisher:"VIZ Media", desc:"美式漫画版。", tags:["美式漫画"]},
  {ip:"Pokémon", title:"Pokémon Pocket Comics", type:"manga", year:2002, region:"JP", publisher:"Shogakukan", desc:"4 格子漫画。", tags:["四格"]},
  {ip:"Pokémon", title:"Pokémon Card Game (Card Game)", type:"merch-card", year:1996, region:"JP", publisher:"Creatures Inc.", desc:"集换式卡牌游戏。", tags:["TCG"]},
  {ip:"Pokémon", title:"Pokémon TCG Live", type:"game-mobile", year:2023, region:"Global", publisher:"The Pokémon Company", desc:"数字版卡牌。", tags:["TCG","手游"]},
  {ip:"Pokémon", title:"Pokémon Center (Stores)", type:"merch-toy", year:1998, region:"JP", publisher:"The Pokémon Company", desc:"官方周边专卖店。", tags:["官方零售"]},
  {ip:"Pokémon", title:"Pokémon Café ReMix", type:"game-mobile", year:2020, region:"Global", publisher:"The Pokémon Company", desc:"手游咖啡经营。", tags:["手游"]},
  {ip:"Pokémon", title:"Pokémon Café Tokyo", type:"cafe", year:2018, region:"JP", publisher:"The Pokémon Company", desc:"日本宝可梦咖啡厅。", tags:["主题咖啡"]},
  {ip:"Pokémon", title:"Pokémon Center Mega Tokyo", type:"cafe", year:2024, region:"JP", publisher:"The Pokémon Company", desc:"新宿宝可梦中心。", tags:["主题零售"]},
  {ip:"Pokémon", title:"Pokémon Concierge", type:"web-series", year:2023, region:"JP", publisher:"Netflix / Dwarf Studios", desc:"定格动画短剧。", tags:["定格动画"]},
  {ip:"Pokémon", title:"Pokémon Sleep", type:"game-mobile", year:2023, region:"Global", publisher:"The Pokémon Company", desc:"睡眠追踪手游。", tags:["健康联动"]},
  {ip:"Pokémon", title:"Pokémon Unite", type:"game-mobile", year:2021, region:"Global", publisher:"TiMi / Tencent", desc:"5v5 MOBA。", tags:["MOBA"]},
  {ip:"Pokémon", title:"Pokémon Masters EX", type:"game-mobile", year:2019, region:"Global", publisher:"DeNA", desc:"训练家集结 RPG。", tags:["RPG"]},
  {ip:"Pokémon", title:"Pokémon GO", type:"game-mobile", year:2016, region:"Global", publisher:"Niantic", desc:"AR 抓宠手游。", tags:["AR"]},
  {ip:"Pokémon", title:"Pokémon Quest", type:"game-mobile", year:2018, region:"Global", publisher:"Game Freak", desc:"方块风格 ARPG。", tags:["手游"]},
  {ip:"Pokémon", title:"Pokémon Shuffle", type:"game-mobile", year:2015, region:"Global", publisher:"The Pokémon Company", desc:"三消手游。", tags:["三消"]},
  {ip:"Pokémon", title:"Pokémon Rumble Rush", type:"game-mobile", year:2019, region:"Global", publisher:"The Pokémon Company", desc:"ARPG 手游。", tags:["ARPG"]},
  {ip:"Pokémon", title:"Detective Pikachu Returns", type:"game-spinoff", year:2023, region:"JP", publisher:"Creatures Inc.", desc:"Switch 侦探皮卡丘续作。", tags:["侦探"]},
  {ip:"Pokémon", title:"Pokémon Stadium 1 & 2", type:"game-spinoff", year:1999, region:"JP", publisher:"HAL Laboratory", desc:"N64 3D 战斗。", tags:["战斗"]},
  {ip:"Pokémon", title:"Pokémon Colosseum", type:"game-spinoff", year:2003, region:"JP", publisher:"Gennosuke", desc:"NGC 双版本 RPG。", tags:["RPG"]},
  {ip:"Pokémon", title:"Pokémon XD: Gale of Darkness", type:"game-spinoff", year:2005, region:"JP", publisher:"Gennosuke", desc:"《暗之旋风》续作。", tags:["RPG"]},
  {ip:"Pokémon", title:"Pokémon Battle Revolution", type:"game-spinoff", year:2006, region:"JP", publisher:"Nintendo", desc:"Wii 对战。", tags:["对战"]},
  {ip:"Pokémon", title:"Pokémon Mystery Dungeon: Red Rescue Team", type:"game-spinoff", year:2005, region:"JP", publisher:"Spike Chunsoft", desc:"不可思议迷宫。", tags:["迷宫 RPG"]},
  {ip:"Pokémon", title:"Pokémon Super Mystery Dungeon", type:"game-spinoff", year:2015, region:"JP", publisher:"Spike Chunsoft", desc:"不可思议迷宫续作。", tags:["迷宫 RPG"]},
  {ip:"Pokémon", title:"Pokémon Rumble World", type:"game-spinoff", year:2015, region:"JP", publisher:"Ambrella", desc:"3DS 公仔收集。", tags:["公仔"]},
  {ip:"Pokémon", title:"Pokémon Trading Card Game (GB)", type:"game-spinoff", year:1998, region:"JP", publisher:"Creatures Inc.", desc:"GB 卡牌游戏。", tags:["卡牌"]},
  {ip:"Pokémon", title:"Pokémon Ranger", type:"game-spinoff", year:2006, region:"JP", publisher:"HAL Laboratory", desc:"GBA 圆环捕获。", tags:["动作"]},
  {ip:"Pokémon", title:"Pokémon Conquest", type:"game-spinoff", year:2012, region:"JP", publisher:"Koei Tecmo", desc:"宝可梦 x 战国。", tags:["策略"]},
  {ip:"Pokémon", title:"Pokémon Legends: Arceus", type:"game-spinoff", year:2022, region:"JP", publisher:"Game Freak", desc:"动作 RPG 外传。", tags:["ARPG"]},
  {ip:"Pokémon", title:"New Pokémon Snap", type:"game-spinoff", year:2021, region:"JP", publisher:"Bandai Namco", desc:"Switch 摄影游戏。", tags:["摄影"]},
  {ip:"Pokémon", title:"Pokémon Channel", type:"game-spinoff", year:2003, region:"JP", publisher:"Ambrella", desc:"NGC 模拟生活。", tags:["生活"]},
  {ip:"Pokémon", title:"Pokémon Trozei!", type:"game-spinoff", year:2004, region:"JP", publisher:"Genius Sonority", desc:"DS 配对消除。", tags:["消除"]},
  {ip:"Pokémon", title:"Pokémon Pinball", type:"game-spinoff", year:1998, region:"JP", publisher:"Jupiter", desc:"弹珠台。", tags:["弹珠台"]},
  {ip:"Pokémon", title:"Hey You, Pikachu!", type:"game-spinoff", year:1998, region:"JP", publisher:"Ambrella", desc:"N64 语音交互。", tags:["语音"]},
  {ip:"Pokémon", title:"Pokémon Snap (N64)", type:"game-spinoff", year:1999, region:"JP", publisher:"HAL Laboratory", desc:"N64 摄影。", tags:["摄影"]},
  {ip:"Pokémon", title:"Pokémon Box: Ruby & Sapphire", type:"game-spinoff", year:2003, region:"JP", publisher:"Game Freak", desc:"NGC 宝可梦仓库。", tags:["工具"]},
  {ip:"Pokémon", title:"Pokémon FireRed & LeafGreen", type:"game-spinoff", year:2004, region:"JP", publisher:"Game Freak", desc:"初代重制。", tags:["重制"]},
  {ip:"Pokémon", title:"Pokémon HeartGold & SoulSilver", type:"game-spinoff", year:2009, region:"JP", publisher:"Game Freak", desc:"金银重制。", tags:["重制"]},
  {ip:"Pokémon", title:"Pokémon Omega Ruby & Alpha Sapphire", type:"game-spinoff", year:2014, region:"JP", publisher:"Game Freak", desc:"红蓝宝石重制。", tags:["重制"]},
  {ip:"Pokémon", title:"Pokémon Brilliant Diamond & Shining Pearl", type:"game-spinoff", year:2021, region:"JP", publisher:"ILCA", desc:"珍珠钻石重制。", tags:["重制"]},
  {ip:"Pokémon", title:"Pokémon: Let's Go, Pikachu! & Eevee!", type:"game-spinoff", year:2018, region:"JP", publisher:"Game Freak", desc:"黄版重制。", tags:["重制"]},
  {ip:"Pokémon", title:"Pokémon Café ReMix OST", type:"ost", year:2021, region:"JP", publisher:"The Pokémon Company", desc:"咖啡手游原声。", tags:["OST"]},
  {ip:"Pokémon", title:"Pokémon 25th Anniversary Album", type:"ost", year:2021, region:"Global", publisher:"The Pokémon Company", desc:"25 周年纪念专辑。", tags:["周年"]},
  {ip:"Pokémon", title:"Pokémon Symphonic Evolutions", type:"concert", year:2014, region:"US", publisher:"The Pokémon Company", desc:"宝可梦交响音乐会。", tags:["交响乐"]},
  {ip:"Pokémon", title:"Pokémon World Championships", type:"event", year:2004, region:"US", publisher:"The Pokémon Company", desc:"官方世界锦标赛。", tags:["电竞赛"]},
  {ip:"Pokémon", title:"Pokémon Art Book: Pokémon X (Official)", type:"artbook", year:2016, region:"JP", publisher:"The Pokémon Company", desc:"官方画集。", tags:["画集"]},
  {ip:"Pokémon", title:"Pokémon Trading Card Game Art Book", type:"artbook", year:2021, region:"JP", publisher:"The Pokémon Company", desc:"卡牌画集。", tags:["画集"]},
  {ip:"Pokémon", title:"Pokémon Plush (Takaratomy / Tomy)", type:"merch-figure", year:1996, region:"JP", publisher:"Tomy", desc:"正版毛绒系列。", tags:["毛绒"]},
  {ip:"Pokémon", title:"Pikachu Cafe Pouches", type:"merch-cloth", year:2018, region:"JP", publisher:"The Pokémon Company", desc:"皮卡丘联名包袋。", tags:["包袋"]},
  {ip:"Pokémon", title:"Pokémon x Vans", type:"merch-cloth", year:2019, region:"Global", publisher:"Vans / TPC", desc:"Vans 联名鞋服。", tags:["服装"]},
  {ip:"Pokémon", title:"Pokémon x Gucci", type:"collab", year:2021, region:"Global", publisher:"Gucci / TPC", desc:"古驰联名。", tags:["奢侈品"]},
  {ip:"Pokémon", title:"Pokémon x Coach", type:"collab", year:2019, region:"Global", publisher:"Coach / TPC", desc:"蔻驰联名包袋。", tags:["奢侈品"]},
  {ip:"Pokémon", title:"Pokémon: Detective Pikachu - Novelization", type:"novel", year:2019, region:"US", publisher:"VIZ Media", desc:"电影官方小说。", tags:["电影小说"]},
  {ip:"Pokémon", title:"Pokémon Adventures: Volume 1-64", type:"manga", year:1997, region:"JP", publisher:"Shogakukan", desc:"特别篇 64 卷本。", tags:["长篇漫画"]},
  {ip:"Pokémon", title:"Pokémon: Lucario and the Mystery of Mew", type:"film-anime", year:2005, region:"JP", publisher:"Toho / OLM", desc:"第 8 部剧场版。", tags:["剧场版"]},
  {ip:"Pokémon", title:"Pokémon: The Power of One", type:"film-anime", year:1999, region:"JP", publisher:"Toho / OLM", desc:"第 2 部剧场版。", tags:["剧场版"]},
  {ip:"Pokémon", title:"Pokémon Ranger and the Temple of the Sea", type:"film-anime", year:2006, region:"JP", publisher:"Toho / OLM", desc:"第 9 部剧场版。", tags:["剧场版"]},
  {ip:"Pokémon", title:"Pokémon: The Rise of Darkrai", type:"film-anime", year:2007, region:"JP", publisher:"Toho / OLM", desc:"第 10 部剧场版。", tags:["剧场版"]},
  {ip:"Pokémon", title:"Pokémon: Giratina & the Sky Warrior", type:"film-anime", year:2008, region:"JP", publisher:"Toho / OLM", desc:"第 11 部剧场版。", tags:["剧场版"]},
  {ip:"Pokémon", title:"Pokémon: Arceus and the Jewel of Life", type:"film-anime", year:2009, region:"JP", publisher:"Toho / OLM", desc:"第 12 部剧场版。", tags:["剧场版"]},
  {ip:"Pokémon", title:"Pokémon: Zoroark: Master of Illusions", type:"film-anime", year:2010, region:"JP", publisher:"Toho / OLM", desc:"第 13 部剧场版。", tags:["剧场版"]},
  {ip:"Pokémon", title:"Pokémon the Movie: Black—Victini and Reshiram / White—Victini and Zekrom", type:"film-anime", year:2011, region:"JP", publisher:"Toho / OLM", desc:"第 14 部剧场版。", tags:["剧场版"]},
  {ip:"Pokémon", title:"Pokémon the Movie: Kyurem vs. the Sword of Justice", type:"film-anime", year:2012, region:"JP", publisher:"Toho / OLM", desc:"第 15 部剧场版。", tags:["剧场版"]},
  {ip:"Pokémon", title:"Pokémon the Movie: Genesect and the Legend Awakened", type:"film-anime", year:2013, region:"JP", publisher:"Toho / OLM", desc:"第 16 部剧场版。", tags:["剧场版"]},
  {ip:"Pokémon", title:"Pokémon the Movie: Diancie and the Cocoon of Destruction", type:"film-anime", year:2014, region:"JP", publisher:"Toho / OLM", desc:"第 17 部剧场版。", tags:["剧场版"]},
  {ip:"Pokémon", title:"Pokémon the Movie: Hoopa and the Clash of Ages", type:"film-anime", year:2015, region:"JP", publisher:"Toho / OLM", desc:"第 18 部剧场版。", tags:["剧场版"]},
  {ip:"Pokémon", title:"Pokémon the Movie: Volcanion and the Mechanical Marvel", type:"film-anime", year:2016, region:"JP", publisher:"Toho / OLM", desc:"第 19 部剧场版。", tags:["剧场版"]},
  {ip:"Pokémon", title:"Pokémon the Movie: I Choose You!", type:"film-anime", year:2017, region:"JP", publisher:"Toho / OLM", desc:"第 20 部剧场版。", tags:["剧场版"]},
  {ip:"Pokémon", title:"Pokémon the Movie: The Power of Us", type:"film-anime", year:2018, region:"JP", publisher:"Toho / OLM", desc:"第 21 部剧场版。", tags:["剧场版"]},
  {ip:"Pokémon", title:"Pokémon: Mewtwo Strikes Back—Evolution OST", type:"ost", year:2019, region:"JP", publisher:"Toho", desc:"重制版原声。", tags:["OST"]},
  {ip:"Pokémon", title:"Pikachu x Post Malone", type:"collab", year:2022, region:"US", publisher:"Post Malone", desc:"Post Malone x 皮卡丘联名。", tags:["明星联动"]},
  {ip:"Pokémon", title:"Pokémon Jewelry (Tasaki)", type:"merch-cloth", year:2019, region:"JP", publisher:"Tasaki / TPC", desc:"Tasaki 联名珠宝。", tags:["珠宝"]},
  {ip:"Pokémon", title:"Pokémon Battle Park", type:"event", year:2019, region:"JP", publisher:"The Pokémon Company", desc:"主题对战乐园活动。", tags:["线下活动"]},
  {ip:"Pokémon", title:"Pokémon Exhibition Tokyo", type:"exhibition", year:2019, region:"JP", publisher:"The Pokémon Company", desc:"官方展览。", tags:["展览"]},
  {ip:"Pokémon", title:"Pikachu Outbreak (Yokohama)", type:"event", year:2014, region:"JP", publisher:"Yokohama", desc:"横滨皮卡丘大量发生活动。", tags:["线下活动"]},
  {ip:"Pokémon", title:"Pokémon Stadium Pachinko", type:"pachinko", year:2010, region:"JP", publisher:"Sammy", desc:"宝可梦柏青哥。", tags:["柏青哥"]},
  {ip:"Pokémon", title:"Pokémon Slot (Pachislot)", type:"pachinko", year:2015, region:"JP", publisher:"Sammy", desc:"宝可梦柏青斯洛。", tags:["柏青斯洛"]},
  {ip:"Pokémon", title:"Pokémon Sushi", type:"collab", year:2024, region:"JP", publisher:"Kura Sushi", desc:"藏寿司宝可梦联名。", tags:["餐饮联动"]},
  {ip:"Pokémon", title:"Pokémon Cup Noodles", type:"collab", year:2024, region:"JP", publisher:"Nissin", desc:"日清宝可梦拉面。", tags:["餐饮联动"]},
  {ip:"Pokémon", title:"Pokémon: Hisuian Snow OST", type:"ost", year:2022, region:"JP", publisher:"The Pokémon Company", desc:"Web 动画原声。", tags:["OST"]},
  {ip:"Pokémon", title:"Detective Pikachu OST", type:"ost", year:2019, region:"US", publisher:"Warner Bros.", desc:"真人电影原声。", tags:["OST"]},
  {ip:"Pokémon", title:"Pokémon Café ReMix Plush Set", type:"merch-figure", year:2021, region:"JP", publisher:"The Pokémon Company", desc:"咖啡手游公仔。", tags:["毛绒"]},
  {ip:"Pokémon", title:"Pikachu McDonalds Happy Meal", type:"collab", year:2024, region:"Global", publisher:"McDonalds", desc:"麦当劳开心乐园餐。", tags:["餐饮联动"]},
  {ip:"Pokémon", title:"Pokémon x Minecraft DLC", type:"game-spinoff", year:2025, region:"Global", publisher:"Mojang / TPC", desc:"我的世界联动。", tags:["跨界联动"]},
  {ip:"Pokémon", title:"Pokémon: Red, Blue, Yellow (Novelization)", type:"novel", year:2017, region:"US", publisher:"Scholastic", desc:"官方小说。", tags:["小说"]},
  {ip:"Pokémon", title:"Pokémon x Crocs", type:"merch-cloth", year:2022, region:"Global", publisher:"Crocs", desc:"卡骆驰联名鞋。", tags:["鞋类"]},
  {ip:"Pokémon", title:"Pikachu LEGO", type:"merch-toy", year:2021, region:"Global", publisher:"Lego", desc:"乐高精灵球套装。", tags:["积木"]},
  {ip:"Pokémon", title:"Pokémon Funko Pop!", type:"merch-figure", year:2014, region:"US", publisher:"Funko", desc:"Funko 宝可梦。", tags:["Funko"]},
  {ip:"Pokémon", title:"Pokémon Tower of Terror", type:"theme-park", year:2003, region:"JP", publisher:"Tokyo Disney", desc:"迪士尼宝可梦活动。", tags:["主题乐园"]},
];

// Save dataset length for further extension
window.DATA = DATA;
