#!/usr/bin/env python3
"""
120 镜头提示词批量生成器
读取镜头数据，输出到 /workspace/prompts/shots/act-XX/shot-XXX.json
"""
import json
import os
from pathlib import Path

OUTPUT_DIR = Path("/workspace/prompts/shots")

# 6 幕主题配置
ACTS = {
    1: {"theme": "清晨苏醒",   "range": "1-20",   "mood": "warm",      "time": "morning"},
    2: {"theme": "上学路上",   "range": "21-40",  "mood": "uplifting", "time": "morning"},
    3: {"theme": "校园日常",   "range": "41-60",  "mood": "funny",     "time": "noon"},
    4: {"theme": "家庭游戏",   "range": "61-80",  "mood": "warm",      "time": "evening"},
    5: {"theme": "睡前故事",   "range": "81-100", "mood": "soft",      "time": "night"},
    6: {"theme": "夜之温柔",   "range": "101-120","mood": "uplifting", "time": "dream"},
}

# 通用风格前后缀
STYLE_PREFIX = "Studio Ghibli inspired, soft lighting, warm color palette, watercolor + 3D render, cozy family animation, 4K, cinematic"
NEGATIVE = "horror, blood, realistic photo, watermark, text, dark scene, violence"

# ============ 120 镜头数据 ============
SHOTS = [
    # ===== 第一幕：清晨苏醒 (1-20) =====
    {"id":1,  "title":"航拍俯瞰云层小镇",            "characters":[],            "location":"云层下日式小镇",       "time":"morning",   "scene_type":"establishing", "image":"Aerial view of a cozy Japanese-style small town under morning clouds, soft golden sunlight, smoke rising from chimneys, watercolor 3D render style",  "motion":"camera_dolly_in", "speed":"slow",  "duration":1.0, "sfx":["birds chirping","wind ambient"], "bgm":"soft piano arpeggio",                "sub":"咕咕嘎嘎之家",          "tags":["航拍","开场","清晨","全景"]},
    {"id":2,  "title":"推近蘑菇形小屋",              "characters":[],            "location":"蘑菇形小屋外观",       "time":"morning",   "scene_type":"establishing", "image":"Push-in to a mushroom-shaped cozy cottage with a sleeping orange bird on the roof, morning dew, fairy tale style",                                              "motion":"camera_dolly_in", "speed":"slow",  "duration":1.0, "sfx":["wind chime"],                "bgm":"soft piano arpeggio",                "sub":"",                       "tags":["推近","建筑","清晨"]},
    {"id":3,  "title":"咕咕闹钟响起",                "characters":["gugu"],      "location":"主卧床头",            "time":"morning",   "scene_type":"portrait",     "image":"Close-up of a feather-shaped alarm clock ringing gugu-gugu, a yellow-orange bird papa reaching out with fluffy wing, warm bedroom",                            "motion":"static",          "speed":"normal","duration":1.0, "sfx":["alarm ringing"],            "bgm":"soft piano arpeggio",                "sub":"",                       "tags":["特写","咕咕","闹钟"]},
    {"id":4,  "title":"咕咕按掉闹钟微笑",            "characters":["gugu"],      "location":"主卧",                "time":"morning",   "scene_type":"portrait",     "image":"Papa gugu bird pressing alarm with wing, smiling with sleepy eyes, glasses slightly askew, soft morning light",                                                       "motion":"static",          "speed":"normal","duration":1.0, "sfx":["alarm click"],              "bgm":"soft piano arpeggio",                "sub":"",                       "tags":["特写","咕咕","表情"]},
    {"id":5,  "title":"嘎嘎妈妈煎蛋",                "characters":["gaga"],      "location":"厨房",                "time":"morning",   "scene_type":"action",       "image":"Mama gaga bird in apron frying eggs in a pan, eggs sizzling with cute gaga sound effect bubbles, warm kitchen",                                                      "motion":"pan_right",       "speed":"normal","duration":1.0, "sfx":["sizzling eggs"],            "bgm":"ukulele strum",                      "sub":"",                       "tags":["厨房","嘎嘎","煎蛋"]},
    {"id":6,  "title":"阳光洒在doro肚皮",            "characters":["doro"],      "location":"doro卧室",            "time":"morning",   "scene_type":"portrait",     "image":"Sunlight through lace curtain falling on round yellow doro belly, dust particles floating, dreamy cozy morning",                                                      "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":["soft wind"],                "bgm":"ukulele strum",                      "sub":"",                       "tags":["特写","doro","阳光"]},
    {"id":7,  "title":"doro滚下床",                  "characters":["doro"],      "location":"doro卧室",            "time":"morning",   "scene_type":"action",       "image":"Round doro bird rolling off bed with a poof sound, landing in pile of plush toys, surprised comic face",                                                            "motion":"static",          "speed":"normal","duration":1.0, "sfx":["poof","toy squeak"],        "bgm":"ukulele strum",                      "sub":"",                       "tags":["动作","doro","搞笑"]},
    {"id":8,  "title":"白子姐姐轻嘘",                "characters":["baizi"],     "location":"doro卧室",            "time":"morning",   "scene_type":"portrait",     "image":"White spirit girl baizi peeking from toy pile, putting finger to lips with a gentle shhh gesture, soft glow",                                                          "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":["shhh"],                     "bgm":"ukulele strum",                      "sub":"嘘～",                   "tags":["特写","白子","安静"]},
    {"id":9,  "title":"菲比啾比揉眼",                "characters":["feibi-jiubi"],"location":"婴儿房",              "time":"morning",   "scene_type":"portrait",     "image":"Tiny purple-blue baby bird feibi-jiubi rubbing eyes in crib, yawning, hugging plush toy, milk-bottle nearby",                                                            "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":["baby yawn"],               "bgm":"music box melody",                    "sub":"",                       "tags":["特写","菲比啾比","婴儿"]},
    {"id":10, "title":"啾比奶声叫妈妈",              "characters":["feibi-jiubi","gaga"],"location":"婴儿房",       "time":"morning",   "scene_type":"dialogue",      "image":"Feibi-jiubi looking up with sparkling eyes calling mama, gaga leaning in from doorway with wooden spoon",                                                              "motion":"static",          "speed":"normal","duration":1.0, "sfx":[],                          "bgm":"music box melody",                    "sub":"啾……啾比？",            "tags":["对白","啾比","嘎嘎"]},
    {"id":11, "title":"嘎嘎喊孩子们吃早餐",          "characters":["gaga"],      "location":"楼梯口",              "time":"morning",   "scene_type":"dialogue",      "image":"Mama gaga bird standing at staircase calling children for breakfast, warm light pouring behind her, gentle smile",                                                          "motion":"static",          "speed":"normal","duration":1.0, "sfx":[],                          "bgm":"cheerful strum",                      "sub":"孩子们，下来吃早餐啦～", "tags":["对白","嘎嘎","召唤"]},
    {"id":12, "title":"doro蹦跳下楼",                "characters":["doro"],      "location":"楼梯",                "time":"morning",   "scene_type":"action",       "image":"Round doro bouncing down wooden staircase, each step with a doro sound effect, energetic and joyful",                                                                  "motion":"tracking_down",    "speed":"fast",  "duration":1.0, "sfx":["boing boing"],             "bgm":"cheerful strum",                      "sub":"doro！doro！",           "tags":["动作","doro","楼梯"]},
    {"id":13, "title":"白子牵着啾比下楼",            "characters":["baizi","feibi-jiubi"],"location":"楼梯",       "time":"morning",   "scene_type":"action",       "image":"White baizi carefully holding tiny purple-jiubi's wing, walking down step by step gently, sisterly love",                                                              "motion":"tracking_down",    "speed":"slow",  "duration":1.0, "sfx":["soft footsteps"],          "bgm":"cheerful strum",                      "sub":"",                       "tags":["动作","白子","啾比"]},
    {"id":14, "title":"餐厅长桌",                    "characters":[],            "location":"餐厅",                "time":"morning",   "scene_type":"establishing", "image":"Long family dining table with checkered cloth and five high chairs neatly arranged, soft morning light, breakfast set",                                                  "motion":"pan_right",       "speed":"slow",  "duration":1.0, "sfx":["ambient room"],            "bgm":"cheerful strum",                      "sub":"",                       "tags":["全景","餐厅","早餐"]},
    {"id":15, "title":"咕咕翻家庭相册",              "characters":["gugu"],      "location":"餐厅",                "time":"morning",   "scene_type":"portrait",     "image":"Papa gugu opening family photo album, cover says our family, warm nostalgic look, family photos visible",                                                              "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":["page turning"],            "bgm":"soft piano",                          "sub":"我们的家",               "tags":["特写","咕咕","相册"]},
    {"id":16, "title":"早餐美食特写",                "characters":[],            "location":"餐桌",                "time":"morning",   "scene_type":"montage",      "image":"Close-up montage of breakfast: fried egg, honey toast, corn soup, strawberry platter, steam rising, food illustration style",                                            "motion":"zoom_in",          "speed":"slow",  "duration":1.0, "sfx":["sizzle","pour"],           "bgm":"soft piano",                          "sub":"",                       "tags":["美食","特写","早餐"]},
    {"id":17, "title":"doro偷草莓被拦",              "characters":["doro","gaga"],"location":"餐桌",                  "time":"morning",   "scene_type":"action",       "image":"Doro reaching sneaky wing toward strawberry, mama gaga tapping wing with wooden spoon, classic family scene, comedic",                                                  "motion":"static",          "speed":"normal","duration":1.0, "sfx":["slap"],                    "bgm":"soft piano",                          "sub":"",                       "tags":["搞笑","doro","嘎嘎"]},
    {"id":18, "title":"doro啾比装委屈",              "characters":["doro","feibi-jiubi"],"location":"餐桌",       "time":"morning",   "scene_type":"action",       "image":"Doro and feibi-jiubi both making fake sad face, then eye-contact and bursting into laughter, sibling chemistry",                                                              "motion":"static",          "speed":"normal","duration":1.0, "sfx":["giggle"],                  "bgm":"soft piano",                          "sub":"",                       "tags":["搞笑","doro","啾比"]},
    {"id":19, "title":"白子分草莓给弟弟",            "characters":["baizi","feibi-jiubi"],"location":"餐桌",       "time":"morning",   "scene_type":"dialogue",      "image":"White baizi placing strawberry on feibi-jiubi's plate with gentle smile, sisterly love, warm light",                                                                    "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":[],                          "bgm":"soft piano",                          "sub":"吃吧，啾比。",           "tags":["温馨","白子","啾比"]},
    {"id":20, "title":"全家合影开动",                "characters":["gugu","gaga","doro","baizi","feibi-jiubi"],"location":"餐桌","time":"morning","scene_type":"dialogue","image":"Whole family of five birds at dining table raising wings together, big smiles, photo freeze moment, family togetherness",                                       "motion":"static",          "speed":"normal","duration":1.0, "sfx":["camera shutter"],          "bgm":"cheerful finish",                     "sub":"谢谢招待——开动啦！",   "tags":["合影","全家","开动"]},

    # ===== 第二幕：上学路上 (21-40) =====
    {"id":21, "title":"咕咕整理书包带",              "characters":["gugu"],      "location":"玄关",                "time":"morning",   "scene_type":"portrait",     "image":"Papa gugu kneeling tying each child's schoolbag strap carefully, loving gaze",                                                                                              "motion":"static",          "speed":"normal","duration":1.0, "sfx":["zipper"],                  "bgm":"playful tune",                        "sub":"",                       "tags":["咕咕","父爱","准备"]},
    {"id":22, "title":"嘎嘎别上橘子挂饰",            "characters":["gaga","doro"],"location":"玄关",                  "time":"morning",   "scene_type":"dialogue",      "image":"Mama gaga pinning a tiny orange charm on doro's schoolbag, doro looking down with curious eyes",                                                                              "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":[],                          "bgm":"playful tune",                        "sub":"路上小心。",             "tags":["嘎嘎","doro","挂饰"]},
    {"id":23, "title":"白子啾比戴帽子围巾",          "characters":["baizi","feibi-jiubi"],"location":"玄关",       "time":"morning",   "scene_type":"portrait",     "image":"Baizi putting on white beret, feibi-jiubi wearing tiny blue scarf, adorable kids dressing up",                                                                                "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":["cloth rustle"],            "bgm":"playful tune",                        "sub":"",                       "tags":["白子","啾比","穿搭"]},
    {"id":24, "title":"手拉手走在樱花路",            "characters":["gugu","gaga","doro","baizi","feibi-jiubi"],"location":"樱花路","time":"morning","scene_type":"action","image":"Family of five walking hand-in-wing along sakura petal road, petals falling, golden hour morning light",                                                          "motion":"tracking",          "speed":"slow",  "duration":1.0, "sfx":["footsteps","wind"],        "bgm":"playful tune",                        "sub":"",                       "tags":["全家","樱花","上学路"]},
    {"id":25, "title":"doro盯奶油卷",                "characters":["doro"],      "location":"面包店橱窗",          "time":"morning",   "scene_type":"portrait",     "image":"Doro staring at cream roll in bakery window with sparkling hungry eyes, mouth watering, comedic still",                                                                       "motion":"zoom_in",          "speed":"slow",  "duration":1.0, "sfx":["stomach growl"],           "bgm":"playful tune",                        "sub":"",                       "tags":["doro","美食","搞笑"]},
    {"id":26, "title":"咕咕劝doro",                  "characters":["gugu","doro"],"location":"面包店前",            "time":"morning",   "scene_type":"dialogue",      "image":"Papa gugu kneeling eye-level with doro, promising after-school family time, doro's eyes lightening up",                                                                       "motion":"static",          "speed":"normal","duration":1.0, "sfx":[],                          "bgm":"playful tune",                        "sub":"放学后的亲子时间哦。",   "tags":["对话","咕咕","doro"]},
    {"id":27, "title":"doro乖乖点头",                "characters":["doro"],      "location":"面包店前",            "time":"morning",   "scene_type":"portrait",     "image":"Doro nodding obediently with bright eyes, little determined face, ready to walk on",                                                                                          "motion":"static",          "speed":"normal","duration":1.0, "sfx":["nod"],                     "bgm":"playful tune",                        "sub":"",                       "tags":["doro","成长"]},
    {"id":28, "title":"小溪边白子遇青蛙",            "characters":["baizi"],     "location":"小溪边",              "time":"morning",   "scene_type":"action",       "image":"Baizi discovering a small frog by creek, frog croaking and jumping into water, splash effect",                                                                                 "motion":"static",          "speed":"normal","duration":1.0, "sfx":["frog croak","splash"],     "bgm":"playful tune",                        "sub":"",                       "tags":["白子","青蛙","自然"]},
    {"id":29, "title":"啾比拍手笑",                  "characters":["feibi-jiubi"],"location":"小溪边",                "time":"morning",   "scene_type":"action",       "image":"Feibi-jiubi clapping tiny wings laughing at frog jumping, baby joy expression",                                                                                                "motion":"static",          "speed":"normal","duration":1.0, "sfx":["baby clap","giggle"],     "bgm":"playful tune",                        "sub":"啾比！啾比！",           "tags":["啾比","可爱"]},
    {"id":30, "title":"云朵校车驶来",                "characters":[],            "location":"校车站",              "time":"morning",   "scene_type":"establishing", "image":"Cloud-shaped vintage school bus driving in with jingling bell, dreamy sky background, fairy-tale transport",                                                              "motion":"pan_left",         "speed":"normal","duration":1.0, "sfx":["bell jingle","engine"],    "bgm":"playful tune",                        "sub":"",                       "tags":["校车","云朵","建立"]},
    {"id":31, "title":"鸽子司机挥手",                "characters":[],            "location":"校车驾驶位",          "time":"morning",   "scene_type":"portrait",     "image":"Cool pigeon driver with sunglasses waving at children, hip and friendly mascot",                                                                                                 "motion":"static",          "speed":"normal","duration":1.0, "sfx":["wave"],                    "bgm":"playful tune",                        "sub":"",                       "tags":["司机","校车"]},
    {"id":32, "title":"doro抢到前排",                "characters":["doro"],      "location":"校车内",              "time":"morning",   "scene_type":"action",       "image":"Doro rushing to front seat of school bus, arms in victory pose, claiming front row",                                                                                            "motion":"tracking",         "speed":"fast",  "duration":1.0, "sfx":["victory cheer"],           "bgm":"playful tune",                        "sub":"doro抢到前排啦！",       "tags":["doro","校车","抢座"]},
    {"id":33, "title":"白子帮啾比系安全带",          "characters":["baizi","feibi-jiubi"],"location":"校车内",       "time":"morning",   "scene_type":"action",       "image":"Baizi carefully buckling feibi-jiubi's seatbelt, baby bird sitting properly and obediently",                                                                                    "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":["seatbelt click"],         "bgm":"playful tune",                        "sub":"",                       "tags":["白子","啾比","安全"]},
    {"id":34, "title":"校车启动合唱",                "characters":["doro","baizi","feibi-jiubi"],"location":"校车内",  "time":"morning",   "scene_type":"action",       "image":"Children singing together in moving school bus, view from window shows scenery passing, joyful choir moment",                                                              "motion":"static",          "speed":"normal","duration":1.0, "sfx":["children singing"],        "bgm":"children choir",                      "sub":"",                       "tags":["校车","合唱"]},
    {"id":35, "title":"咕咕嘎嘎挥手告别",            "characters":["gugu","gaga"],"location":"校车站路口",            "time":"morning",   "scene_type":"action",       "image":"Papa and mama gugu waving at school bus from intersection, bus disappearing in distance, loving farewell",                                                                   "motion":"zoom_out",         "speed":"slow",  "duration":1.0, "sfx":["wave","bus fading"],       "bgm":"soft piano",                          "sub":"",                       "tags":["告别","咕咕","嘎嘎"]},
    {"id":36, "title":"父母对视感慨",                "characters":["gugu","gaga"],"location":"校车站路口",            "time":"morning",   "scene_type":"dialogue",      "image":"Gugu and gaga looking at each other with nostalgic smile, time-flies feeling",                                                                                                  "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":[],                          "bgm":"soft piano",                          "sub":"时间过得真快。",         "tags":["对话","父母","感慨"]},
    {"id":37, "title":"牵手去菜市场",                "characters":["gugu","gaga"],"location":"小镇街道",              "time":"morning",   "scene_type":"action",       "image":"Gugu and gaga walking arm-in-wing toward market, planning shopping, cheerful couple moment",                                                                                  "motion":"tracking",         "speed":"normal","duration":1.0, "sfx":["footsteps"],               "bgm":"soft piano",                          "sub":"走，给孩子们加菜。",     "tags":["父母","菜市场"]},
    {"id":38, "title":"菜市场全景",                  "characters":[],            "location":"菜市场",              "time":"morning",   "scene_type":"establishing", "image":"Colorful vegetable and fruit market with piles of fresh produce, morning bustle, family market vibe",                                                                          "motion":"pan_right",       "speed":"slow",  "duration":1.0, "sfx":["market chatter"],          "bgm":"folk tune",                          "sub":"",                       "tags":["菜市场","全景"]},
    {"id":39, "title":"咕咕讨价还价",                "characters":["gugu"],      "location":"菜摊",                "time":"morning",   "scene_type":"action",       "image":"Papa gugu haggling with vegetable vendor, animated wing gestures, comedic bargaining scene",                                                                                  "motion":"static",          "speed":"normal","duration":1.0, "sfx":["bargain chatter"],         "bgm":"folk tune",                           "sub":"",                       "tags":["咕咕","搞笑"]},
    {"id":40, "title":"嘎嘎拎战利品",                "characters":["gaga"],      "location":"菜市场出口",          "time":"morning",   "scene_type":"portrait",     "image":"Mama gaga holding shopping bags with three small fish and a bag of cherries, triumphant smile, ready to go home",                                                          "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":["bag rustle"],              "bgm":"folk tune",                           "sub":"",                       "tags":["嘎嘎","收获"]},

    # ===== 第三幕：校园日常 (41-60) =====
    {"id":41, "title":"教室门口木牌",                "characters":[],            "location":"教室门口",            "time":"noon",      "scene_type":"establishing", "image":"Wooden sign at classroom door reading today we learn to share, cozy school entrance",                                                                                          "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":[],                          "bgm":"school bell ring",                    "sub":"今天我们学分享",         "tags":["学校","教室","分享"]},
    {"id":42, "title":"猫头鹰老师上课",              "characters":[],            "location":"教室",                "time":"noon",      "scene_type":"portrait",     "image":"Owl teacher with glasses standing at blackboard beginning lesson, wise and friendly look",                                                                                       "motion":"static",          "speed":"normal","duration":1.0, "sfx":["chalk writing"],           "bgm":"school melody",                       "sub":"",                       "tags":["老师","猫头鹰"]},
    {"id":43, "title":"doro举手积极",                "characters":["doro"],      "location":"教室座位",            "time":"noon",      "scene_type":"action",       "image":"Doro's wing raised high, almost jumping out of chair with eagerness, comic energy",                                                                                              "motion":"static",          "speed":"normal","duration":1.0, "sfx":["hand raise"],              "bgm":"school melody",                       "sub":"",                       "tags":["doro","学校"]},
    {"id":44, "title":"白子认真做笔记",              "characters":["baizi"],     "location":"教室座位",            "time":"noon",      "scene_type":"portrait",     "image":"Baizi quietly taking notes, handwriting neat like flower petals, focused expression",                                                                                          "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":["pen writing"],             "bgm":"school melody",                       "sub":"",                       "tags":["白子","学习"]},
    {"id":45, "title":"啾比堆城堡",                  "characters":["feibi-jiubi"],"location":"教室角落",              "time":"noon",      "scene_type":"action",       "image":"Feibi-jiubi building a small castle with blocks in classroom corner, deep in concentration, baby cuteness",                                                                  "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":["block stacking"],         "bgm":"school melody",                       "sub":"",                       "tags":["啾比","玩"]},
    {"id":46, "title":"doro和小狐狸赛跑",            "characters":["doro"],      "location":"操场",                "time":"noon",      "scene_type":"action",       "image":"Doro racing with fox classmate around the playground, three laps, energetic motion lines",                                                                                      "motion":"tracking",         "speed":"fast",  "duration":1.0, "sfx":["running footsteps"],       "bgm":"energetic beat",                      "sub":"",                       "tags":["doro","运动"]},
    {"id":47, "title":"doro输了趴地",                "characters":["doro"],      "location":"操场",                "time":"noon",      "scene_type":"portrait",     "image":"Doro lying on ground panting after losing race, stubborn expression saying next time for sure",                                                                                  "motion":"static",          "speed":"normal","duration":1.0, "sfx":["panting"],                 "bgm":"energetic beat",                      "sub":"下次……下次一定……",     "tags":["doro","失败"]},
    {"id":48, "title":"白子递水壶",                  "characters":["baizi","doro"],"location":"操场",                  "time":"noon",      "scene_type":"dialogue",      "image":"Baizi handing water bottle to doro, doro's eyes welling with grateful tears, sisterly moment",                                                                                  "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":["water pouring"],           "bgm":"soft piano",                          "sub":"",                       "tags":["温馨","兄妹"]},
    {"id":49, "title":"草地野餐",                    "characters":["gaga","doro","baizi","feibi-jiubi"],"location":"校园草地","time":"noon","scene_type":"establishing","image":"Family picnic on school grass, checkered cloth, five birds sitting in circle, lunch boxes open",                                                                       "motion":"pan_right",       "speed":"slow",  "duration":1.0, "sfx":["wind","birds"],            "bgm":"soft piano",                          "sub":"",                       "tags":["野餐","校园"]},
    {"id":50, "title":"便当盒打开",                  "characters":[],            "location":"草地",                "time":"noon",      "scene_type":"montage",      "image":"Lunch box opening reveal: smiley rice balls, heart-shaped fried egg, food-art close-up, cute bento",                                                                       "motion":"zoom_in",          "speed":"slow",  "duration":1.0, "sfx":["box open"],               "bgm":"soft piano",                          "sub":"",                       "tags":["美食","便当"]},
    {"id":51, "title":"doro抢最大饭团",              "characters":["doro","baizi"],"location":"草地",                  "time":"noon",      "scene_type":"action",       "image":"Doro grabbing the largest rice ball, baizi gently tapping doro's head, classic sibling moment",                                                                                  "motion":"static",          "speed":"normal","duration":1.0, "sfx":["tap"],                     "bgm":"soft piano",                          "sub":"",                       "tags":["doro","搞笑"]},
    {"id":52, "title":"啾比饭粒粘鼻尖",              "characters":["feibi-jiubi"],"location":"草地",                  "time":"noon",      "scene_type":"portrait",     "image":"Feibi-jiubi with rice grain stuck on nose tip, confused adorable face, family laughing in background",                                                                         "motion":"static",          "speed":"normal","duration":1.0, "sfx":["giggle"],                  "bgm":"soft piano",                          "sub":"",                       "tags":["啾比","可爱"]},
    {"id":53, "title":"蝴蝶停在指尖",                "characters":["feibi-jiubi"],"location":"草地",                  "time":"noon",      "scene_type":"portrait",     "image":"A small butterfly landing on feibi-jiubi's tiny finger, baby bird holding breath, magical close-up moment",                                                                   "motion":"zoom_in",          "speed":"slow",  "duration":1.0, "sfx":["wing flutter"],           "bgm":"magical chime",                       "sub":"",                       "tags":["啾比","蝴蝶","梦"]},
    {"id":54, "title":"啾比说再见",                  "characters":["feibi-jiubi"],"location":"草地",                  "time":"noon",      "scene_type":"dialogue",      "image":"Feibi-jiubi watching butterfly fly away, whispering goodbye with gentle smile, emotional growth moment",                                                                     "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":[],                          "bgm":"magical chime",                       "sub":"再见。",                 "tags":["啾比","成长"]},
    {"id":55, "title":"doro冲出教室",                "characters":["doro"],      "location":"教室门口",            "time":"noon",      "scene_type":"action",       "image":"Doro bursting out of classroom at school bell, arms wide, yelling freedom, energetic exit",                                                                                     "motion":"tracking",         "speed":"fast",  "duration":1.0, "sfx":["bell ring","cheer"],      "bgm":"energetic beat",                      "sub":"自由啦——doro！",         "tags":["doro","放学"]},
    {"id":56, "title":"白子收拾文具",                "characters":["baizi"],     "location":"教室",                "time":"noon",      "scene_type":"portrait",     "image":"Baizi carefully organizing all stationery, even helping classmates, neat and responsible big sister",                                                                        "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":["stationery click"],       "bgm":"soft piano",                          "sub":"",                       "tags":["白子","懂事"]},
    {"id":57, "title":"父母校门口等候",              "characters":["gugu","gaga"],"location":"校门口",                "time":"afternoon", "scene_type":"portrait",     "image":"Gugu and gaga waiting at school gate with hot tea, smiling and waving at children coming out",                                                                                  "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":["tea steam"],              "bgm":"soft piano",                          "sub":"",                       "tags":["父母","接娃"]},
    {"id":58, "title":"咕咕张开翅膀抱孩子",          "characters":["gugu","doro","baizi","feibi-jiubi"],"location":"校门口","time":"afternoon","scene_type":"action","image":"Papa gugu spreading big wings hugging all three children at once, warm family huddle",                                                                              "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":["hug"],                     "bgm":"emotional piano",                      "sub":"",                       "tags":["拥抱","父爱"]},
    {"id":59, "title":"嘎嘎按快门",                  "characters":["gaga","gugu","doro","baizi","feibi-jiubi"],"location":"校门口","time":"afternoon","scene_type":"action","image":"Mama gaga pressing camera shutter, family of five posing together, instant photo developing animation",                                                              "motion":"static",          "speed":"normal","duration":1.0, "sfx":["shutter click"],          "bgm":"emotional piano",                      "sub":"",                       "tags":["合影","温馨"]},
    {"id":60, "title":"夕阳回家路",                  "characters":["gugu","gaga","doro","baizi","feibi-jiubi"],"location":"回家路","time":"afternoon","scene_type":"establishing","image":"Family walking home under sunset, five long shadows stretching on road, golden warm light, peaceful ending of day",                                                  "motion":"tracking_back",     "speed":"slow",  "duration":1.0, "sfx":["footsteps","wind"],        "bgm":"warm guitar",                         "sub":"",                       "tags":["夕阳","回家"]},

    # ===== 第四幕：家庭游戏 (61-80) =====
    {"id":61, "title":"客厅玩具全景",                "characters":[],            "location":"客厅",                "time":"evening",   "scene_type":"establishing", "image":"Living room carpet covered with blocks, puzzles and plush toys, warm evening light, game night setup",                                                                          "motion":"pan_right",       "speed":"slow",  "duration":1.0, "sfx":[],                          "bgm":"playful tune",                        "sub":"",                       "tags":["客厅","游戏"]},
    {"id":62, "title":"咕咕宣布游戏夜",              "characters":["gugu"],      "location":"客厅",                "time":"evening",   "scene_type":"dialogue",      "image":"Papa gugu announcing family game night, loser does the dishes, excited announcement pose",                                                                                         "motion":"static",          "speed":"normal","duration":1.0, "sfx":[],                          "bgm":"playful tune",                        "sub":"输的人洗碗！",           "tags":["对话","咕咕","游戏"]},
    {"id":63, "title":"doro自信满满",                "characters":["doro"],      "location":"客厅",                "time":"evening",   "scene_type":"portrait",     "image":"Doro confident jumping with chest puffed, claiming he is the best at games",                                                                                                  "motion":"static",          "speed":"normal","duration":1.0, "sfx":["boast"],                  "bgm":"playful tune",                        "sub":"doro最会玩游戏！",       "tags":["doro","自信"]},
    {"id":64, "title":"猜猜我是谁开始",              "characters":["gugu","gaga","doro","baizi","feibi-jiubi"],"location":"客厅","time":"evening","scene_type":"action","image":"Family sitting in circle, white board ready for pictionary game, excited faces",                                                                                                "motion":"static",          "speed":"normal","duration":1.0, "sfx":["drum roll"],              "bgm":"playful tune",                        "sub":"猜猜我是谁",             "tags":["游戏","全家"]},
    {"id":65, "title":"白子画doro",                  "characters":["baizi"],     "location":"客厅",                "time":"evening",   "scene_type":"action",       "image":"Baizi drawing a round yellow bird on whiteboard, everyone immediately guesses doro",                                                                                              "motion":"static",          "speed":"normal","duration":1.0, "sfx":["chalk scribble"],          "bgm":"playful tune",                        "sub":"是doro！",               "tags":["白子","画画"]},
    {"id":66, "title":"doro画神秘物体",              "characters":["doro"],      "location":"客厅",                "time":"evening",   "scene_type":"action",       "image":"Doro drawing a mysterious blob on whiteboard, family tilting heads in confusion, comedic guessing moment",                                                                    "motion":"static",          "speed":"normal","duration":1.0, "sfx":["chalk scribble"],          "bgm":"playful tune",                        "sub":"",                       "tags":["doro","搞笑"]},
    {"id":67, "title":"啾比意外答对",                "characters":["feibi-jiubi"],"location":"客厅",                  "time":"evening",   "scene_type":"dialogue",      "image":"Feibi-jiubi answering cake in baby voice, accidentally correct, everyone surprised and happy",                                                                                  "motion":"static",          "speed":"normal","duration":1.0, "sfx":["correct bell"],          "bgm":"playful tune",                        "sub":"是……蛋糕？",             "tags":["啾比","可爱"]},
    {"id":68, "title":"父母抛高啾比",                "characters":["gugu","gaga","feibi-jiubi"],"location":"客厅",     "time":"evening",   "scene_type":"action",       "image":"Gugu and gaga high-fiving and tossing feibi-jiubi gently in the air, baby laughing with joy, family celebration",                                                          "motion":"static",          "speed":"normal","duration":1.0, "sfx":["baby laugh","high five"], "bgm":"celebrate chime",                      "sub":"",                       "tags":["庆祝","啾比"]},
    {"id":69, "title":"家庭大冒险棋",                "characters":[],            "location":"客厅地板",            "time":"evening",   "scene_type":"establishing", "image":"Giant life-size board game spread on living room floor, colored squares visible, dice in center",                                                                              "motion":"pan_right",       "speed":"slow",  "duration":1.0, "sfx":[],                          "bgm":"playful tune",                        "sub":"",                       "tags":["棋盘","游戏"]},
    {"id":70, "title":"骰子滚到厨房",                "characters":["feibi-jiubi"],"location":"客厅",                  "time":"evening",   "scene_type":"action",       "image":"Feibi-jiubi throwing dice that rolls into kitchen, whole family running after it in line, comedic chase",                                                                      "motion":"tracking",         "speed":"fast",  "duration":1.0, "sfx":["dice roll","running"],     "bgm":"playful tune",                        "sub":"",                       "tags":["搞笑","啾比"]},
    {"id":71, "title":"doro抢先捡骰子",              "characters":["doro"],      "location":"厨房门口",            "time":"evening",   "scene_type":"action",       "image":"Doro rushing to pick up the dice, victoriously holding it up, claiming 6 steps",                                                                                                  "motion":"static",          "speed":"normal","duration":1.0, "sfx":["victory"],                "bgm":"playful tune",                        "sub":"doro走6步！",            "tags":["doro","搞笑"]},
    {"id":72, "title":"白子帮爸爸捶背",              "characters":["baizi","gugu"],"location":"客厅",                  "time":"evening",   "scene_type":"action",       "image":"Baizi landing on massage-back square, seriously massaging papa gugu's wings, papa moved to tears",                                                                              "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":["tap tap"],                "bgm":"soft piano",                          "sub":"",                       "tags":["温馨","白子"]},
    {"id":73, "title":"咕咕感动胡子抖",              "characters":["gugu"],      "location":"客厅",                "time":"evening",   "scene_type":"portrait",     "image":"Papa gugu's mustache quivering with emotion, big fatherly tears, calling baizi dear daughter",                                                                                  "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":[],                          "bgm":"soft piano",                          "sub":"乖女儿……",              "tags":["父女","感动"]},
    {"id":74, "title":"嘎嘎亲亲妈妈格",              "characters":["gaga","doro","baizi","feibi-jiubi"],"location":"客厅","time":"evening","scene_type":"action","image":"Mama gaga landing on kiss-mama square, kissing each child's forehead one by one, group hug moment",                                                                            "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":["kiss sound"],             "bgm":"soft piano",                          "sub":"",                       "tags":["母爱","温馨"]},
    {"id":75, "title":"doro再掷一次",                "characters":["doro"],      "location":"客厅",                "time":"evening",   "scene_type":"action",       "image":"Doro landing on roll-again square, ecstatic doing somersault, joyful flips",                                                                                                  "motion":"static",          "speed":"fast",  "duration":1.0, "sfx":["cheer"],                  "bgm":"playful tune",                        "sub":"",                       "tags":["doro","庆祝"]},
    {"id":76, "title":"夜幕萤火虫",                  "characters":[],            "location":"窗边",                "time":"evening",   "scene_type":"establishing", "image":"Fireflies starting to glow outside window, night falling, magical twilight transition",                                                                                          "motion":"pan_left",        "speed":"slow",  "duration":1.0, "sfx":["crickets","fireflies"],   "bgm":"night ambient",                       "sub":"",                       "tags":["夜景","萤火虫"]},
    {"id":77, "title":"星星灯点亮",                  "characters":["gugu"],      "location":"客厅",                "time":"evening",   "scene_type":"action",       "image":"Papa gugu turning off main light, switching on star-shaped lamp, room turning warm orange, magical cozy atmosphere",                                                          "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":["light switch click"],      "bgm":"night ambient",                       "sub":"",                       "tags":["灯光","咕咕"]},
    {"id":78, "title":"全家围坐沙发",                "characters":["gugu","gaga","doro","baizi","feibi-jiubi"],"location":"客厅","time":"evening","scene_type":"portrait","image":"Family cuddled on big sofa under checkered blanket, ready for story time, warm starry lamp light",                                                                                "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":["blanket rustle"],          "bgm":"night ambient",                       "sub":"",                       "tags":["全家","温馨"]},
    {"id":79, "title":"嘎嘎拿故事书",                "characters":["gaga"],      "location":"客厅",                "time":"evening",   "scene_type":"portrait",     "image":"Mama gaga picking up the legend of gugu gaga story book, book cover visible, children gathering around",                                                                   "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":["book open"],              "bgm":"night ambient",                       "sub":"",                       "tags":["嘎嘎","故事"]},
    {"id":80, "title":"孩子们期待听故事",            "characters":["doro","baizi","feibi-jiubi"],"location":"客厅",     "time":"evening",   "scene_type":"portrait",     "image":"Three children with sparkling eyes looking at mama, ready for bedtime story, anticipation in their faces",                                                                     "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":[],                          "bgm":"music box",                           "sub":"",                       "tags":["期待","孩子"]},

    # ===== 第五幕：睡前故事 (81-100) =====
    {"id":81, "title":"故事开始旁白",                "characters":["gaga"],      "location":"客厅",                "time":"night",     "scene_type":"dialogue",      "image":"Mama gaga opening story book, voice-over narration style, soft glow around the book, magical reading moment",                                                              "motion":"zoom_in",          "speed":"slow",  "duration":1.0, "sfx":["page turn"],              "bgm":"music box",                           "sub":"很久很久以前……",        "tags":["旁白","故事","嘎嘎"]},
    {"id":82, "title":"云朵森林想象",                "characters":[],            "location":"梦境·云朵森林",        "time":"dream",     "scene_type":"dream",         "image":"Imagination sequence: cloud forest in the sky, floating trees, soft white clouds as ground, fairy-tale wonderland",                                                       "motion":"pan_right",       "speed":"slow",  "duration":1.0, "sfx":["magical chime"],          "bgm":"dream orchestra",                     "sub":"",                       "tags":["想象","云朵","梦境"]},
    {"id":83, "title":"爷爷教小咕咕飞翔",            "characters":[],            "location":"梦境·云朵森林",        "time":"dream",     "scene_type":"dream",         "image":"Grandpa gugu with long beard teaching little gugu to fly, wings spread, encouraging smile",                                                                                       "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":["wind whoosh"],            "bgm":"dream orchestra",                     "sub":"",                       "tags":["祖孙","教学","梦境"]},
    {"id":84, "title":"小咕咕撞进棉花糖云",          "characters":[],            "location":"梦境·云朵森林",        "time":"dream",     "scene_type":"dream",         "image":"Little gugu flying for first time, crashing into cotton-candy cloud with a poof, funny landing pose",                                                                          "motion":"tracking",         "speed":"fast",  "duration":1.0, "sfx":["poof"],                    "bgm":"dream orchestra",                     "sub":"",                       "tags":["搞笑","飞行","梦境"]},
    {"id":85, "title":"doro笑出声",                  "characters":["doro"],      "location":"客厅",                "time":"night",     "scene_type":"portrait",     "image":"Doro laughing out loud at story, throwing head back, big belly laugh",                                                                                                          "motion":"static",          "speed":"normal","duration":1.0, "sfx":["big laugh"],              "bgm":"music box",                           "sub":"doro也撞过！",           "tags":["doro","笑"]},
    {"id":86, "title":"嘎嘎奶奶蛋糕店",              "characters":[],            "location":"梦境·云朵森林",        "time":"dream",     "scene_type":"dream",         "image":"Grandma gaga as the best pastry chef in forest, making giant cloud cake, decorations everywhere",                                                                              "motion":"pan_right",       "speed":"slow",  "duration":1.0, "sfx":["baking sizzle"],          "bgm":"dream orchestra",                     "sub":"",                       "tags":["奶奶","烘焙","梦境"]},
    {"id":87, "title":"月亮流口水",                  "characters":[],            "location":"梦境·云朵森林夜空",     "time":"dream",     "scene_type":"dream",         "image":"Moon in sky with drool dripping down at the cake aroma, funny celestial reaction, drool animation",                                                                            "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":["drool drop"],             "bgm":"dream orchestra",                     "sub":"",                       "tags":["月亮","搞笑","梦境"]},
    {"id":88, "title":"白子听得入神",                "characters":["baizi"],     "location":"客厅",                "time":"night",     "scene_type":"portrait",     "image":"Baizi listening attentively to story, hand unconsciously touching her own white feathers, dreamy gaze",                                                                     "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":[],                          "bgm":"music box",                           "sub":"",                       "tags":["白子","专注"]},
    {"id":89, "title":"家族迁徙讲述",                "characters":[],            "location":"梦境·迁徙场景",        "time":"dream",     "scene_type":"dream",         "image":"Ancestors migrating from cloud forest down to earth town, long line of bird family walking together, epic but gentle",                                                       "motion":"tracking",         "speed":"slow",  "duration":1.0, "sfx":["wind epic"],              "bgm":"epic gentle",                         "sub":"",                       "tags":["迁徙","家族","梦境"]},
    {"id":90, "title":"祖先的约定",                  "characters":[],            "location":"梦境·星空下",          "time":"dream",     "scene_type":"dream",         "image":"Ancestors making promise under starry sky, raising wings together, family oath moment",                                                                                          "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":[],                          "bgm":"emotional strings",                    "sub":"无论走多远，都要一起回家吃饭。", "tags":["约定","家族","梦境"]},
    {"id":91, "title":"嘎嘎声音变轻",                "characters":["gaga","feibi-jiubi"],"location":"客厅",          "time":"night",     "scene_type":"portrait",     "image":"Mama gaga voice getting softer, feibi-jiubi's eyelids starting to droop, sleepiness spreading",                                                                                    "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":["yawn"],                   "bgm":"music box fade",                      "sub":"",                       "tags":["睡眠","嘎嘎","啾比"]},
    {"id":92, "title":"doro打瞌睡",                  "characters":["doro"],      "location":"客厅",                "time":"night",     "scene_type":"portrait",     "image":"Doro nodding off, head bobbing up and down, fighting sleep with comic effort",                                                                                                  "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":["head bob"],               "bgm":"music box fade",                      "sub":"",                       "tags":["doro","困"]},
    {"id":93, "title":"咕咕轻声说去睡吧",            "characters":["gugu"],      "location":"客厅",                "time":"night",     "scene_type":"dialogue",      "image":"Papa gugu gently saying children go sleep first, soft voice, loving look",                                                                                                       "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":[],                          "bgm":"music box fade",                      "sub":"孩子们，先去睡吧。",     "tags":["对话","咕咕","温柔"]},
    {"id":94, "title":"白子帮弟弟脱鞋",              "characters":["baizi","feibi-jiubi"],"location":"卧室",         "time":"night",     "scene_type":"action",       "image":"Baizi helping feibi-jiubi take off small shoes, placing them neatly beside bed, sisterly bedtime routine",                                                                  "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":["shoe drop"],              "bgm":"music box fade",                      "sub":"",                       "tags":["白子","啾比","睡前"]},
    {"id":95, "title":"嘎嘎掖被角亲额头",            "characters":["gaga","doro","baizi","feibi-jiubi"],"location":"卧室","time":"night","scene_type":"action","image":"Mama gaga tucking in each child and kissing foreheads three times, ritual of love, soft warm light",                                                                       "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":["kiss"],                   "bgm":"music box fade",                      "sub":"",                       "tags":["母爱","温馨"]},
    {"id":96, "title":"咕咕关灯留小夜灯",            "characters":["gugu"],      "location":"卧室",                "time":"night",     "scene_type":"action",       "image":"Papa gugu turning off main light, keeping small night light on, careful not to wake children",                                                                                  "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":["light click"],            "bgm":"silence",                             "sub":"",                       "tags":["咕咕","夜灯"]},
    {"id":97, "title":"三张小床半圆",                "characters":["doro","baizi","feibi-jiubi"],"location":"卧室",   "time":"night",     "scene_type":"portrait",     "image":"Three small beds arranged in semicircle, family album in center, children peacefully sleeping, soft night light glow",                                                       "motion":"pan_right",       "speed":"slow",  "duration":1.0, "sfx":["breathing"],              "bgm":"silence",                             "sub":"",                       "tags":["睡眠","孩子"]},
    {"id":98, "title":"doro梦中笑",                  "characters":["doro"],      "location":"梦境",                "time":"dream",     "scene_type":"dream",         "image":"Doro laughing in sleep, dreaming about strawberry cake, sleep-smile close-up",                                                                                                  "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":["sleep laugh"],            "bgm":"dream soft",                          "sub":"嘿嘿……草莓蛋糕……",     "tags":["doro","梦"]},
    {"id":99, "title":"啾比抱玩偶",                  "characters":["feibi-jiubi"],"location":"梦境",                  "time":"dream",     "scene_type":"dream",         "image":"Feibi-jiubi hugging plush toy, murmuring gugu gaga in sleep, baby dream talk",                                                                                                  "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":["murmur"],                 "bgm":"dream soft",                          "sub":"咕……嘎……",              "tags":["啾比","梦"]},
    {"id":100,"title":"白子闭眼微笑",                "characters":["baizi"],     "location":"梦境",                "time":"dream",     "scene_type":"dream",         "image":"Baizi closing eyes with gentle smile, eyelashes like crescents, peaceful sleep",                                                                                                  "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":[],                          "bgm":"dream soft",                          "sub":"",                       "tags":["白子","睡"]},

    # ===== 第六幕：夜之温柔 (101-120) =====
    {"id":101,"title":"镜头拉远卧室窗",              "characters":[],            "location":"卧室窗外",            "time":"night",     "scene_type":"establishing", "image":"Camera slowly pulling back from bedroom window, moon and stars in sky, peaceful house exterior",                                                                          "motion":"zoom_out",         "speed":"slow",  "duration":1.0, "sfx":["night ambient"],          "bgm":"dream soft",                          "sub":"",                       "tags":["拉远","夜景"]},
    {"id":102,"title":"父母收拾玩具",                "characters":["gugu","gaga"],"location":"客厅",                  "time":"night",     "scene_type":"action",       "image":"Gugu and gaga tidying up toys in living room, working together silently in moonlight",                                                                                            "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":["toy clink"],              "bgm":"dream soft",                          "sub":"",                       "tags":["父母","收拾"]},
    {"id":103,"title":"默契配合舞蹈",                "characters":["gugu","gaga"],"location":"客厅",                  "time":"night",     "scene_type":"action",       "image":"Gugu and gaga passing toys hand-to-wing in dance-like rhythm, perfect couple sync",                                                                                              "motion":"pan_left",         "speed":"slow",  "duration":1.0, "sfx":[],                          "bgm":"dream soft",                          "sub":"",                       "tags":["默契","父母"]},
    {"id":104,"title":"嘎嘎看合照",                  "characters":["gaga"],      "location":"客厅",                "time":"night",     "scene_type":"portrait",     "image":"Mama gaga stops to look at today's family photo for a long time, emotional mother moment, gentle smile",                                                                          "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":[],                          "bgm":"emotional piano",                      "sub":"",                       "tags":["嘎嘎","照片","感慨"]},
    {"id":105,"title":"咕咕背后环抱",                "characters":["gugu","gaga"],"location":"客厅",                  "time":"night",     "scene_type":"dialogue",      "image":"Papa gugu gently hugging gaga from behind, asking what she's thinking, intimate moment",                                                                                          "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":[],                          "bgm":"emotional piano",                      "sub":"在想什么？",             "tags":["对话","父母","爱情"]},
    {"id":106,"title":"嘎嘎感慨长大",                "characters":["gaga"],      "location":"客厅",                "time":"night",     "scene_type":"dialogue",      "image":"Mama gaga saying will they remember today when they grow up, emotional mother worry, soft lighting",                                                                            "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":[],                          "bgm":"emotional piano",                      "sub":"以后他们长大了，会不会记得今天？", "tags":["对话","嘎嘎","母爱"]},
    {"id":107,"title":"咕咕温柔回答",                "characters":["gugu"],      "location":"客厅",                "time":"night",     "scene_type":"dialogue",      "image":"Papa gugu answering yes they will, because we will always be like this, loving gaze at gaga",                                                                                    "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":[],                          "bgm":"emotional piano",                      "sub":"会的，因为我们会一直这样。", "tags":["对话","咕咕","承诺"]},
    {"id":108,"title":"望向月亮",                    "characters":["gugu","gaga"],"location":"客厅窗边",              "time":"night",     "scene_type":"portrait",     "image":"Gugu and gaga looking out window at the moon, moon looking back at them gently, three-way tender moment",                                                                  "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":[],                          "bgm":"emotional piano",                      "sub":"",                       "tags":["月亮","父母"]},
    {"id":109,"title":"镜头回到卧室",                "characters":["doro","baizi","feibi-jiubi"],"location":"卧室",   "time":"night",     "scene_type":"portrait",     "image":"Camera returning to bedroom, three children's even breathing visible as soft puffs of air, peaceful scene",                                                                  "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":["soft breathing"],         "bgm":"emotional piano",                      "sub":"",                       "tags":["睡眠","孩子"]},
    {"id":110,"title":"萤火虫飞入",                  "characters":[],            "location":"卧室",                "time":"night",     "scene_type":"portrait",     "image":"Firefly flying into bedroom, circling feibi-jiubi's small bed, magical soft glow",                                                                                                "motion":"tracking",         "speed":"slow",  "duration":1.0, "sfx":["wing flutter"],           "bgm":"magical chime",                       "sub":"",                       "tags":["萤火虫","魔法"]},
    {"id":111,"title":"萤火虫停相册",                "characters":[],            "location":"卧室",                "time":"night",     "scene_type":"portrait",     "image":"A firefly landing on family album cover, glowing like a small star on the book",                                                                                                  "motion":"zoom_in",          "speed":"slow",  "duration":1.0, "sfx":["wing flutter"],           "bgm":"magical chime",                       "sub":"",                       "tags":["相册","萤火虫"]},
    {"id":112,"title":"进入梦境世界",                "characters":[],            "location":"梦境",                "time":"dream",     "scene_type":"dream",         "image":"Transition to dream world, fade-in to magical sky landscape, family of five about to fly",                                                                                       "motion":"fade_in",          "speed":"slow",  "duration":1.0, "sfx":["magical whoosh"],         "bgm":"dream orchestra",                     "sub":"",                       "tags":["梦境","过渡"]},
    {"id":113,"title":"全家云朵飞翔",                "characters":["gugu","gaga","doro","baizi","feibi-jiubi"],"location":"梦境·云朵森林","time":"dream","scene_type":"dream","image":"Family of five flying together in cloud forest dream world, holding wings, free and happy, magical wonderland",                                                       "motion":"tracking",         "speed":"normal","duration":1.0, "sfx":["wind whoosh"],            "bgm":"dream orchestra",                     "sub":"",                       "tags":["飞翔","全家","梦境"]},
    {"id":114,"title":"飞行姿态",                    "characters":["gugu","gaga","doro","baizi","feibi-jiubi"],"location":"梦境·云朵森林","time":"dream","scene_type":"dream","image":"Papa carrying doro on back, mama holding feibi-jiubi, baizi holding family together, beautiful flying formation",                                                       "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":[],                          "bgm":"dream orchestra",                     "sub":"",                       "tags":["飞翔","全家","梦境"]},
    {"id":115,"title":"云朵上的家",                  "characters":[],            "location":"梦境·云朵",            "time":"dream",     "scene_type":"dream",         "image":"Cloud shaped like a sign reading gugu gaga family, with subtitle always together, magical typography in sky",                                                              "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":[],                          "bgm":"dream orchestra",                     "sub":"永远在一起",             "tags":["云朵","家族","梦境"]},
    {"id":116,"title":"飞越记忆地标",                "characters":[],            "location":"梦境·全景",            "time":"dream",     "scene_type":"dream",         "image":"Flying over grandpa forest, grandma bakery, childhood town, montage of memory locations in one wide shot",                                                                  "motion":"tracking",         "speed":"normal","duration":1.0, "sfx":[],                          "bgm":"epic gentle",                         "sub":"",                       "tags":["回忆","全景","梦境"]},
    {"id":117,"title":"doro喊飞到宇宙",              "characters":["doro"],      "location":"梦境",                "time":"dream",     "scene_type":"dialogue",      "image":"Doro shouting let's fly to the universe, arms spread wide, full of imagination",                                                                                                "motion":"static",          "speed":"normal","duration":1.0, "sfx":[],                          "bgm":"epic gentle",                         "sub":"doro——飞到宇宙去！",      "tags":["doro","梦想"]},
    {"id":118,"title":"拉远至地球",                  "characters":[],            "location":"太空",                "time":"dream",     "scene_type":"dream",         "image":"Camera pulling back fast, earth becomes a blue marble floating in galaxy, cosmic scale transition",                                                                          "motion":"zoom_out",         "speed":"fast",  "duration":1.0, "sfx":["cosmic whoosh"],          "bgm":"epic gentle",                         "sub":"",                       "tags":["宇宙","地球","拉远"]},
    {"id":119,"title":"星星组成字",                  "characters":[],            "location":"银河",                "time":"dream",     "scene_type":"ending",        "image":"Countless stars in galaxy arranging into gugu gaga four characters, cosmic typographic art",                                                                                      "motion":"static",          "speed":"slow",  "duration":1.0, "sfx":["star chime"],             "bgm":"emotional strings",                    "sub":"",                       "tags":["星星","宇宙","文字"]},
    {"id":120,"title":"片尾字幕与歌曲",              "characters":[],            "location":"银河",                "time":"night",     "scene_type":"ending",        "image":"Closing subtitle appears: gugu gaga, a family's voice is the warmest song in the world, end credits roll with song",                                                       "motion":"fade_out",         "speed":"slow",  "duration":1.0, "sfx":["end song"],               "bgm":"ending song gugu gaga",                "sub":"咕咕嘎嘎，一家人的声音，是世界上最温暖的歌。", "tags":["片尾","字幕","结束"]},
]

# 验证数量
assert len(SHOTS) == 120, f"镜头数量错误: {len(SHOTS)}"

# 公共字段构造函数
def build_shot(s):
    act = (s["id"] - 1) // 20 + 1
    order = (s["id"] - 1) % 20 + 1
    shot_id = f"{s['id']:03d}"
    return {
        "shot_id": shot_id,
        "act": act,
        "order": order,
        "duration_sec": s["duration"],
        "title": s["title"],
        "scene_type": s["scene_type"],
        "characters_in_shot": s["characters"],
        "location": s["location"],
        "time_of_day": s["time"],
        "image_prompt": {
            "main": f"{s['image']}, {STYLE_PREFIX}",
            "negative": NEGATIVE
        },
        "video_prompt": {
            "main": f"{s['image']}, {s['motion']} motion, {s['speed']} speed, cinematic 24fps, {s['duration']} second",
            "motion": s["motion"],
            "speed": s["speed"]
        },
        "audio": {
            "bgm": s["bgm"],
            "sfx": s["sfx"],
            "dialogue": [],
            "narration": ""
        },
        "subtitle": s["sub"],
        "transition_in": "fade_in" if s["id"] == 1 else ("fade_in" if s["scene_type"] == "dream" and s["id"] == 112 else "cut"),
        "transition_out": "fade_out" if s["id"] == 120 else "cut",
        "tags": s["tags"],
        "notes": f"第{act}幕第{order}个镜头",
        "linked_shots": [f"{s['id']-1:03d}", f"{s['id']+1:03d}"] if 1 < s["id"] < 120 else ([f"{s['id']+1:03d}"] if s["id"] == 1 else [f"{s['id']-1:03d}"]),
        "version": "1.0",
        "status": "draft"
    }

# 写入文件
count = 0
for s in SHOTS:
    act_num = (s["id"] - 1) // 20 + 1
    act_dir = OUTPUT_DIR / f"act-{act_num:02d}"
    act_dir.mkdir(parents=True, exist_ok=True)
    file_path = act_dir / f"shot-{s['id']:03d}.json"
    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(build_shot(s), f, ensure_ascii=False, indent=2)
    count += 1

print(f"✅ 已生成 {count} 个镜头 JSON 文件")
print(f"📁 输出目录: {OUTPUT_DIR}")
