import type { DialogueLine } from '@/engine/types'

export const dialogueScript: Record<string, DialogueLine> = {
  start: {
    id: 'start',
    chapter: 'intro',
    scene: 'kiln_night',
    bgm: 'main_theme',
    text: '千年窑火，映照古今。裂痕生光，慢火传灯。',
    next: 'intro_2',
  },
  intro_2: {
    id: 'intro_2',
    scene: 'kiln_night',
    text: '南宋龙泉，章氏兄弟的窑火在此燃起。千年之后，张氏兄弟在同一片土地上，重新点燃了这炉火。',
    next: 'intro_3',
  },
  intro_3: {
    id: 'intro_3',
    text: '你想先聆听哪一段故事？',
    choices: [
      { text: '古线·章氏兄弟——裂痕如何催生至美', next: 'ancient_1' },
      { text: '今线·张氏兄弟——慢火如何传递人心', next: 'modern_1' },
    ],
  },

  ancient_1: {
    id: 'ancient_1',
    chapter: 'ancient',
    scene: 'ancient_kiln_exterior',
    bgm: 'ancient_kiln',
    showCharacters: ['zhangCunGen'],
    character: 'zhangCunGen',
    expression: 'determined',
    text: '窑火不熄，章氏不灭。生一、生二，你们兄弟二人，要共守这窑火。',
    next: 'ancient_2',
  },
  ancient_2: {
    id: 'ancient_2',
    character: 'narrator',
    text: '章村根临终握二子之手，目光如炬。窑火映照在他苍老的面容上，那是一生守窑的执念。',
    next: 'ancient_3',
  },
  ancient_3: {
    id: 'ancient_3',
    hideCharacters: ['zhangCunGen'],
    showCharacters: ['zhangShengYi'],
    character: 'zhangShengYi',
    expression: 'determined',
    text: '父亲放心，我定守好这窑。',
    next: 'ancient_4',
  },
  ancient_4: {
    id: 'ancient_4',
    showCharacters: ['zhangShengEr'],
    character: 'zhangShengEr',
    expression: 'sad',
    text: '……我也会的。',
    next: 'ancient_5',
  },
  ancient_5: {
    id: 'ancient_5',
    character: 'narrator',
    text: '然兄刚弟柔，性情各异。同一窑火，两种执念——终分立窑炉。',
    next: 'ancient_6',
  },
  ancient_6: {
    id: 'ancient_6',
    scene: 'ancient_kiln_interior',
    character: 'narrator',
    text: '生一取铁胎紫土，生二取白胎青土。兄窑出紫口铁足，弟窑出温润粉青。',
    next: 'ancient_7',
  },
  ancient_7: {
    id: 'ancient_7',
    character: 'zhangShengYi',
    expression: 'determined',
    text: '铁胎紫土，方为正道。弟之青土，过于柔弱。',
    next: 'ancient_8',
  },
  ancient_8: {
    id: 'ancient_8',
    character: 'zhangShengEr',
    expression: 'sad',
    text: '兄长何出此言？白胎青土，亦能烧出绝世之釉。',
    next: 'ancient_9',
  },
  ancient_9: {
    id: 'ancient_9',
    character: 'narrator',
    text: '兄受皇恩贡瓷，声名远播。弟心生不平，暗夜潜入兄窑……',
    next: 'ancient_choice_1',
  },
  ancient_choice_1: {
    id: 'ancient_choice_1',
    scene: 'kiln_night',
    bgm: 'tension',
    character: 'zhangShengEr',
    expression: 'angry',
    text: '……我该不该投草木灰于兄之釉缸？',
    choices: [
      { text: '投灰——让兄长也尝尝不如人的滋味', next: 'ancient_throw', setVar: { key: 'ancient_jealousy', value: true } },
      { text: '放下——不该如此', next: 'ancient_hesitate', setVar: { key: 'ancient_jealousy', value: false } },
    ],
  },
  ancient_throw: {
    id: 'ancient_throw',
    character: 'zhangShengEr',
    expression: 'angry',
    sfx: 'kiln_fire',
    text: '……草木灰入釉，且看明日开窑，兄长如何收场！',
    next: 'ancient_crack',
  },
  ancient_hesitate: {
    id: 'ancient_hesitate',
    character: 'zhangShengEr',
    expression: 'sad',
    text: '不……我不能如此。但——',
    next: 'ancient_hesitate_2',
  },
  ancient_hesitate_2: {
    id: 'ancient_hesitate_2',
    character: 'narrator',
    text: '然而命运弄人，一阵夜风吹开了窑门，草木灰自行飘入了釉缸。该来的，终究会来。',
    next: 'ancient_crack',
  },
  ancient_crack: {
    id: 'ancient_crack',
    scene: 'crack_closeup',
    sfx: 'crack',
    hideCharacters: ['zhangShengEr'],
    character: 'narrator',
    text: '翌日开窑——釉面竟生冰裂纹路！大纹若铁线，细纹如金丝！',
    next: 'ancient_crack_2',
  },
  ancient_crack_2: {
    id: 'ancient_crack_2',
    character: 'narrator',
    text: '"金丝铁线"自此诞生。破坏催生至美，嫉妒开出奇花。',
    next: 'ancient_crack_3',
  },
  ancient_crack_3: {
    id: 'ancient_crack_3',
    showCharacters: ['zhangShengYi'],
    character: 'zhangShengYi',
    expression: 'surprised',
    text: '这……这裂纹！竟有如此之美？',
    next: 'ancient_reveal',
  },
  ancient_reveal: {
    id: 'ancient_reveal',
    showCharacters: ['zhangShengEr'],
    character: 'zhangShengEr',
    expression: 'guilty',
    text: '兄长……是我。是我投了草木灰。',
    next: 'ancient_split',
  },
  ancient_split: {
    id: 'ancient_split',
    bgm: 'tension',
    character: 'zhangShengYi',
    expression: 'angry',
    text: '你！……你竟做出如此之事！',
    next: 'ancient_split_2',
  },
  ancient_split_2: {
    id: 'ancient_split_2',
    character: 'zhangShengEr',
    expression: 'sad',
    text: '我……负疚远走。另辟窑址，苦心孤诣——终烧出梅子青釉。',
    next: 'ancient_meizi',
  },
  ancient_meizi: {
    id: 'ancient_meizi',
    scene: 'ancient_kiln_exterior',
    character: 'narrator',
    text: '色如初梅，翠欲滴。与兄之开片并称双绝。',
    next: 'ancient_tribute',
  },
  ancient_tribute: {
    id: 'ancient_tribute',
    character: 'narrator',
    text: '后朝廷加征万件贡瓷，一窑难承——兄弟被迫联手。',
    next: 'ancient_joint',
  },
  ancient_joint: {
    id: 'ancient_joint',
    scene: 'joint_firing',
    bgm: 'reunion',
    showCharacters: ['zhangShengYi'],
    character: 'narrator',
    text: '合烧之日，开片与厚釉共存一器，裂纹与温润相映。',
    next: 'ancient_joint_2',
  },
  ancient_joint_2: {
    id: 'ancient_joint_2',
    showCharacters: ['zhangShengEr'],
    character: 'narrator',
    text: '兄弟相视无言，和解于窑火之中。',
    next: 'ancient_end',
  },
  ancient_end: {
    id: 'ancient_end',
    character: 'narrator',
    text: '章氏窑火经元外销四海、明奉旨烧造，至清渐熄沉埋，唯残片犹在。',
    next: 'after_ancient',
  },
  after_ancient: {
    id: 'after_ancient',
    hideCharacters: ['zhangShengYi', 'zhangShengEr'],
    text: '古线故事已毕。是否聆听今线？',
    choices: [
      { text: '继续——今线·张氏兄弟', next: 'modern_1' },
      { text: '直接前往双线共振', next: 'resonance_1' },
    ],
  },

  modern_1: {
    id: 'modern_1',
    chapter: 'modern',
    scene: 'creek',
    bgm: 'modern_longquan',
    showCharacters: ['zhangJi'],
    character: 'narrator',
    text: '龙泉老宅，张寄与张生元幼时以泥为伴，手印留在湿坯上，笑声融进窑烟里。',
    next: 'modern_2',
  },
  modern_2: {
    id: 'modern_2',
    showCharacters: ['zhangShengYuan'],
    character: 'zhangJi',
    expression: 'happy',
    text: '生元，你看！我捏了一只小碗！',
    next: 'modern_3',
  },
  modern_3: {
    id: 'modern_3',
    character: 'zhangShengYuan',
    expression: 'happy',
    text: '歪歪扭扭的，哈哈！不过……泥巴真好啊。',
    next: 'modern_4',
  },
  modern_4: {
    id: 'modern_4',
    hideCharacters: ['zhangShengYuan'],
    scene: 'modern_workshop',
    character: 'narrator',
    text: '成年后兄弟分途。张寄拜师入青瓷厂，一窑又一窑废品堆成小山……',
    next: 'modern_5',
  },
  modern_5: {
    id: 'modern_5',
    showCharacters: ['master'],
    character: 'zhangJi',
    expression: 'determined',
    text: '碎瓷割手不割志。师傅，我还能再试。',
    next: 'modern_6',
  },
  modern_6: {
    id: 'modern_6',
    character: 'master',
    expression: 'neutral',
    sfx: 'shard',
    text: '……拿着。这是章生一的残片。开片金丝铁线，千年犹在。',
    next: 'modern_7',
  },
  modern_7: {
    id: 'modern_7',
    hideCharacters: ['master'],
    character: 'zhangJi',
    expression: 'determined',
    text: '残片如祖训……我定不负此片。',
    next: 'modern_8',
  },
  modern_8: {
    id: 'modern_8',
    scene: 'school',
    hideCharacters: ['zhangJi'],
    character: 'narrator',
    text: '张生元考入师范，远赴宝溪乡支教。漏雨教室、泥地操场……',
    next: 'modern_9',
  },
  modern_9: {
    id: 'modern_9',
    showCharacters: ['student'],
    character: 'student',
    expression: 'surprised',
    text: '老师，青瓷是什么？',
    next: 'modern_10',
  },
  modern_10: {
    id: 'modern_10',
    showCharacters: ['zhangShengYuan'],
    character: 'zhangShengYuan',
    expression: 'sad',
    text: '故土之器，故土之人竟不知……',
    next: 'modern_11',
  },
  modern_11: {
    id: 'modern_11',
    scene: 'creek',
    sfx: 'shard',
    hideCharacters: ['student'],
    character: 'narrator',
    text: '他于废弃窑址溪边拾得残片，莲瓣纹犹存。遂以此开陶艺课，以残片为教材，以窑址为课堂。',
    next: 'modern_clash',
  },
  modern_clash: {
    id: 'modern_clash',
    scene: 'storm_night',
    bgm: 'tension',
    hideCharacters: ['student', 'zhangShengYuan'],
    showCharacters: ['zhangJi', 'zhangShengYuan'],
    character: 'zhangJi',
    expression: 'angry',
    text: '你浪费了才华！应该回城做瓷！',
    next: 'modern_clash_2',
  },
  modern_clash_2: {
    id: 'modern_clash_2',
    sfx: 'rain',
    character: 'zhangShengYuan',
    expression: 'determined',
    text: '你守的是窑，我守的是人。',
    next: 'modern_clash_3',
  },
  modern_clash_3: {
    id: 'modern_clash_3',
    character: 'narrator',
    text: '暴雨夜争吵，雷声与窑火同燃。兄弟二人，各执一词。',
    next: 'modern_choice',
  },
  modern_choice: {
    id: 'modern_choice',
    text: '此刻，你站在窑火与教室之间——',
    choices: [
      { text: '理解张寄——技艺需要传承', next: 'modern_side_ji', setVar: { key: 'modern_side', value: 'ji' } },
      { text: '理解张生元——人心需要播种', next: 'modern_side_yuan', setVar: { key: 'modern_side', value: 'yuan' } },
    ],
  },
  modern_side_ji: {
    id: 'modern_side_ji',
    character: 'zhangJi',
    expression: 'determined',
    text: '窑火不续，何来传承？没有人做瓷，一切都是空谈。',
    next: 'modern_turning',
  },
  modern_side_yuan: {
    id: 'modern_side_yuan',
    character: 'zhangShengYuan',
    expression: 'determined',
    text: '窑火再旺，无人添柴终将熄灭。教育是慢火，传承是长窑。',
    next: 'modern_turning',
  },
  modern_turning: {
    id: 'modern_turning',
    scene: 'summer_camp',
    bgm: 'reunion',
    hideCharacters: ['zhangJi', 'zhangShengYuan'],
    character: 'narrator',
    text: '转折起于张寄带残片到学校，为学生演示拉坯。泥在转盘上旋转，孩子们眼中映出千年窑火。',
    next: 'modern_turning_2',
  },
  modern_turning_2: {
    id: 'modern_turning_2',
    showCharacters: ['student'],
    character: 'student',
    expression: 'happy',
    text: '老师！我烧出了一个小碗！虽然歪歪的……但它会发光！',
    next: 'modern_camp',
  },
  modern_camp: {
    id: 'modern_camp',
    hideCharacters: ['student'],
    showCharacters: ['zhangJi', 'zhangShengYuan'],
    character: 'narrator',
    text: '兄弟遂合办龙窑夏令营。兄收支教点学生为徒，弟编写乡土教材《青瓷课》。',
    next: 'modern_joint',
  },
  modern_joint: {
    id: 'modern_joint',
    scene: 'joint_firing',
    character: 'narrator',
    text: '终有一日，兄弟合烧一窑，窑门封堵，火光映照两张脸——',
    next: 'modern_joint_2',
  },
  modern_joint_2: {
    id: 'modern_joint_2',
    character: 'narrator',
    text: '致敬章生一·章生二。千年窑火，同一炉焰。',
    next: 'modern_end',
  },
  modern_end: {
    id: 'modern_end',
    character: 'narrator',
    text: '传承不在器物而在人心。守窑是传技，育人是传心。',
    next: 'after_modern',
  },
  after_modern: {
    id: 'after_modern',
    hideCharacters: ['zhangJi', 'zhangShengYuan'],
    text: '今线故事已毕。是否聆听古线？',
    choices: [
      { text: '回溯——古线·章氏兄弟', next: 'ancient_1' },
      { text: '前往双线共振', next: 'resonance_1' },
    ],
  },

  resonance_1: {
    id: 'resonance_1',
    chapter: 'resonance',
    scene: 'resonance',
    bgm: 'reunion',
    character: 'narrator',
    text: '千年窑火，古今共振。裂痕与传承，在此交汇。',
    next: 'resonance_2',
  },
  resonance_2: {
    id: 'resonance_2',
    character: 'narrator',
    text: '古线以父嘱为起点，今线以泥伴为起点——皆因血脉与泥土而生。',
    next: 'resonance_3',
  },
  resonance_3: {
    id: 'resonance_3',
    character: 'narrator',
    text: '古线以嫉妒投灰为裂痕，今线以理念碰撞为裂痕——裂痕皆因爱而生。',
    next: 'resonance_4',
  },
  resonance_4: {
    id: 'resonance_4',
    character: 'narrator',
    text: '古线裂痕催生开片之美，今线碰撞催生教育之新——裂隙是新生的起点。',
    next: 'resonance_5',
  },
  resonance_5: {
    id: 'resonance_5',
    character: 'narrator',
    text: '古人以合烧和解，今人以合烧致敬——同一炉火，跨越千年。',
    next: 'resonance_theme',
  },
  resonance_theme: {
    id: 'resonance_theme',
    scene: 'joint_firing',
    character: 'narrator',
    text: '裂而不断，和而不同。千年窑火不灭，非因火不曾熄，乃因总有人重新点燃。',
    next: 'resonance_final',
  },
  resonance_final: {
    id: 'resonance_final',
    scene: 'resonance',
    text: '烧的是瓷，传的是人。',
    isEnding: true,
  },
}
