<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import {
  type DatasetInfo, type AnnotationEntry,
  fetchDatasets, createDataset, deleteDataset, annotateEntry,
  autoLabel, exportDataset, fetchDatasetStats, uploadImage, addText,
} from '../core/datasets'

const datasets = ref<DatasetInfo[]>([])
const selectedId = ref<string | null>(null)
const loading = ref(false)
const showCreateForm = ref(false)
const newDsName = ref('')
const newDsDesc = ref('')
const newDsType = ref('image-text')
const statusMsg = ref('')

const annPrompt = ref('')
const annLabelsStr = ref('')
const annCaption = ref('')

const computing = ref(false)
const computeProgress = ref(0)
const computeStep = ref('')
const computeLog = ref<{ time: string; msg: string; color: string }[]>([])

const activeSection = ref<'annotations' | 'compute' | 'training-set'>('annotations')

const selected = computed(() => datasets.value.find(d => d.id === selectedId.value) || null)

const allAnnotations = computed(() => {
  const all: (AnnotationEntry & { datasetName: string; datasetId: string })[] = []
  for (const ds of datasets.value) {
    for (const ann of ds.annotations || []) {
      all.push({ ...ann, datasetName: ds.name, datasetId: ds.id })
    }
  }
  return all
})

const trainingSetStats = computed(() => {
  let totalAnnotations = 0
  let totalImages = 0
  let totalTexts = 0
  let highQuality = 0
  let autoGenerated = 0
  for (const ds of datasets.value) {
    totalAnnotations += ds.stats.annotated || 0
    totalImages += ds.stats.images || 0
    totalTexts += ds.stats.texts || 0
    for (const ann of ds.annotations || []) {
      if (ann.quality?.score > 0.8) highQuality++
      if ((ann.params as Record<string, unknown>)?.autoGenerated) autoGenerated++
    }
  }
  return { totalAnnotations, totalImages, totalTexts, highQuality, autoGenerated, totalDatasets: datasets.value.length }
})

onMounted(() => { refresh() })

async function refresh() {
  loading.value = true
  try {
    datasets.value = await fetchDatasets()
    statusMsg.value = `共 ${datasets.value.length} 个数据集 · ${trainingSetStats.value.totalAnnotations} 条标注`
  } catch {
    statusMsg.value = '连接API失败 (localhost:4000)'
  } finally {
    loading.value = false
  }
}

async function handleCreate() {
  if (!newDsName.value.trim()) return
  await createDataset({ name: newDsName.value, description: newDsDesc.value, type: newDsType.value })
  newDsName.value = ''
  newDsDesc.value = ''
  showCreateForm.value = false
  await refresh()
}

async function handleDelete(id: string) {
  await deleteDataset(id)
  if (selectedId.value === id) selectedId.value = null
  await refresh()
}

async function handleAutoLabel() {
  if (!selectedId.value) return
  computing.value = true
  computeProgress.value = 0
  computeLog.value = []
  activeSection.value = 'compute'

  const steps = [
    { pct: 10, msg: '扫描数据集图像文件...', color: '#44ddff' },
    { pct: 25, msg: '扫描数据集文本文件...', color: '#44ddff' },
    { pct: 40, msg: '提取图像特征关键词...', color: '#a29bfe' },
    { pct: 55, msg: '匹配文本语义标签...', color: '#ff6b9d' },
    { pct: 70, msg: '生成标注条目 (prompt + caption)...', color: '#ffaa00' },
    { pct: 85, msg: '计算质量评分...', color: '#00ff88' },
    { pct: 95, msg: '写入标注数据...', color: '#00ff88' },
  ]

  for (const step of steps) {
    computeProgress.value = step.pct
    computeStep.value = step.msg
    computeLog.value.push({ time: new Date().toISOString().slice(11, 23), msg: step.msg, color: step.color })
    await new Promise(r => setTimeout(r, 400 + Math.random() * 300))
  }

  await autoLabel(selectedId.value, { maxPairs: 10 })
  computeProgress.value = 100
  computeStep.value = '标注计算完成!'
  computeLog.value.push({ time: new Date().toISOString().slice(11, 23), msg: '✓ 标注计算完成!', color: '#00ff88' })
  computing.value = false
  await refresh()
}

async function handleBatchAutoLabel() {
  if (datasets.value.length === 0) return
  computing.value = true
  computeProgress.value = 0
  computeLog.value = []
  activeSection.value = 'compute'

  for (let i = 0; i < datasets.value.length; i++) {
    const ds = datasets.value[i]
    computeStep.value = `处理数据集 [${i + 1}/${datasets.value.length}]: ${ds.name}`
    computeProgress.value = Math.round((i / datasets.value.length) * 90)
    computeLog.value.push({ time: new Date().toISOString().slice(11, 23), msg: `开始标注: ${ds.name} (${ds.stats.images}图 ${ds.stats.texts}文)`, color: '#ffaa00' })
    await autoLabel(ds.id, { maxPairs: 10 })
    computeLog.value.push({ time: new Date().toISOString().slice(11, 23), msg: `完成标注: ${ds.name}`, color: '#00ff88' })
  }

  computeProgress.value = 100
  computeStep.value = '全部数据集标注完成!'
  computeLog.value.push({ time: new Date().toISOString().slice(11, 23), msg: `✓ 批量标注完成! 共处理 ${datasets.value.length} 个数据集`, color: '#00ff88' })
  computing.value = false
  await refresh()
}

async function handleExport(format: string) {
  if (!selectedId.value) return
  await exportDataset(selectedId.value, format)
  await refresh()
}

async function handleSubmitAnnotate() {
  if (!selectedId.value) return
  const labels = annLabelsStr.value.split(',').map(s => s.trim()).filter(Boolean)
  await annotateEntry(selectedId.value, { prompt: annPrompt.value, labels, caption: annCaption.value })
  annPrompt.value = ''
  annLabelsStr.value = ''
  annCaption.value = ''
  await refresh()
}

async function handleUploadImage() {
  if (!selectedId.value) return
  const input = document.createElement('input')
  input.type = 'file'
  input.accept = 'image/*'
  input.multiple = true
  input.onchange = async () => {
    if (!input.files) return
    for (const file of Array.from(input.files)) {
      await uploadImage(selectedId.value!, file)
    }
    await refresh()
  }
  input.click()
}

async function handleAddText() {
  if (!selectedId.value) return
  const name = `text_${Date.now()}.txt`
  const content = annCaption.value || '示例文本内容'
  await addText(selectedId.value, name, content)
  await refresh()
}

function selectDataset(id: string) {
  selectedId.value = id
  activeSection.value = 'annotations'
}

function formatBytes(bytes: number) {
  if (bytes < 1024) return bytes + 'B'
  if (bytes < 1048576) return (bytes / 1024).toFixed(1) + 'KB'
  return (bytes / 1048576).toFixed(1) + 'MB'
}
</script>

<template>
  <div class="ds-page">
    <header class="ds-header">
      <span class="ds-logo">DATASET</span>
      <span class="ds-title">数据集 · 标注计算</span>
      <span class="ds-sub">文生图训练数据制作</span>
      <span class="spacer"></span>
      <button class="ds-btn accent" @click="showCreateForm = !showCreateForm">{{ showCreateForm ? '取消' : '+ 新建' }}</button>
      <button class="ds-btn compute" @click="handleBatchAutoLabel" :disabled="computing || datasets.length === 0">{{ computing ? '⏳ 计算中...' : '⚡ 全量标注计算' }}</button>
      <button class="ds-btn" @click="refresh">↻</button>
    </header>

    <div class="ds-create" v-if="showCreateForm">
      <input class="ds-input" v-model="newDsName" placeholder="数据集名称..." @keyup.enter="handleCreate">
      <input class="ds-input" v-model="newDsDesc" placeholder="描述（可选）...">
      <select class="ds-select" v-model="newDsType">
        <option value="image-text">图文对</option>
        <option value="image-only">仅图像</option>
        <option value="text-only">仅文本</option>
      </select>
      <button class="ds-btn accent" @click="handleCreate">创建</button>
    </div>

    <div class="ds-body">
      <aside class="ds-sidebar">
        <div class="ds-sidebar-head">数据集列表</div>
        <div v-if="datasets.length === 0" class="ds-empty">暂无数据集</div>
        <div v-for="ds in datasets" :key="ds.id" class="ds-item" :class="{ active: selectedId === ds.id }" @click="selectDataset(ds.id)">
          <span class="ds-item-icon" :style="{ color: ds.type === 'image-text' ? '#ffaa00' : ds.type === 'image-only' ? '#00ff88' : '#44ddff' }">{{ ds.type === 'image-text' ? '◈' : ds.type === 'image-only' ? '▣' : '▤' }}</span>
          <div class="ds-item-text">
            <span class="ds-item-name">{{ ds.name }}</span>
            <span class="ds-item-meta">{{ ds.stats.annotated || 0 }} 标注 · {{ ds.stats.images || 0 }} 图 · {{ ds.stats.texts || 0 }} 文</span>
          </div>
          <button class="ds-del" @click.stop="handleDelete(ds.id)">✕</button>
        </div>

        <div class="ds-sidebar-divider"></div>
        <div class="ds-sidebar-head" style="color:#ffaa00">训练集合</div>
        <div class="ds-stats-mini">
          <div class="ds-stat-row"><span>数据集</span><span style="color:#ffaa00">{{ trainingSetStats.totalDatasets }}</span></div>
          <div class="ds-stat-row"><span>总标注</span><span style="color:#00ff88">{{ trainingSetStats.totalAnnotations }}</span></div>
          <div class="ds-stat-row"><span>总图像</span><span style="color:#44ddff">{{ trainingSetStats.totalImages }}</span></div>
          <div class="ds-stat-row"><span>总文本</span><span style="color:#a29bfe">{{ trainingSetStats.totalTexts }}</span></div>
          <div class="ds-stat-row"><span>高质量</span><span style="color:#00ff88">{{ trainingSetStats.highQuality }}</span></div>
          <div class="ds-stat-row"><span>自动生成</span><span style="color:#ff6b9d">{{ trainingSetStats.autoGenerated }}</span></div>
        </div>
      </aside>

      <main class="ds-main">
        <template v-if="selected">
          <div class="ds-toolbar">
            <span class="ds-badge" :style="{ color: '#ffaa00', borderColor: '#ffaa00' }">{{ selected.name }}</span>
            <span class="ds-meta">{{ selected.type }} · {{ selected.format }}</span>
            <div class="ds-section-tabs">
              <span class="ds-sec-tab" :class="{ active: activeSection === 'annotations' }" @click="activeSection = 'annotations'">标注数据</span>
              <span class="ds-sec-tab" :class="{ active: activeSection === 'compute' }" @click="activeSection = 'compute'">标注计算</span>
              <span class="ds-sec-tab" :class="{ active: activeSection === 'training-set' }" @click="activeSection = 'training-set'">训练集合</span>
            </div>
            <span class="spacer"></span>
            <button class="ds-btn" @click="handleUploadImage">⬆ 上传图像</button>
            <button class="ds-btn" @click="handleAddText">+ 添加文本</button>
            <button class="ds-btn compute" @click="handleAutoLabel" :disabled="computing">{{ computing ? '⏳' : '⚡ 标注计算' }}</button>
            <button class="ds-btn" @click="handleExport('jsonl')">⬇ JSONL</button>
            <button class="ds-btn" @click="handleExport('json')">⬇ JSON</button>
            <button class="ds-btn" @click="handleExport('csv')">⬇ CSV</button>
          </div>

          <!-- 标注数据 -->
          <div class="ds-content" v-if="activeSection === 'annotations'">
            <div class="ds-split">
              <div class="ds-split-left">
                <div class="ds-section-title" style="color:#ffaa00">▣ 标注数据 ({{ selected.annotations?.length || 0 }})</div>
                <div class="ds-split-scroll">
                  <div v-if="!selected.annotations || selected.annotations.length === 0" class="ds-empty-panel">
                    暂无标注。点击"⚡ 标注计算"自动生成。
                  </div>
                  <div v-for="ann in selected.annotations" :key="ann.id" class="ann-card">
                    <div class="ann-header">
                      <span class="ann-id">{{ ann.id.slice(0, 8) }}</span>
                      <span class="ann-score" :style="{ color: (ann.quality?.score || 0) > 0.8 ? '#00ff88' : '#ffaa00' }">{{ ((ann.quality?.score || 0) * 100).toFixed(0) }}%</span>
                      <span v-if="(ann.params as any)?.autoGenerated" class="ann-auto">AUTO</span>
                    </div>
                    <div class="ann-labels">
                      <span v-for="lbl in ann.labels" :key="lbl" class="ann-label">{{ lbl }}</span>
                    </div>
                    <div class="ann-caption">{{ ann.caption }}</div>
                    <div class="ann-prompt">prompt: {{ ann.prompt || '(无)' }}</div>
                    <div class="ann-meta">
                      <span v-if="ann.image">📷 {{ ann.image }}</span>
                      <span v-if="ann.text">📄 {{ ann.text }}</span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="ds-split-right">
                <div class="ds-section-title" style="color:#44ddff">✏ 手动添加标注</div>
                <div class="ds-split-scroll" style="padding: 10px">
                  <div class="ann-form">
                    <label class="ann-form-label">提示词 Prompt</label>
                    <input class="ann-input" v-model="annPrompt" placeholder="描述图像内容的提示词...">
                    <label class="ann-form-label">标签 Labels</label>
                    <input class="ann-input" v-model="annLabelsStr" placeholder="标签1, 标签2, ...">
                    <label class="ann-form-label">描述 Caption</label>
                    <textarea class="ann-textarea" v-model="annCaption" placeholder="详细的图像描述..." rows="4"></textarea>
                    <button class="ds-btn accent" style="align-self:flex-end" @click="handleSubmitAnnotate">添加标注</button>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- 标注计算 -->
          <div class="ds-content" v-if="activeSection === 'compute'">
            <div class="compute-panel">
              <div class="compute-header">
                <span class="compute-title">⚡ 标注计算引擎</span>
                <span class="compute-status" :style="{ color: computing ? '#ffaa00' : '#00ff88' }">{{ computing ? '计算中...' : '就绪' }}</span>
              </div>

              <div class="compute-progress-wrap">
                <div class="compute-progress-bar">
                  <div class="compute-progress-fill" :style="{ width: computeProgress + '%' }"></div>
                </div>
                <span class="compute-pct">{{ computeProgress }}%</span>
              </div>

              <div class="compute-step" v-if="computeStep">{{ computeStep }}</div>

              <div class="compute-log">
                <div v-if="computeLog.length === 0" class="ds-empty-panel">点击"⚡ 标注计算"开始自动标注</div>
                <div v-for="(log, i) in computeLog" :key="i" class="compute-log-row">
                  <span class="compute-log-time">{{ log.time }}</span>
                  <span class="compute-log-dot" :style="{ background: log.color }"></span>
                  <span class="compute-log-msg" :style="{ color: log.color }">{{ log.msg }}</span>
                </div>
              </div>

              <div class="compute-actions">
                <button class="ds-btn compute" @click="handleAutoLabel" :disabled="computing">{{ computing ? '⏳ 计算中...' : '⚡ 单集标注计算' }}</button>
                <button class="ds-btn compute" @click="handleBatchAutoLabel" :disabled="computing">{{ computing ? '⏳' : '⚡⚡ 全量标注计算' }}</button>
              </div>

              <div class="compute-info">
                <div class="compute-info-row">
                  <span>当前数据集</span>
                  <span style="color:#ffaa00">{{ selected.name }}</span>
                </div>
                <div class="compute-info-row">
                  <span>图像数</span>
                  <span style="color:#44ddff">{{ selected.stats.images }}</span>
                </div>
                <div class="compute-info-row">
                  <span>文本数</span>
                  <span style="color:#a29bfe">{{ selected.stats.texts }}</span>
                </div>
                <div class="compute-info-row">
                  <span>已标注</span>
                  <span style="color:#00ff88">{{ selected.stats.annotated || 0 }}</span>
                </div>
              </div>
            </div>
          </div>

          <!-- 训练集合 -->
          <div class="ds-content" v-if="activeSection === 'training-set'">
            <div class="training-panel">
              <div class="training-header">
                <span class="training-title">▣ 训练集合聚合</span>
                <span class="training-count">{{ allAnnotations.length }} 条标注数据</span>
              </div>

              <div class="training-stats-grid">
                <div class="training-stat-card">
                  <span class="tsc-val" style="color:#ffaa00">{{ trainingSetStats.totalDatasets }}</span>
                  <span class="tsc-label">数据集</span>
                </div>
                <div class="training-stat-card">
                  <span class="tsc-val" style="color:#00ff88">{{ trainingSetStats.totalAnnotations }}</span>
                  <span class="tsc-label">总标注</span>
                </div>
                <div class="training-stat-card">
                  <span class="tsc-val" style="color:#44ddff">{{ trainingSetStats.totalImages }}</span>
                  <span class="tsc-label">总图像</span>
                </div>
                <div class="training-stat-card">
                  <span class="tsc-val" style="color:#a29bfe">{{ trainingSetStats.totalTexts }}</span>
                  <span class="tsc-label">总文本</span>
                </div>
                <div class="training-stat-card">
                  <span class="tsc-val" style="color:#00ff88">{{ trainingSetStats.highQuality }}</span>
                  <span class="tsc-label">高质量(>80%)</span>
                </div>
                <div class="training-stat-card">
                  <span class="tsc-val" style="color:#ff6b9d">{{ trainingSetStats.autoGenerated }}</span>
                  <span class="tsc-label">自动生成</span>
                </div>
              </div>

              <div class="training-quality-bar">
                <span class="tqb-label">质量分布</span>
                <div class="tqb-bar">
                  <div class="tqb-fill high" :style="{ width: trainingSetStats.totalAnnotations > 0 ? (trainingSetStats.highQuality / trainingSetStats.totalAnnotations * 100) + '%' : '0%' }"></div>
                </div>
                <span class="tqb-pct">{{ trainingSetStats.totalAnnotations > 0 ? (trainingSetStats.highQuality / trainingSetStats.totalAnnotations * 100).toFixed(0) : 0 }}% 高质量</span>
              </div>

              <div class="training-list-head">全部标注条目</div>
              <div class="training-list">
                <div v-if="allAnnotations.length === 0" class="ds-empty-panel">暂无标注数据。先进行标注计算。</div>
                <div v-for="ann in allAnnotations" :key="ann.datasetId + ann.id" class="training-row">
                  <span class="tr-ds" :style="{ color: '#ffaa00' }">{{ ann.datasetName }}</span>
                  <span class="tr-labels">
                    <span v-for="lbl in ann.labels" :key="lbl" class="ann-label">{{ lbl }}</span>
                  </span>
                  <span class="tr-caption">{{ ann.caption }}</span>
                  <span class="tr-score" :style="{ color: (ann.quality?.score || 0) > 0.8 ? '#00ff88' : '#ffaa00' }">{{ ((ann.quality?.score || 0) * 100).toFixed(0) }}%</span>
                </div>
              </div>
            </div>
          </div>

          <div class="ds-stats-panel">
            <span>图: {{ selected.stats.images }} | 文: {{ selected.stats.texts }} | 标注: {{ selected.stats.annotated || 0 }} | 大小: {{ formatBytes(selected.stats.sizeBytes) }}</span>
          </div>
        </template>

        <template v-else>
          <div class="ds-no-selection">
            <span class="ds-no-icon">◈</span>
            <span class="ds-no-text">选择一个数据集以查看标注详情</span>
            <span class="ds-no-hint">或点击"⚡ 全量标注计算"批量处理所有数据集</span>
          </div>
        </template>
      </main>
    </div>

    <footer class="ds-statusbar">
      <span class="ds-indicator" :style="{ background: computing ? '#ffaa00' : loading ? '#ffaa00' : '#00ff88' }"></span>
      <span>{{ statusMsg }}</span>
      <span class="sep">|</span>
      <span>标注: {{ trainingSetStats.totalAnnotations }} | 高质量: {{ trainingSetStats.highQuality }}</span>
      <span class="sep">|</span>
      <span>API: localhost:4000</span>
    </footer>
  </div>
</template>

<style scoped>
.ds-page { display: flex; flex-direction: column; height: 100vh; background: #050508; color: #d0ffd0; font-family: 'Share Tech Mono', monospace; }

.ds-header { height: 42px; background: #0a0a12; border-bottom: 1px solid #1a2a1a; display: flex; align-items: center; padding: 0 16px; gap: 10px; flex-shrink: 0; }
.ds-logo { font-family: 'Press Start 2P', monospace; font-size: 9px; color: #ffaa00; text-shadow: 0 0 10px rgba(255,170,0,0.4); letter-spacing: 2px; }
.ds-title { font-family: 'Press Start 2P', monospace; font-size: 6px; color: #d0ffd0; letter-spacing: 1px; }
.ds-sub { font-size: 10px; color: #3a5a3a; }
.spacer { flex: 1; }
.sep { color: #1a2a1a; }
.ds-btn { font-family: 'Press Start 2P', monospace; font-size: 5px; padding: 4px 10px; background: transparent; border: 1px solid #1a2a1a; color: #6a8a6a; border-radius: 2px; cursor: pointer; transition: all 0.2s; letter-spacing: 1px; }
.ds-btn:hover { border-color: #00ff88; color: #00ff88; }
.ds-btn.accent { border-color: #ffaa00; color: #ffaa00; }
.ds-btn.accent:hover { background: rgba(255,170,0,0.1); }
.ds-btn.compute { border-color: #ff6b9d; color: #ff6b9d; }
.ds-btn.compute:hover { background: rgba(255,107,157,0.1); }
.ds-btn:disabled { opacity: 0.4; cursor: not-allowed; }
.ds-create { height: 38px; background: #0f0f1a; border-bottom: 1px solid #1a2a1a; display: flex; align-items: center; padding: 0 16px; gap: 8px; flex-shrink: 0; }
.ds-input { height: 24px; background: #050508; border: 1px solid #1a2a1a; color: #d0ffd0; font-family: 'Share Tech Mono', monospace; font-size: 10px; padding: 0 6px; border-radius: 2px; min-width: 140px; }
.ds-input:focus { border-color: #ffaa00; outline: none; }
.ds-select { height: 24px; background: #050508; border: 1px solid #1a2a1a; color: #d0ffd0; font-family: 'Share Tech Mono', monospace; font-size: 10px; padding: 0 4px; border-radius: 2px; }

.ds-body { flex: 1; display: flex; overflow: hidden; }
.ds-sidebar { width: 220px; background: #0a0a12; border-right: 1px solid #1a2a1a; overflow-y: auto; flex-shrink: 0; display: flex; flex-direction: column; }
.ds-sidebar-head { font-family: 'Press Start 2P', monospace; font-size: 5px; color: #3a5a3a; padding: 8px 10px; letter-spacing: 1px; border-bottom: 1px solid #1a2a1a; flex-shrink: 0; }
.ds-sidebar-divider { height: 1px; background: #1a2a1a; margin: 4px 0; flex-shrink: 0; }
.ds-empty { padding: 20px; font-size: 10px; color: #2a3a2a; text-align: center; }
.ds-item { display: flex; align-items: center; gap: 8px; padding: 8px 10px; cursor: pointer; border-bottom: 1px solid rgba(26,42,26,0.5); transition: all 0.15s; }
.ds-item:hover { background: rgba(255,255,255,0.02); }
.ds-item.active { background: rgba(255,170,0,0.06); border-right: 2px solid #ffaa00; }
.ds-item-icon { font-size: 14px; flex-shrink: 0; }
.ds-item-text { display: flex; flex-direction: column; gap: 1px; flex: 1; min-width: 0; }
.ds-item-name { font-size: 10px; color: #d0ffd0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.ds-item-meta { font-size: 8px; color: #3a5a3a; }
.ds-del { font-size: 10px; color: #3a5a3a; background: none; border: none; cursor: pointer; padding: 2px 4px; }
.ds-del:hover { color: #ff3366; }

.ds-stats-mini { padding: 6px 10px; }
.ds-stat-row { display: flex; justify-content: space-between; padding: 2px 0; font-size: 9px; color: #3a5a3a; }

.ds-main { flex: 1; display: flex; flex-direction: column; overflow: hidden; }
.ds-toolbar { height: 36px; background: #0f0f1a; border-bottom: 1px solid #1a2a1a; display: flex; align-items: center; padding: 0 12px; gap: 8px; flex-shrink: 0; }
.ds-badge { font-family: 'Press Start 2P', monospace; font-size: 6px; padding: 2px 8px; border: 1px solid; border-radius: 2px; letter-spacing: 1px; }
.ds-meta { font-size: 9px; color: #3a5a3a; }
.ds-section-tabs { display: flex; gap: 2px; margin-left: 12px; }
.ds-sec-tab { font-family: 'Press Start 2P', monospace; font-size: 5px; padding: 3px 8px; color: #3a5a3a; cursor: pointer; border: 1px solid transparent; border-radius: 2px; transition: all 0.2s; letter-spacing: 0.5px; }
.ds-sec-tab:hover { color: #6a8a6a; }
.ds-sec-tab.active { color: #ff6b9d; border-color: #ff6b9d; background: rgba(255,107,157,0.06); }

.ds-content { flex: 1; overflow: hidden; display: flex; flex-direction: column; }
.ds-split { flex: 1; display: flex; overflow: hidden; }
.ds-split-left { flex: 1; display: flex; flex-direction: column; border-right: 1px solid #1a2a1a; overflow: hidden; }
.ds-split-right { flex: 0 0 280px; display: flex; flex-direction: column; overflow: hidden; }
.ds-section-title { font-family: 'Press Start 2P', monospace; font-size: 6px; padding: 8px 10px; letter-spacing: 1px; background: #0a0a12; border-bottom: 1px solid #1a2a1a; flex-shrink: 0; }
.ds-split-scroll { flex: 1; overflow-y: auto; padding: 8px; }
.ds-empty-panel { padding: 30px; text-align: center; font-size: 10px; color: #2a3a2a; }

.ann-card { border: 1px solid #1a2a1a; border-radius: 3px; padding: 8px; margin-bottom: 6px; background: rgba(255,255,255,0.01); }
.ann-header { display: flex; align-items: center; gap: 6px; margin-bottom: 4px; }
.ann-id { font-family: 'Fira Code', monospace; font-size: 8px; color: #3a5a3a; }
.ann-score { font-family: 'Press Start 2P', monospace; font-size: 6px; }
.ann-auto { font-family: 'Press Start 2P', monospace; font-size: 4px; padding: 1px 4px; background: rgba(255,107,157,0.15); color: #ff6b9d; border-radius: 1px; letter-spacing: 0.5px; }
.ann-labels { display: flex; gap: 3px; flex-wrap: wrap; margin-bottom: 4px; }
.ann-label { font-family: 'Press Start 2P', monospace; font-size: 4px; padding: 1px 4px; background: rgba(255,170,0,0.1); color: #ffaa00; border-radius: 1px; letter-spacing: 0.5px; }
.ann-caption { font-size: 10px; color: #d0ffd0; margin-bottom: 3px; }
.ann-prompt { font-size: 9px; color: #3a5a3a; font-style: italic; margin-bottom: 3px; }
.ann-meta { display: flex; gap: 8px; font-size: 8px; color: #3a5a3a; }

.ann-form { display: flex; flex-direction: column; gap: 6px; }
.ann-form-label { font-family: 'Press Start 2P', monospace; font-size: 5px; color: #3a5a3a; letter-spacing: 1px; }
.ann-input { height: 24px; background: #050508; border: 1px solid #1a2a1a; color: #d0ffd0; font-family: 'Share Tech Mono', monospace; font-size: 10px; padding: 0 6px; border-radius: 2px; }
.ann-input:focus { border-color: #44ddff; outline: none; }
.ann-textarea { background: #050508; border: 1px solid #1a2a1a; color: #d0ffd0; font-family: 'Share Tech Mono', monospace; font-size: 10px; padding: 6px; border-radius: 2px; resize: vertical; }
.ann-textarea:focus { border-color: #44ddff; outline: none; }

.compute-panel { flex: 1; display: flex; flex-direction: column; padding: 16px; overflow-y: auto; gap: 12px; }
.compute-header { display: flex; justify-content: space-between; align-items: center; }
.compute-title { font-family: 'Press Start 2P', monospace; font-size: 8px; color: #ff6b9d; letter-spacing: 2px; text-shadow: 0 0 8px rgba(255,107,157,0.3); }
.compute-status { font-family: 'Press Start 2P', monospace; font-size: 6px; letter-spacing: 1px; }
.compute-progress-wrap { display: flex; align-items: center; gap: 10px; }
.compute-progress-bar { flex: 1; height: 8px; background: #1a2a1a; border-radius: 4px; overflow: hidden; }
.compute-progress-fill { height: 100%; background: linear-gradient(90deg, #ff6b9d, #ffaa00, #00ff88); border-radius: 4px; transition: width 0.3s ease; }
.compute-pct { font-family: 'Press Start 2P', monospace; font-size: 7px; color: #ffaa00; min-width: 36px; }
.compute-step { font-size: 11px; color: #6a8a6a; }
.compute-log { flex: 1; background: #0a0a12; border: 1px solid #1a2a1a; border-radius: 4px; padding: 8px; overflow-y: auto; min-height: 120px; max-height: 300px; }
.compute-log-row { display: flex; align-items: center; gap: 6px; padding: 3px 0; border-bottom: 1px solid rgba(26,42,26,0.3); }
.compute-log-time { font-family: 'Fira Code', monospace; font-size: 8px; color: #2a3a2a; min-width: 90px; }
.compute-log-dot { width: 5px; height: 5px; border-radius: 50%; flex-shrink: 0; }
.compute-log-msg { font-size: 10px; }
.compute-actions { display: flex; gap: 8px; }
.compute-info { display: flex; flex-wrap: wrap; gap: 12px; padding: 8px; background: #0a0a12; border: 1px solid #1a2a1a; border-radius: 4px; }
.compute-info-row { display: flex; gap: 6px; font-size: 10px; color: #3a5a3a; }

.training-panel { flex: 1; display: flex; flex-direction: column; overflow: hidden; }
.training-header { padding: 12px 16px; display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid #1a2a1a; }
.training-title { font-family: 'Press Start 2P', monospace; font-size: 7px; color: #ffaa00; letter-spacing: 1px; }
.training-count { font-size: 10px; color: #3a5a3a; }
.training-stats-grid { display: flex; gap: 8px; padding: 12px 16px; flex-wrap: wrap; }
.training-stat-card { display: flex; flex-direction: column; align-items: center; gap: 2px; padding: 8px 14px; border: 1px solid #1a2a1a; border-radius: 4px; background: #0a0a12; min-width: 80px; }
.tsc-val { font-family: 'Press Start 2P', monospace; font-size: 12px; }
.tsc-label { font-family: 'Press Start 2P', monospace; font-size: 4px; color: #3a5a3a; letter-spacing: 0.5px; }
.training-quality-bar { display: flex; align-items: center; gap: 8px; padding: 0 16px 8px; }
.tqb-label { font-family: 'Press Start 2P', monospace; font-size: 5px; color: #3a5a3a; letter-spacing: 0.5px; }
.tqb-bar { flex: 1; height: 6px; background: #1a2a1a; border-radius: 3px; overflow: hidden; }
.tqb-fill { height: 100%; border-radius: 3px; transition: width 0.3s; }
.tqb-fill.high { background: linear-gradient(90deg, #00ff88, #44ddff); }
.tqb-pct { font-size: 9px; color: #00ff88; min-width: 70px; }
.training-list-head { font-family: 'Press Start 2P', monospace; font-size: 5px; color: #3a5a3a; padding: 6px 16px; letter-spacing: 1px; border-top: 1px solid #1a2a1a; border-bottom: 1px solid #1a2a1a; flex-shrink: 0; }
.training-list { flex: 1; overflow-y: auto; padding: 6px 16px; }
.training-row { display: flex; align-items: center; gap: 8px; padding: 5px 0; border-bottom: 1px solid rgba(26,42,26,0.3); }
.tr-ds { font-family: 'Press Start 2P', monospace; font-size: 5px; min-width: 60px; letter-spacing: 0.5px; }
.tr-labels { display: flex; gap: 3px; }
.tr-caption { flex: 1; font-size: 10px; color: #d0ffd0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.tr-score { font-family: 'Press Start 2P', monospace; font-size: 5px; min-width: 30px; text-align: right; }

.ds-stats-panel { height: 24px; background: #0a0a12; border-top: 1px solid #1a2a1a; display: flex; align-items: center; padding: 0 12px; font-size: 9px; color: #3a5a3a; flex-shrink: 0; }
.ds-no-selection { flex: 1; display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 10px; }
.ds-no-icon { font-size: 48px; color: #1a2a1a; }
.ds-no-text { font-family: 'Press Start 2P', monospace; font-size: 7px; color: #3a5a3a; letter-spacing: 1px; }
.ds-no-hint { font-size: 10px; color: #2a3a2a; }
.ds-statusbar { height: 22px; background: #0a0a12; border-top: 1px solid #1a2a1a; display: flex; align-items: center; padding: 0 12px; font-family: 'Press Start 2P', monospace; font-size: 5px; color: #3a5a3a; letter-spacing: 1px; gap: 12px; flex-shrink: 0; }
.ds-indicator { width: 6px; height: 6px; border-radius: 50%; }
</style>